### ISSUE TITLE
PicklingError when using plugin installed via setup.py develop

### ISSUE THREAD

**Issue by asottile** [PyCQA/flake8#1015]
In GitLab by @xZise on Jul 10, 2016, 14:52

Using Flake8 3.0.0b2 I get a PicklingError when I try to it with a plugin ([flake8-string-format](https://github.com/xZise/flake8-string-format)) installed via `python setup.py develop`. When I use `pip install flake8-string-format` it won't cause the error. I tested it on Python version 2.7.10 and 3.5.2. Both show similar results:

```
$ flake8 flake8_string_format.py 
Traceback (most recent call last):
  File "/usr/lib64/python2.7/multiprocessing/queues.py", line 268, in _feed
    send(obj)
PicklingError: Can't pickle <type 'function'>: attribute lookup __builtin__.function failed
```

```
$ flake8 flake8_string_format.py 
Traceback (most recent call last):
  File "/home/xzise/.pyenv/versions/3.5.1/lib/python3.5/multiprocessing/queues.py", line 241, in _feed
    obj = ForkingPickler.dumps(obj)
  File "/home/xzise/.pyenv/versions/3.5.1/lib/python3.5/multiprocessing/reduction.py", line 50, in dumps
    cls(buf, protocol).dump(obj)
AttributeError: Can't pickle local object 'compile.<locals>.marker_fn'
```

Uninstalling the plugin does not fix the error, but reinstalling `flake8` (obviously without the plugin). I'm also not sure what part of the plugin is actually causing that error. And maybe this is related to #164, but I'm not using `python setup.py flake8`.

To reproduce you can use the following commands:
```
$ cd …into a directory of your choosing…
$ wget https://github.com/xZise/flake8-string-format/archive/0.2.2.zip
$ unzip 0.2.2.zip 
$ cd flake8-string-format-0.2.2/
$ virtualenv failure
$ source failure/bin/activate
$ pip install flake8==3.0.0b2
$ python setup.py develop
$ flake8 flake8_string_format.py
```

**Comment by asottile** [comment]
In GitLab by @sigmavirus24 on Jul 11, 2016, 03:51

This is a duplicate of #164. It has to do with eggs having weird interaction issues with multiprocessing
