### ISSUE TITLE
AssertionError on Python 2.6 - 3.4

### ISSUE THREAD

**Issue by asottile** [PyCQA/flake8#1023]
In GitLab by @wavi on Jul 23, 2016, 13:09

I'm getting this in Travis CI on all Python versions. Unfortunately I don't seem to be able to reproduce it locally. Any ideas?

    Traceback (most recent call last):
      File "/home/travis/virtualenv/python2.7.9/bin/flake8", line 11, in <module>
        sys.exit(main())
      File "/home/travis/virtualenv/python2.7.9/lib/python2.7/site-packages/flake8/main.py", line 28, in main
        flake8_style = get_style_guide(parse_argv=True)
      File "/home/travis/virtualenv/python2.7.9/lib/python2.7/site-packages/flake8/engine.py", line 234, in get_style_guide
        styleguide = StyleGuide(**kwargs)
      File "/home/travis/virtualenv/python2.7.9/lib/python2.7/site-packages/flake8/engine.py", line 154, in __init__
        self._styleguide = kwargs.pop('styleguide', NoQAStyleGuide(**kwargs))
      File "/home/travis/virtualenv/python2.7.9/lib/python2.7/site-packages/pycodestyle.py", line 1833, in __init__
        arglist, parse_argv, config_file, parser)
      File "/home/travis/virtualenv/python2.7.9/lib/python2.7/site-packages/pycodestyle.py", line 2120, in process_options
        options = read_config(options, args, arglist, parser)
      File "/home/travis/virtualenv/python2.7.9/lib/python2.7/site-packages/pycodestyle.py", line 2076, in read_config
        assert opt_type in ('store_true', 'store_false')
    AssertionError

**Comment by asottile** [comment]
In GitLab by @sigmavirus24 on Jul 23, 2016, 17:05

Can you at least point me to an instance where this failed on Travis CI? I have several projects using Travis CI and not having problems like this. :/

**Comment by asottile** [comment]
In GitLab by @wavi on Jul 24, 2016, 05:20

Hi, sorry for the lack of details, I was in a bit of a hurry.
Here's the link https://travis-ci.org/richrd/suplemon/jobs/146899728 .
Could it be related to using flake8-quotes maybe?

**Comment by asottile** [comment]
In GitLab by @xZise on Jul 24, 2016, 07:45

This could be just a guess but if `flake8-quotes` is to blame it is because since 0.7.0 it has the parameter as a choice (so only `"` and `'` are accepted) and maybe ~"component:pycodestyle" can't really handle that. So the reason it doesn't fail for you locally is because you don't use an updated version for `flake8-quotes`. Although I can't really understand why that would be the case as the tests for `flake8-quotes` succeeded fine and `pep8` does the same assertion. But it would make sense because it first uses the option's type and then it's action. And the type is actually `choice` which acts according to the [optparse documentation](https://docs.python.org/2/library/optparse.html#standard-option-types) like a `string`.

So possible ideas to narrow it down is to update `flake8-quotes` to 0.7.0 locally and to check if you can reproduce it. You could also remove the option in the `setup.cfg` and rerun tests on Travis (probably on another branch to reduce noise). This will cause errors as you probably use the other quote style, but if it will produce errors it is related.

And I'm going to check whether my guess is correct by trying to reproducing your issue and by checking what is actually happening.

**Comment by asottile** [comment]
In GitLab by @xZise on Jul 24, 2016, 08:11

Okay I did some testing and could reproduce your assertion error. Reported it on [pycodestyle](https://github.com/PyCQA/pycodestyle/issues/561) as there is the bug. Not sure if Flake8 could monkey patch something there.

**Comment by asottile** [comment]
In GitLab by @wavi on Jul 24, 2016, 10:41

Thanks a lot! I've just been using flake8 and didn't really understand how it worked. Sorry for reporting in the wrong place. Thanks again for the help, flake8 is a wonderful tool!
