### ISSUE TITLE
Flake8 3.0.1 doesn't work, throw _pickle.PicklingError and setup.py flake8 - hangs?

### ISSUE THREAD

**Issue by asottile** [PyCQA/flake8#1027]
In GitLab by @skirpichev on Jul 26, 2016, 01:13

```
$ python --version
Python 3.4.2
```

Flake8 installed with pip-8.1.2, setuptools-19.4.

Traceback:
```
$ python setup.py flake8
running flake8
Traceback (most recent call last):
  File "/opt/python/3.4.2/lib/python3.4/multiprocessing/queues.py", line 242, in _feed
    obj = ForkingPickler.dumps(obj)
  File "/opt/python/3.4.2/lib/python3.4/multiprocessing/reduction.py", line 50, in dumps
    cls(buf, protocol).dump(obj)
_pickle.PicklingError: Can't pickle <function compile.<locals>.marker_fn at 0x7fc481fe98c8>: attribute lookup marker_fn on _markerlib.markers failed
```

Travis job was killed by 10 min time limit for a command.  Full travis log:
https://api.travis-ci.org/jobs/147168228/log.txt?deansi=true

If I turn off this limit with travis_wait - travis job killed by 20min time limit:
https://s3.amazonaws.com/archive.travis-ci.org/jobs/147377230/log.txt 
```
$ travis_wait python setup.py flake8
Still running (1 of 20): python setup.py flake8
Still running (2 of 20): python setup.py flake8
Still running (3 of 20): python setup.py flake8
Still running (4 of 20): python setup.py flake8
Still running (5 of 20): python setup.py flake8
Still running (6 of 20): python setup.py flake8
Still running (7 of 20): python setup.py flake8
Still running (8 of 20): python setup.py flake8
Still running (9 of 20): python setup.py flake8
Still running (10 of 20): python setup.py flake8
Still running (11 of 20): python setup.py flake8
Still running (12 of 20): python setup.py flake8
Still running (13 of 20): python setup.py flake8
Still running (14 of 20): python setup.py flake8
Still running (15 of 20): python setup.py flake8
Still running (16 of 20): python setup.py flake8
Still running (17 of 20): python setup.py flake8
Still running (18 of 20): python setup.py flake8
Still running (19 of 20): python setup.py flake8
Still running (20 of 20): python setup.py flake8
[31;1mTimeout (20 minutes) reached. Terminating "python setup.py flake8"[0m
[31;1mThe command python setup.py flake8 exited with 137.[0m
[32;1mLog:[0m
running flake8
Traceback (most recent call last):
  File "/opt/python/3.4.2/lib/python3.4/multiprocessing/queues.py", line 242, in _feed
    obj = ForkingPickler.dumps(obj)
  File "/opt/python/3.4.2/lib/python3.4/multiprocessing/reduction.py", line 50, in dumps
    cls(buf, protocol).dump(obj)
_pickle.PicklingError: Can't pickle <function compile.<locals>.marker_fn at 0x7fd83e6b98c8>: attribute lookup marker_fn on _markerlib.markers failed
travis_time:end:1cba09f7:start=1469512164241516658,finish=1469513364289329319,duration=1200047812661
[0K
[31;1mThe command "travis_wait python setup.py flake8" exited with 137.[0m
travis_time:start:274feb42
```

If flake8 now is just so slow by default - it's  a very severe bug too, imho.

**Comment by asottile** [comment]
In GitLab by @skirpichev on Jul 26, 2016, 01:17

Sorry, perhaps this is a duplicate of https://gitlab.com/pycqa/flake8/issues/164

**Comment by asottile** [comment]
In GitLab by @sigmavirus24 on Jul 26, 2016, 04:24

@skirpichev thanks for reporting it, even if it is a duplicate. :)

I hope the work around on #164 works for you too.

**Comment by asottile** [comment]
In GitLab by @skirpichev on Jul 26, 2016, 07:54

> I hope the work around on #164 works for you too.

Yep, thank you.  btw, you could add references to such major known issues to the release notes.
