### ISSUE TITLE
flake8 fails to work as it used to be on python 2.6.9

### ISSUE THREAD

**Issue by asottile** [PyCQA/flake8#1031]
In GitLab by @chfw on Jul 26, 2016, 13:40

*Please provide the following version information*

- Version of Python which has Flake8 installed (e.g., `python -V`)

python 2.6.9

- How you installed Flake8 (e.g., `pip`, `apt`, `yum`, etc.)

pip install flake8, the latest

  - If you used pip, the version of pip installed (e.g., `pip --version`)

pip 7.1

- Version of setuptools installed (e.g., `python -c 'import setuptools; print(setuptools.__version__)'`)

setuptools 25.1

- Version of Flake8 installed (i.e., copy and paste all of the output from `flake8 --version`)

flake8 3.0.1

*Please describe the problem or feature*

Traceback (most recent call last):
  File "/opt/python/2.6.9/lib/python2.6/multiprocessing/process.py", line 232, in _bootstrap
    self.run()
  File "/opt/python/2.6.9/lib/python2.6/multiprocessing/process.py", line 88, in run
    self._target(*self._args, **self._kwargs)
  File "/home/travis/virtualenv/python2.6.9/lib/python2.6/site-packages/flake8/checker.py", line 222, in _run_checks_from_queue
    checker.run_checks(self.results_queue, self.statistics_queue)
  File "/home/travis/virtualenv/python2.6.9/lib/python2.6/site-packages/flake8/checker.py", line 559, in run_checks
    self.process_tokens()
  File "/home/travis/virtualenv/python2.6.9/lib/python2.6/site-packages/flake8/checker.py", line 536, in process_tokens
    self.check_physical_eol(token)
  File "/home/travis/virtualenv/python2.6.9/lib/python2.6/site-packages/flake8/checker.py", line 599, in check_physical_eol
    self.run_physical_checks(token[4])
  File "/home/travis/virtualenv/python2.6.9/lib/python2.6/site-packages/flake8/checker.py", line 509, in run_physical_checks
    for plugin in self.checks.physical_line_plugins:
  File "/home/travis/virtualenv/python2.6.9/lib/python2.6/site-packages/flake8/plugins/manager.py", line 476, in physical_line_plugins
    plugins = list(self.checks_expecting('physical_line'))
  File "/home/travis/virtualenv/python2.6.9/lib/python2.6/site-packages/flake8/plugins/manager.py", line 427, in checks_expecting
    if argument_name == plugin.parameter_names[0]:
  File "/home/travis/virtualenv/python2.6.9/lib/python2.6/site-packages/flake8/plugins/manager.py", line 85, in parameter_names
    self._parameter_names = list(self.parameters)
  File "/home/travis/virtualenv/python2.6.9/lib/python2.6/site-packages/flake8/plugins/manager.py", line 78, in parameters
    self._parameters = utils.parameters_for(self)
  File "/home/travis/virtualenv/python2.6.9/lib/python2.6/site-packages/flake8/utils.py", line 287, in parameters_for
    parameters = collections.OrderedDict([
AttributeError: 'module' object has no attribute 'OrderedDict'

Here is the full stack trace: https://travis-ci.org/pyexcel/pyexcel/jobs/147496701

*If this is a bug report, please explain with examples (and example code) what you expected to happen and what actually happened.*

Here is the normal(used to be) trace with version 2.6.2: https://travis-ci.org/pyexcel/pyexcel/jobs/147582898

**Comment by asottile** [comment]
In GitLab by @chfw on Jul 26, 2016, 13:41

Changed title: **flake8 fails to work as it used to be on python 2.6** → **flake8 fails to work as it used to be on python 2.6{+.9+}**

**Comment by asottile** [comment]
In GitLab by @sigmavirus24 on Jul 26, 2016, 13:59

[Flake8 no longer supports Python 2.6](http://flake8.pycqa.org/en/latest/release-notes/3.0.0.html).
