### ISSUE TITLE
PicklingError: Can't pickle <type 'function'>: attribute lookup __builtin__.function failed

### ISSUE THREAD

**Issue by asottile** [PyCQA/flake8#1038]
In GitLab by @moylop260 on Jul 29, 2016, 19:38

https://travis-ci.org/OCA/maintainer-tools/builds/147765216#L565

```bash
(python2.7_with_system_site_packages)travis@c4c32467a96f:~/OCA/maintainer-tools$ python setup.py flake8
running flake8
Traceback (most recent call last):
  File "/usr/lib/python2.7/multiprocessing/queues.py", line 266, in _feed
    send(obj)
PicklingError: Can't pickle <type 'function'>: attribute lookup __builtin__.function failed
^CProcess Process-5:
Process Process-8:
Process Process-6:
Traceback (most recent call last):
Traceback (most recent call last):
Process Process-7:
  File "/usr/lib/python2.7/multiprocessing/process.py", line 258, in _bootstrap
  File "/usr/lib/python2.7/multiprocessing/process.py", line 258, in _bootstrap
Traceback (most recent call last):
Traceback (most recent call last):
  File "/usr/lib/python2.7/multiprocessing/process.py", line 258, in _bootstrap
  File "/usr/lib/python2.7/multiprocessing/process.py", line 258, in _bootstrap
Process Process-4:
Traceback (most recent call last):
  File "/usr/lib/python2.7/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
    self.run()
  File "/usr/lib/python2.7/multiprocessing/process.py", line 114, in run
  File "/usr/lib/python2.7/multiprocessing/process.py", line 114, in run
    self.run()
    self.run()
  File "/usr/lib/python2.7/multiprocessing/process.py", line 114, in run
  File "/usr/lib/python2.7/multiprocessing/process.py", line 114, in run
    self._target(*self._args, **self._kwargs)
  File "/home/travis/virtualenv/python2.7_with_system_site_packages/local/lib/python2.7/site-packages/flake8/checker.py", line 220, in _run_checks_from_queue
Process Process-3:
    self._target(*self._args, **self._kwargs)
    self._target(*self._args, **self._kwargs)
Traceback (most recent call last):
  File "/home/travis/virtualenv/python2.7_with_system_site_packages/local/lib/python2.7/site-packages/flake8/checker.py", line 220, in _run_checks_from_queue
  File "/home/travis/virtualenv/python2.7_with_system_site_packages/local/lib/python2.7/site-packages/flake8/checker.py", line 220, in _run_checks_from_queue
    self.run()
  File "/usr/lib/python2.7/multiprocessing/process.py", line 258, in _bootstrap
Process Process-2:
Traceback (most recent call last):
  File "/usr/lib/python2.7/multiprocessing/process.py", line 258, in _bootstrap
    for checker in iter(self.process_queue.get, 'DONE'):
  File "/usr/lib/python2.7/multiprocessing/queues.py", line 115, in get
    self.run()
  File "/usr/lib/python2.7/multiprocessing/process.py", line 114, in run
    for checker in iter(self.process_queue.get, 'DONE'):
  File "/usr/lib/python2.7/multiprocessing/queues.py", line 115, in get
    self._target(*self._args, **self._kwargs)
    self.run()
  File "/home/travis/virtualenv/python2.7_with_system_site_packages/local/lib/python2.7/site-packages/flake8/checker.py", line 220, in _run_checks_from_queue
  File "/usr/lib/python2.7/multiprocessing/process.py", line 114, in run
    self._target(*self._args, **self._kwargs)
  File "/home/travis/virtualenv/python2.7_with_system_site_packages/local/lib/python2.7/site-packages/flake8/checker.py", line 220, in _run_checks_from_queue
    self._rlock.acquire()
    self._rlock.acquire()
KeyboardInterrupt
KeyboardInterrupt
    for checker in iter(self.process_queue.get, 'DONE'):
  File "/usr/lib/python2.7/multiprocessing/queues.py", line 115, in get
    for checker in iter(self.process_queue.get, 'DONE'):
  File "/usr/lib/python2.7/multiprocessing/queues.py", line 115, in get
    self._rlock.acquire()
KeyboardInterrupt
    self._rlock.acquire()
KeyboardInterrupt
    self._target(*self._args, **self._kwargs)
  File "/home/travis/virtualenv/python2.7_with_system_site_packages/local/lib/python2.7/site-packages/flake8/checker.py", line 220, in _run_checks_from_queue
Process Process-1:
Traceback (most recent call last):
  File "/usr/lib/python2.7/multiprocessing/process.py", line 258, in _bootstrap
    for checker in iter(self.process_queue.get, 'DONE'):
  File "/usr/lib/python2.7/multiprocessing/queues.py", line 115, in get
    self.run()
  File "/usr/lib/python2.7/multiprocessing/process.py", line 114, in run
    self._rlock.acquire()
KeyboardInterrupt
    self._target(*self._args, **self._kwargs)
  File "/home/travis/virtualenv/python2.7_with_system_site_packages/local/lib/python2.7/site-packages/flake8/checker.py", line 220, in _run_checks_from_queue
Traceback (most recent call last):
  File "setup.py", line 9, in <module>
    package_data={'': ['*.yaml']}
  File "/usr/lib/python2.7/distutils/core.py", line 152, in setup
    for checker in iter(self.process_queue.get, 'DONE'):
  File "/usr/lib/python2.7/multiprocessing/queues.py", line 117, in get
    dist.run_commands()
  File "/usr/lib/python2.7/distutils/dist.py", line 953, in run_commands
    res = self._recv()
KeyboardInterrupt
    self.run_command(cmd)
  File "/usr/lib/python2.7/distutils/dist.py", line 972, in run_command
    cmd_obj.run()
  File "/home/travis/virtualenv/python2.7_with_system_site_packages/local/lib/python2.7/site-packages/flake8/main/setuptools_command.py", line 91, in run
    for checker in iter(self.process_queue.get, 'DONE'):
      File "/usr/lib/python2.7/multiprocessing/process.py", line 114, in run
  File "/usr/lib/python2.7/multiprocessing/queues.py", line 115, in get
    self._target(*self._args, **self._kwargs)
  File "/home/travis/virtualenv/python2.7_with_system_site_packages/local/lib/python2.7/site-packages/flake8/checker.py", line 220, in _run_checks_from_queue
    self._rlock.acquire()
KeyboardInterrupt
    for checker in iter(self.process_queue.get, 'DONE'):
  File "/usr/lib/python2.7/multiprocessing/queues.py", line 115, in get
    self._rlock.acquire()
KeyboardInterrupt
self.flake8.run_checks(list(self.distribution_files()))
  File "/home/travis/virtualenv/python2.7_with_system_site_packages/local/lib/python2.7/site-packages/flake8/main/application.py", line 231, in run_checks
    self.file_checker_manager.run()
  File "/home/travis/virtualenv/python2.7_with_system_site_packages/local/lib/python2.7/site-packages/flake8/checker.py", line 355, in run
    raise exceptions.EarlyQuit('Early quit while running checks')
flake8.exceptions.EarlyQuit: Early quit while running checks
```

<img width="879" alt="screen shot 2016-07-29 at 9 27 07 pm" src="https://cloud.githubusercontent.com/assets/6644187/17267624/8582df84-55d3-11e6-9911-92cb66932bea.png">

Freezing v2.6.2 working fine!
<img width="856" alt="screen shot 2016-07-29 at 9 29 05 pm" src="https://cloud.githubusercontent.com/assets/6644187/17267623/856b2e20-55d3-11e6-9c88-4afce487c54e.png">

**Comment by asottile** [comment]
In GitLab by @sigmavirus24 on Jul 30, 2016, 04:47

This is a duplicate of #164
