### ISSUE TITLE
TypeError: parse_options() takes 2 positional arguments but 4 were given

### ISSUE THREAD

**Issue by asottile** [PyCQA/flake8#1039]
In GitLab by @ssbarnea on Jul 31, 2016, 10:58

```
flake8 --version
3.0.2 (pyflakes: 1.2.3, flake8-respect-noqa: 0.3, mccabe: 0.5.0, pycodestyle: 2.0.0) CPython 3.5.2 on Darwin
```
Installed using pip 8.1.2 and setuptools 21.0.0
```
flake8
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/site-packages/flake8/plugins/manager.py", line 184, in provide_options
    parse_options(optmanager, options, extra_args)
TypeError: parse_options() takes 2 positional arguments but 4 were given

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/bin/flake8", line 11, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.5/site-packages/flake8/main/cli.py", line 16, in main
    app.run(argv)
  File "/usr/local/lib/python3.5/site-packages/flake8/main/application.py", line 316, in run
    self._run(argv)
  File "/usr/local/lib/python3.5/site-packages/flake8/main/application.py", line 299, in _run
    self.initialize(argv)
  File "/usr/local/lib/python3.5/site-packages/flake8/main/application.py", line 291, in initialize
    self.parse_configuration_and_cli(argv)
  File "/usr/local/lib/python3.5/site-packages/flake8/main/application.py", line 172, in parse_configuration_and_cli
    self.args)
  File "/usr/local/lib/python3.5/site-packages/flake8/plugins/manager.py", line 395, in provide_options
    list(self.manager.map(call_provide_options))
  File "/usr/local/lib/python3.5/site-packages/flake8/plugins/manager.py", line 261, in map
    yield func(self.plugins[name], *args, **kwargs)
  File "/usr/local/lib/python3.5/site-packages/flake8/plugins/manager.py", line 357, in generated_function
    return method(optmanager, *args, **kwargs)
  File "/usr/local/lib/python3.5/site-packages/flake8/plugins/manager.py", line 186, in provide_options
    parse_options(options)
  File "/usr/local/lib/python3.5/site-packages/flake8_respect_noqa.py", line 38, in parse_options
    options.report = RespectNoqaReport(options)
  File "/usr/local/lib/python3.5/site-packages/pep8.py", line 1721, in __init__
    super(StandardReport, self).__init__(options)
  File "/usr/local/lib/python3.5/site-packages/pep8.py", line 1628, in __init__
    self._benchmark_keys = options.benchmark_keys
AttributeError: 'Values' object has no attribute 'benchmark_keys'
```

**Comment by asottile** [comment]
In GitLab by @ssbarnea on Jul 31, 2016, 10:59

As a note: I uninstalled pep8 (which was not ever reported as a flake8 used module) and run flake8 again, getting almost the same error:
```
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/site-packages/flake8/plugins/manager.py", line 184, in provide_options
    parse_options(optmanager, options, extra_args)
TypeError: parse_options() takes 2 positional arguments but 4 were given

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/bin/flake8", line 11, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.5/site-packages/flake8/main/cli.py", line 16, in main
    app.run(argv)
  File "/usr/local/lib/python3.5/site-packages/flake8/main/application.py", line 316, in run
    self._run(argv)
  File "/usr/local/lib/python3.5/site-packages/flake8/main/application.py", line 299, in _run
    self.initialize(argv)
  File "/usr/local/lib/python3.5/site-packages/flake8/main/application.py", line 291, in initialize
    self.parse_configuration_and_cli(argv)
  File "/usr/local/lib/python3.5/site-packages/flake8/main/application.py", line 172, in parse_configuration_and_cli
    self.args)
  File "/usr/local/lib/python3.5/site-packages/flake8/plugins/manager.py", line 395, in provide_options
    list(self.manager.map(call_provide_options))
  File "/usr/local/lib/python3.5/site-packages/flake8/plugins/manager.py", line 261, in map
    yield func(self.plugins[name], *args, **kwargs)
  File "/usr/local/lib/python3.5/site-packages/flake8/plugins/manager.py", line 357, in generated_function
    return method(optmanager, *args, **kwargs)
  File "/usr/local/lib/python3.5/site-packages/flake8/plugins/manager.py", line 186, in provide_options
    parse_options(options)
  File "/usr/local/lib/python3.5/site-packages/flake8_respect_noqa.py", line 38, in parse_options
    options.report = RespectNoqaReport(options)
  File "/usr/local/lib/python3.5/site-packages/pycodestyle.py", line 1756, in __init__
    super(StandardReport, self).__init__(options)
  File "/usr/local/lib/python3.5/site-packages/pycodestyle.py", line 1662, in __init__
    self._benchmark_keys = options.benchmark_keys
AttributeError: 'Values' object has no attribute 'benchmark_keys'
```

**Comment by asottile** [comment]
In GitLab by @sigmavirus24 on Jul 31, 2016, 11:44

Towards the bottom of your traceback, you might have noticed:

```
  File "/usr/local/lib/python3.5/site-packages/flake8_respect_noqa.py", line 38, in parse_options
    options.report = RespectNoqaReport(options)
```

Which indicates that this is a path taken by flake8-respect-noqa. If you uninstall that, you should have no problems, especially if you read [flake8-respect-noqa's README](https://github.com/spookylukey/flake8-respect-noqa#flake8-respect-noqa).

**Comment by asottile** [comment]
In GitLab by @ssbarnea on Aug 1, 2016, 02:43

Is there a way to specify which flake8 extension you want to enable --- mainly not to allow auto-loading of all extensions that were installed on the system?

PS. Usually the use virtualenv is supposed to address this but in our case we do use virtualenvs that do inherit system libraries due to serious performance and disk space requirements (you don't want to install or compile the big-fat libraries like numpy).

While this approach works fine in most cases, flake8 seems like one place where things go insane just because one flake8 extension was installed on the system.
