### ISSUE TITLE
Problems with PEP 498: f-strings

### ISSUE THREAD

**Issue by asottile** [PyCQA/flake8#1044]
In GitLab by @xsteadfastx on Jan 13, 2017, 01:27

*Please describe how you installed Flake8*

```
$ python -m venv ~/.virtualenvs/mossbot
$ source ~/.virtualenvs/mossbot/bin/activate
$ pip install flake8
```

*Please provide the exact, unmodified output of `flake8 --bug-report`*

```
{
  "dependencies": [
    {
      "dependency": "setuptools",
      "version": "28.8.0"
    }
  ],
  "platform": {
    "python_implementation": "CPython",
    "python_version": "3.6.0",
    "system": "Linux"
  },
  "plugins": [
    {
      "plugin": "import-order",
      "version": "0.11"
    },
    {
      "plugin": "mccabe",
      "version": "0.5.3"
    },
    {
      "plugin": "pycodestyle",
      "version": "2.2.0"
    },
    {
      "plugin": "pyflakes",
      "version": "1.3.0"
    }
  ],
  "version": "3.2.1"
}

```

*Please describe the problem or feature*

I try to use flake8 on a file that contains a f-string. It fails.

*If this is a bug report, please explain with examples (and example code) what you expected to happen and what actually happened.*

This is the file:
```
foo = 'bar'
print(f'this is {foo}')
```

This happens if i run flake8 against it:

```
$ flake8 foo.py             
Process Process-1:
Traceback (most recent call last):
  File "/home/mpreuss/.pyenv/versions/3.6.0/lib/python3.6/multiprocessing/process.py", line 249, in _bootstrap
    self.run()
  File "/home/mpreuss/.pyenv/versions/3.6.0/lib/python3.6/multiprocessing/process.py", line 93, in run
    self._target(*self._args, **self._kwargs)
  File "/home/mpreuss/.virtualenvs/mossbot/lib/python3.6/site-packages/flake8/checker.py", line 666, in _run_checks_from_queue
    checker.run_checks(results_queue, statistics_queue)
  File "/home/mpreuss/.virtualenvs/mossbot/lib/python3.6/site-packages/flake8/checker.py", line 606, in run_checks
    self.run_ast_checks()
  File "/home/mpreuss/.virtualenvs/mossbot/lib/python3.6/site-packages/flake8/checker.py", line 510, in run_ast_checks
    checker = self.run_check(plugin, tree=ast)
  File "/home/mpreuss/.virtualenvs/mossbot/lib/python3.6/site-packages/flake8/checker.py", line 464, in run_check
    return plugin['plugin'](**arguments)
  File "/home/mpreuss/.virtualenvs/mossbot/lib/python3.6/site-packages/flake8/plugins/pyflakes.py", line 74, in __init__
    withDoctest=with_doctest)
  File "/home/mpreuss/.virtualenvs/mossbot/lib/python3.6/site-packages/pyflakes/checker.py", line 494, in __init__
    self.handleChildren(tree)
  File "/home/mpreuss/.virtualenvs/mossbot/lib/python3.6/site-packages/pyflakes/checker.py", line 816, in handleChildren
    self.handleNode(node, tree)
  File "/home/mpreuss/.virtualenvs/mossbot/lib/python3.6/site-packages/pyflakes/checker.py", line 863, in handleNode
    handler(node)
  File "/home/mpreuss/.virtualenvs/mossbot/lib/python3.6/site-packages/pyflakes/checker.py", line 816, in handleChildren
    self.handleNode(node, tree)
  File "/home/mpreuss/.virtualenvs/mossbot/lib/python3.6/site-packages/pyflakes/checker.py", line 863, in handleNode
    handler(node)
  File "/home/mpreuss/.virtualenvs/mossbot/lib/python3.6/site-packages/pyflakes/checker.py", line 816, in handleChildren
    self.handleNode(node, tree)
  File "/home/mpreuss/.virtualenvs/mossbot/lib/python3.6/site-packages/pyflakes/checker.py", line 862, in handleNode
    handler = self.getNodeHandler(node.__class__)
  File "/home/mpreuss/.virtualenvs/mossbot/lib/python3.6/site-packages/pyflakes/checker.py", line 696, in getNodeHandler
    self._nodeHandlers[node_class] = handler = getattr(self, nodeType)
AttributeError: 'FlakesChecker' object has no attribute 'JOINEDSTR'

```

**Comment by asottile** [comment]
In GitLab by @johnthagen on Jan 14, 2017, 10:03

It looks like recent versions of `pyflakes` have fixed several Python 3.6 related issues. I think that if `flake8` bumps its version of `pyflakes` that will help solve these issues.

**Comment by asottile** [comment]
In GitLab by @xsteadfastx on Jan 17, 2017, 01:07

i upgraded manually to a newer pyflakes version and flake8 works :) thanks for that information.

**Comment by asottile** [comment]
In GitLab by @xsteadfastx on Jan 17, 2017, 01:07

closed
