### ISSUE TITLE
UTF8 encoding not respected for stdin input

### ISSUE THREAD

**Issue by asottile** [PyCQA/flake8#1047]
In GitLab by @arcanemagus on Feb 15, 2017, 15:05

*Please describe how you installed Flake8*

```
> pip install flake8
```

*Please provide the exact, unmodified output of `flake8 --bug-report`*

```json
{
  "dependencies": [
    {
      "dependency": "setuptools",
      "version": "34.2.0"
    }
  ],
  "platform": {
    "python_implementation": "CPython",
    "python_version": "3.6.0",
    "system": "Windows"
  },
  "plugins": [
    {
      "plugin": "mccabe",
      "version": "0.6.1"
    },
    {
      "plugin": "pycodestyle",
      "version": "2.3.1"
    },
    {
      "plugin": "pyflakes",
      "version": "1.5.0"
    }
  ],
  "version": "3.3.0"
}
```

*Please describe the problem or feature*

It seems that the `# -*- coding: utf-8 -*-` line isn't being respected when the input is fed in via `stdin`, leading to incorrect column counts as the higher valued characters start counting as two characters.

*If this is a bug report, please explain with examples (and example code) what you expected to happen and what actually happened.*

Using the following code:

```py
# -*- coding: utf-8 -*-
"""
Created on 2016-11-18 15:03 CET

@author: xyz
# Send ‘1’ for type E = asset type urn:epc:id:grai:7613264.00381.100000147476
# Send ‘2’ for type B = asset type urn:epc:id:grai:7613264.00307.100000147476
# Send ‘3’ for type C = asset type urn:epc:id:grai:7613264.00308.100000147476
# Send ‘4’ for type U = asset type urn:epc:id:grai:7613264.00319.100000147476
"""
```

If you run `flake8 --max-line-length 79 code.py` you (correctly) get no results. However if you run `cat code.py | flake8 --max-line-length 79 -` you get a message stating that each of those lines has 81 characters.

If the `‘` and `’` marks are replaced with `'` then the file works correctly in either mode.

_Note: Originally filed as [AtomLinter/linter-flake8#282](https://github.com/AtomLinter/linter-flake8/issues/282)._

**Comment by asottile** [comment]
In GitLab by @sigmavirus24 on Feb 19, 2017, 05:51

So I confirmed this by merely reading the source.

We have one method that handles stdin/filename line reading: https://gitlab.com/pycqa/flake8/blob/a98ec12bc6ac7877e70fd356668fb28fe5e24a12/src/flake8/processor.py#L292

When reading from a file it does: https://gitlab.com/pycqa/flake8/blob/a98ec12bc6ac7877e70fd356668fb28fe5e24a12/src/flake8/processor.py#L311 only on Python 3.

On Python 2 (https://gitlab.com/pycqa/flake8/blob/a98ec12bc6ac7877e70fd356668fb28fe5e24a12/src/flake8/processor.py#L304) and when using stdin (https://gitlab.com/pycqa/flake8/blob/a98ec12bc6ac7877e70fd356668fb28fe5e24a12/src/flake8/processor.py#L330) it doesn't look for that.

In the interest of full transparency: I stole this logic from pycodestyle. I suspect that the coding detection is unnecessary on Py2, but it's clearly necessary for stdin everywhere.

**Comment by asottile** [comment]
In GitLab by @sigmavirus24 on Feb 19, 2017, 07:06

`tokenize.detect_encoding` does not exist on Python 2. =/

This is also complicated, a little, by the fact that `sys.stdin.read()` on Python 3 returns a `str`. I suspect it's based entirely on `locale` settings. I have a little code worked on to make `stdin_get_value` always return bytes. That way we can handle this uniformly on Python 3.

**Comment by asottile** [comment]
In GitLab by @sigmavirus24 on Feb 19, 2017, 12:45

mentioned in merge request !177

**Comment by asottile** [comment]
In GitLab by @sigmavirus24 on Feb 20, 2017, 06:19

Hey @arcanemagus I believe I've fixed this in !177 but I am not 100% confident. Care to take it for a spin?

**Comment by asottile** [comment]
In GitLab by @arcanemagus on Feb 21, 2017, 16:09

Hmm, assuming that I have properly installed the version from the build artefacts it isn't working properly on my machine at least.

What information can I provide to help debug this further?

**Comment by asottile** [comment]
In GitLab by @sigmavirus24 on Feb 23, 2017, 17:52

> What information can I provide to help debug this further?

I'm not certain, honestly. I might have to find a Windows image and test this there. That could take me some time though.

**Comment by asottile** [comment]
In GitLab by @arcanemagus on Feb 28, 2017, 14:02

Okay... this is just plain _bizarre_. !177 _does_ fix the bug... but _only_ when running inside certain environments.

Inside Atom and from Command Prompt the bug is fixed, however inside PowerShell (my default CLI environment) it isn't.

----

Also, it seems that !177 fixes a somewhat related set of bugs ([AtomLinter/linter-flake8#318](https://github.com/AtomLinter/linter-flake8/issues/318) and [AtomLinter/linter-flake8#356](https://github.com/AtomLinter/linter-flake8/issues/356)). Again, these two are only fixed within Atom and Command Prompt. (The method of execution of `flake8` inside the Atom plugin eventually ends up being wrapped in a Command Prompt shell, so this makes sense.)

----
Using this as a test:
```py
u = u'нормальные слова
```
PowerShell prints it out as this:
![image](/uploads/623523bc56b66842cc50c525802ec415/image.png)

And Command Prompt does no better with this:
![image](/uploads/d9f8061037984fd0d8a066012f582281/image.png)

I'm guessing that the reason this initially looked like it hadn't worked is due to some bizarre encoding thing within PowerShell itself.

Also worth noting: When the currently released v3.3.0 is ran on the above file from `stdin` the following traceback is thrown:
```
Traceback (most recent call last):
  File "c:\program files\python36\lib\site-packages\flake8\checker.py", line 471, in run_ast_checks
    ast = self.processor.build_ast()
  File "c:\program files\python36\lib\site-packages\flake8\processor.py", line 211, in build_ast
    return compile(''.join(self.lines), '', 'exec', PyCF_ONLY_AST)
UnicodeEncodeError: 'utf-8' codec can't encode character '\udc81' in position 28: surrogates not allowed

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\program files\python36\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "c:\program files\python36\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Program Files\Python36\Scripts\flake8.exe\__main__.py", line 9, in <module>
  File "c:\program files\python36\lib\site-packages\flake8\main\cli.py", line 16, in main
    app.run(argv)
  File "c:\program files\python36\lib\site-packages\flake8\main\application.py", line 328, in run
    self._run(argv)
  File "c:\program files\python36\lib\site-packages\flake8\main\application.py", line 316, in _run
    self.run_checks()
  File "c:\program files\python36\lib\site-packages\flake8\main\application.py", line 246, in run_checks
    self.file_checker_manager.run()
  File "c:\program files\python36\lib\site-packages\flake8\checker.py", line 319, in run
    self.run_serial()
  File "c:\program files\python36\lib\site-packages\flake8\checker.py", line 303, in run_serial
    checker.run_checks()
  File "c:\program files\python36\lib\site-packages\flake8\checker.py", line 573, in run_checks
    self.run_ast_checks()
  File "c:\program files\python36\lib\site-packages\flake8\checker.py", line 474, in run_ast_checks
    row, column = self._extract_syntax_information(exception)
  File "c:\program files\python36\lib\site-packages\flake8\checker.py", line 441, in _extract_syntax_information
    if column > 0 and token and isinstance(exception, SyntaxError):
TypeError: '>' not supported between instances of 'str' and 'int'
```

While the version from !177 works perfectly. (If you want this filed as a separate bug just let me know)

**Comment by asottile** [comment]
In GitLab by @sigmavirus24 on Mar 1, 2017, 04:40

I have absolutely no idea how to fix that bug with PowerShell. You should file it separately, but *I* will likely never get to it. If someone else needs it fixed, it'll be there for them to attempt.

**Comment by asottile** [comment]
In GitLab by @sigmavirus24 on Mar 1, 2017, 04:40

closed via merge request !177

**Comment by asottile** [comment]
In GitLab by @sigmavirus24 on Mar 16, 2017, 12:48

mentioned in commit asottile/flake8@733a4f053b093d0d061ce780963e936861327c95

**Comment by asottile** [comment]
In GitLab by @arcanemagus on Mar 20, 2017, 10:30

Any idea when the next release will be? I'm seeing a few reports a week that are likely caused by this (only a few confirmed though).
