### ISSUE TITLE
It seems like a bug under emacs+python mode+python3.6

### ISSUE THREAD

**Issue by asottile** [PyCQA/flake8#1053]
In GitLab by @asdyjd on Apr 10, 2017, 14:05

*Please describe how you installed Flake8*

```pip install flake8```

*Please provide the exact, unmodified output of `flake8 --bug-report`*

```
D:\>flake8 --bug-report
{
  "dependencies": [
    {
      "dependency": "setuptools",
      "version": "27.2.0"
    }
  ],
  "platform": {
    "python_implementation": "CPython",
    "python_version": "3.6.0",
    "system": "Windows"
  },
  "plugins": [
    {
      "plugin": "mccabe",
      "version": "0.6.1"
    },
    {
      "plugin": "pycodestyle",
      "version": "2.3.1"
    },
    {
      "plugin": "pyflakes",
      "version": "1.5.0"
    }
  ],
  "version": "3.3.0"
}
```
*Please describe the problem or feature*

With win10, emacs,  python-mode,  anaconda3 64bit.

Emacs hint me this:
```
Suspicious state from syntax checker python-flake8: Flycheck checker python-flake8 returned non-zero exit code 1, but its output contained no errors: Traceback (most recent call last):
  File "d:\anaconda3\lib\site-packages\flake8\checker.py", line 471, in run_ast_checks
    ast = self.processor.build_ast()
  File "d:\anaconda3\lib\site-packages\flake8\processor.py", line 211, in build_ast
    return compile(''.join(self.lines), '', 'exec', PyCF_ONLY_AST)
UnicodeEncodeError: 'utf-8' codec can't encode character '\udcab' in position 3446: surrogates not allowed

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "d:\anaconda3\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "d:\anaconda3\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "d:\Anaconda3\Scripts\flake8.exe\__main__.py", line 9, in <module>
  File "d:\anaconda3\lib\site-packages\flake8\main\cli.py", line 16, in main
    app.run(argv)
  File "d:\anaconda3\lib\site-packages\flake8\main\application.py", line 328, in run
    self._run(argv)
  File "d:\anaconda3\lib\site-packages\flake8\main\application.py", line 316, in _run
    self.run_checks()
  File "d:\anaconda3\lib\site-packages\flake8\main\application.py", line 246, in run_checks
    self.file_checker_manager.run()
  File "d:\anaconda3\lib\site-packages\flake8\checker.py", line 319, in run
    self.run_serial()
  File "d:\anaconda3\lib\site-packages\flake8\checker.py", line 303, in run_serial
    checker.run_checks()
  File "d:\anaconda3\lib\site-packages\flake8\checker.py", line 573, in run_checks
    self.run_ast_checks()
  File "d:\anaconda3\lib\site-packages\flake8\checker.py", line 474, in run_ast_checks
    row, column = self._extract_syntax_information(exception)
  File "d:\anaconda3\lib\site-packages\flake8\checker.py", line 441, in _extract_syntax_information
    if column > 0 and token and isinstance(exception, SyntaxError):
TypeError: '>' not supported between instances of 'str' and 'int'

Try installing a more recent version of python-flake8, and please open a bug report if the issue persists in the latest release.  Thanks!
```
*If this is a bug report, please explain with examples (and example code) what you expected to happen and what actually happened.*

**Comment by asottile** [comment]
In GitLab by @asdyjd on Apr 11, 2017, 04:02

changed title from **It seems like a bug under emacs+{-ycmd-}+python3.6** to **It seems like a bug under emacs+{+python mode+}+python3.6**

**Comment by asottile** [comment]
In GitLab by @sigmavirus24 on Apr 13, 2017, 05:46

This looks like a bug, yes, but I have no idea how to reproduce it if you don't give me a code sample to run Flake8 against.

**Comment by asottile** [comment]
In GitLab by @asdyjd on Apr 13, 2017, 07:09

It works in the python2.7 but not in python3.6.
Emacs hint me that for every key I input.
When I disable flycheck package.It doesn't hint me that message.

**Comment by asottile** [comment]
In GitLab by @luisgerhorst on May 1, 2017, 13:09

Seems as if I have the same problem: https://gitlab.com/pycqa/flake8/issues/331

**Comment by asottile** [comment]
In GitLab by @luisgerhorst on May 3, 2017, 01:38

I believe the problem was that Python was trying to use ASCII to encode it's output, adding 

```
(setenv "PYTHONIOENCODING" "utf8")
```

to my config fixed it.

**Comment by asottile** [comment]
In GitLab by @sigmavirus24 on May 12, 2017, 17:53

@asdyjd can you try @luisgerhorst's suggestion? That was my suspicion. That or that your LOCALE settings are a bit wonky.

**Comment by asottile** [comment]
In GitLab by @sigmavirus24 on May 27, 2017, 04:07

Closing due to inactivity and what I strong suspect is the appropriate fix. If anyone wants to revive this with more information, I'll be happy to reopen it.

**Comment by asottile** [comment]
In GitLab by @sigmavirus24 on May 27, 2017, 04:07

closed

**Comment by asottile** [comment]
In GitLab by @zarybnicky on Jul 20, 2017, 12:29

After having had the same problem, trying the suggested fix worked well.
