### ISSUE TITLE
Trouble running checkers in parallel (as a result of new pydocstyle release?)

### ISSUE THREAD

**Issue by asottile** [PyCQA/flake8#1055]
In GitLab by @tyger.tyger on Apr 18, 2017, 19:16

Our Travis-CI tests suddenly and seemingly for no reason started throwing this error when running `flake8` on any file or directory in our code base. Tried Python 2.7.12 and 3.5.2:

```
Traceback (most recent call last):
  File "/Users/gordo/.virtualenvs/am-django-project/bin/flake8", line 11, in <module>
    sys.exit(main())
  File "/Users/gordo/.virtualenvs/am-django-project/lib/python2.7/site-packages/flake8/main/cli.py", line 16, in main
    app.run(argv)
  File "/Users/gordo/.virtualenvs/am-django-project/lib/python2.7/site-packages/flake8/main/application.py", line 328, in run
    self._run(argv)
  File "/Users/gordo/.virtualenvs/am-django-project/lib/python2.7/site-packages/flake8/main/application.py", line 316, in _run
    self.run_checks()
  File "/Users/gordo/.virtualenvs/am-django-project/lib/python2.7/site-packages/flake8/main/application.py", line 246, in run_checks
    self.file_checker_manager.run()
  File "/Users/gordo/.virtualenvs/am-django-project/lib/python2.7/site-packages/flake8/checker.py", line 317, in run
    self.run_parallel()
  File "/Users/gordo/.virtualenvs/am-django-project/lib/python2.7/site-packages/flake8/checker.py", line 286, in run_parallel
    for ret in pool_map:
  File "/usr/local/Cellar/python/2.7.12_2/Frameworks/Python.framework/Versions/2.7/lib/python2.7/multiprocessing/pool.py", line 287, in <genexpr>
    return (item for chunk in result for item in chunk)
  File "/usr/local/Cellar/python/2.7.12_2/Frameworks/Python.framework/Versions/2.7/lib/python2.7/multiprocessing/pool.py", line 668, in next
    raise value
AttributeError: 'module' object has no attribute 'PEP257Checker'
```

Relevant dependencies:
```
flake8 (3.3.0)
flake8-docstrings (1.0.3)
pydocstyle (2.0.0)
```

The telling clue for me was that pydocstyle just today uploaded a [new release to pypi](https://pypi.python.org/pypi/pydocstyle). The error stops happening when I downgrade to pydocstyle 1.1.1.

**Comment by asottile** [comment]
In GitLab by @pjacock on May 1, 2017, 09:13

This should be fixed with flake8-docstrings 1.1.0 which was updated to cope with pydocstyle 2.0.0

**Comment by asottile** [comment]
In GitLab by @tyger.tyger on May 3, 2017, 18:16

Awesome. Thanks!

**Comment by asottile** [comment]
In GitLab by @tyger.tyger on May 3, 2017, 18:16

closed

**Comment by asottile** [comment]
In GitLab by @krasimir.nikolov on May 10, 2017, 02:43

Great. Thanks!
