### ISSUE TITLE
flake8 3.5.0 is incompatible with pycodestyle 2.0.0 - 2.2.0

### ISSUE THREAD

**Issue by asottile** [PyCQA/flake8#1068]
In GitLab by @ghost1 on Oct 24, 2017, 07:16

*How you installed Flake8*

via Ansible task
```
- name: install python dependencies
  become: true
  become_user: root
  pip:
    executable=pip3
    requirements={{ requirements }}
    extra_args='--upgrade'
```
with requirements file
```
flake8>=3.3.0
prospector>=0.12.5
```

*Exact, unmodified output of `flake8 --bug-report`*

It changes from run to run, either
```
Traceback (most recent call last):
  File "/usr/local/lib/python3.4/dist-packages/pkg_resources/__init__.py", line 2417, in resolve
    return functools.reduce(getattr, self.attrs, module)
AttributeError: 'module' object has no attribute 'bare_except'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.4/dist-packages/flake8/plugins/manager.py", line 178, in load_plugin
    self._load(verify_requirements)
  File "/usr/local/lib/python3.4/dist-packages/flake8/plugins/manager.py", line 150, in _load
    self._plugin = resolve()
  File "/usr/local/lib/python3.4/dist-packages/pkg_resources/__init__.py", line 2419, in resolve
    raise ImportError(str(exc))
ImportError: 'module' object has no attribute 'bare_except'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/bin/flake8", line 11, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.4/dist-packages/flake8/main/cli.py", line 16, in main
    app.run(argv)
  File "/usr/local/lib/python3.4/dist-packages/flake8/main/application.py", line 396, in run
    self._run(argv)
  File "/usr/local/lib/python3.4/dist-packages/flake8/main/application.py", line 383, in _run
    self.initialize(argv)
  File "/usr/local/lib/python3.4/dist-packages/flake8/main/application.py", line 365, in initialize
    self.find_plugins()
  File "/usr/local/lib/python3.4/dist-packages/flake8/main/application.py", line 191, in find_plugins
    self.check_plugins.load_plugins()
  File "/usr/local/lib/python3.4/dist-packages/flake8/plugins/manager.py", line 423, in load_plugins
    plugins = list(self.manager.map(load_plugin))
  File "/usr/local/lib/python3.4/dist-packages/flake8/plugins/manager.py", line 311, in map
    yield func(self.plugins[name], *args, **kwargs)
  File "/usr/local/lib/python3.4/dist-packages/flake8/plugins/manager.py", line 421, in load_plugin
    return plugin.load_plugin()
  File "/usr/local/lib/python3.4/dist-packages/flake8/plugins/manager.py", line 186, in load_plugin
    raise failed_to_load
flake8.exceptions.FailedToLoadPlugin: Flake8 failed to load plugin "pycodestyle.bare_except" due to 'module' object has no attribute 'bare_except'.
```
or
```
Traceback (most recent call last):
  File "/usr/local/lib/python3.4/dist-packages/pkg_resources/__init__.py", line 2417, in resolve
    return functools.reduce(getattr, self.attrs, module)
AttributeError: 'module' object has no attribute 'ambiguous_identifier'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.4/dist-packages/flake8/plugins/manager.py", line 178, in load_plugin
    self._load(verify_requirements)
  File "/usr/local/lib/python3.4/dist-packages/flake8/plugins/manager.py", line 150, in _load
    self._plugin = resolve()
  File "/usr/local/lib/python3.4/dist-packages/pkg_resources/__init__.py", line 2419, in resolve
    raise ImportError(str(exc))
ImportError: 'module' object has no attribute 'ambiguous_identifier'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/bin/flake8", line 11, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.4/dist-packages/flake8/main/cli.py", line 16, in main
    app.run(argv)
  File "/usr/local/lib/python3.4/dist-packages/flake8/main/application.py", line 396, in run
    self._run(argv)
  File "/usr/local/lib/python3.4/dist-packages/flake8/main/application.py", line 383, in _run
    self.initialize(argv)
  File "/usr/local/lib/python3.4/dist-packages/flake8/main/application.py", line 365, in initialize
    self.find_plugins()
  File "/usr/local/lib/python3.4/dist-packages/flake8/main/application.py", line 191, in find_plugins
    self.check_plugins.load_plugins()
  File "/usr/local/lib/python3.4/dist-packages/flake8/plugins/manager.py", line 423, in load_plugins
    plugins = list(self.manager.map(load_plugin))
  File "/usr/local/lib/python3.4/dist-packages/flake8/plugins/manager.py", line 311, in map
    yield func(self.plugins[name], *args, **kwargs)
  File "/usr/local/lib/python3.4/dist-packages/flake8/plugins/manager.py", line 421, in load_plugin
    return plugin.load_plugin()
  File "/usr/local/lib/python3.4/dist-packages/flake8/plugins/manager.py", line 186, in load_plugin
    raise failed_to_load
flake8.exceptions.FailedToLoadPlugin: Flake8 failed to load plugin "pycodestyle.ambiguous_identifier" due to 'module' object has no attribute 'ambiguous_identifier'.
```

*Describe the problem or feature*

Flake8 crashes with exceptions above when pycodestyle 2.0.0/2.1.0/2.2.0 is installed. I have this old version because prospector, which we also use, depends on it.

Currently Flake8 lists pycodestyle dependency as "pycodestyle >= 2.0.0, < 2.4.0", looks like it's incorrect. Either Flake8 needs to be fixed to work with old pycodestyle again, or dependency record needs to be adjusted.

**Comment by asottile** [comment]
In GitLab by @ghost1 on Oct 24, 2017, 07:27

changed title from **flake8 3.5.0 is incompatible with pycodestyle 2.0.0** to **flake8 3.5.0 is incompatible with pycodestyle 2.0.0{+ - 2.2.0+}**

**Comment by asottile** [comment]
In GitLab by @ghost1 on Oct 24, 2017, 07:27

changed the description

**Comment by asottile** [comment]
In GitLab by @sigmavirus24 on Oct 24, 2017, 15:04

I would happily merge a contribution that updates the lower limit to 2.3.0

**Comment by asottile** [comment]
In GitLab by @jackattack24 on Oct 27, 2017, 12:27

mentioned in merge request !212

**Comment by asottile** [comment]
In GitLab by @sigmavirus24 on Oct 28, 2017, 04:33

closed via merge request !212

**Comment by asottile** [comment]
In GitLab by @sigmavirus24 on Oct 28, 2017, 04:33

closed via commit 1ecf97005a024391fb07ad8941f4d25c4e0aae6e

**Comment by asottile** [comment]
In GitLab by @andreas-h on Aug 31, 2018, 10:15

mentioned in commit andreas-h/pyatran@8aa9b548f6adb225ebabac181967332968e56e7c

**Comment by asottile** [comment]
In GitLab by @andreas-h on Aug 31, 2018, 13:56

mentioned in commit andreas-h/pyatran@e7f395305ee73124e92f7d201350d76fbbb218e5

**Comment by asottile** [comment]
In GitLab by @andreas-h on Aug 31, 2018, 14:28

mentioned in commit andreas-h/pyatran@5c6ff5f8ce74a0ff9275c7b9a0c285ef173edd76

**Comment by asottile** [comment]
In GitLab by @andreas-h on Aug 31, 2018, 14:53

mentioned in commit andreas-h/pyatran@7e8193bc0ac1021276291e5212b32f016182531a
