### ISSUE TITLE
Verbosity config & `TypeError: '>=' not supported between instances of 'str' and 'int'`

### ISSUE THREAD

**Issue by asottile** [PyCQA/flake8#1069]
In GitLab by @nnadeau on Oct 28, 2017, 11:30

*Please describe how you installed Flake8*

```
$ pip install flake8
```

*Please provide the exact, unmodified output of `flake8 --bug-report`*

```
{
  "dependencies": [
    {
      "dependency": "setuptools",
      "version": "36.2.7"
    }
  ],
  "platform": {
    "python_implementation": "CPython",
    "python_version": "3.6.1",
    "system": "Windows"
  },
  "plugins": [
    {
      "plugin": "flake8-docstrings",
      "version": "1.1.0, pydocstyle: 2.0.0"
    },
    {
      "plugin": "mccabe",
      "version": "0.6.1"
    },
    {
      "plugin": "pycodestyle",
      "version": "2.3.1"
    },
    {
      "plugin": "pyflakes",
      "version": "1.5.0"
    }
  ],
  "version": "3.3.0"
}
```

*Please describe the problem or feature*

- Want to set flake8 verbosity in `setup.cfg`, as below:

```
[flake8]
verbose = 1
```

*If this is a bug report, please explain with examples (and example code) what you expected to happen and what actually happened.*

- The following error is thrown:

```
Traceback (most recent call last):
  File "c:\users\nicholas\appdata\local\programs\python\python36\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "c:\users\nicholas\appdata\local\programs\python\python36\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Users\nicholas\AppData\Local\Programs\Python\Python36\Scripts\flake8.exe\__main__.py", line 9, in <module>
  File "c:\users\nicholas\appdata\local\programs\python\python36\lib\site-packages\flake8\main\cli.py", line 16, in main
    app.run(argv)
  File "c:\users\nicholas\appdata\local\programs\python\python36\lib\site-packages\flake8\main\application.py", line 328, in run
    self._run(argv)
  File "c:\users\nicholas\appdata\local\programs\python\python36\lib\site-packages\flake8\main\application.py", line 316, in _run
    self.run_checks()
  File "c:\users\nicholas\appdata\local\programs\python\python36\lib\site-packages\flake8\main\application.py", line 246, in run_checks
    self.file_checker_manager.run()
  File "c:\users\nicholas\appdata\local\programs\python\python36\lib\site-packages\flake8\checker.py", line 319, in run
    self.run_serial()
  File "c:\users\nicholas\appdata\local\programs\python\python36\lib\site-packages\flake8\checker.py", line 303, in run_serial
    checker.run_checks()
  File "c:\users\nicholas\appdata\local\programs\python\python36\lib\site-packages\flake8\checker.py", line 568, in run_checks
    self.process_tokens()
  File "c:\users\nicholas\appdata\local\programs\python\python36\lib\site-packages\flake8\checker.py", line 555, in process_tokens
    self.handle_newline(token_type)
  File "c:\users\nicholas\appdata\local\programs\python\python36\lib\site-packages\flake8\checker.py", line 591, in handle_newline
    self.run_logical_checks()
  File "c:\users\nicholas\appdata\local\programs\python\python36\lib\site-packages\flake8\checker.py", line 507, in run_logical_checks
    for offset, text in results:
  File "c:\users\nicholas\appdata\local\programs\python\python36\lib\site-packages\pycodestyle.py", line 501, in continued_indentation
    if verbose >= 3:
TypeError: '>=' not supported between instances of 'str' and 'int'
```

## Notes
- The passing of `verbose` from `flake8` to `pycodestyle` is not converted `int`
- I'm not sure is this issue belongs here or in https://gitlab.com/pycqa/flake8-docstrings

**Comment by asottile** [comment]
In GitLab by @sigmavirus24 on Oct 28, 2017, 14:42

Can you reproduce this on the latest version?

**Comment by asottile** [comment]
In GitLab by @nnadeau on Oct 29, 2017, 08:02

Nope, it works with the following. My bad for not having the latest release.

```
{
  "dependencies": [
    {
      "dependency": "setuptools",
      "version": "36.2.7"
    }
  ],
  "platform": {
    "python_implementation": "CPython",
    "python_version": "3.6.1",
    "system": "Windows"
  },
  "plugins": [
    {
      "is_local": false,
      "plugin": "flake8-docstrings",
      "version": "1.1.0, pydocstyle: 2.1.1"
    },
    {
      "is_local": false,
      "plugin": "mccabe",
      "version": "0.6.1"
    },
    {
      "is_local": false,
      "plugin": "pycodestyle",
      "version": "2.3.1"
    },
    {
      "is_local": false,
      "plugin": "pyflakes",
      "version": "1.6.0"
    }
  ],
  "version": "3.5.0"
}
```

**Comment by asottile** [comment]
In GitLab by @nnadeau on Oct 29, 2017, 08:02

closed
