### ISSUE TITLE
Option Conflict error on flake8 >= 3.7

### ISSUE THREAD

**Issue by asottile** [PyCQA/flake8#1089]
In GitLab by @matthieugouel on Apr 14, 2019, 14:48

Hi, I have the following issue running flake8 on MacOS Mojave with Python3.7 in userland with flake8 >= 3.7 (the problem does not appear in a virtualenv).

*Please describe how you installed Flake8*

```
$ pip install --user flake8
```

*Please provide the exact, unmodified output of `flake8 --bug-report`*

```
Traceback (most recent call last):
  File "/usr/local/bin/flake8", line 10, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.7/site-packages/flake8/main/cli.py", line 18, in main
    app.run(argv)
  File "/usr/local/lib/python3.7/site-packages/flake8/main/application.py", line 394, in run
    self._run(argv)
  File "/usr/local/lib/python3.7/site-packages/flake8/main/application.py", line 381, in _run
    self.initialize(argv)
  File "/usr/local/lib/python3.7/site-packages/flake8/main/application.py", line 365, in initialize
    self.register_plugin_options()
  File "/usr/local/lib/python3.7/site-packages/flake8/main/application.py", line 206, in register_plugin_options
    self.check_plugins.register_options(self.option_manager)
  File "/usr/local/lib/python3.7/site-packages/flake8/plugins/manager.py", line 496, in register_options
    list(self.manager.map(register_and_enable))
  File "/usr/local/lib/python3.7/site-packages/flake8/plugins/manager.py", line 302, in map
    yield func(self.plugins[name], *args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/flake8/plugins/manager.py", line 492, in register_and_enable
    call_register_options(plugin)
  File "/usr/local/lib/python3.7/site-packages/flake8/plugins/manager.py", line 404, in generated_function
    return method(optmanager, *args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/flake8/plugins/manager.py", line 221, in register_options
    add_options(optmanager)
  File "/usr/local/lib/python3.7/site-packages/flake8/plugins/pyflakes.py", line 103, in add_options
    help="define more built-ins, comma separated",
  File "/usr/local/lib/python3.7/site-packages/flake8/options/manager.py", line 230, in add_option
    self.parser.add_option(option.to_optparse())
  File "/usr/local/Cellar/python/3.7.1/Frameworks/Python.framework/Versions/3.7/lib/python3.7/optparse.py", line 1008, in add_option
    self._check_conflict(option)
  File "/usr/local/Cellar/python/3.7.1/Frameworks/Python.framework/Versions/3.7/lib/python3.7/optparse.py", line 983, in _check_conflict
    option)
optparse.OptionConflictError: option --builtins: conflicting option string(s): --builtins
```

Best, 
Matthieu.

**Comment by asottile** [comment]
In GitLab by @asottile on Apr 14, 2019, 14:50

Could you fill this out please?

*Please provide the exact, unmodified output of `flake8 --bug-report`*

**Comment by asottile** [comment]
In GitLab by @matthieugouel on Apr 14, 2019, 14:53

The traceback is appearing for any option on `flake8` command including `--bug-report` so unfortunately I don't have any additional information.

**Comment by asottile** [comment]
In GitLab by @asottile on Apr 14, 2019, 14:54

hmmmm, how about `pip freeze --all`

**Comment by asottile** [comment]
In GitLab by @matthieugouel on Apr 14, 2019, 14:59

```
appdirs==1.4.3
appnope==0.1.0
arrow==0.12.1
attrs==18.2.0
backcall==0.1.0
bandit==1.5.1
binaryornot==0.4.4
black==18.9b0
CacheControl==0.12.5
cachy==0.2.0
certifi==2018.8.24
chardet==3.0.4
cleo==0.6.8
click==6.7
cookiecutter==1.6.0
decorator==4.3.0
entrypoints==0.3
flake8==3.7.7
future==0.16.0
gitdb2==2.0.5
GitPython==2.1.11
html5lib==1.0.1
idna==2.7
ipython==7.0.1
ipython-genutils==0.2.0
jedi==0.12.1
Jinja2==2.10
jinja2-time==0.2.0
jsonschema==3.0.1
lockfile==0.12.2
MarkupSafe==1.0
mccabe==0.6.1
msgpack==0.6.1
mypy==0.641
mypy-extensions==0.4.1
parso==0.3.1
pastel==0.1.0
pbr==5.1.1
pew==1.1.5
pexpect==4.6.0
pickleshare==0.7.4
pip==19.0.3
pipenv==2018.11.26
pkginfo==1.5.0.1
poetry==0.12.12
poyo==0.4.1
prompt-toolkit==2.0.5
ptyprocess==0.6.0
pycodestyle==2.5.0
pyflakes==2.1.1
Pygments==2.2.0
pylev==1.3.0
pyparsing==2.4.0
pyrsistent==0.14.11
python-dateutil==2.7.3
PyYAML==3.13
requests==2.19.1
requests-toolbelt==0.8.0
setuptools==40.5.0
shellingham==1.3.1
simplegeneric==0.8.1
six==1.11.0
smmap2==2.0.5
stevedore==1.30.0
toml==0.10.0
tomlkit==0.5.3
traitlets==4.3.2
typed-ast==1.1.0
urllib3==1.23
virtualenv==16.0.0
virtualenv-clone==0.3.0
wcwidth==0.1.7
webencodings==0.5.1
wheel==0.32.2
whichcraft==0.4.1
```

I created a new virtualenv and installed flake 8 and its dependencies was in the same version yet it works on the virtualenv. I don't get the difference beside the others packages that maybe could spoil other dependencies. 

The traceback indicates `pyflakes` but the version is the same and it does not have any dependencies.

**Comment by asottile** [comment]
In GitLab by @matthieugouel on Apr 14, 2019, 15:02

In a virtualenv I have this freeze and it works perfectly : 

```
appdirs         1.4.3
atomicwrites    1.3.0
attrs           19.1.0
black           18.9b0
Click           7.0
cycler          0.10.0
entrypoints     0.3
flake8          3.7.7
kiwisolver      1.0.1
matplotlib      3.0.3
mccabe          0.6.1
more-itertools  7.0.0
mypy            0.700
mypy-extensions 0.4.1
numpy           1.16.2
pandas          0.24.2
pip             19.0.3
pluggy          0.9.0
py              1.8.0
pycodestyle     2.5.0
pyflakes        2.1.1
pyparsing       2.4.0
pytest          3.10.1
python-dateutil 2.8.0
pytz            2019.1
scikit-learn    0.20.3
scipy           1.2.1
setuptools      39.0.1
six             1.12.0
toml            0.10.0
typed-ast       1.3.1
```

and the version of python is the same : 

```
Python 3.7.1
```

**Comment by asottile** [comment]
In GitLab by @asottile on Apr 14, 2019, 15:08

Can you try `/usr/local/bin/python3.7 -mpip freeze` instead maybe?

**Comment by asottile** [comment]
In GitLab by @matthieugouel on Apr 14, 2019, 23:23

It looks like the same : 
```
appdirs==1.4.3
appnope==0.1.0
arrow==0.12.1
attrs==18.2.0
backcall==0.1.0
bandit==1.5.1
binaryornot==0.4.4
black==18.9b0
CacheControl==0.12.5
cachy==0.2.0
certifi==2018.8.24
chardet==3.0.4
cleo==0.6.8
click==6.7
cookiecutter==1.6.0
decorator==4.3.0
entrypoints==0.3
flake8==3.7.7
future==0.16.0
gitdb2==2.0.5
GitPython==2.1.11
html5lib==1.0.1
idna==2.7
ipython==7.0.1
ipython-genutils==0.2.0
jedi==0.12.1
Jinja2==2.10
jinja2-time==0.2.0
jsonschema==3.0.1
lockfile==0.12.2
MarkupSafe==1.0
mccabe==0.6.1
msgpack==0.6.1
mypy==0.641
mypy-extensions==0.4.1
parso==0.3.1
pastel==0.1.0
pbr==5.1.1
pew==1.1.5
pexpect==4.6.0
pickleshare==0.7.4
pipenv==2018.11.26
pkginfo==1.5.0.1
poetry==0.12.12
poyo==0.4.1
prompt-toolkit==2.0.5
ptyprocess==0.6.0
pycodestyle==2.5.0
pyflakes==2.1.1
Pygments==2.2.0
pylev==1.3.0
pyparsing==2.4.0
pyrsistent==0.14.11
python-dateutil==2.7.3
PyYAML==3.13
requests==2.19.1
requests-toolbelt==0.8.0
shellingham==1.3.1
simplegeneric==0.8.1
six==1.11.0
smmap2==2.0.5
stevedore==1.30.0
toml==0.10.0
tomlkit==0.5.3
traitlets==4.3.2
typed-ast==1.1.0
urllib3==1.23
virtualenv==16.0.0
virtualenv-clone==0.3.0
wcwidth==0.1.7
webencodings==0.5.1
whichcraft==0.4.1
```

I also tried to do the following command with no more success : 
```
/usr/local/bin/python3.7 -m flake8
```

**Comment by asottile** [comment]
In GitLab by @asottile on Apr 14, 2019, 23:29

That's very strange, the error almost looks like multiple copies of flake8 are somehow installed...

Can you try running this for me?

```
find /usr/local/lib/python3.7 -iname '*flake8*'
```

**Comment by asottile** [comment]
In GitLab by @matthieugouel on Apr 14, 2019, 23:37

You are absolutly right. The result of the command is : 
```
/usr/local/lib/python3.7/site-packages/flake8
/usr/local/lib/python3.7/site-packages/flake8/example-plugin/src/flake8_example_plugin
/usr/local/lib/python3.7/site-packages/flake8/tests/fixtures/config_files/no-flake8-section.ini
/usr/local/lib/python3.7/site-packages/flake8/src/flake8
/usr/local/lib/python3.7/site-packages/flake8/src/flake8.egg-info
/usr/local/lib/python3.7/site-packages/flake8-3.7.7.dist-info
```

whereas with a former version of python : 
```
/usr/local/lib/python3.6/site-packages/flake8
/usr/local/lib/python3.6/site-packages/flake8-3.5.0.dist-info
```

I wiped everything under `/usr/local/lib/python3.7/site-packages/` and made a clean install of flake8 using pip and everything is working again. 

Thank you so much for your help your responsiveness !

Best,

Matthieu.

**Comment by asottile** [comment]
In GitLab by @matthieugouel on Apr 14, 2019, 23:37

closed

**Comment by asottile** [comment]
In GitLab by @asottile on Apr 14, 2019, 23:40

ah, looks like at some point you had (maybe) done `pip install -e git+https://gitlab.com/pycqa/flake8.git` or something of the sort

pip has a hard time keeping track of these installs since they don't go through the normal install process, sometimes leading to multiple installs of the same package (yikes!)

probably would have also been sufficient to:

```
pip uninstall -y flake8
pip uninstall -y flake8
pip install flake8
```

cool that we found the issue though :tada:
