### ISSUE TITLE
KeyError default formatting plugin

### ISSUE THREAD

**Issue by asottile** [PyCQA/flake8#1103]
In GitLab by @Dreamsorcerer on Jul 1, 2019, 12:02

I installed a number of plugins to try out. But now I am getting an error, with no indication as to which plugin might have caused it.

```
Traceback (most recent call last):
  File "/usr/local/bin/flake8", line 10, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.7/site-packages/flake8/main/cli.py", line 18, in main
    app.run(argv)
  File "/usr/local/lib/python3.7/site-packages/flake8/main/application.py", line 394, in run
    self._run(argv)
  File "/usr/local/lib/python3.7/site-packages/flake8/main/application.py", line 381, in _run
    self.initialize(argv)
  File "/usr/local/lib/python3.7/site-packages/flake8/main/application.py", line 367, in initialize
    self.make_formatter()
  File "/usr/local/lib/python3.7/site-packages/flake8/main/application.py", line 261, in make_formatter
    formatter_class = self.formatter_for(format_plugin)
  File "/usr/local/lib/python3.7/site-packages/flake8/main/application.py", line 239, in formatter_for
    default_formatter = self.formatting_plugins["default"]
  File "/usr/local/lib/python3.7/site-packages/flake8/plugins/manager.py", line 369, in __getitem__
    return self.plugins[name]
KeyError: ‘default'
```

--bug-report:
```
{
  "dependencies": [
    {
      "dependency": "entrypoints",
      "version": "0.3"
    }
  ],
  "platform": {
    "python_implementation": "CPython",
    "python_version": "3.7.3",
    "system": "Darwin"
  },
  "plugins": [
    {
      "is_local": false,
      "plugin": "aaa",
      "version": "0.6.1"
    },
    {
      "is_local": false,
      "plugin": "assertive",
      "version": "1.1.0"
    },
    {
      "is_local": false,
      "plugin": "flake8-annotations-complexity",
      "version": "0.0.2"
    },
    {
      "is_local": false,
      "plugin": "flake8-bandit",
      "version": "2.1.1"
    },
    {
      "is_local": false,
      "plugin": "flake8-broken-line",
      "version": "0.1.0"
    },
    {
      "is_local": false,
      "plugin": "flake8-bugbear",
      "version": "19.3.0"
    },
    {
      "is_local": false,
      "plugin": "flake8-comprehensions",
      "version": "2.1.0"
    },
    {
      "is_local": false,
      "plugin": "flake8-confusables",
      "version": "0.1.0"
    },
    {
      "is_local": false,
      "plugin": "flake8-debugger",
      "version": "3.1.0"
    },
    {
      "is_local": false,
      "plugin": "flake8-docstrings",
      "version": "1.3.0, pydocstyle: 3.0.0"
    },
    {
      "is_local": false,
      "plugin": "flake8-eradicate",
      "version": "0.2.0"
    },
    {
      "is_local": false,
      "plugin": "flake8-executable",
      "version": "2.0.1"
    },
    {
      "is_local": false,
      "plugin": "flake8-lineleak",
      "version": "1.0.2"
    },
    {
      "is_local": false,
      "plugin": "flake8-mypy",
      "version": "17.8.0"
    },
    {
      "is_local": false,
      "plugin": "flake8-print",
      "version": "3.1.0"
    },
    {
      "is_local": false,
      "plugin": "flake8-requires",
      "version": "1.1.1"
    },
    {
      "is_local": false,
      "plugin": "flake8-return",
      "version": "0.1.3"
    },
    {
      "is_local": false,
      "plugin": "flake8-sorted-keys",
      "version": "0.2.0"
    },
    {
      "is_local": false,
      "plugin": "flake8-spellcheck",
      "version": "0.8.1"
    },
    {
      "is_local": false,
      "plugin": "flake8-string-format",
      "version": "0.2.3"
    },
    {
      "is_local": false,
      "plugin": "flake8-type-annotations",
      "version": "0.1.0"
    },
    {
      "is_local": false,
      "plugin": "flake8.datetimez",
      "version": "19.5.4.0"
    },
    {
      "is_local": false,
      "plugin": "flake8_builtins",
      "version": "1.4.1"
    },
    {
      "is_local": false,
      "plugin": "flake8_coding",
      "version": "1.3.2"
    },
    {
      "is_local": false,
      "plugin": "flake8_commas",
      "version": "2.0.0"
    },
    {
      "is_local": false,
      "plugin": "flake8_isort",
      "version": "2.3"
    },
    {
      "is_local": false,
      "plugin": "flake8_multiline_containers",
      "version": "0.0.3"
    },
    {
      "is_local": false,
      "plugin": "flake8_ownership",
      "version": "2.0.0"
    },
    {
      "is_local": false,
      "plugin": "flake8_pep3101",
      "version": "1.2.1"
    },
    {
      "is_local": false,
      "plugin": "flake8_quotes",
      "version": "2.0.1"
    },
    {
      "is_local": false,
      "plugin": "good-smell",
      "version": "0.1"
    },
    {
      "is_local": false,
      "plugin": "import-order",
      "version": "0.18.1"
    },
    {
      "is_local": false,
      "plugin": "logging-format",
      "version": "0.6.0"
    },
    {
      "is_local": false,
      "plugin": "mccabe",
      "version": "0.6.1"
    },
    {
      "is_local": false,
      "plugin": "naming",
      "version": "0.8.2"
    },
    {
      "is_local": false,
      "plugin": "sql",
      "version": "0.3.0"
    },
    {
      "is_local": false,
      "plugin": "wemake-python-styleguide",
      "version": "0.9.0"
    }
  ],
  "version": "3.7.7"
}
```

**Comment by asottile** [comment]
In GitLab by @asottile on Jul 1, 2019, 12:15

Have you done any effort to narrow down which is the broken plugin?

**Comment by asottile** [comment]
In GitLab by @Dreamsorcerer on Jul 1, 2019, 12:17

I tried printing things from within flake8's code, but didn't get anywhere useful. As there is no way obvious way to disable plugins, I suppose the only way to narrow it down is to uninstall and reinstall plugins, which could take some time.

**Comment by asottile** [comment]
In GitLab by @asottile on Jul 1, 2019, 12:25

yeah I would suggest uninstalling things

**Comment by asottile** [comment]
In GitLab by @Dreamsorcerer on Jul 1, 2019, 13:03

But, my main point of the bug report, is that it is difficult to see which plugin is causing the issue. A couple of the plugins have caused other errors, but the errors were very clear as to which plugin was the problem.

**Comment by asottile** [comment]
In GitLab by @asottile on Jul 1, 2019, 13:04

yeah but the thing that would have to happen is a plugin would have to reach into flake8's private implementation detail and delete stuff -- or the installation of flake8 is broken.  either of which aren't things worth defending against imo

**Comment by asottile** [comment]
In GitLab by @asottile on Jul 1, 2019, 13:31

so I installed all of those plugins (minus `confusables` and `ownership` which appear to be broken) and it works fine for me -- this makes me think your `flake8` installation is corrupted in some way.  I'd suggest uninstalling that (2-3 times until it's definitely gone) and then reinstalling.

**Comment by asottile** [comment]
In GitLab by @Pierre-Sassoulas on Jul 1, 2019, 13:33

I don't know if I understood the code correctly, but I think that the default value that is expected in `main/application.py` should not be defined in the configuration file. Even if we want this to be in the configuration file without default value, the error message should be clearer. Something like "Please add a default formatter in your plugin configuration for example : ```{
   plugins = {
     default="custom.default_formatter"
     ...
  }
}```
"

Reading the last comment by @asottile maybe it should be `Your flake8 installation is broken we can't find the default formatter` ?

**Comment by asottile** [comment]
In GitLab by @asottile on Jul 1, 2019, 13:42

There's an infinite number of situations where one could break the installation by running the wrong `rm` commands. Defending against this in code is not worth it

**Comment by asottile** [comment]
In GitLab by @asottile on Jul 3, 2019, 09:08

closed

**Comment by asottile** [comment]
In GitLab by @Dreamsorcerer on Jul 3, 2019, 12:34

Yep, so I uninstalled the 2 broken plugins (which I had manually fixed), uninstalled flake8. Then reinstalled it. It is now working just fine. After reinstalling flake8-confusables, I got a completely different error from last time (I fixed the one about missing files), so I'm not sure what is going on with that plugin.

**Comment by asottile** [comment]
In GitLab by @asottile on Jul 3, 2019, 14:14

`flake8-confusables` is a weird one indeed.  From following some of the history `flake8-confusables` used to depend on a package called `confusables` (~around 2017).  The `confusables` package was abandoned and someone else snatched up the name and produced a new "confusables" package.  This package was completely broken, but I [fixed it for no reason](https://github.com/woodgern/confusables/pull/9)

Anyway, the `flake8-confusables` expects the old package -- seems abandonware I'd probably avoid it ;)
