### ISSUE TITLE
Flake8>=3.8.0: 'Namespace' object has no attribute 'output_file'

### ISSUE THREAD

**Issue by asottile** [PyCQA/flake8#1112]
In GitLab by @skirpichev on May 12, 2020, 02:47

This error come from flake8-rst:
```
# flake8-rst
Traceback (most recent call last):
  File "/opt/hostedtoolcache/Python/3.7.6/x64/bin/flake8-rst", line 8, in <module>
    sys.exit(main())
  File "/opt/hostedtoolcache/Python/3.7.6/x64/lib/python3.7/site-packages/flake8_rst/cli.py", line 16, in main
    app.run(argv)
  File "/opt/hostedtoolcache/Python/3.7.6/x64/lib/python3.7/site-packages/flake8/main/application.py", line 360, in run
    self._run(argv)
  File "/opt/hostedtoolcache/Python/3.7.6/x64/lib/python3.7/site-packages/flake8/main/application.py", line 347, in _run
    self.initialize(argv)
  File "/opt/hostedtoolcache/Python/3.7.6/x64/lib/python3.7/site-packages/flake8/main/application.py", line 333, in initialize
    self.make_formatter()
  File "/opt/hostedtoolcache/Python/3.7.6/x64/lib/python3.7/site-packages/flake8/main/application.py", line 226, in make_formatter
    self.formatter = formatter_class(self.options)
  File "/opt/hostedtoolcache/Python/3.7.6/x64/lib/python3.7/site-packages/flake8/plugins/manager.py", line 131, in execute
    return self.plugin(*args, **kwargs)  # pylint: disable=not-callable
  File "/opt/hostedtoolcache/Python/3.7.6/x64/lib/python3.7/site-packages/flake8/formatting/base.py", line 48, in __init__
    self.filename = options.output_file
AttributeError: 'Namespace' object has no attribute 'output_file'
```
See full [build logs](https://github.com/diofant/diofant/actions/runs/102266133).

**Comment by asottile** [comment]
In GitLab by @sigmavirus24 on May 12, 2020, 04:16

Does this happen with _just_ flake8?

**Comment by asottile** [comment]
In GitLab by @skirpichev on May 12, 2020, 04:42

@sigmavirus24, I don't know.   Maybe flake8-rst wrongly uses your plugin API, but right now it seems to me as a flake8 issue.

**Comment by asottile** [comment]
In GitLab by @sigmavirus24 on May 12, 2020, 05:08

We don't have a public API the way that project uses flake8 so to me it
seems like flake8-rst is using things incorrectly and you're suffering for
it

**Comment by asottile** [comment]
In GitLab by @skirpichev on May 12, 2020, 05:30

So, you think I should reopen this issue against flake8-rst repo?

Any glue on _how_ flake8-rst is using things incorrectly?

**Comment by asottile** [comment]
In GitLab by @ericvw on May 12, 2020, 06:25

@skirpichev There was a regression in `flake8==3.8.0` with respect to `--output-file` (see #637).  Can you please confirm if you still observe this issue with `flake8 >= 3.8.1`.  Thanks.

**Comment by asottile** [comment]
In GitLab by @skirpichev on May 12, 2020, 07:03

Yes.  The referenced above build logs are for flake8==3.8.1.

**Comment by asottile** [comment]
In GitLab by @ericvw on May 12, 2020, 07:19

Thank you for confirming.  The referenced build logs URI expired, so I was unable to see what version was being used.

**Comment by asottile** [comment]
In GitLab by @ericvw on May 12, 2020, 07:27

`flake8-rst` is using a private API here and is using `flake8` incorrectly.

**Comment by asottile** [comment]
In GitLab by @asottile on May 12, 2020, 07:29

indeed, was about to comment the same -- thanks for the investigation @ericvw

**Comment by asottile** [comment]
In GitLab by @asottile on May 12, 2020, 07:29

closed

**Comment by asottile** [comment]
In GitLab by @skirpichev on May 12, 2020, 07:40

changed the description

**Comment by asottile** [comment]
In GitLab by @skirpichev on May 12, 2020, 07:41

Sorry, corrected.

**Comment by asottile** [comment]
In GitLab by @skirpichev on May 12, 2020, 07:43

Ok, thank you for "explanation".

**Comment by asottile** [comment]
In GitLab by @ericvw on Oct 21, 2020, 10:16

mentioned in merge request !458
