### ISSUE TITLE
OSError Errno 28 / semaphores on Mac OS X

### ISSUE THREAD

**Issue by asottile** [PyCQA/flake8#117]
In GitLab by @mcandre on Jul 9, 2015, 14:50

From time to time, flake8 crashes with `IOError: [Errno 28] No space left on device`, related to semaphores, on Mac OS X. This happens for any Python file I try to lint with flake8.

System:

```
flake8 --version
2.3.0 (pep8: 1.6.2, pyflakes: 0.9.2, mccabe: 0.3.1) CPython 3.3.6 on Darwin
```

Mac OS X 10.10.4

Mitigation:

Rebooting my Mac temporarily fixes the problem.

**Comment by asottile** [comment]
In GitLab by @sigmavirus24 on Jul 10, 2015, 06:08

Could you provide the full traceback? We rely on multiprocessing (from the standard library) if there are exceptions being raised about semaphores, then they're probably coming from [here](https://hg.python.org/cpython/file/ddb839c239d9/Lib/multiprocessing/semaphore_tracker.py). I haven't seen this on OSX at all.

If this is a persistent problem, try adjusting the `--jobs` flag.

**Comment by asottile** [comment]
In GitLab by @mcandre on Jul 10, 2015, 12:02

Trace:

```
flake8 python/Shoutlet/command/pubsub/email_notifications.py
Traceback (most recent call last):
  File "/Users/bryan.nelson/.python/bin/flake8", line 11, in <module>
    sys.exit(main())
  File "/Users/bryan.nelson/.python/lib/python3.3/site-packages/flake8/main.py", line 24, in main
    flake8_style = get_style_guide(parse_argv=True, config_file=DEFAULT_CONFIG)
  File "/Users/bryan.nelson/.python/lib/python3.3/site-packages/flake8/engine.py", line 141, in get_style_guide
    report = styleguide.init_report(reporter)
  File "/Users/bryan.nelson/.python/lib/python3.3/site-packages/pep8.py", line 1817, in init_report
    self.options.report = (reporter or self.options.reporter)(self.options)
  File "/Users/bryan.nelson/.python/lib/python3.3/site-packages/pep8.py", line 1711, in __init__
    super(StandardReport, self).__init__(options)
  File "/Users/bryan.nelson/.python/lib/python3.3/site-packages/flake8/reporter.py", line 28, in __init__
    self.task_queue = multiprocessing.Queue()
  File "/usr/local/Cellar/python3/3.3.5/Frameworks/Python.framework/Versions/3.3/lib/python3.3/multiprocessing/__init__.py", line 201, in Queue
    return Queue(maxsize)
  File "/usr/local/Cellar/python3/3.3.5/Frameworks/Python.framework/Versions/3.3/lib/python3.3/multiprocessing/queues.py", line 38, in __init__
    self._rlock = Lock()
  File "/usr/local/Cellar/python3/3.3.5/Frameworks/Python.framework/Versions/3.3/lib/python3.3/multiprocessing/synchronize.py", line 120, in __init__
    SemLock.__init__(self, SEMAPHORE, 1, 1)
  File "/usr/local/Cellar/python3/3.3.5/Frameworks/Python.framework/Versions/3.3/lib/python3.3/multiprocessing/synchronize.py", line 48, in __init__
    sl = self._semlock = _multiprocessing.SemLock(kind, value, maxvalue)
OSError: [Errno 28] No space left on device
```

**Comment by asottile** [comment]
In GitLab by @cank on Jul 19, 2015, 08:20

Me too with the exact same traceback, on OS X 10.10. Versions:

```
$ flake8 --version
2.4.1 (pep8: 1.6.2, pyflakes: 0.8.1, mccabe: 0.3.1) CPython 3.4.3 on Darwin
```

This happens out of nowhere. Flake8 works for a while, maybe several days. Only solution is to restart the computer. This issue is isolated to flake8. I don't seem to have any disk space issues.

**Comment by asottile** [comment]
In GitLab by @sigmavirus24 on Jul 19, 2015, 09:15

So this seems to be a problem that is [seen with the multiprocessing](https://stackoverflow.com/questions/28788319/no-space-left-on-device-when-creating-semaphore) module in general on OSX.

The only solution I can really offer is a fallback to not using multiprocessing when we see that exception. Can one of you confirm that when this happens running 

`flake8 -j0` is sufficient to bypass the problem?

**Comment by asottile** [comment]
In GitLab by @cank on Jul 19, 2015, 09:58

I can confirm -j0 fixes this. I added this to my `~/.config/flake8` file to make change global:

```config
[flake8]
jobs = 1
```

Thanks!

**Comment by asottile** [comment]
In GitLab by @sigmavirus24 on Aug 19, 2015, 18:36

mentioned in commit 1c6c1f51163784005dac358d60ecb8781d726151

**Comment by asottile** [comment]
In GitLab by @sigmavirus24 on Aug 19, 2015, 18:38

mentioned in merge request !36

**Comment by asottile** [comment]
In GitLab by @sigmavirus24 on Aug 22, 2015, 17:48

mentioned in commit f1aa58889df0af538e5dc97047bc441edfe61a1d

**Comment by asottile** [comment]
In GitLab by @sigmavirus24 on Aug 22, 2015, 17:50

mentioned in merge request !36

**Comment by asottile** [comment]
In GitLab by @sigmavirus24 on Aug 22, 2015, 17:59

Status changed to closed by commit 9d734158ca72c264810c6a4c2d22c3c3160864b1

**Comment by asottile** [comment]
In GitLab by @sigmavirus24 on Aug 22, 2015, 17:59

mentioned in commit a1154e41dfc858c9520563ec41eb11982fc191ad

**Comment by asottile** [comment]
In GitLab by @sigmavirus24 on Mar 28, 2016, 14:22

mentioned in merge request !57
