### ISSUE TITLE
Python 3.6 support

### ISSUE THREAD

**Issue by asottile** [PyCQA/flake8#119]
In GitLab by @Wooble on Jul 24, 2015, 10:43

In Python 3.6, the deprecated `inspect.getargspec` is being removed. This breaks flake8.

Output from Travis, using "nightly" python environment:

    Traceback (most recent call last):
      File "/home/travis/virtualenv/python3.6-dev/bin/flake8", line 7, in <module>
        from flake8.main import main
      File "/home/travis/virtualenv/python3.6-dev/lib/python3.6/site-packages/flake8/main.py", line 8, in <module>
        from flake8.engine import get_parser, get_style_guide
      File "/home/travis/virtualenv/python3.6-dev/lib/python3.6/site-packages/flake8/engine.py", line 6, in <module>
        import pep8
      File "/home/travis/virtualenv/python3.6-dev/lib/python3.6/site-packages/pep8.py", line 1204, in <module>
        init_checks_registry()
      File "/home/travis/virtualenv/python3.6-dev/lib/python3.6/site-packages/pep8.py", line 1203, in init_checks_registry
        register_check(function)
      File "/home/travis/virtualenv/python3.6-dev/lib/python3.6/site-packages/pep8.py", line 1186, in register_check
        args = inspect.getargspec(check)[0]
    AttributeError: module 'inspect' has no attribute 'getargspec'

**Comment by asottile** [comment]
In GitLab by @sigmavirus24 on Jul 24, 2015, 10:47

Please read the traceback more closely. This

**Comment by asottile** [comment]
In GitLab by @Wooble on Jul 24, 2015, 10:48

Err... yeah. sorry about that.

**Comment by asottile** [comment]
In GitLab by @sigmavirus24 on Jul 24, 2015, 11:13

Sorry my phone at the rest of that message. What I meant to say was

> This is coming out of pep8 and has already been fixed in that project.
