### ISSUE TITLE
Allow None in the normalize_path(s) functions - [closed]

### ISSUE THREAD

**Issue by asottile** [PyCQA/flake8#1217]
In GitLab by @pjacock on Aug 8, 2019, 03:51

_Merges norm_none_path -> master_

This is to enable using ``default=None, normalize_paths=True`` in a configuration setting where it is important to be able to tell apart not set (still ``None``) and set to an empty string.

I am unclear how to update the ``:rtype:`` annotation etc to indicate ``str`` or ``None``.

Motivating example to follow as a comment.

**Comment by asottile** [comment]
In GitLab by @pjacock on Aug 8, 2019, 03:57

[setup.py](/uploads/05c8ded8e91a8e545f9d489ec99204e7/setup.py)

[flake8_none_path.py](/uploads/0e0f35ab33f75a9143452fa7f6e1c2bf/flake8_none_path.py)

With the patched flake8, and not using a config file:

```
$ flake8 --isolated -v . 2>&1 | grep example
flake8                    MainProcess    161 INFO     flake8-example: example-file=None
$ flake8 --isolated --example-file '' -v . 2>&1 | grep example
flake8                    MainProcess    161 INFO     flake8-example: example-file=''
$ flake8 --isolated --example-file "" -v . 2>&1 | grep example
flake8                    MainProcess    162 INFO     flake8-example: example-file=''
$ flake8 --isolated --example-file wibble.txt -v . 2>&1 | grep example
flake8                    MainProcess    161 INFO     flake8-example: example-file='wibble.txt'
```

The code can distinguish ``None`` (no user setting supplied, remains with default value) and the empty string (which would mean do not use any external file), or the more typical use case of an arbitrary filename (here ``wibble.txt``).

This works nicely with configuration files too.

**Comment by asottile** [comment]
In GitLab by @pjacock on Aug 8, 2019, 04:44

With flake8 v3.7.8 unpatched, all the examples fail with an exception like the following:

```
$ flake8 -h
Traceback (most recent call last):
  File "/Users/xxx/miniconda3/bin/flake8", line 10, in <module>
    sys.exit(main())
  File "/Users/xxx/miniconda3/lib/python3.7/site-packages/flake8/main/cli.py", line 18, in main
    app.run(argv)
  File "/Users/xxx/miniconda3/lib/python3.7/site-packages/flake8/main/application.py", line 393, in run
    self._run(argv)
  File "/Users/xxx/miniconda3/lib/python3.7/site-packages/flake8/main/application.py", line 380, in _run
    self.initialize(argv)
  File "/Users/xxx/miniconda3/lib/python3.7/site-packages/flake8/main/application.py", line 365, in initialize
    self.parse_configuration_and_cli(argv)
  File "/Users/xxx/miniconda3/lib/python3.7/site-packages/flake8/main/application.py", line 218, in parse_configuration_and_cli
    self.option_manager, self.config_finder, argv
  File "/Users/xxx/miniconda3/lib/python3.7/site-packages/flake8/options/aggregator.py", line 33, in aggregate_options
    default_values, _ = manager.parse_args([], values=values)
  File "/Users/xxx/miniconda3/lib/python3.7/site-packages/flake8/options/manager.py", line 314, in parse_args
    self._normalize(options)
  File "/Users/xxx/miniconda3/lib/python3.7/site-packages/flake8/options/manager.py", line 307, in _normalize
    setattr(options, option.dest, option.normalize(old_value))
  File "/Users/xxx/miniconda3/lib/python3.7/site-packages/flake8/options/manager.py", line 150, in normalize
    return normalize(value, *normalize_args)
  File "/Users/xxx/miniconda3/lib/python3.7/site-packages/flake8/utils.py", line 189, in normalize_path
    if separator in path or (
TypeError: argument of type 'NoneType' is not iterable
```

**Comment by asottile** [comment]
In GitLab by @pjacock on Aug 8, 2019, 05:05

restored source branch `norm_none_path`

**Comment by asottile** [comment]
In GitLab by @codecov on Aug 8, 2019, 05:12

# [Codecov](https://codecov.io/gl/pycqa/flake8/pull/337?src=pr&el=h1) Report
> Merging [#337](https://codecov.io/gl/pycqa/flake8/pull/337?src=pr&el=desc) into [master](https://codecov.io/gl/pycqa/flake8/commit/d43d498d419fa1a0ec1489301d29d50fdd5be3f9?src=pr&el=desc) will **decrease** coverage by `0.06%`.
> The diff coverage is `0%`.

[![Impacted file tree graph](https://codecov.io/gl/pycqa/flake8/pull/337/graphs/tree.svg?width=650&token=QL6TVnaXih&height=150&src=pr)](https://codecov.io/gl/pycqa/flake8/pull/337?src=pr&el=tree)

```diff
@@            Coverage Diff             @@
##           master     #337      +/-   ##
==========================================
- Coverage   80.41%   80.34%   -0.07%     
==========================================
  Files          25       25              
  Lines        2364     2366       +2     
  Branches      390      391       +1     
==========================================
  Hits         1901     1901              
- Misses        386      387       +1     
- Partials       77       78       +1
```


| [Impacted Files](https://codecov.io/gl/pycqa/flake8/pull/337?src=pr&el=tree) | Coverage Δ | |
|---|---|---|
| [src/flake8/utils.py](https://codecov.io/gl/pycqa/flake8/pull/337/diff?src=pr&el=tree#diff-c3JjL2ZsYWtlOC91dGlscy5weQ==) | `85.27% <0%> (-0.88%)` | :arrow_down: |

------

[Continue to review full report at Codecov](https://codecov.io/gl/pycqa/flake8/pull/337?src=pr&el=continue).
> **Legend** - [Click here to learn more](https://docs.codecov.io/docs/codecov-delta)
> `Δ = absolute <relative> (impact)`, `ø = not affected`, `? = missing data`
> Powered by [Codecov](https://codecov.io/gl/pycqa/flake8/pull/337?src=pr&el=footer). Last update [d43d498...77c7fca](https://codecov.io/gl/pycqa/flake8/pull/337?src=pr&el=lastupdated). Read the [comment docs](https://docs.codecov.io/docs/pull-request-comments).

**Comment by asottile** [comment]
In GitLab by @asottile on Aug 8, 2019, 08:20

Commented on [src/flake8/utils.py line 179](https://github.com/PyCQA/flake8/compare/d43d498d419fa1a0ec1489301d29d50fdd5be3f9..77c7fca73a480ccb0e87ceb7d3067af14efcc0ee#diff-4dc953c7c4a3eccee77676924dd4cb99R179)



the type annotation requires `str` here, you'd need to update that

**Comment by asottile** [comment]
In GitLab by @asottile on Aug 8, 2019, 08:25

I'd rather not touch this for now, I'm going to be rewriting the parsing using `argparse` which I believe will make this obsolete

Follow #541 for status / progress

Also can't accept this without a test

**Comment by asottile** [comment]
In GitLab by @pjacock on Aug 9, 2019, 01:43

Commented on [src/flake8/utils.py line 179](https://github.com/PyCQA/flake8/compare/d43d498d419fa1a0ec1489301d29d50fdd5be3f9..77c7fca73a480ccb0e87ceb7d3067af14efcc0ee#diff-4dc953c7c4a3eccee77676924dd4cb99R179)



As per the commit comment, I was unclear on the syntax to follow here and in the signature - just commas?

**Comment by asottile** [comment]
In GitLab by @asottile on Aug 9, 2019, 07:41

Commented on [src/flake8/utils.py line 179](https://github.com/PyCQA/flake8/compare/d43d498d419fa1a0ec1489301d29d50fdd5be3f9..77c7fca73a480ccb0e87ceb7d3067af14efcc0ee#diff-4dc953c7c4a3eccee77676924dd4cb99R179)



PEP484 describes type annotations and type comments

**Comment by asottile** [comment]
In GitLab by @ericvw on Aug 29, 2019, 10:11

In !344, I did some work with the path normalization.

Since the path normalization utilities **can** be used independently of configuration/argument parsing, I would advocate for keeping the contract of `normalize_path(s)` strict and put the burden of handling the optionality of configuration at a higher layer.  It makes the code paths easier to reason about without having logic to handle `None` in low-level utility functions.

I'm not a core maintainer of this project and will defer to whatever they desire.  I am on a long-winding journey for addressing #517 and am looking to also figure out how to simplify the configuration/argument parsing.

**Comment by asottile** [comment]
In GitLab by @asottile on Jan 16, 2020, 11:25

closing this for now (inactivity, non-addressed comments), the internals have been rewritten to use argparse so you may find something easier to do with that

**Comment by asottile** [comment]
In GitLab by @asottile on Jan 16, 2020, 11:25

closed
