### ISSUE TITLE
use proper exception attributes - [merged]

### ISSUE THREAD

**Issue by asottile** [PyCQA/flake8#1229]
In GitLab by @wbolster on Aug 5, 2016, 02:19

_Merges issue-203-exception-attributes -> master_

should address #203.

**Comment by asottile** [comment]
In GitLab by @wbolster on Aug 5, 2016, 02:21

before this change flake8 crashes on a file with a syntax error:

```python
Process Process-1:
Traceback (most recent call last):
  File "/home/wbolster/.local/venvs/flake8/lib/python3.5/site-packages/flake8/processor.py", line 238, in generate_tokens
    for token in tokenize.generate_tokens(self.next_line):
  File "/home/wbolster/.local/venvs/flake8/lib/python3.5/tokenize.py", line 597, in _tokenize
    raise TokenError("EOF in multi-line statement", (lnum, 0))
tokenize.TokenError: ('EOF in multi-line statement', (1937, 0))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.5/multiprocessing/process.py", line 249, in _bootstrap
    self.run()
  File "/usr/lib/python3.5/multiprocessing/process.py", line 93, in run
    self._target(*self._args, **self._kwargs)
  File "/home/wbolster/.local/venvs/flake8/lib/python3.5/site-packages/flake8/checker.py", line 46, in _run_checks_from_queue
    checker.run_checks(results_queue, statistics_queue)
  File "/home/wbolster/.local/venvs/flake8/lib/python3.5/site-packages/flake8/checker.py", line 579, in run_checks
    self.process_tokens()
  File "/home/wbolster/.local/venvs/flake8/lib/python3.5/site-packages/flake8/checker.py", line 554, in process_tokens
    for token in file_processor.generate_tokens():
  File "/home/wbolster/.local/venvs/flake8/lib/python3.5/site-packages/flake8/processor.py", line 250, in generate_tokens
    raise exceptions.InvalidSyntax(exc.message, exception=exc)
AttributeError: 'TokenError' object has no attribute 'message'
```

after this change it simply reports the error:

```
/path/to/some_file.py:1:1: E902 ('EOF in multi-line statement', (1937, 0))
/path/to/some_file.py:1303:4: E999 SyntaxError: invalid syntax
```
