### ISSUE TITLE
Tests: Add a value to mocked entry_points, so pytest 6+ can log it - [merged]

### ISSUE THREAD

**Issue by asottile** [PyCQA/flake8#1277]
In GitLab by @hroncok on Jul 20, 2020, 04:23

_Merges pytest6 -> master_

Pytest 6.0.0rc1 attempts to log a repr of our mocked entry_point,
but it fails, becasue the repr metohod expects a valua attribute:

Reproducer:

    $ tox -e py38 --force-dep 'pytest==6.0.0rc1'
    ...
    Traceback (most recent call last):
      File "/usr/lib/python3.8/logging/__init__.py", line 1081, in emit
        msg = self.format(record)
      File "/usr/lib/python3.8/logging/__init__.py", line 925, in format
        return fmt.format(record)
      File "/usr/lib/python3.8/logging/__init__.py", line 664, in format
        record.message = record.getMessage()
      File "/usr/lib/python3.8/logging/__init__.py", line 369, in getMessage
        msg = msg % self.args
      File "/tmp/flake8/.tox/py38/lib/python3.8/site-packages/flake8/plugins/manager.py", line 44, in __repr__
        self.name, self.entry_point.value
      File "/tmp/flake8/.tox/py38/lib/python3.8/site-packages/mock/mock.py", line 632, in __getattr__
        raise AttributeError("Mock object has no attribute %r" % name)
    AttributeError: Mock object has no attribute 'value'

**Comment by asottile** [comment]
In GitLab by @asottile on Jul 20, 2020, 08:39

the stacktrace is important, I think there's probably something pytest should change here and/or it implies we're leaking this object in some way which is bad

**Comment by asottile** [comment]
In GitLab by @asottile on Jul 20, 2020, 08:42

ah, this is the new pytest feature to expose logging errors -- it isn't a pytest problem but one with our test suite entirely:

```
Traceback (most recent call last):
  File "/usr/lib/python3.8/logging/__init__.py", line 1081, in emit
    msg = self.format(record)
  File "/usr/lib/python3.8/logging/__init__.py", line 925, in format
    return fmt.format(record)
  File "/usr/lib/python3.8/logging/__init__.py", line 664, in format
    record.message = record.getMessage()
  File "/usr/lib/python3.8/logging/__init__.py", line 369, in getMessage
    msg = msg % self.args
  File "/tmp/flake8/.tox/py38/lib/python3.8/site-packages/flake8/plugins/manager.py", line 44, in __repr__
    self.name, self.entry_point.value
  File "/tmp/flake8/.tox/py38/lib/python3.8/site-packages/mock/mock.py", line 632, in __getattr__
    raise AttributeError("Mock object has no attribute %r" % name)
AttributeError: Mock object has no attribute 'value'
```

it's our repr, and our logging

**Comment by asottile** [comment]
In GitLab by @asottile on Jul 20, 2020, 08:42

Commented on [tests/integration/test_checker.py line 103](https://github.com/PyCQA/flake8/compare/a7be77f761a4c29121d6bb6f61c11902281f9105..c3fc5f3b85ec44080d74527300d050147145aa03#diff-e74548765fe3cce2dffec14a5af84d89R103)



this mocked value isn't quite correct, it should be `'modname:attr'` or something similar

**Comment by asottile** [comment]
In GitLab by @hroncok on Jul 20, 2020, 08:49

Commented on [tests/integration/test_checker.py line 103](https://github.com/PyCQA/flake8/compare/a7be77f761a4c29121d6bb6f61c11902281f9105..c3fc5f3b85ec44080d74527300d050147145aa03#diff-e74548765fe3cce2dffec14a5af84d89R103)



changed this line in [version 2 of the diff](/pycqa/flake8/-/merge_requests/443/diffs?diff_id=101843174&start_sha=c3fc5f3b85ec44080d74527300d050147145aa03#9210ab5917090aa94e8029dee22a63c03246a806_103_103)

**Comment by asottile** [comment]
In GitLab by @hroncok on Jul 20, 2020, 08:49

added 1 commit

<ul><li>91b09d5b - Tests: Add a value to mocked entry_points, so pytest 6+ can log it</li></ul>

[Compare with previous version](/pycqa/flake8/-/merge_requests/443/diffs?diff_id=101843174&start_sha=c3fc5f3b85ec44080d74527300d050147145aa03)

**Comment by asottile** [comment]
In GitLab by @hroncok on Jul 20, 2020, 08:50

Commented on [tests/integration/test_checker.py line 103](https://github.com/PyCQA/flake8/compare/a7be77f761a4c29121d6bb6f61c11902281f9105..c3fc5f3b85ec44080d74527300d050147145aa03#diff-e74548765fe3cce2dffec14a5af84d89R103)



I've used `mocked:value` -- if that ever shows up somewhere, at lest it will be easy to find where it is from.

**Comment by asottile** [comment]
In GitLab by @hroncok on Jul 20, 2020, 08:50

changed the description

**Comment by asottile** [comment]
In GitLab by @hroncok on Jul 20, 2020, 08:51

Amended.

**Comment by asottile** [comment]
In GitLab by @hroncok on Jul 20, 2020, 08:51

resolved all threads

**Comment by asottile** [comment]
In GitLab by @asottile on Jul 20, 2020, 08:53

approved this merge request

**Comment by asottile** [comment]
In GitLab by @asottile on Jul 20, 2020, 08:54

mentioned in commit 029fa1d797e3b5cc98f52725323fcafbf25a256d
