### ISSUE TITLE
flake8 complains about '__class__' [REPLACEMENT ISSUE]

### ISSUE THREAD

**Issue by asottile** [PyCQA/flake8#128]
The original issue

	Id: 85
	Title: flake8 complains about '__class__'

could not be created.
This is a dummy issue, replacing the original one. It contains everything but the original issue description. In case the gitlab repository is still existing, visit the following link to show the original issue:

TODO

**Comment by asottile** [comment]
In GitLab by @sigmavirus24 on Aug 21, 2015, 06:13

There's not enough information here to reproduce this for a test case. Closing until an example that can be used to reproduce this is provided.

**Comment by asottile** [comment]
In GitLab by @rumpelsepp on Aug 21, 2015, 06:16

What about just using `__class__.__name__` as I described?

```python
class Test:
    def __init__(self):
        print(__class__.__name__)


t = Test()
```

```
test.py:3:15: F821 undefined name '__class__'
```

**Comment by asottile** [comment]
In GitLab by @sigmavirus24 on Aug 21, 2015, 11:17

Have you tried running that code?

```py
~ ❯❯❯ python test.py
Traceback (most recent call last):
  File "test.py", line 6, in <module>
    t = Test()
  File "test.py", line 3, in __init__
    print(__class__.__name__)
NameError: global name '__class__' is not defined
```

**Comment by asottile** [comment]
In GitLab by @rumpelsepp on Aug 21, 2015, 11:20

sure.

```
$ python test.py
Test
```

You're using python2? In python2 that code does not seem to work.

**Comment by asottile** [comment]
In GitLab by @sigmavirus24 on Aug 21, 2015, 11:26

So that still doesn't work on Python 2. If you're running `flake8` on Python 2 that's why you're seeing this message.

**Comment by asottile** [comment]
In GitLab by @sigmavirus24 on Aug 21, 2015, 11:28

The version that does work is

```py
class Test(object):
    def __init__(self):
        print(self.__class__.__name__)
```

**Comment by asottile** [comment]
In GitLab by @rumpelsepp on Aug 21, 2015, 11:29

> If you're running flake8 on Python 2 that's why you're seeing this message.

I'm using the arch linux package which is built with python 3.4.

**Comment by asottile** [comment]
In GitLab by @sigmavirus24 on Aug 21, 2015, 11:44

Yeah. Doesn't help that I tested the version that works on Python 2 in general. This is a pyflakes bug. Please file a bug over at [pyflakes' bug report](https://launchpad.net/pyflakes).
