### ISSUE TITLE
flake8 == 3.9.1

### ISSUE THREAD

**Issue by zaufi** [PyCQA/flake8#1318]
*Please describe how you installed Flake8*

```
$ pipenv install --dev
```

The `Pipenv` file has the dev section w/ a bunch of plugins:
```
...
[dev-packages]
coverage = {extras = ["toml"], version = "*"}
flake8 = "~= 3.9, != 3.9.1"
flake8-2020 = "*"
flake8-bugbear = "*"
flake8-builtins = "*"
flake8-comprehensions = "*"
flake8-eradicate = "*"
flake8-isort = "*"
flake8-mutable = "*"
flake8-pep3101 = "*"
flake8-pytest-style = "*"
flake8-quotes = "*"
flake8-return = "*"
flake8-rst-docstrings = "*"
flake8-simplify = "*"
flake8-use-fstring = "*"
flake8-variables-names = "*"
flakehell = "*"
...
```

*Please provide the exact, unmodified output of ...*

[flake8-report.json.gz](https://github.com/PyCQA/flake8/files/6327606/flake8-report.json.gz)

*Please describe the problem or feature*
```
Traceback (most recent call last):
  File "/work/.venv/bin/flakehell", line 8, in <module>
    sys.exit(entrypoint())
  File "/work/.venv/lib/python3.9/site-packages/flakehell/_cli.py", line 40, in entrypoint
    exit_code, msg = main(argv)
  File "/work/.venv/lib/python3.9/site-packages/flakehell/_cli.py", line 32, in main
    return COMMANDS[command_name](argv=argv[1:])
  File "/work/.venv/lib/python3.9/site-packages/flakehell/commands/_lint.py", line 12, in lint_command
    app.run(argv)
  File "/work/.venv/lib/python3.9/site-packages/flake8/main/application.py", line 363, in run
    self._run(argv)
  File "/work/.venv/lib/python3.9/site-packages/flake8/main/application.py", line 350, in _run
    self.initialize(argv)
  File "/work/.venv/lib/python3.9/site-packages/flake8/main/application.py", line 337, in initialize
    self.make_guide()
  File "/work/.venv/lib/python3.9/site-packages/flakehell/_patched/_app.py", line 177, in make_guide
    self.guide = FlakeHellStyleGuideManager(self.options, self.formatter)
  File "/work/.venv/lib/python3.9/site-packages/flakehell/_patched/_style_guide.py", line 17, in __init__
    super().__init__(options, formatter, decider)
  File "/work/.venv/lib/python3.9/site-packages/flake8/style_guide.py", line 339, in __init__
    self.decider = decider or DecisionEngine(options)
  File "/work/.venv/lib/python3.9/site-packages/flake8/style_guide.py", line 171, in __init__
    ).union(options.extended_default_ignore)
AttributeError: 'Namespace' object has no attribute 'extended_default_ignore'
```

The latest release 3.9.1 has filed w/ namespace package %(

**Comment by asottile** [comment]
flakehell is using unsupported private interfaces
