### ISSUE TITLE
Flake8 3.0.2 hangs when run on Windows

### ISSUE THREAD

**Issue by asottile** [PyCQA/flake8#134]
In GitLab by @johnthagen on Jul 27, 2016, 15:04

Environment:

- python 3.5.2
- `pip`
 ```
pip install flake8
Collecting flake8
  Using cached flake8-3.0.2-py2.py3-none-any.whl
Collecting pyflakes!=1.2.0,!=1.2.1,!=1.2.2,<1.3.0,>=0.8.1 (from flake8)
  Using cached pyflakes-1.2.3-py2.py3-none-any.whl
Collecting pycodestyle<2.1.0,>=2.0.0 (from flake8)
  Using cached pycodestyle-2.0.0-py2.py3-none-any.whl
Collecting mccabe<0.6.0,>=0.5.0 (from flake8)
  Using cached mccabe-0.5.0-py2.py3-none-any.whl
Installing collected packages: pyflakes, pycodestyle, mccabe, flake8
Successfully installed flake8-3.0.2 mccabe-0.5.0 pycodestyle-2.0.0 pyflakes-1.2.3
```
```
pip list
flake8 (3.0.2)
mccabe (0.5.0)
pip (8.1.2)
pycodestyle (2.0.0)
pyflakes (1.2.3)
setuptools (20.10.1)
```

- ```C:\Users\John Hagen\PycharmProjects\test>flake8 --version
3.0.2 (mccabe: 0.5.0, pyflakes: 1.2.3, pycodestyle: 2.0.0) CPython 3.5.2 on Windows```

```
flake8
Process Process-1:
Traceback (most recent call last):
  File "c:\python35\lib\multiprocessing\process.py", line 249, in _bootstrap
    self.run()
  File "c:\python35\lib\multiprocessing\process.py", line 93, in run
    self._target(*self._args, **self._kwargs)
  File "c:\python35\lib\site-packages\flake8\checker.py", line 222, in _run_checks_from_queue
    checker.run_checks(self.results_queue, self.statistics_queue)
  File "c:\python35\lib\site-packages\flake8\checker.py", line 564, in run_checks
    self.run_ast_checks()
  File "c:\python35\lib\site-packages\flake8\checker.py", line 468, in run_ast_checks
    checker = self.run_check(plugin, tree=ast)
  File "c:\python35\lib\site-packages\flake8\checker.py", line 448, in run_check
    return plugin.execute(**arguments)
  File "c:\python35\lib\site-packages\flake8\plugins\manager.py", line 126, in execute
    return self.plugin(*args, **kwargs)  # pylint: disable=not-callable
  File "c:\python35\lib\site-packages\flake8\plugins\pyflakes.py", line 53, in __init__
    with_doctest = self.with_doctest
AttributeError: 'FlakesChecker' object has no attribute 'with_doctest'
... stopped while processing files
```
This hangs on the last line.  Tested on Windows 10 x64.

**Comment by asottile** [comment]
In GitLab by @sigmavirus24 on Jul 28, 2016, 11:25

This is a duplicate of #179
