### ISSUE TITLE
Flake8 failed to load plugin "X101" due to No module named 'utils'

### ISSUE THREAD

**Issue by friyaz** [PyCQA/flake8#1343]
*Please describe how you installed Flake8*
```
pip install flake8==3.7.9
```

*Please provide the exact, unmodified output of `flake8 --bug-report`*
```
{
  "dependencies": [
    {
      "dependency": "entrypoints",
      "version": "0.3"
    }
  ],
  "platform": {
    "python_implementation": "CPython",
    "python_version": "3.8.5",
    "system": "Linux"
  },
  "plugins": [
    {
      "is_local": false,
      "plugin": "flake8-docstrings",
      "version": "1.5.0, pydocstyle: 5.0.3rc"
    },
    {
      "is_local": false,
      "plugin": "mccabe",
      "version": "0.6.1"
    },
    {
      "is_local": false,
      "plugin": "pycodestyle",
      "version": "2.5.0"
    },
    {
      "is_local": false,
      "plugin": "pyflakes",
      "version": "2.1.1"
    }
  ],
  "version": "3.7.9"
}
```
*Please describe the problem or feature*
Running flake8 on [sphinx](https://github.com/angrycaptain19/sphinx) project produces ```ModuleNotFoundError: No module named 'utils'```. I think this is a problem with my python path as the sphinx project has a folder named `utils` which is messing things up.

*If this is a bug report, please explain with examples (and example code) what you expected to happen and what actually happened.*
```
>>> flake8 sphinx/
Traceback (most recent call last):
  File "/home/faisal/ENVIRONMENTS/ds_py3/lib/python3.8/site-packages/flake8/plugins/manager.py", line 158, in load_plugin
    self._load()
  File "/home/faisal/ENVIRONMENTS/ds_py3/lib/python3.8/site-packages/flake8/plugins/manager.py", line 135, in _load
    self._plugin = self.entry_point.load()
  File "/home/faisal/ENVIRONMENTS/ds_py3/lib/python3.8/site-packages/entrypoints.py", line 82, in load
    mod = import_module(self.module_name)
  File "/usr/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 961, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 973, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'utils'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/faisal/ENVIRONMENTS/ds_py3/bin/flake8", line 8, in <module>
    sys.exit(main())
  File "/home/faisal/ENVIRONMENTS/ds_py3/lib/python3.8/site-packages/flake8/main/cli.py", line 18, in main
    app.run(argv)
  File "/home/faisal/ENVIRONMENTS/ds_py3/lib/python3.8/site-packages/flake8/main/application.py", line 393, in run
    self._run(argv)
  File "/home/faisal/ENVIRONMENTS/ds_py3/lib/python3.8/site-packages/flake8/main/application.py", line 380, in _run
    self.initialize(argv)
  File "/home/faisal/ENVIRONMENTS/ds_py3/lib/python3.8/site-packages/flake8/main/application.py", line 363, in initialize
    self.find_plugins()
  File "/home/faisal/ENVIRONMENTS/ds_py3/lib/python3.8/site-packages/flake8/main/application.py", line 199, in find_plugins
    self.check_plugins.load_plugins()
  File "/home/faisal/ENVIRONMENTS/ds_py3/lib/python3.8/site-packages/flake8/plugins/manager.py", line 410, in load_plugins
    plugins = list(self.manager.map(load_plugin))
  File "/home/faisal/ENVIRONMENTS/ds_py3/lib/python3.8/site-packages/flake8/plugins/manager.py", line 297, in map
    yield func(self.plugins[name], *args, **kwargs)
  File "/home/faisal/ENVIRONMENTS/ds_py3/lib/python3.8/site-packages/flake8/plugins/manager.py", line 408, in load_plugin
    return plugin.load_plugin()
  File "/home/faisal/ENVIRONMENTS/ds_py3/lib/python3.8/site-packages/flake8/plugins/manager.py", line 165, in load_plugin
    raise failed_to_load
flake8.exceptions.FailedToLoadPlugin: Flake8 failed to load plugin "X101" due to No module named 'utils'.
```

**Comment by asottile** [comment]
sphinx has a [local plugin](https://github.com/angrycaptain19/sphinx/blob/8db329f70a25f78a8e0562cf6ab91eafa7608185/setup.cfg#L36-L40)

this isn't a flake8 issue, please bring it up with the sphinx project
