### ISSUE TITLE
Unknown UnicodeDecodeError during `Reporting errors`

### ISSUE THREAD

**Issue by ikus060** [PyCQA/flake8#1350]
*Please describe how you installed Flake8*

On Windows 10 with Python 3.7
```
$ pip install flake8
```

*Please provide the exact, unmodified output of `flake8 --bug-report`*

```
flake8 run-test: commands[0] | flake8 --bug-report setup.py minarca_client
{
  "dependencies": [],
  "platform": {
    "python_implementation": "CPython",
    "python_version": "3.7.9",
    "system": "Windows"
  },
  "plugins": [
    {
      "is_local": false,
      "plugin": "mccabe",
      "version": "0.6.1"
    },
    {
      "is_local": false,
      "plugin": "pycodestyle",
      "version": "2.7.0"
    },
    {
      "is_local": false,
      "plugin": "pyflakes",
      "version": "2.3.1"
    }
  ],
  "version": "3.9.2"
}
```

*Please describe the problem or feature*

```
flake8.checker            MainProcess    355 INFO     Making checkers
flake8.checker            MainProcess    385 INFO     Checking 19 files
flake8.main.application   MainProcess   1864 INFO     Finished running
flake8.main.application   MainProcess   1872 INFO     Reporting errors
Traceback (most recent call last):
  File "c:\users\vmtest\appdata\local\programs\python\python37-32\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "c:\users\vmtest\appdata\local\programs\python\python37-32\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Users\vmtest\git\minarca.git\minarca-client\.tox\flake8\Scripts\flake8.EXE\__main__.py", line 7, in <module>
  File "c:\users\vmtest\git\minarca.git\minarca-client\.tox\flake8\lib\site-packages\flake8\main\cli.py", line 22, in main
    app.run(argv)
  File "c:\users\vmtest\git\minarca.git\minarca-client\.tox\flake8\lib\site-packages\flake8\main\application.py", line 363, in run
    self._run(argv)
  File "c:\users\vmtest\git\minarca.git\minarca-client\.tox\flake8\lib\site-packages\flake8\main\application.py", line 352, in _run
    self.report()
  File "c:\users\vmtest\git\minarca.git\minarca-client\.tox\flake8\lib\site-packages\flake8\main\application.py", line 343, in report
    self.report_errors()
  File "c:\users\vmtest\git\minarca.git\minarca-client\.tox\flake8\lib\site-packages\flake8\main\application.py", line 298, in report_errors
    results = self.file_checker_manager.report()
  File "c:\users\vmtest\git\minarca.git\minarca-client\.tox\flake8\lib\site-packages\flake8\checker.py", line 261, in report
    results_reported += self._handle_results(filename, results)
  File "c:\users\vmtest\git\minarca.git\minarca-client\.tox\flake8\lib\site-packages\flake8\checker.py", line 165, in _handle_results
    physical_line=physical_line,
  File "c:\users\vmtest\git\minarca.git\minarca-client\.tox\flake8\lib\site-packages\flake8\style_guide.py", line 425, in handle_error
    code, filename, line_number, column_number, text, physical_line
  File "c:\users\vmtest\git\minarca.git\minarca-client\.tox\flake8\lib\site-packages\flake8\style_guide.py", line 572, in handle_error
    is_not_inline_ignored = error.is_inline_ignored(disable_noqa) is False
  File "c:\users\vmtest\git\minarca.git\minarca-client\.tox\flake8\lib\site-packages\flake8\style_guide.py", line 83, in is_inline_ignored
    physical_line = linecache.getline(self.filename, self.line_number)
  File "c:\users\vmtest\appdata\local\programs\python\python37-32\lib\linecache.py", line 16, in getline
    lines = getlines(filename, module_globals)
  File "c:\users\vmtest\appdata\local\programs\python\python37-32\lib\linecache.py", line 47, in getlines
    return updatecache(filename, module_globals)
  File "c:\users\vmtest\appdata\local\programs\python\python37-32\lib\linecache.py", line 137, in updatecache
    lines = fp.readlines()
  File "c:\users\vmtest\appdata\local\programs\python\python37-32\lib\codecs.py", line 322, in decode
    (result, consumed) = self._buffer_decode(data, self.errors, final)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xf6 in position 770: invalid start byte
ERROR: InvocationError for command 'C:\Users\vmtest\git\minarca.git\minarca-client\.tox\flake8\Scripts\flake8.EXE' -v setup.py minarca_client (exited with code 1)
```

**Comment by asottile** [comment]
if you run with `-vvv` do you get more information?  this looks like a bug with python itself in `linecache` trying to read a file with the incorrect encoding
