### ISSUE TITLE
Py3.6 compatibility broken

### ISSUE THREAD

**Issue by inducer** [PyCQA/flake8#1425]
Since flake8 still advertises Python 3.6 compatibility:

https://github.com/PyCQA/flake8/blob/ecee230c6f1e11444f2738ced522526c3112738c/setup.cfg#L46

I figured I would let you know that, by way of a wayward type annotation, that compatibility has been broken. See [this CI log](https://github.com/inducer/compyte/runs/3916979124?check_suite_focus=true) for an example. Since the CI log will eventually disappear, I'll reproduce the relevant parts here:
```
-----------------------------------------------------------------
Collecting flake8
  Downloading flake8-4.0.1-py2.py3-none-any.whl (64 kB)
Collecting pep8-naming
  Downloading pep8_naming-0.12.1-py2.py3-none-any.whl (8.9 kB)
Collecting flake8-quotes
  Downloading flake8-quotes-3.3.0.tar.gz (13 kB)
  Preparing metadata (setup.py): started
  Preparing metadata (setup.py): finished with status 'done'
Collecting importlib-metadata<4.3
  Downloading importlib_metadata-4.2.0-py3-none-any.whl (16 kB)
Collecting mccabe<0.7.0,>=0.6.0
  Downloading mccabe-0.6.1-py2.py3-none-any.whl (8.6 kB)
Collecting pyflakes<2.5.0,>=2.4.0
  Downloading pyflakes-2.4.0-py2.py3-none-any.whl (69 kB)
Collecting pycodestyle<2.9.0,>=2.8.0
  Downloading pycodestyle-2.8.0-py2.py3-none-any.whl (42 kB)
Collecting flake8-polyfill<2,>=1.0.2
  Downloading flake8_polyfill-1.0.2-py2.py3-none-any.whl (7.3 kB)
Collecting zipp>=0.5
  Downloading zipp-3.6.0-py3-none-any.whl (5.3 kB)
Collecting typing-extensions>=3.6.4
  Downloading typing_extensions-3.10.0.2-py3-none-any.whl (26 kB)
Building wheels for collected packages: flake8-quotes
  Building wheel for flake8-quotes (setup.py): started
  Building wheel for flake8-quotes (setup.py): finished with status 'done'
  Created wheel for flake8-quotes: filename=flake8_quotes-3.3.0-py3-none-any.whl size=8614 sha256=e47ae216d3d402f7991c1cd54e150e41f212a49bf97a6473b110e15f5b9b3472
  Stored in directory: /home/runner/.cache/pip/wheels/96/10/ef/eafd978ce9cb7a8631504895f56467fb4d90c3f7256a639328
Successfully built flake8-quotes
Installing collected packages: zipp, typing-extensions, pyflakes, pycodestyle, mccabe, importlib-metadata, flake8, flake8-polyfill, pep8-naming, flake8-quotes
Successfully installed flake8-4.0.1 flake8-polyfill-1.0.2 flake8-quotes-3.3.0 importlib-metadata-4.2.0 mccabe-0.6.1 pep8-naming-0.12.1 pycodestyle-2.8.0 pyflakes-2.4.0 typing-extensions-3.10.0.2 zipp-3.6.0
Traceback (most recent call last):
  File "/opt/hostedtoolcache/Python/3.6.15/x64/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/opt/hostedtoolcache/Python/3.6.15/x64/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/runner/work/compyte/compyte/.env/lib/python3.6/site-packages/flake8/__main__.py", line 2, in <module>
    from flake8.main import cli
  File "/home/runner/work/compyte/compyte/.env/lib/python3.6/site-packages/flake8/main/cli.py", line 6, in <module>
    from flake8.main import application
  File "/home/runner/work/compyte/compyte/.env/lib/python3.6/site-packages/flake8/main/application.py", line 15, in <module>
    from flake8 import checker
  File "/home/runner/work/compyte/compyte/.env/lib/python3.6/site-packages/flake8/checker.py", line 661, in <module>
    ) -> Optional[multiprocessing.pool.Pool]:
AttributeError: 'NoneType' object has no attribute 'pool'
```
(In case you're wondering: I advertise 3.6 compatibility for my packages and use "run flake8 on 3.6 as a way of ensuring that remains true.)

I think simply "stringifying" that type annotation might be sufficientt.

**Comment by asottile** [comment]
it looks like your python is broken, notably it is missing the `multiprocessing` module

**Comment by asottile** [comment]
please fill out the issue template

**Comment by inducer** [comment]
Nvm, I *can* reproduce this on a clean install. It seems to hinge on running `python -m flake8 ...` instead of `flake8`. Here's the method to reproduce, using the "official" (?) Python 3.6.15 Docker image (on Debian buster):
```
$ docker pull python:3.6.15-buster 
$ docker run -t -i python:3.6.15-buster /bin/bash
root@93b7f587e490:/# cd
root@93b7f587e490:~# git clone https://github.com/inducer/compyte
Cloning into 'compyte'... (snip)
root@93b7f587e490:~# cd compyte/
root@93b7f587e490:~/compyte# pip install flake8
Collecting flake8
  Downloading flake8-4.0.1-py2.py3-none-any.whl (64 kB)
     |████████████████████████████████| 64 kB 94 kB/s 
Collecting importlib-metadata<4.3
  Downloading importlib_metadata-4.2.0-py3-none-any.whl (16 kB)
Collecting pycodestyle<2.9.0,>=2.8.0
  Downloading pycodestyle-2.8.0-py2.py3-none-any.whl (42 kB)
     |████████████████████████████████| 42 kB 53 kB/s 
Collecting mccabe<0.7.0,>=0.6.0
  Downloading mccabe-0.6.1-py2.py3-none-any.whl (8.6 kB)
Collecting pyflakes<2.5.0,>=2.4.0
  Downloading pyflakes-2.4.0-py2.py3-none-any.whl (69 kB)
     |████████████████████████████████| 69 kB 318 kB/s 
Collecting zipp>=0.5
  Downloading zipp-3.6.0-py3-none-any.whl (5.3 kB)
Collecting typing-extensions>=3.6.4
  Downloading typing_extensions-3.10.0.2-py3-none-any.whl (26 kB)
Installing collected packages: zipp, typing-extensions, pyflakes, pycodestyle, mccabe, importlib-metadata, flake8
Successfully installed flake8-4.0.1 importlib-metadata-4.2.0 mccabe-0.6.1 pycodestyle-2.8.0 pyflakes-2.4.0 typing-extensions-3.10.0.2 zipp-3.6.0
root@93b7f587e490:~/compyte# python -m flake8 *.py
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/local/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/usr/local/lib/python3.6/site-packages/flake8/__main__.py", line 2, in <module>
    from flake8.main import cli
  File "/usr/local/lib/python3.6/site-packages/flake8/main/cli.py", line 6, in <module>
    from flake8.main import application
  File "/usr/local/lib/python3.6/site-packages/flake8/main/application.py", line 15, in <module>
    from flake8 import checker
  File "/usr/local/lib/python3.6/site-packages/flake8/checker.py", line 661, in <module>
    ) -> Optional[multiprocessing.pool.Pool]:
AttributeError: 'NoneType' object has no attribute 'pool'
root@93b7f587e490:~/compyte# 
```

**Comment by asottile** [comment]
I suspect your `array.py` shadows [the standard library](https://docs.python.org/3/library/array.html) breaking the `multiprocessing` library: https://github.com/inducer/compyte/blob/main/array.py

**Comment by asottile** [comment]
yep confirmed

**Comment by sigmavirus24** [comment]
https://github.com/search?q=%22import+array%22+repo%3Apython%2Fcpython+path%3ALib%2Fmultiprocessing+language%3APython+language%3APython&type=Code 

`multiprocessing` relies heavily on arrays in case you're confused @inducer

**Comment by inducer** [comment]
Ah. Thanks for figuring this out, and sorry about the noise.
