### ISSUE TITLE
AttributeError: '_io.StringIO' object has no attribute 'buffer'

### ISSUE THREAD

**Issue by karthiknadig** [PyCQA/flake8#1445]
Install flake8 using `python -m pip install flake8`.

Failure stack:
```
Traceback (most recent call last):
  File "c:\GIT\repro\scratch\something2.py", line 20, in <module>
    raise ex
  File "c:\GIT\repro\scratch\something2.py", line 16, in <module>
    runpy.run_module('flake8', run_name="__main__")
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.240.0_x64__qbz5n2kfra8p0\lib\runpy.py", line 212, in run_module
    return _run_code(code, {}, init_globals, run_name, mod_spec)
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.240.0_x64__qbz5n2kfra8p0\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "c:\GIT\repro\scratch\.venv\lib\site-packages\flake8\__main__.py", line 4, in <module>
    cli.main()
  File "c:\GIT\repro\scratch\.venv\lib\site-packages\flake8\main\cli.py", line 22, in main
    app.run(argv)
  File "c:\GIT\repro\scratch\.venv\lib\site-packages\flake8\main\application.py", line 375, in run
    self._run(argv)
  File "c:\GIT\repro\scratch\.venv\lib\site-packages\flake8\main\application.py", line 365, in _run
    self.report()
  File "c:\GIT\repro\scratch\.venv\lib\site-packages\flake8\main\application.py", line 357, in report
    self.report_errors()
  File "c:\GIT\repro\scratch\.venv\lib\site-packages\flake8\main\application.py", line 309, in report_errors
    results = self.file_checker_manager.report()
  File "c:\GIT\repro\scratch\.venv\lib\site-packages\flake8\checker.py", line 249, in report
    results_reported += self._handle_results(filename, results)
  File "c:\GIT\repro\scratch\.venv\lib\site-packages\flake8\checker.py", line 155, in _handle_results
    reported_results_count += style_guide.handle_error(
  File "c:\GIT\repro\scratch\.venv\lib\site-packages\flake8\style_guide.py", line 429, in handle_error
    return guide.handle_error(
  File "c:\GIT\repro\scratch\.venv\lib\site-packages\flake8\style_guide.py", line 581, in handle_error
    self.formatter.handle(error)
  File "c:\GIT\repro\scratch\.venv\lib\site-packages\flake8\formatting\base.py", line 100, in handle
    self.write(line, source)
  File "c:\GIT\repro\scratch\.venv\lib\site-packages\flake8\formatting\base.py", line 203, in write
    self._write(line)
  File "c:\GIT\repro\scratch\.venv\lib\site-packages\flake8\formatting\base.py", line 187, in _write
    sys.stdout.buffer.write(output.encode() + self.newline.encode())
AttributeError: '_io.StringIO' object has no attribute 'buffer'
```

Repro code:
```python
import io
import contextlib
import sys
import runpy

str_io = io.StringIO()

original_argv = sys.argv[:]
try:
    sys.argv = [
        'flake8',
        "--format=%(row)d,%(col)d,%(code).1s,%(code)s:%(text)s",
        r"C:\GIT\repro\scratch\somethin.py",
    ]
    with contextlib.redirect_stdout(str_io), contextlib.redirect_stderr(str_io):
        runpy.run_module('flake8', run_name="__main__")
except SystemExit:
    pass
except Exception as ex:
    raise ex
finally:
    sys.argv = original_argv

print(str_io.getvalue())
```

This was introduced by this commit https://github.com/PyCQA/flake8/commit/eea10665da3d32e86bbcdc229890269d5ed624dc  PR https://github.com/PyCQA/flake8/pull/1382

**Comment by asottile** [comment]
check the pinned issue

**Comment by HebaruSan** [comment]
The pinned issue is definitely the same problem, but it doesn't say much about what affected users should do about this.

If PyTest doing something it shoudn't be, then one of the main ways of managing and consolidating flake8 with other testing tools is malfunctioning. That would be worth explaining somewhere.

**Comment by asottile** [comment]
read closely, I say exactly what should be done
