### ISSUE TITLE
Running flake8 issue on python 3.9.9

### ISSUE THREAD

**Issue by matejsp** [PyCQA/flake8#1494]
There is in issue running flake8 directly as a command installed in bin. But it works when runned with python -m flake8.

*Please describe how you installed Flake8*

```
$ mkvirtualenv testflake8
$ workon testflake8 
$ pip install flake8
$ flake8

```

```
Traceback (most recent call last):
  File "/Users/user/.virtualenvs/testflake9/lib/python3.9/site-packages/flake8/plugins/manager.py", line 161, in load_plugin
    self._load()
  File "/Users/user/.virtualenvs/testflake9/lib/python3.9/site-packages/flake8/plugins/manager.py", line 138, in _load
    self._plugin = self.entry_point.load()
  File "/usr/local/Cellar/python@3.9/3.9.9/Frameworks/Python.framework/Versions/3.9/lib/python3.9/importlib/metadata.py", line 77, in load
    module = import_module(match.group('module'))
  File "/usr/local/Cellar/python@3.9/3.9.9/Frameworks/Python.framework/Versions/3.9/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 972, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 972, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 984, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'resources'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/user/.virtualenvs/testflake9/bin/flake8", line 8, in <module>
    sys.exit(main())
  File "/Users/user/.virtualenvs/testflake9/lib/python3.9/site-packages/flake8/main/cli.py", line 22, in main
    app.run(argv)
  File "/Users/user/.virtualenvs/testflake9/lib/python3.9/site-packages/flake8/main/application.py", line 375, in run
    self._run(argv)
  File "/Users/user/.virtualenvs/testflake9/lib/python3.9/site-packages/flake8/main/application.py", line 363, in _run
    self.initialize(argv)
  File "/Users/user/.virtualenvs/testflake9/lib/python3.9/site-packages/flake8/main/application.py", line 343, in initialize
    self.find_plugins(config_finder)
  File "/Users/user/.virtualenvs/testflake9/lib/python3.9/site-packages/flake8/main/application.py", line 163, in find_plugins
    self.check_plugins.load_plugins()
  File "/Users/user/.virtualenvs/testflake9/lib/python3.9/site-packages/flake8/plugins/manager.py", line 422, in load_plugins
    plugins = list(self.manager.map(load_plugin))
  File "/Users/user/.virtualenvs/testflake9/lib/python3.9/site-packages/flake8/plugins/manager.py", line 309, in map
    yield func(self.plugins[name], *args, **kwargs)
  File "/Users/user/.virtualenvs/testflake9/lib/python3.9/site-packages/flake8/plugins/manager.py", line 420, in load_plugin
    return plugin.load_plugin()
  File "/Users/user/.virtualenvs/testflake9/lib/python3.9/site-packages/flake8/plugins/manager.py", line 168, in load_plugin
    raise failed_to_load
flake8.exceptions.FailedToLoadPlugin: Flake8 failed to load plugin "I25" due to No module named 'resources'.

```

```
python -m flake8 --bug-report
{
  "dependencies": [],
  "platform": {
    "python_implementation": "CPython",
    "python_version": "3.9.9",
    "system": "Darwin"
  },
  "plugins": [
    {
      "is_local": false,
      "plugin": "flake8-tidy-imports",
      "version": "4.2.1"
    },
    {
      "is_local": false,
      "plugin": "mccabe",
      "version": "0.6.1"
    },
    {
      "is_local": false,
      "plugin": "pycodestyle",
      "version": "2.8.0"
    },
    {
      "is_local": false,
      "plugin": "pyflakes",
      "version": "2.4.0"
    }
  ],
  "version": "4.0.1"
}
```

**Comment by asottile** [comment]
there's some ~partially installed `I25` plugin -- your reproduction steps for instance do not work for me -- I suspect if you completely remove that environment and recreate it then it will no longer be broken

**Comment by matejsp** [comment]
@asottile 
You are onto something :)

I missed that we are using a local plugin:
[flake8:local-plugins]
extension =
    I25 = resources.flake8_plugins.custom_checker:CustomChecker

The problem is if I run from flake8 (it does not pick extension from local folder.
So ... if I run with flake8 script it does not pick module from current folder.
If I run with python -m flake8 it does.

Is this a bug? or feature?

**Comment by asottile** [comment]
then you're missing `paths` as specified in [the docs](https://flake8.pycqa.org/en/latest/user/configuration.html#using-local-plugins)

**Comment by matejsp** [comment]
Thank you. Adding paths = . worked.
The difference between environments was in the env PYTHONPATH=.

**Comment by matejsp** [comment]
@asottile 
However there is another problem with relative path.
Running flake8 from the same folder as .flake8 file works OK. But running it from the subfolder it does not.
It seems that . is relative to the where the flake8 is ran from and not from the .flake8 file.

```
   .flake8
   resources/some_checker.py
   src/test.py
```

```
[flake8:local-plugins]
extension =
    I25 = resources.some_checker:SomeChecker
paths =
    .
```

Running flake8 in src flake finds parent configuration (.flake8) however folder is not relative to .flake8 but to the current path.

**Comment by asottile** [comment]
yeah I'm working on fixing that, try out this branch? https://github.com/asottile/flake8/tree/plugin_simplification

**Comment by matejsp** [comment]
Here you go:
```
pip uninstall flake8
pip install git+https://github.com/asottile/flake8.git@plugin_simplification
```

```
(testflake9) ➜  subfolder / flake8                                                                      
Traceback (most recent call last):
  File "/Users/XXXX/.virtualenvs/testflake9/lib/python3.9/site-packages/flake8/plugins/finder.py", line 203, in _load_plugin
    obj = plugin.entry_point.load()
  File "/usr/local/Cellar/python@3.9/3.9.9/Frameworks/Python.framework/Versions/3.9/lib/python3.9/importlib/metadata.py", line 77, in load
    module = import_module(match.group('module'))
  File "/usr/local/Cellar/python@3.9/3.9.9/Frameworks/Python.framework/Versions/3.9/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 972, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 972, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 984, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'resources'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/XXXX/.virtualenvs/testflake9/bin/flake8", line 8, in <module>
    sys.exit(main())
  File "/Users/XXXX/.virtualenvs/testflake9/lib/python3.9/site-packages/flake8/main/cli.py", line 41, in main
    loaded_plugins = finder.load_plugins(plugins, plugin_paths)
  File "/Users/XXXX/.virtualenvs/testflake9/lib/python3.9/site-packages/flake8/plugins/finder.py", line 256, in load_plugins
    return _classify_plugins(_import_plugins(plugins, paths))
  File "/Users/XXXX/.virtualenvs/testflake9/lib/python3.9/site-packages/flake8/plugins/finder.py", line 218, in _import_plugins
    return [_load_plugin(p) for p in plugins]
  File "/Users/XXXX/.virtualenvs/testflake9/lib/python3.9/site-packages/flake8/plugins/finder.py", line 218, in <listcomp>
    return [_load_plugin(p) for p in plugins]
  File "/Users/XXXX/.virtualenvs/testflake9/lib/python3.9/site-packages/flake8/plugins/finder.py", line 205, in _load_plugin
    raise FailedToLoadPlugin(plugin.package, e)
flake8.exceptions.FailedToLoadPlugin: Flake8 failed to load plugin "local" due to No module named 'resources'.
```

Yeah tried and unfortunately does not work (same issue as with latest release).
Happy to test if you have another fix. 

I have used .flake8 using:
```
[flake8:local-plugins]
extension =
    I25 = resources.some_checker:SomeChecker
paths =
    .
```

**Comment by asottile** [comment]
ah, you want `paths = ./` actually it seems

**Comment by matejsp** [comment]
I see ... yes paths = ./ seems to work even from subfolder (with flake 3.9.2).
I would prefer more lenient setup ... "." should be valid path or it should report as error/warn if "." is ignored.

From my side "paths = ./" is actually a solution to my problem.

**Comment by asottile** [comment]
they mean ~slightly different things -- `.` isn't invalid it's just not normalized to the configuration location (since it does not contain a `/`)
