### ISSUE TITLE
TypeError instead of reported syntax error

### ISSUE THREAD

**Issue by asottile** [PyCQA/flake8#154]
In GitLab by @jamert on Sep 2, 2016, 10:32

Version information:

`$ python --version
Python 2.7.11
`
flake8 installed through pipsi, which executes command pip install -U flake8

`$ pip --version
pip 8.1.2 from /Users/install/.local/venvs/flake8/lib/python2.7/site-packages (python 2.7)
`
`$ python -c 'import setuptools; print(setuptools.__version__)'
18.2
`
`$ flake8 --version
3.0.4 (mccabe: 0.5.2, pyflakes: 1.2.3, pycodestyle: 2.0.0) CPython 2.7.11 on Darwin
`

Problem is reproduced by running flake8 command on file with the following content (also in attachment):
`
$ cat flake_error.py
"".format(columns='', 0)`
(non-keyword argument after keyword argument)

Expected: flake8 reports syntax error

Encountered:
`
$ flake8 flake_error.py
Traceback (most recent call last):
  File "/Users/install/.local/bin/flake8", line 11, in <module>
    sys.exit(main())
  File "/Users/install/.local/venvs/flake8/lib/python2.7/site-packages/flake8/main/cli.py", line 16, in main
    app.run(argv)
  File "/Users/install/.local/venvs/flake8/lib/python2.7/site-packages/flake8/main/application.py", line 316, in run
    self._run(argv)
  File "/Users/install/.local/venvs/flake8/lib/python2.7/site-packages/flake8/main/application.py", line 302, in _run
    self.report_errors()
  File "/Users/install/.local/venvs/flake8/lib/python2.7/site-packages/flake8/main/application.py", line 268, in report_errors
    results = self.file_checker_manager.report()
  File "/Users/install/.local/venvs/flake8/lib/python2.7/site-packages/flake8/checker.py", line 298, in report
    results)
  File "/Users/install/.local/venvs/flake8/lib/python2.7/site-packages/flake8/checker.py", line 215, in _handle_results
    physical_line=physical_line,
  File "/Users/install/.local/venvs/flake8/lib/python2.7/site-packages/flake8/style_guide.py", line 257, in handle_error
    error = Error(code, filename, line_number, column_number + 1, text,
TypeError: unsupported operand type(s) for +: 'NoneType' and 'int'
`[flake_error.py](/uploads/0628972886f7fcd73b63874dcda70f7d/flake_error.py)

**Comment by asottile** [comment]
In GitLab by @sigmavirus24 on Sep 5, 2016, 05:41

Thank you for the detailed report! This is awesome!

This is a duplicate of #214.
