### ISSUE TITLE
Exception when handling kwargs before args

### ISSUE THREAD

**Issue by asottile** [PyCQA/flake8#157]
In GitLab by @ericlarssen-wf on Sep 14, 2016, 10:44

Flake8 breaks when handling kwargs before args. 

``` python
foo(y='baz', 'bar')
```

``` sh
Traceback (most recent call last):
  File "/bin/flake8", line 11, in <module>
    load_entry_point('flake8==3.0.4', 'console_scripts', 'flake8')()
  File "/lib/python2.7/site-packages/flake8/main/cli.py", line 16, in main
    app.run(argv)
  File "/lib/python2.7/site-packages/flake8/main/application.py", line 316, in run
    self._run(argv)
  File "/lib/python2.7/site-packages/flake8/main/application.py", line 302, in _run
    self.report_errors()
  File "/lib/python2.7/site-packages/flake8/main/application.py", line 268, in report_errors
    results = self.file_checker_manager.report()
  File "/lib/python2.7/site-packages/flake8/checker.py", line 298, in report
    results)
  File "/lib/python2.7/site-packages/flake8/checker.py", line 215, in _handle_results
    physical_line=physical_line,
  File "/lib/python2.7/site-packages/flake8/style_guide.py", line 257, in handle_error
    error = Error(code, filename, line_number, column_number + 1, text,
TypeError: unsupported operand type(s) for +: 'NoneType' and 'int'
```

------------------------------------------------------------------------------------------------------------------------
- Python 2.7.10
- Installed via pip 6.0.6
- Setuptools version 26.1.1
- Flake8 3.0.4 (mccabe: 0.5.2, pyflakes: 1.2.3, pycodestyle: 2.0.0) CPython 2.7.10 on Darwin

**Comment by asottile** [comment]
In GitLab by @sigmavirus24 on Sep 15, 2016, 18:21

See also #214 which has been fixed on master.
