### ISSUE TITLE
`--config` option breaks relative paths when searching for plugins

### ISSUE THREAD

**Issue by JordanLongstaff** [PyCQA/flake8#1606]
### how did you install flake8?

```console
$ pip install flake8
```

### unmodified output of `flake8 --bug-report`

```json
{
  "dependencies": [],
  "platform": {
    "python_implementation": "CPython",
    "python_version": "3.9.9",
    "system": "Darwin"
  },
  "plugins": [
    {
      "is_local": false,
      "plugin": "encircle-import-layers",
      "version": "0.1"
    },
    {
      "is_local": false,
      "plugin": "flake8-docstrings",
      "version": "1.5.0, pydocstyle: 5.0.2"
    },
    {
      "is_local": false,
      "plugin": "flake8-no-pep420",
      "version": "1.2.0"
    },
    {
      "is_local": false,
      "plugin": "flake8-noqa",
      "version": "1.2.1"
    },
    {
      "is_local": false,
      "plugin": "mccabe",
      "version": "0.6.1"
    },
    {
      "is_local": false,
      "plugin": "pycodestyle",
      "version": "2.8.0"
    },
    {
      "is_local": false,
      "plugin": "pyflakes",
      "version": "2.4.0"
    },
    {
      "is_local": false,
      "plugin": "warn-symbols",
      "version": "1.1.1"
    }
  ],
  "version": "4.0.1"
}
```

#### what I expected to happen

The `flake8` command is contained in the sample code, which runs as part of the Python script that is failing (see "commands ran"). It reads config from `.flake8` (in the checkout directory), writes it to a temp file (e.g. `/var/folders/g8/92bxgvv513v7nr_44jx8x3t80000gn/T/tmp520cn52e`), and then uses that temp file as a temporary config file for `flake8`. It's supposed to work properly, but it doesn't, because the config includes a custom plugin that should be found relative to the checkout directory, but apparently the directory of the temp file is being searched instead. Forcing the temp file to be written in the checkout directory fixes the issue.

Here's the relevant piece of the config in `.flake8`:

```
[flake8:local-plugins]
extension =
  ENC1 = server.flake8.import_layers:ImportLayersChecker
# Note: Without the trailing slash this only works from the checkout root!
paths = ./
```

#### sample code

```python
def run_flake8(config: str) -> str:
    with NamedTemporaryFile() as tmp:
        tmp.write(config.encode("utf8"))
        tmp.flush()
        return subprocess.run(
            [
                "flake8",
                "--config",
                tmp.name,
                "server",
            ],
            cwd=CHECKOUT,
            stdout=subprocess.PIPE,
        ).stdout.decode("utf8")
```

#### commands ran

```console
$ python3 -m server.scripts.refactoring.flake8_exceptions
Traceback (most recent call last):
  File "/Users/jordanlongstaff/.local/share/virtualenvs/encircle/lib/python3.9/site-packages/flake8/plugins/manager.py", line 161, in load_plugin
    self._load()
  File "/Users/jordanlongstaff/.local/share/virtualenvs/encircle/lib/python3.9/site-packages/flake8/plugins/manager.py", line 138, in _load
    self._plugin = self.entry_point.load()
  File "/Users/jordanlongstaff/.pyenv/versions/3.9.9/lib/python3.9/importlib/metadata.py", line 77, in load
    module = import_module(match.group('module'))
  File "/Users/jordanlongstaff/.pyenv/versions/3.9.9/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 972, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 972, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 984, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'server'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/jordanlongstaff/.local/share/virtualenvs/encircle/bin/flake8", line 8, in <module>
    sys.exit(main())
  File "/Users/jordanlongstaff/.local/share/virtualenvs/encircle/lib/python3.9/site-packages/flake8/main/cli.py", line 22, in main
    app.run(argv)
  File "/Users/jordanlongstaff/.local/share/virtualenvs/encircle/lib/python3.9/site-packages/flake8/main/application.py", line 375, in run
    self._run(argv)
  File "/Users/jordanlongstaff/.local/share/virtualenvs/encircle/lib/python3.9/site-packages/flake8/main/application.py", line 363, in _run
    self.initialize(argv)
  File "/Users/jordanlongstaff/.local/share/virtualenvs/encircle/lib/python3.9/site-packages/flake8/main/application.py", line 343, in initialize
    self.find_plugins(config_finder)
  File "/Users/jordanlongstaff/.local/share/virtualenvs/encircle/lib/python3.9/site-packages/flake8/main/application.py", line 163, in find_plugins
    self.check_plugins.load_plugins()
  File "/Users/jordanlongstaff/.local/share/virtualenvs/encircle/lib/python3.9/site-packages/flake8/plugins/manager.py", line 422, in load_plugins
    plugins = list(self.manager.map(load_plugin))
  File "/Users/jordanlongstaff/.local/share/virtualenvs/encircle/lib/python3.9/site-packages/flake8/plugins/manager.py", line 309, in map
    yield func(self.plugins[name], *args, **kwargs)
  File "/Users/jordanlongstaff/.local/share/virtualenvs/encircle/lib/python3.9/site-packages/flake8/plugins/manager.py", line 420, in load_plugin
    return plugin.load_plugin()
  File "/Users/jordanlongstaff/.local/share/virtualenvs/encircle/lib/python3.9/site-packages/flake8/plugins/manager.py", line 168, in load_plugin
    raise failed_to_load
flake8.exceptions.FailedToLoadPlugin: Flake8 failed to load plugin "ENC1" due to No module named 'server'.
```

**Comment by asottile** [comment]
local plugin paths are relative to the configuration -- that's why they're "local" -- this is intentional and not going to change

you can probably use `python -m flake8` to add `.` to the path (or more explicitly use `PYTHONPATH` -- though that's usually a smell that you're trying to do something hacky)
