### ISSUE TITLE
Error while trying to use flake8 via Win10 console

### ISSUE THREAD

**Issue by asottile** [PyCQA/flake8#162]
In GitLab by @Wolfone on Sep 24, 2016, 02:43

Hello everyone,

my version information is as follows:

-Python 3.5.2

flake installed via pip with version:

-pip 8.1.2

trying to find setup-tools produced the following output:
> C:\Users\Wolfone>python -c 'import setuptools; print(setuptools.__version__)'
>   File "<string>", line 1
>     'import
>           ^
> SyntaxError: EOL while scanning string literal

output of `flake8 --version`:

> 3.0.4 (pycodestyle: 2.0.0, mccabe: 0.5.2, hacking.core: 0.0.1, ProxyChecker: 0.0.1, flake8-docstrings: 1.0.2, pydocstyle: 1.0.0, pyflakes: 1.2.3) CPython 3.5.2 on Windows 

I was trying was to check a simple testfile with the following content:

```
def product(x, y):
    return x*y

    x=b

```
What i expected was something like:

> [...] undefined name 'b' 

what i got was:

> Traceback (most recent call last):
>   File "e:\programmierung\python\lib\site-packages\flake8\checker.py", line 449, in run_check
>     arguments,
>   File "e:\programmierung\python\lib\site-packages\flake8\processor.py", line 214, in keyword_arguments_for
>     arguments[param] = getattr(self, param)
> AttributeError: 'FileProcessor' object has no attribute 'physical_line'
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last):
>   File "e:\programmierung\python\lib\runpy.py", line 184, in _run_module_as_main
>     "__main__", mod_spec)
>   File "e:\programmierung\python\lib\runpy.py", line 85, in _run_code
>     exec(code, run_globals)
>   File "E:\Programmierung\Python\Scripts\flake8.exe\__main__.py", line 9, in <module>
>   File "e:\programmierung\python\lib\site-packages\flake8\main\cli.py", line 16, in main
>     app.run(argv)
>   File "e:\programmierung\python\lib\site-packages\flake8\main\application.py", line 316, in run
>     self._run(argv)
>   File "e:\programmierung\python\lib\site-packages\flake8\main\application.py", line 300, in _run
>     self.run_checks()
>   File "e:\programmierung\python\lib\site-packages\flake8\main\application.py", line 238, in run_checks
>     self.file_checker_manager.run()
>   File "e:\programmierung\python\lib\site-packages\flake8\checker.py", line 343, in run
>     self.run_serial()
>   File "e:\programmierung\python\lib\site-packages\flake8\checker.py", line 327, in run_serial
>     checker.run_checks(self.results_queue, self.statistics_queue)
>   File "e:\programmierung\python\lib\site-packages\flake8\checker.py", line 568, in run_checks
>     self.process_tokens()
>   File "e:\programmierung\python\lib\site-packages\flake8\checker.py", line 552, in process_tokens
>     self.handle_newline(token_type)
>   File "e:\programmierung\python\lib\site-packages\flake8\checker.py", line 595, in handle_newline
>     self.run_logical_checks()
>   File "e:\programmierung\python\lib\site-packages\flake8\checker.py", line 503, in run_logical_checks
>     results = self.run_check(plugin, logical_line=logical_line) or ()
>   File "e:\programmierung\python\lib\site-packages\flake8\checker.py", line 455, in run_check
>     exception=ae,
> flake8.exceptions.PluginRequestedUnknownParameters: "hacking.core" requested unknown parameters causing 'FileProcessor' object has no attribute 'physical_line'

I was doing the setup to start working with python, so i have no real experience and i apologize if i did any mistakes which led to me stealing someones time.

Best wishes 
Wolf

**Comment by asottile** [comment]
In GitLab by @sigmavirus24 on Sep 25, 2016, 06:21

Hi Wolf!

The Hacking extension is not yet compatible with Flake8 3. This means that it will not work for you and Flake8 will appear broken until you uninstall Hacking. Alternatively, if you do `pip install -U --force-reinstall hacking` then it will downgrade Flake8 to a version it supports.

Cheers,
Ian
