### ISSUE TITLE
flake8 does not start after upgrade from 4.0.1 to 5.0.0

### ISSUE THREAD

**Issue by inputvalidation** [PyCQA/flake8#1627]
### how did you install flake8?

```console
pip install flake8
```

### unmodified output of `flake8 --bug-report`

```json
{
"error": "impossible to provide this, --bug-report exits with an Exception"
}
```

#### what I expected to happen

flake8 runs, it stopped working after our CI automatically upgraded from 4.0.1 to 5.0.0. Running on Python 3.8 which is installed through RHELs Software Collections.

#### commands ran

```console
$ flake8 .
Traceback (most recent call last):
  File "/home/x/repo/.env/bin/flake8", line 8, in <module>
    sys.exit(main())
  File "/home/x/repo/.env/lib64/python3.8/site-packages/flake8/main/cli.py", line 22, in main
    app.run(argv)
  File "/home/x/repo/.env/lib64/python3.8/site-packages/flake8/main/application.py", line 336, in run
    self._run(argv)
  File "/home/x/repo/.env/lib64/python3.8/site-packages/flake8/main/application.py", line 324, in _run
    self.initialize(argv)
  File "/home/x/repo/.env/lib64/python3.8/site-packages/flake8/main/application.py", line 308, in initialize
    self.register_plugin_options()
  File "/home/x/repo/.env/lib64/python3.8/site-packages/flake8/main/application.py", line 140, in register_plugin_options
    self.option_manager.register_plugins(self.plugins)
  File "/home/x/repo/.env/lib64/python3.8/site-packages/flake8/options/manager.py", line 376, in register_plugins
    add_options(self)
  File "/home/x/repo/.env/lib64/python3.8/site-packages/mccabe.py", line 256, in add_options
    parser.add_option(flag, **kwargs)
  File "/home/x/repo/.env/lib64/python3.8/site-packages/flake8/options/manager.py", line 398, in add_option
    self._current_group.add_argument(*option_args, **option_kwargs)
  File "/opt/rh/rh-python38/root/usr/lib64/python3.8/argparse.py", line 1386, in add_argument
    return self._add_action(action)
  File "/opt/rh/rh-python38/root/usr/lib64/python3.8/argparse.py", line 1590, in _add_action
    action = super(_ArgumentGroup, self)._add_action(action)
  File "/opt/rh/rh-python38/root/usr/lib64/python3.8/argparse.py", line 1400, in _add_action
    self._check_conflict(action)
  File "/opt/rh/rh-python38/root/usr/lib64/python3.8/argparse.py", line 1539, in _check_conflict
    conflict_handler(action, confl_optionals)
  File "/opt/rh/rh-python38/root/usr/lib64/python3.8/argparse.py", line 1548, in _handle_conflict_error
    raise ArgumentError(action, message % conflict_string)
argparse.ArgumentError: argument --max-complexity: conflicting option string: --max-complexity
```

**Comment by asottile** [comment]
can you show reproducibly how you've set up flake8?  the error message indicates you have two different copies of flake8 installed

**Comment by sigmavirus24** [comment]
I agree with @asottile . You say you used pip and then software collections and those two are not the same thing

**Comment by inputvalidation** [comment]
Apologies, wanted to make clear that Python 3.8 itself was installed through SCL. I'm then creating a venv with Python 3.8 and using pip to install flake8:

```
# scl enable rh-python38 bash

# python -m venv flake8-start

# source flake8-start/bin/activate

(flake8-start) # pip install flake8
Collecting flake8
  Using cached https://files.pythonhosted.org/packages/ad/b5/27d1c9553cfd5282e5f94fe0306b231890d42d86506fb7f623bc638e741e/flake8-5.0.0-py2.py3-none-any.whl
Collecting pycodestyle<2.10.0,>=2.9.0
  Using cached https://files.pythonhosted.org/packages/a4/9e/2f9e7d5b13ad7c326f99d08d36757fc02fcd137cd5898b216a9faca38f9a/pycodestyle-2.9.0-py2.py3-none-any.whl
Collecting pyflakes<2.6.0,>=2.5.0
  Using cached https://files.pythonhosted.org/packages/dc/13/63178f59f74e53acc2165aee4b002619a3cfa7eeaeac989a9eb41edf364e/pyflakes-2.5.0-py2.py3-none-any.whl
Collecting mccabe<0.8.0,>=0.7.0
  Using cached https://files.pythonhosted.org/packages/27/1a/1f68f9ba0c207934b35b86a8ca3aad8395a3d6dd7921c0686e23853ff5a9/mccabe-0.7.0-py2.py3-none-any.whl
Installing collected packages: pycodestyle, pyflakes, mccabe, flake8
Successfully installed flake8-5.0.0 mccabe-0.7.0 pycodestyle-2.9.0 pyflakes-2.5.0
WARNING: You are using pip version 19.3.1; however, version 22.2.1 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.

(flake8-start)# pip freeze
flake8==5.0.0
mccabe==0.7.0
pycodestyle==2.9.0
pyflakes==2.5.0

(flake8-start) # flake8
Traceback (most recent call last):
  File "/home/x/flake8-start/bin/flake8", line 8, in <module>
    sys.exit(main())
  File "/home/x/flake8-start/lib64/python3.8/site-packages/flake8/main/cli.py", line 22, in main
    app.run(argv)
  File "/home/x/flake8-start/lib64/python3.8/site-packages/flake8/main/application.py", line 336, in run
    self._run(argv)
  File "/home/x/flake8-start/lib64/python3.8/site-packages/flake8/main/application.py", line 324, in _run
    self.initialize(argv)
  File "/home/x/flake8-start/lib64/python3.8/site-packages/flake8/main/application.py", line 308, in initialize
    self.register_plugin_options()
  File "/home/x/flake8-start/lib64/python3.8/site-packages/flake8/main/application.py", line 140, in register_plugin_options
    self.option_manager.register_plugins(self.plugins)
  File "/home/x/flake8-start/lib64/python3.8/site-packages/flake8/options/manager.py", line 376, in register_plugins
    add_options(self)
  File "/home/x/flake8-start/lib64/python3.8/site-packages/mccabe.py", line 256, in add_options
    parser.add_option(flag, **kwargs)
  File "/home/x/flake8-start/lib64/python3.8/site-packages/flake8/options/manager.py", line 398, in add_option
    self._current_group.add_argument(*option_args, **option_kwargs)
  File "/opt/rh/rh-python38/root/usr/lib64/python3.8/argparse.py", line 1386, in add_argument
    return self._add_action(action)
  File "/opt/rh/rh-python38/root/usr/lib64/python3.8/argparse.py", line 1590, in _add_action
    action = super(_ArgumentGroup, self)._add_action(action)
  File "/opt/rh/rh-python38/root/usr/lib64/python3.8/argparse.py", line 1400, in _add_action
    self._check_conflict(action)
  File "/opt/rh/rh-python38/root/usr/lib64/python3.8/argparse.py", line 1539, in _check_conflict
    conflict_handler(action, confl_optionals)
  File "/opt/rh/rh-python38/root/usr/lib64/python3.8/argparse.py", line 1548, in _handle_conflict_error
    raise ArgumentError(action, message % conflict_string)
argparse.ArgumentError: argument --max-complexity: conflicting option string: --max-complexity
```

**Comment by asottile** [comment]
hmm this is arguably 2 bugs:
- rhel's packaging of python adds both `lib` and `lib64` to `sys.path` (though `lib64` is a symlink to `lib`)
- python's `importlib.metadata.distributions` provides duplicate distributions in this situation (despite one of the `sys.path` entries being unreachable)

I can hack around these two things being broken but I'd recommend reporting both of those to each of the respective upstreams
