### ISSUE TITLE
AttributeError: 'OptionManager' object has no attribute 'generate_versions'

### ISSUE THREAD

**Issue by iuiu34** [PyCQA/flake8#1638]
### how did you install flake8?

```console
pip install flake8
```

### unmodified output of `flake8 --bug-report`

```json
{
  "platform": {
    "python_implementation": "CPython",
    "python_version": "3.9.9",
    "system": "Windows"
  },
  "plugins": [
    {
      "plugin": "flake8-html",
      "version": "0.4.2"
    },
    {
      "plugin": "mccabe",
      "version": "0.7.0"
    },
    {
      "plugin": "pycodestyle",
      "version": "2.9.0"
    },
    {
      "plugin": "pyflakes",
      "version": "2.5.0"
    }
  ],
  "version": "5.0.1"
}
```

### describe the problem

flake8==5.0.1 throws following error (With flake8==4.0.1 didn't happen)

flake8 '--exclude=*_old*,*.idea*' --max-complexity 15 --format=html --htmldir=tox/flake-report src    
Traceback (most recent call last):
  File "C:\MyProgramFiles\Python\Python39\lib\runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\MyProgramFiles\Python\Python39\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\Users\user\repo\.tox\flake8\Scripts\flake8.EXE\__main__.py", line 7, in <module>
  File "C:\Users\user\repo\.tox\flake8\lib\site-packages\flake8\main\cli.py", line 22, in main
    app.run(argv)
  File "C:\Users\user\repo\.tox\flake8\lib\site-packages\flake8\main\application.py", line 336, in run
    self._run(argv)
  File "C:\Users\user\repo\.tox\flake8\lib\site-packages\flake8\main\application.py", line 326, in _run        
    self.report()
  File "C:\Users\user\repo\.tox\flake8\lib\site-packages\flake8\main\application.py", line 321, in report      
    self.formatter.stop()
  File "C:\Users\user\repo\.tox\flake8\lib\site-packages\flake8_html\plugin.py", line 245, in stop
    self.write_index()
  File "C:\Users\user\repo\.tox\flake8\lib\site-packages\flake8_html\plugin.py", line 281, in write_index      
    versions=self.option_manager.generate_versions(),
AttributeError: 'OptionManager' object has no attribute 'generate_versions'
ERROR: InvocationError for command 'C:\Users\user\repo\.tox\flake8\Scripts\flake8.EXE' '--exclude=*_old*,*.idea
*' --max-complexity 15 --format=html --htmldir=tox/flake-report src (exited with code 1)
_____________________________________________________________ summary ______________________________________________________________ 
ERROR:   flake8: commands failed
ERROR: InvocationError for command 'C:\Users\user\repo\.tox\py39\Scripts\tox.EXE' -e flake8 (exited with code 1
)
_____________________________________________________________ summary ______________________________________________________________ 
ERROR:   py39: commands failed

**Comment by asottile** [comment]
please report to flake8-html, they are attempting to monkeypatch internals which is not supported

**Comment by iuiu34** [comment]
https://github.com/lordmauve/flake8-html/issues/30

**Comment by immanuel-h** [comment]
> please report to flake8-html, they are attempting to monkeypatch / access internals which is not supported

That would be a much more useful statement if there was any indication on what is considered "internal" and what isn't. The method used previously looks innocent enough and has no indication that it shouldn't be used. I wanted to have a look on how to address the issue, but there does not appear to be any sort of actual API reference around that one could use.

**Comment by asottile** [comment]
@immanuel-h there's an `api` module
