### ISSUE TITLE
AttributeError: 'OptionManager' object has no attribute 'generate_versions'

### ISSUE THREAD

**Issue by shadownetdev1** [PyCQA/flake8#1644]
### how did you install flake8?

```console
pip install coverage flake8 pytest pytest-html genbadge[all] vulture pylint
Collecting coverage
  Downloading coverage-6.4.2-cp310-cp310-manylinux_2_5_x86_64.manylinux1_x86_64.manylinux_2_17_x86_64.manylinux2014_x86_64.whl (212 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 212.3/212.3 kB 10.8 MB/s eta 0:00:00
Collecting flake8
  Downloading flake8-5.0.2-py2.py3-none-any.whl (61 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 61.9/61.9 kB 18.6 MB/s eta 0:00:00
...
Collecting flake8-html
  Downloading flake8_html-0.4.2-py2.py3-none-any.whl (12 kB)
...
Installing collected packages: iniconfig, wrapt, urllib3, tomlkit, tomli, toml, pyparsing, pygments, pyflakes, pycodestyle, py, pluggy, platformdirs, pillow, mccabe, MarkupSafe, lazy-object-proxy, isort, idna, dill, defusedxml, coverage, click, charset-normalizer, certifi, attrs, vulture, requests, packaging, jinja2, flake8, astroid, pytest, pylint, genbadge, flake8-html, pytest-metadata, pytest-html
Successfully installed MarkupSafe-2.1.1 astroid-2.11.7 attrs-22.1.0 certifi-2022.6.15 charset-normalizer-2.1.0 click-8.1.3 coverage-6.4.2 defusedxml-0.7.1 dill-0.3.5.1 flake8-5.0.2 flake8-html-0.4.2 genbadge-1.1.0 idna-3.3 iniconfig-1.1.1 isort-5.10.1 jinja2-3.1.2 lazy-object-proxy-1.7.1 mccabe-0.7.0 packaging-21.3 pillow-9.2.0 platformdirs-2.5.2 pluggy-1.0.0 py-1.11.0 pycodestyle-2.9.0 pyflakes-2.5.0 pygments-2.12.0 pylint-2.14.5 pyparsing-3.0.9 pytest-7.1.2 pytest-html-3.1.1 pytest-metadata-2.0.2 requests-2.28.1 toml-0.10.2 tomli-2.0.1 tomlkit-0.11.1 urllib3-1.26.11 vulture-2.5 wrapt-1.14.1
```

### unmodified output of `flake8 --bug-report`

```json
Cannot provide
Ran via Github actions
Installed versions are in the install log
Python version is 3.10
os is Ubuntu-latest
mccabe is 0.7.0
pycodestyle is 2.9.0
pyflakes is 2.5.0
flake8 is 5.0.2
The workflow that ran flake8 is at https://github.com/shadownetdev1/hydrus-experimental/blob/master/.github/workflows/push_pull_handling.yml
```

#### what I expected to happen
expected it to create a report
...

#### commands ran and output

```console
$ flake8 . --extend-exclude venv,.venv --count --exit-zero --format=html --htmldir .github/reports/flake8 --statistics --tee --output-file .github/reports/flake8stats.txt
...
hydrus/core/HydrusClipHandling.py has issues: high: 3 medium: 195
Traceback (most recent call last):
2     E114 indentation is not a multiple of 4 (comment)
  File "/opt/hostedtoolcache/Python/3.10.5/x64/bin/flake8", line 8, in <module>
    sys.exit(main())
  File "/opt/hostedtoolcache/Python/3.10.5/x64/lib/python3.10/site-packages/flake8/main/cli.py", line 22, in main
    app.run(argv)
  File "/opt/hostedtoolcache/Python/3.10.5/x64/lib/python3.10/site-packages/flake8/main/application.py", line 336, in run
    self._run(argv)
  File "/opt/hostedtoolcache/Python/3.10.5/x64/lib/python3.10/site-packages/flake8/main/application.py", line 326, in _run
    self.report()
  File "/opt/hostedtoolcache/Python/3.10.5/x64/lib/python3.10/site-packages/flake8/main/application.py", line 321, in report
    self.formatter.stop()
  File "/opt/hostedtoolcache/Python/3.10.5/x64/lib/python3.10/site-packages/flake8_html/plugin.py", line 245, in stop
    self.write_index()
  File "/opt/hostedtoolcache/Python/3.10.5/x64/lib/python3.10/site-packages/flake8_html/plugin.py", line 281, in write_index
    versions=self.option_manager.generate_versions(),
AttributeError: 'OptionManager' object has no attribute 'generate_versions'
4     E116 unexpected indentation (comment)
...
```

**Comment by asottile** [comment]
in the future please search the tracker https://github.com/PyCQA/flake8/issues?q=is%3Aissue+generate_versions+is%3Aclosed
