### ISSUE TITLE
Release v5.0.3 - ImportError: cannot import name 'ConfigFileFinder'

### ISSUE THREAD

**Issue by vjeeva** [PyCQA/flake8#1652]
### how did you install flake8?

```console
poetry install flake8==5.0.3
```

### unmodified output of `flake8 --bug-report`

```json
This won't run either, due to the traceback.
```

#### what I expected to happen

```console
$ flake8 .
```

Should just exit 0.

#### what I'm seeing

```console
Traceback (most recent call last):
  File "/Users/vjeeva/.pyenv/versions/3.9.11/envs/pgbelt/lib/python3.9/site-packages/flake8/plugins/finder.py", line 296, in _load_plugin
    obj = plugin.entry_point.load()
  File "/Users/vjeeva/.pyenv/versions/3.9.11/lib/python3.9/importlib/metadata.py", line 86, in load
    module = import_module(match.group('module'))
  File "/Users/vjeeva/.pyenv/versions/3.9.11/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/Users/vjeeva/.pyenv/versions/3.9.11/envs/pgbelt/lib/python3.9/site-packages/flake8_bandit.py", line 10, in <module>
    from flake8.options.config import ConfigFileFinder
ImportError: cannot import name 'ConfigFileFinder' from 'flake8.options.config' (/Users/vjeeva/.pyenv/versions/3.9.11/envs/pgbelt/lib/python3.9/site-packages/flake8/options/config.py)
```

I see this both on my local Mac (running Python 3.9.11, Poetry 1.1.14), and my GitHub Actions CI (ubuntu-latest).

#### commands ran

```console
$ flake8 .
```

**Comment by asottile** [comment]
`flake8-bandit` access private implementation details

**Comment by valeriupredoi** [comment]
@asottile this is a much wider issue reported by many others, see https://github.com/tholo/pytest-flake8/issues/87 - I think you guys should have a closer look please :+1:

**Comment by asottile** [comment]
pytest-flake8 accesses private implementation detail
