### ISSUE TITLE
flake8.exceptions.FailedToLoadPlugin: Flake8 failed to load plugin "pycodestyle.missing_whitespace_after_import_keyword"

### ISSUE THREAD

**Issue by danschef** [PyCQA/flake8#1668]
### how did you install flake8?

```console
pip install pycodestyle  # which depends on flake8
```

### unmodified output of `flake8 --bug-report`

```json
(ci_env) [root]# flake8 --bug-report
Traceback (most recent call last):
  File "/root/mambaforge/envs/ci_env/lib/python3.10/site-packages/flake8/plugins/manager.py", line 161, in load_plugin
    self._load()
  File "/root/mambaforge/envs/ci_env/lib/python3.10/site-packages/flake8/plugins/manager.py", line 138, in _load
    self._plugin = self.entry_point.load()
  File "/root/mambaforge/envs/ci_env/lib/python3.10/importlib/metadata/__init__.py", line 173, in load
    return functools.reduce(getattr, attrs, module)
AttributeError: module 'pycodestyle' has no attribute 'missing_whitespace_after_import_keyword'. Did you mean: 'missing_whitespace_after_keyword'?

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/root/mambaforge/envs/ci_env/bin/flake8", line 8, in <module>
    sys.exit(main())
  File "/root/mambaforge/envs/ci_env/lib/python3.10/site-packages/flake8/main/cli.py", line 22, in main
    app.run(argv)
  File "/root/mambaforge/envs/ci_env/lib/python3.10/site-packages/flake8/main/application.py", line 375, in run
    self._run(argv)
  File "/root/mambaforge/envs/ci_env/lib/python3.10/site-packages/flake8/main/application.py", line 363, in _run
    self.initialize(argv)
  File "/root/mambaforge/envs/ci_env/lib/python3.10/site-packages/flake8/main/application.py", line 343, in initialize
    self.find_plugins(config_finder)
  File "/root/mambaforge/envs/ci_env/lib/python3.10/site-packages/flake8/main/application.py", line 163, in find_plugins
    self.check_plugins.load_plugins()
  File "/root/mambaforge/envs/ci_env/lib/python3.10/site-packages/flake8/plugins/manager.py", line 422, in load_plugins
    plugins = list(self.manager.map(load_plugin))
  File "/root/mambaforge/envs/ci_env/lib/python3.10/site-packages/flake8/plugins/manager.py", line 309, in map
    yield func(self.plugins[name], *args, **kwargs)
  File "/root/mambaforge/envs/ci_env/lib/python3.10/site-packages/flake8/plugins/manager.py", line 420, in load_plugin
    return plugin.load_plugin()
  File "/root/mambaforge/envs/ci_env/lib/python3.10/site-packages/flake8/plugins/manager.py", line 168, in load_plugin
    raise failed_to_load
flake8.exceptions.FailedToLoadPlugin: Flake8 failed to load plugin "pycodestyle.missing_whitespace_after_import_keyword" due to module 'pycodestyle' has no attribute 'missing_whitespace_after_import_keyword'.
```

#### sample code

pycodestyle>=2.9.0 seems to be incompatible with the current flake8 release.

```
flake8 --max-line-length=120 heatr_benchmarks tests > ./tests/linting/flake8.log || \
        (cat ./tests/linting/flake8.log && exit 1)
Traceback (most recent call last):
  File "/root/mambaforge/envs/ci_env/lib/python3.10/site-packages/flake8/plugins/manager.py", line 161, in load_plugin
    self._load()
  File "/root/mambaforge/envs/ci_env/lib/python3.10/site-packages/flake8/plugins/manager.py", line 138, in _load
    self._plugin = self.entry_point.load()
  File "/root/mambaforge/envs/ci_env/lib/python3.10/importlib/metadata/__init__.py", line 173, in load
    return functools.reduce(getattr, attrs, module)
AttributeError: module 'pycodestyle' has no attribute 'missing_whitespace_after_import_keyword'. Did you mean: 'missing_whitespace_after_keyword'?

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/root/mambaforge/envs/ci_env/bin/flake8", line 8, in <module>
    sys.exit(main())
  File "/root/mambaforge/envs/ci_env/lib/python3.10/site-packages/flake8/main/cli.py", line 22, in main
    app.run(argv)
  File "/root/mambaforge/envs/ci_env/lib/python3.10/site-packages/flake8/main/application.py", line 375, in run
    self._run(argv)
  File "/root/mambaforge/envs/ci_env/lib/python3.10/site-packages/flake8/main/application.py", line 363, in _run
    self.initialize(argv)
  File "/root/mambaforge/envs/ci_env/lib/python3.10/site-packages/flake8/main/application.py", line 343, in initialize
    self.find_plugins(config_finder)
  File "/root/mambaforge/envs/ci_env/lib/python3.10/site-packages/flake8/main/application.py", line 163, in find_plugins
    self.check_plugins.load_plugins()
  File "/root/mambaforge/envs/ci_env/lib/python3.10/site-packages/flake8/plugins/manager.py", line 422, in load_plugins
    plugins = list(self.manager.map(load_plugin))
  File "/root/mambaforge/envs/ci_env/lib/python3.10/site-packages/flake8/plugins/manager.py", line 309, in map
    yield func(self.plugins[name], *args, **kwargs)
  File "/root/mambaforge/envs/ci_env/lib/python3.10/site-packages/flake8/plugins/manager.py", line 420, in load_plugin
    return plugin.load_plugin()
  File "/root/mambaforge/envs/ci_env/lib/python3.10/site-packages/flake8/plugins/manager.py", line 168, in load_plugin
    raise failed_to_load
flake8.exceptions.FailedToLoadPlugin: Flake8 failed to load plugin "pycodestyle.missing_whitespace_after_import_keyword" due to module 'pycodestyle' has no attribute 'missing_whitespace_after_import_keyword'.

**Comment by asottile** [comment]
search the issue tracker #1636 -- also read the output because pip will show you a big red thing
