### ISSUE TITLE
Empty `--stdin-display-name` raises `IndexError`

### ISSUE THREAD

**Issue by asottile** [PyCQA/flake8#167]
In GitLab by @dakra on Oct 7, 2016, 08:01

*Please provide the following version information*

- Version of Python which has Flake8 installed (e.g., `python -V`)
Python 3.5.2

- How you installed Flake8 (e.g., `pip`, `apt`, `yum`, etc.)

Both pip and arch pacman versions fail.

 - If you used pip, the version of pip installed (e.g., `pip --version`)

pip 8.1.2 from /usr/lib/python3.5/site-packages (python 3.5)

- Version of setuptools installed (e.g., `python -c 'import setuptools; print(setuptools.__version__)'`)

28.0.0

- Version of Flake8 installed (i.e., copy and paste all of the output from `flake8 --version`)

3.0.4 (pycodestyle: 2.0.0, mccabe: 0.5.2, pyflakes: 1.2.3) CPython 3.5.2 on Linux

*Please describe the problem or feature*

Emacs flycheck passes an empty string to the `--stdin-display-name` option if the buffer isn't saved.
This causes an exception in flake8.

```
echo "#test" | flake8 --stdin-display-name '' --format=default -
Traceback (most recent call last):
  File "/home/daniel/.virtualenvs/atomx/bin/flake8", line 11, in <module>
    sys.exit(main())
  File "/home/daniel/.virtualenvs/atomx/lib/python3.5/site-packages/flake8/main/cli.py", line 16, in main
    app.run(argv)
  File "/home/daniel/.virtualenvs/atomx/lib/python3.5/site-packages/flake8/main/application.py", line 316, in run
    self._run(argv)
  File "/home/daniel/.virtualenvs/atomx/lib/python3.5/site-packages/flake8/main/application.py", line 300, in _run
    self.run_checks()
  File "/home/daniel/.virtualenvs/atomx/lib/python3.5/site-packages/flake8/main/application.py", line 238, in run_checks
    self.file_checker_manager.run()
  File "/home/daniel/.virtualenvs/atomx/lib/python3.5/site-packages/flake8/checker.py", line 343, in run
    self.run_serial()
  File "/home/daniel/.virtualenvs/atomx/lib/python3.5/site-packages/flake8/checker.py", line 327, in run_serial
    checker.run_checks(self.results_queue, self.statistics_queue)
  File "/home/daniel/.virtualenvs/atomx/lib/python3.5/site-packages/flake8/checker.py", line 573, in run_checks
    self.run_ast_checks()
  File "/home/daniel/.virtualenvs/atomx/lib/python3.5/site-packages/flake8/checker.py", line 477, in run_ast_checks
    checker = self.run_check(plugin, tree=ast)
  File "/home/daniel/.virtualenvs/atomx/lib/python3.5/site-packages/flake8/checker.py", line 457, in run_check
    return plugin['plugin'](**arguments)
  File "/home/daniel/.virtualenvs/atomx/lib/python3.5/site-packages/flake8/plugins/pyflakes.py", line 55, in __init__
    filename = utils.normalize_paths(filename)[0]
IndexError: list index out of range
```

**Comment by asottile** [comment]
In GitLab by @sigmavirus24 on Oct 28, 2016, 05:14

Mentioned in merge request !129

**Comment by asottile** [comment]
In GitLab by @sigmavirus24 on Oct 28, 2016, 05:15

Thanks for the report @dakra!

**Comment by asottile** [comment]
In GitLab by @sigmavirus24 on Oct 28, 2016, 05:19

Status changed to closed by commit 352a7250b7f2f86d22a8172583b100e748fb70f9

**Comment by asottile** [comment]
In GitLab by @sigmavirus24 on Oct 28, 2016, 16:36

Mentioned in commit sigmavirus24/flake8@352a7250b7f2f86d22a8172583b100e748fb70f9

**Comment by asottile** [comment]
In GitLab by @sigmavirus24 on Oct 28, 2016, 16:36

Mentioned in commit sigmavirus24/flake8@b924191b3bc41343ba42156c357e72aa83417256
