### ISSUE TITLE
KeyError: 'bold' when we ran flake8 .

### ISSUE THREAD

**Issue by petrisorionel** [PyCQA/flake8#1672]
### how did you install flake8?

```console
pip install flake8
```

### unmodified output of `flake8 --bug-report`

```json
flake8 --bug-report
{                                       
  "platform": {
    "python_implementation": "CPython", 
    "python_version": "3.10.4",
    "system": "Windows"                 
  },                                    
  "plugins": [                          
    {                                   
      "plugin": "flake8-bugbear",       
      "version": "22.8.23"              
    },                                  
    {
      "plugin": "flake8-builtins",      
      "version": "1.5.3"
    },                                  
    {
      "plugin": "flake8-comprehensions",
      "version": "3.10.0"               
    },
    {
      "plugin": "flake8-docstrings",    
      "version": "1.6.0"                
    },
    {
      "plugin": "flake8-formatter-abspath",
      "version": "1.0.1"
    },
    {
      "plugin": "flake8-import-order",
      "version": "0.18.1"
    },
    {
      "plugin": "flake8-leading-blank-lines",
      "version": "1.0.4"
    },
    {
      "plugin": "flake8-length",
      "version": "0.3.0"
    },
    {
      "plugin": "flake8-logging-format",
      "version": "0.7.5"
    },
    {
      "plugin": "flake8-no-types",
      "version": "1.5.0"
    },
    {
      "plugin": "flake8-pie",
      "version": "0.16.0"
    },
    {
      "plugin": "flake8-pytest-style",
      "version": "1.6.0"
    },
    {
      "plugin": "flake8-return",
      "version": "1.1.3"
    },
    {
      "plugin": "flake8-simplify",
      "version": "0.19.3"
    },
    {
      "plugin": "flake8-tuple",
      "version": "0.4.1"
    },
    {
      "plugin": "flake8-unused-arguments",
      "version": "0.0.11"
    },
    {
      "plugin": "mccabe",
      "version": "0.7.0"
    },
    {
      "plugin": "pep8-naming",
      "version": "0.13.2"
    },
    {
      "plugin": "pycodestyle",
      "version": "2.9.1"
    },
    {
      "plugin": "pyflakes",
      "version": "2.5.0"
    }
  ],
  "version": "5.0.4"
}

```

### describe the problem

I have a tox.ini file in my root project with the following setup for flake8

```python
[flake8]
ignore = E501 PT006 R503 R504 SIM113 D100 D101 D102 D103 D104 D107 I100 I201 I202 PIE786 PIE799 PIE803 PIE795 SIM106 W503
exclude =
    __pycache__
    .git
    .idea
    .ipynb_checkpoints
    .mypy_cache
    .pytest_cache
    .vscode
    docker
    venv
count = True
format = abspath
max-line-length = 128
statistics = True
; flake8-import-order config
application-import-names = tests
import-order-style = pycharm
; flake8-docstrings config
docstring-convention = google
; flake8-logging-format config
enable-extensions=G
```

when we run flake8 . command KeyError: 'bold' is present.
when we run flake8 ... command no error is present

#### what I expected to happen
to see the number of flake8 errors
...

#### commands ran

```console
with venv activate run flake8 .

flake8 .
Traceback (most recent call last):
  File "C:\Users\user\AppData\Local\Programs\Python\Python310\lib\runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\user\AppData\Local\Programs\Python\Python310\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "C:\Users\user\workspace\project\venv\Scripts\flake8.exe\__main__.py", line 7, in <module>
  File "C:\Users\user\workspace\project\venv\lib\site-packages\flake8\main\cli.py", line 22, in main
    app.run(argv)
  File "C:\Users\user\workspace\project\venv\lib\site-packages\flake8\main\application.py", line 336, in run
    self._run(argv)
  File "C:\Users\user\workspace\project\venv\lib\site-packages\flake8\main\application.py", line 326, in _run
    self.report()
  File "C:\Users\user\workspace\project\venv\lib\site-packages\flake8\main\application.py", line 318, in report
    self.report_errors()
  File "C:\Users\user\workspace\project\venv\lib\site-packages\flake8\main\application.py", line 267, in report_errors
    results = self.file_checker_manager.report()
  File "C:\Users\user\workspace\project\venv\lib\site-packages\flake8\checker.py", line 191, in report
    results_reported += self._handle_results(filename, results)
  File "C:\Users\user\workspace\project\venv\lib\site-packages\flake8\checker.py", line 145, in _handle_results
    reported_results_count += style_guide.handle_error(
  File "C:\Users\user\workspace\project\venv\lib\site-packages\flake8\style_guide.py", line 301, in handle_error
    return guide.handle_error(
  File "C:\Users\user\workspace\project\venv\lib\site-packages\flake8\style_guide.py", line 449, in handle_error
    self.formatter.handle(error)
  File "C:\Users\user\workspace\project\venv\lib\site-packages\flake8\formatting\base.py", line 98, in handle
    line = self.format(error)
  File "C:\Users\user\workspace\project\venv\lib\site-packages\flake8_formatter_abspath\plugin.py", line 15, in format
    return default.Default.error_format % {
KeyError: 'bold'



flake8 ...  
0

...
```

**Comment by asottile** [comment]
please report it to the plugin that's erroring. this isn't a flake8 issue

**Comment by petrisorionel** [comment]
@asottile why is invalid, it is related to flake8 version "5.0.4"

**Comment by petrisorionel** [comment]
@asottile sorry, my bad, thanks.
