### ISSUE TITLE
Unable to make formatting plugin for flake8

### ISSUE THREAD

**Issue by asottile** [PyCQA/flake8#168]
In GitLab by @SalmonMode on Oct 12, 2016, 13:51

*Please provide the following version information*

- Python version: `2.7.12`
- How you installed Flake8: `pip`
  - pip version: `8.1.2`
- setuptools version: `28.0.0`
- Flake8 version: `3.0.4 (mccabe: 0.5.2, flake8-truveris: 0.1.0, pyflakes: 1.2.3, pycodestyle: 2.0.0) CPython 2.7.12 on Darwin`

*Please describe the problem or feature*

I managed to get an extension working to yield custom flake8 warnings, and was hoping to have flake8 also automatically fix those issues when found. I attempted to follow the documentation on how to create a formatting plugin, but no matter what I do, it just seems to show this error when I run `flake8`:

```
Traceback (most recent call last):
  File "/Users/cnejame/homebrew/bin/flake8", line 11, in <module>
    load_entry_point('flake8', 'console_scripts', 'flake8')()
  File "/Users/cnejame/homebrew/lib/python2.7/site-packages/flake8/main/cli.py", line 16, in main
    app.run(argv)
  File "/Users/cnejame/homebrew/lib/python2.7/site-packages/flake8/main/application.py", line 316, in run
    self._run(argv)
  File "/Users/cnejame/homebrew/lib/python2.7/site-packages/flake8/main/application.py", line 299, in _run
    self.initialize(argv)
  File "/Users/cnejame/homebrew/lib/python2.7/site-packages/flake8/main/application.py", line 293, in initialize
    self.make_notifier()
  File "/Users/cnejame/homebrew/lib/python2.7/site-packages/flake8/main/application.py", line 201, in make_notifier
    self.listener_trie = self.listening_plugins.build_notifier()
  File "/Users/cnejame/homebrew/lib/python2.7/site-packages/flake8/plugins/manager.py", line 428, in build_notifier
    notifier_trie.register_listener(name, self.manager[name])
TypeError: 'PluginManager' object has no attribute '__getitem__'
```

I'm mostly guessing at how to approach this, so I could be approaching this the wrong way, but here's [a link to the extension](https://github.com/truveris/flake8-truveris) I have working. To create the formatter, I just changed the `entry_points` arg in my `setup.py` file to this:

```python
    entry_points={
        "flake8.extension": [
            'T = flake8_truveris:CheckTruveris',
        ],
        "flake8.listen": [
            'T = flake8_truveris:FormatTruveris',
        ],
    },
```

and just made that `FormatTruveris` class in the `flake8_truveris/__init__.py` file. The class looked like this:

```python
class FormatTruveris(base.BaseFormatter):

    def format(self, error):
        return 'Example formatter: {0!r}'.format(error)
```

as I just wanted to see where this got me.

**Comment by asottile** [comment]
In GitLab by @sigmavirus24 on Oct 12, 2016, 13:55

Hi Chris,

Looking at [the documentation](http://flake8.pycqa.org/en/latest/plugin-development/registering-plugins.html) it says

> Finally, if your plugin performs extra report handling (formatting, filtering, etc.) it will use `flake8.report`.

But you're using `flake8.listen` so that won't work. Let me know how using `flake8.report` works.

**Comment by asottile** [comment]
In GitLab by @SalmonMode on Oct 12, 2016, 14:51

Ah, that did the trick. Thanks so much!
