### ISSUE TITLE
Specifying a non-keyword arg after a keyword arg crashes flake8 3.0.4.

### ISSUE THREAD

**Issue by asottile** [PyCQA/flake8#170]
In GitLab by @stavros on Oct 18, 2016, 04:35

This example will crash pyflakes:

```.python
test(arg1=True, "hi", arg3="bar")
```

with:

```.python
Traceback (most recent call last):
  File "/home/stavros/.virtualenvs/accountsweb/bin/flake8", line 11, in <module>
    sys.exit(main())
  File "/home/stavros/.virtualenvs/accountsweb/local/lib/python2.7/site-packages/flake8/main/cli.py", line 16, in main
    app.run(argv)
  File "/home/stavros/.virtualenvs/accountsweb/local/lib/python2.7/site-packages/flake8/main/application.py", line 316, in run
    self._run(argv)
  File "/home/stavros/.virtualenvs/accountsweb/local/lib/python2.7/site-packages/flake8/main/application.py", line 302, in _run
    self.report_errors()
  File "/home/stavros/.virtualenvs/accountsweb/local/lib/python2.7/site-packages/flake8/main/application.py", line 268, in report_errors
    results = self.file_checker_manager.report()
  File "/home/stavros/.virtualenvs/accountsweb/local/lib/python2.7/site-packages/flake8/checker.py", line 298, in report
    results)
  File "/home/stavros/.virtualenvs/accountsweb/local/lib/python2.7/site-packages/flake8/checker.py", line 215, in _handle_results
    physical_line=physical_line,
  File "/home/stavros/.virtualenvs/accountsweb/local/lib/python2.7/site-packages/flake8/style_guide.py", line 257, in handle_error
    error = Error(code, filename, line_number, column_number + 1, text,
TypeError: unsupported operand type(s) for +: 'NoneType' and 'int'
```

**Comment by asottile** [comment]
In GitLab by @eirnym on Oct 20, 2016, 07:39

This crash is only on Python 2.7.  flake8 on Python 3.5 doesn't have this error.

**Comment by asottile** [comment]
In GitLab by @sigmavirus24 on Nov 12, 2016, 11:48

This is a duplicate of #214 and the fix has already been committed to master.
