### ISSUE TITLE
AttributeError: 'EntryPoints' object has no attribute 'get'

### ISSUE THREAD

**Issue by Dai-Wenxun** [PyCQA/flake8#1708]
### how did you install flake8?

```console
None
```

### unmodified output of `flake8 --bug-report`

```json
Traceback (most recent call last):
  File "/home/runner/.cache/pre-commit/repo5rv4x7m3/py_env-python3.7/bin/flake8", line 8, in <module>
    sys.exit(main())
  File "/home/runner/.cache/pre-commit/repo5rv4x7m3/py_env-python3.7/lib/python3.7/site-packages/flake8/main/cli.py", line 22, in main
    app.run(argv)
  File "/home/runner/.cache/pre-commit/repo5rv4x7m3/py_env-python3.7/lib/python3.7/site-packages/flake8/main/application.py", line 360, in run
    self._run(argv)
  File "/home/runner/.cache/pre-commit/repo5rv4x7m3/py_env-python3.7/lib/python3.7/site-packages/flake8/main/application.py", line 347, in _run
    self.initialize(argv)
  File "/home/runner/.cache/pre-commit/repo5rv4x7m3/py_env-python3.7/lib/python3.7/site-packages/flake8/main/application.py", line 328, in initialize
    self.find_plugins(config_finder)
  File "/home/runner/.cache/pre-commit/repo5rv4x7m3/py_env-python3.7/lib/python3.7/site-packages/flake8/main/application.py", line 153, in find_plugins
    self.check_plugins = plugin_manager.Checkers(local_plugins.extension)
  File "/home/runner/.cache/pre-commit/repo5rv4x7m3/py_env-python3.7/lib/python3.7/site-packages/flake8/plugins/manager.py", line 357, in __init__
    self.namespace, local_plugins=local_plugins
  File "/home/runner/.cache/pre-commit/repo5rv4x7m3/py_env-python3.7/lib/python3.7/site-packages/flake8/plugins/manager.py", line 238, in __init__
    self._load_entrypoint_plugins()
  File "/home/runner/.cache/pre-commit/repo5rv4x7m3/py_env-python3.7/lib/python3.7/site-packages/flake8/plugins/manager.py", line 254, in _load_entrypoint_plugins
    eps = importlib_metadata.entry_points().get(self.namespace, ())
AttributeError: 'EntryPoints' object has no attribute 'get'
```

### describe the problem

None

**Comment by asottile** [comment]
dupe #1701
