### ISSUE TITLE
flake8 --enable-extensions problem.

### ISSUE THREAD

**Issue by asottile** [PyCQA/flake8#171]
In GitLab by @warsaw on Oct 24, 2016, 10:51

```
% flake8 --version
3.0.4 (pyflakes: 1.2.3, mccabe: 0.5.2, pycodestyle: 2.0.0) CPython 3.5.2+ on Linux
```

Originally posted on the code-quality mailing list, with some follow up with @sigmavirus24 

I am working on a [plugin](https://gitlab.com/warsaw/flufl.testhelpers) which provides a checker for GNU Mailman style imports.  I'm having trouble getting flake8 v3's `--enable-extensions` feature to work.  Here's what I'm doing:

```
class ImportOrder:
    name = 'flufl-import-order'
    version = '0.2'
    off_by_default = True

    def __init__(self, tree, filename):
        # ...

    def run(self):
        # ...
```

and it registers itself via:

```
setup(
    # ...
    entry_points={
        'flake8.extensions': ['U4 = flufl.testhelpers.imports:ImportOrder'],
        },
    # ...
    )
```

All of the plugin's error codes are `U40X` and `U41X` codes.  What I'd like to be able to do is to tell users to add this to their tox.ini file to enable the plugin:

```
[flake8]
enable-extensions = U4
```

But this doesn't seem to work.  I know that the extension runs just fine if I don't include the `off_by_default=True` class attribute, but as soon as I add that, there doesn't seem to be a way to re-enable it.  I don't want to have to tell users that the plugin always runs and that they have to suppress the U4 errors if they don't want it.

I've pdb'd through the code and have some additional information.

My plugin is getting called, and is reported its errors, but the `StyleGuide` in place has a different `self._extended_selected` depending on whether my plugin's `off_by_default` is True or False.

In the False case, I see my 'U4' code in `options.extended_default_select`.  In the True case, my code is *not* in that set.  In the True case, `is_user_selected()` returns `Ignored.Implicitly` because of that, while in the False case it returns `Selected.Implicitly`.  That's why I see the error code in the False case but not in the True case.

What appears to be happening is this:

With `off_by_default=False`, I can see that `Optionmanager.extend_default_select()` gets called with my error code *before* the `StyleGuide` instance is created (where the options are passed in to the `__init__()`).  With `off_by_default=True`, it seems like my error code gets passed in *after* the `StyleGuide` gets instantiated.  Thus, when the `StyleGuide` sees `options.extended_default_select`, it has a different set of error codes in
the True or False case, and thus it either gets reported or not as described above.

**Comment by asottile** [comment]
In GitLab by @sigmavirus24 on Oct 25, 2016, 16:22

Mentioned in merge request !128

**Comment by asottile** [comment]
In GitLab by @sigmavirus24 on Oct 26, 2016, 04:39

Mentioned in commit 185a073c296e2276597b564d31796e9cd38f7b93

**Comment by asottile** [comment]
In GitLab by @warsaw on Oct 26, 2016, 07:25

This doesn't quite fix the problem.  I installed flake8 from git master as well as flufl.testhelpers into my ubuntu-image project, but the U4 codes still don't get reported.  After pdb tracing, the issue is this: because my plugin sets `off_by_default=True`, the `U4` codes get added to the `OptionManager.extended_default_ignore` set  (via `.disable()` on manager.py:192.  Now when the end-user enables the plugin by setting this in their tox.ini:

```
[flake8]
enable-extensions = U4
extend-default-select = U4
```

when a `U4` code gets reported,  it doesn't get printed because the code never got removed from the `options.ignore` list.

(This is besides the fact that I get the following traceback:

```
qa develop-inst-nodeps: /home/barry/projects/ubuntu/allsnappy/ubuntu-image
qa installed: flake8==3.1.0.dev0,flufl.testhelpers==0.1,mccabe==0.5.2,pkg-resources==0.0.0,pycodestyle==2.0.0,pyflakes==1.3.0,-e git+git@github.com:CanonicalLtd/ubuntu-image.git@c66cce9c2824af79b5cb6d8acf32fad8d19f2d2f#egg=ubuntu_image
qa runtests: PYTHONHASHSEED='3380399139'
qa runtests: commands[0] | python -m flake8 ubuntu_image
Traceback (most recent call last):
  File "/usr/lib/python3.5/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.5/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/barry/projects/ubuntu/allsnappy/ubuntu-image/.tox/qa/lib/python3.5/site-packages/flake8/__main__.py", line 4, in <module>
    cli.main()
  File "/home/barry/projects/ubuntu/allsnappy/ubuntu-image/.tox/qa/lib/python3.5/site-packages/flake8/main/cli.py", line 16, in main
    app.run(argv)
  File "/home/barry/projects/ubuntu/allsnappy/ubuntu-image/.tox/qa/lib/python3.5/site-packages/flake8/main/application.py", line 316, in run
    self._run(argv)
  File "/home/barry/projects/ubuntu/allsnappy/ubuntu-image/.tox/qa/lib/python3.5/site-packages/flake8/main/application.py", line 302, in _run
    self.report_errors()
  File "/home/barry/projects/ubuntu/allsnappy/ubuntu-image/.tox/qa/lib/python3.5/site-packages/flake8/main/application.py", line 268, in report_errors
    results = self.file_checker_manager.report()
  File "/home/barry/projects/ubuntu/allsnappy/ubuntu-image/.tox/qa/lib/python3.5/site-packages/flake8/checker.py", line 298, in report
    results)
  File "/home/barry/projects/ubuntu/allsnappy/ubuntu-image/.tox/qa/lib/python3.5/site-packages/flake8/checker.py", line 215, in _handle_results
    physical_line=physical_line,
  File "/home/barry/projects/ubuntu/allsnappy/ubuntu-image/.tox/qa/lib/python3.5/site-packages/flake8/style_guide.py", line 263, in handle_error
    error_is_selected = (self.should_report_error(error.code) is
  File "/home/barry/projects/ubuntu/allsnappy/ubuntu-image/.tox/qa/lib/python3.5/site-packages/flake8/style_guide.py", line 155, in should_report_error
    decision = self._decision_for(code)
  File "/home/barry/projects/ubuntu/allsnappy/ubuntu-image/.tox/qa/lib/python3.5/site-packages/flake8/style_guide.py", line 121, in _decision_for
    selected = sorted([s for s in self._selected if startswith(s)])[0]
IndexError: list index out of range
ERROR: InvocationError: '/home/barry/projects/ubuntu/allsnappy/ubuntu-image/.tox/qa/bin/python -m flake8 ubuntu_image'
___________________________________ summary ___________________________________
ERROR:   qa: commands failed
```

**Comment by asottile** [comment]
In GitLab by @sigmavirus24 on Oct 28, 2016, 05:11

Mentioned in commit sigmavirus24/flake8@68a273144e5bd24a8f88cbf61070ab020be00498

**Comment by asottile** [comment]
In GitLab by @warsaw on Oct 31, 2016, 11:04

Mentioned in merge request !132

**Comment by asottile** [comment]
In GitLab by @sigmavirus24 on Nov 2, 2016, 08:26

Mentioned in merge request !133

**Comment by asottile** [comment]
In GitLab by @sigmavirus24 on Nov 8, 2016, 18:58

Mentioned in commit 9334ca9834043e8ac0a2647798382257f4a2470e

**Comment by asottile** [comment]
In GitLab by @sigmavirus24 on Nov 9, 2016, 16:13

Aha! Found the bug!

**Comment by asottile** [comment]
In GitLab by @sigmavirus24 on Nov 9, 2016, 16:48

Mentioned in merge request !138

**Comment by asottile** [comment]
In GitLab by @warsaw on Nov 11, 2016, 07:57

@sigmavirus24 I'm glad you found the bug!  Has the fix landed in master yet?  (I think "no" because the local bug is still reproducible, but maybe I have cruft in my environment.)   Thanks!

**Comment by asottile** [comment]
In GitLab by @sigmavirus24 on Nov 11, 2016, 08:05

I believe the pull request is still open and awaiting your review. I
mentioned you in the original description but perhaps that didn't generate
a notification. It is !138

**Comment by asottile** [comment]
In GitLab by @sigmavirus24 on Nov 11, 2016, 08:46

Status changed to closed by commit 1dfd6bae771619386f7251c3c8281cbb81486b95

**Comment by asottile** [comment]
In GitLab by @sigmavirus24 on Nov 12, 2016, 09:30

Mentioned in commit sigmavirus24/flake8@22233b6b4fc6f36ed1757b31f7306192fa8d6e05

**Comment by asottile** [comment]
In GitLab by @sigmavirus24 on Nov 15, 2016, 17:52

Mentioned in merge request !148

**Comment by asottile** [comment]
In GitLab by @sigmavirus24 on Nov 18, 2016, 17:24

Mentioned in commit sigmavirus24/flake8@c50b747a1a8b470574b5fc1016ee8cb598ab951e

**Comment by asottile** [comment]
In GitLab by @sigmavirus24 on Nov 18, 2016, 17:24

Mentioned in commit sigmavirus24/flake8@fd1cc3843598fd3445026d78603ec498513b6260
