### ISSUE TITLE
Use flake8.api to create JSON data fails

### ISSUE THREAD

**Issue by arossert** [PyCQA/flake8#1715]
### how did you install flake8?

```console
pip install flake8
```

### unmodified output of `flake8 --bug-report`

```json
{
  "platform": {
    "python_implementation": "CPython",
    "python_version": "3.9.6",
    "system": "Darwin"
  },
  "plugins": [
    {
      "plugin": "flake8-json",
      "version": "21.7.0"
    },
    {
      "plugin": "mccabe",
      "version": "0.7.0"
    },
    {
      "plugin": "pycodestyle",
      "version": "2.9.1"
    },
    {
      "plugin": "pyflakes",
      "version": "2.5.0"
    }
  ],
  "version": "5.0.4"
}
```

### describe the problem

I'm trying to use the flak8.api to run the check programmatically and not from the CLI.

Looking at the example I'm using it this way

```
from flake8.api import legacy as flake8
style_guide = flake8.get_style_guide(format="json")
report = style_guide.check_files(["..."])
report.get_statistics("E")
```
I want to output as JSON so it can be easily parsed, but I'm getting this error:

```
AttributeError: 'DefaultJSON' object has no attribute 'files_reported_count'
```

**Comment by asottile** [comment]
please don't leave anything out of the output

**Comment by arossert** [comment]
@asottile what output do you need? the full stack trace?
```
Traceback (most recent call last):
  File "/Users/arossert/Shared/Bitbucket/pythonect_provider/test.py", line 4, in <module>
    report = style_guide.check_files(["..."])
  File "/Users/arossert/Shared/Bitbucket/pythonect_provider/venv/lib/python3.9/site-packages/flake8/api/legacy.py", line 119, in check_files
    self._application.report_errors()
  File "/Users/arossert/Shared/Bitbucket/pythonect_provider/venv/lib/python3.9/site-packages/flake8/main/application.py", line 267, in report_errors
    results = self.file_checker_manager.report()
  File "/Users/arossert/Shared/Bitbucket/pythonect_provider/venv/lib/python3.9/site-packages/flake8/checker.py", line 190, in report
    with self.style_guide.processing_file(filename):
  File "/Users/arossert/.pyenv/versions/3.9.6/lib/python3.9/contextlib.py", line 117, in __enter__
    return next(self.gen)
  File "/Users/arossert/Shared/Bitbucket/pythonect_provider/venv/lib/python3.9/site-packages/flake8/style_guide.py", line 268, in processing_file
    with guide.processing_file(filename):
  File "/Users/arossert/.pyenv/versions/3.9.6/lib/python3.9/contextlib.py", line 117, in __enter__
    return next(self.gen)
  File "/Users/arossert/Shared/Bitbucket/pythonect_provider/venv/lib/python3.9/site-packages/flake8/style_guide.py", line 365, in processing_file
    self.formatter.beginning(filename)
  File "/Users/arossert/Shared/Bitbucket/pythonect_provider/venv/lib/python3.9/site-packages/flake8_json_reporter/reporters.py", line 40, in beginning
    if self.files_reported_count > 0:
AttributeError: 'DefaultJSON' object has no attribute 'files_reported_count'
```

**Comment by asottile** [comment]
(there's some report initialization missing which is why the formatter hasn't been `start()`ed yet)

**Comment by asottile** [comment]
I'd also recommend using subprocess instead -- I'm planning to delete the legacy api in the future and replace it with something better and you'll be more future proof that way

**Comment by arossert** [comment]
@asottile So instead of calling the code directly from my app should I spawn a new `flake8` process and parse the output? this is the recommended way to go?

**Comment by asottile** [comment]
that is probably what I would do for now (and what yesqa does for example)
