### ISSUE TITLE
TypeError: Flake8IsortBase.add_options() missing 1 required positional argument: 'option_manager'

### ISSUE THREAD

**Issue by dscrofts** [PyCQA/flake8#1742]
### how did you install flake8?

```console
$ pip install flake8
Collecting flake8
  Using cached flake8-5.0.4-py2.py3-none-any.whl (61 kB)
Requirement already satisfied: mccabe<0.8.0,>=0.7.0 in /usr/local/lib/python3.10/site-packages (from flake8) (0.7.0)
Requirement already satisfied: pycodestyle<2.10.0,>=2.9.0 in /usr/local/lib/python3.10/site-packages (from flake8) (2.9.1)
Requirement already satisfied: pyflakes<2.6.0,>=2.5.0 in /usr/local/lib/python3.10/site-packages (from flake8) (2.5.0)
Installing collected packages: flake8
Successfully installed flake8-5.0.4
```

### unmodified output of `flake8 --bug-report`

```json
$ flake8 --bug-report
Traceback (most recent call last):
  File "/usr/local/bin/flake8", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.10/site-packages/flake8/main/cli.py", line 22, in main
    app.run(argv)
  File "/usr/local/lib/python3.10/site-packages/flake8/main/application.py", line 336, in run
    self._run(argv)
  File "/usr/local/lib/python3.10/site-packages/flake8/main/application.py", line 324, in _run
    self.initialize(argv)
  File "/usr/local/lib/python3.10/site-packages/flake8/main/application.py", line 308, in initialize
    self.register_plugin_options()
  File "/usr/local/lib/python3.10/site-packages/flake8/main/application.py", line 140, in register_plugin_options
    self.option_manager.register_plugins(self.plugins)
  File "/usr/local/lib/python3.10/site-packages/flake8/options/manager.py", line 376, in register_plugins
    add_options(self)
TypeError: Flake8IsortBase.add_options() missing 1 required positional argument: 'option_manager'
```

#### what I expected to happen

Flake8 should run as expected, but for some reason I receive a `TypeError.` This problem started happening after I installed (and subsequently uninstalled) the `wemake-python-styleguide` [plugin](https://github.com/wemake-services/wemake-python-styleguide). I've tried clearing my pip cache and reinstalling again but it still doesn't work. Any help is greatly appreciated!

#### commands ran

```console
$ flake8
Traceback (most recent call last):
  File "/usr/local/bin/flake8", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.10/site-packages/flake8/main/cli.py", line 22, in main
    app.run(argv)
  File "/usr/local/lib/python3.10/site-packages/flake8/main/application.py", line 336, in run
    self._run(argv)
  File "/usr/local/lib/python3.10/site-packages/flake8/main/application.py", line 324, in _run
    self.initialize(argv)
  File "/usr/local/lib/python3.10/site-packages/flake8/main/application.py", line 308, in initialize
    self.register_plugin_options()
  File "/usr/local/lib/python3.10/site-packages/flake8/main/application.py", line 140, in register_plugin_options
    self.option_manager.register_plugins(self.plugins)
  File "/usr/local/lib/python3.10/site-packages/flake8/options/manager.py", line 376, in register_plugins
    add_options(self)
TypeError: Flake8IsortBase.add_options() missing 1 required positional argument: 'option_manager'
```

**Comment by asottile** [comment]
this isn't a flake8 issue, please report this to the plugin that's failing

**Comment by dscrofts** [comment]
> this isn't a flake8 issue, please report this to the plugin that's failing

Thanks for the quick response. It seems like an issue with `flake8-isort`, see here https://github.com/gforcada/flake8-isort/issues/128
