### ISSUE TITLE
flake8 v6 alueError: 'choice' is not callable

### ISSUE THREAD

**Issue by RyoYang** [PyCQA/flake8#1758]
### how did you install flake8?

```console
`pip install flake8>=3.8.4`
```

### unmodified output of `flake8 --bug-report`

```json
Success: no issues found in 173 source files
Traceback (most recent call last):
  File "/opt/conda/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/opt/conda/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/home/superbench_azpcontainer/.local/lib/python3.8/site-packages/flake8/__main__.py", line 7, in <module>
    raise SystemExit(main())
  File "/home/superbench_azpcontainer/.local/lib/python3.8/site-packages/flake8/main/cli.py", line 23, in main
    app.run(argv)
  File "/home/superbench_azpcontainer/.local/lib/python3.8/site-packages/flake8/main/application.py", line 198, in run
    self._run(argv)
  File "/home/superbench_azpcontainer/.local/lib/python3.8/site-packages/flake8/main/application.py", line 186, in _run
    self.initialize(argv)
  File "/home/superbench_azpcontainer/.local/lib/python3.8/site-packages/flake8/main/application.py", line 165, in initialize
    self.plugins, self.options = parse_args(argv)
  File "/home/superbench_azpcontainer/.local/lib/python3.8/site-packages/flake8/options/parse_args.py", line 51, in parse_args
    option_manager.register_plugins(plugins)
  File "/home/superbench_azpcontainer/.local/lib/python3.8/site-packages/flake8/options/manager.py", line 259, in register_plugins
    add_options(self)
  File "/home/superbench_azpcontainer/.local/lib/python3.8/site-packages/flake8_quotes/__init__.py", line 109, in add_options
    cls._register_opt(parser, '--quotes', action='store',
  File "/home/superbench_azpcontainer/.local/lib/python3.8/site-packages/flake8_quotes/__init__.py", line 99, in _register_opt
    parser.add_option(*args, **kwargs)
  File "/home/superbench_azpcontainer/.local/lib/python3.8/site-packages/flake8/options/manager.py", line 281, in add_option
    self._current_group.add_argument(*option_args, **option_kwargs)
  File "/opt/conda/lib/python3.8/argparse.py", line 1373, in add_argument
    raise ValueError('%r is not callable' % (type_func,))
ValueError: 'choice' is not callable
##[error]Bash exited with code '1'.
```

#### what I expected to happen
Can not use flake8 in pipeline after updating to v6

**Comment by looztra** [comment]
Same error for me using python `3.9.15`
I don't have the problem with python `3.10.7`

**Comment by asottile** [comment]
please report this to the plugin in question.  optparse support has been deprecated for 2 years and warning about it and finally removed.
