### ISSUE TITLE
Broken with pycodestyle 2.1 due to the new attribute previous_unindented_logical_line

### ISSUE THREAD

**Issue by asottile** [PyCQA/flake8#178]
In GitLab by @yan12125 on Nov 6, 2016, 07:12

*Please provide the following version information*

- Arch Linux
- CPython 3.5.2
- setuptools 28.7.1
- flake8 9553c8d8ccf54221153f498e28297d9cc74ca12d, with the patch at https://github.com/PyCQA/flake8/pull/7, pycodestyle 2.1.0 installed with pip

*Please describe the problem or feature*

PS. I know ```setup.py``` of flake8 depends pycodestyle < 2.1.0. But 2.1.0 compatibility should be landed sooner or later, right?

In https://github.com/PyCQA/pycodestyle/commit/6b75c4de380c5e786d277851a7da8a581da53bcb and later https://github.com/PyCQA/pycodestyle/commit/2a5e575611674b0d202c5ea0322fce23718d6e02, ```blank_lines``` plugin of pycodestyle introduces a new variable ```previous_unindented_logical_line```, causing the following error:
```
$ flake8 -j1
Traceback (most recent call last):
  File "/home/yen/.local/lib/python3.5/site-packages/flake8-3.1.0.dev0-py3.5.egg/flake8/checker.py", line 449, in run_check
  File "/home/yen/.local/lib/python3.5/site-packages/flake8-3.1.0.dev0-py3.5.egg/flake8/processor.py", line 235, in keyword_arguments_for
AttributeError: 'FileProcessor' object has no attribute 'previous_unindented_logical_line'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/yen/.local/bin/flake8", line 11, in <module>
    load_entry_point('flake8==3.1.0.dev0', 'console_scripts', 'flake8')()
  File "/home/yen/.local/lib/python3.5/site-packages/flake8-3.1.0.dev0-py3.5.egg/flake8/main/cli.py", line 16, in main
  File "/home/yen/.local/lib/python3.5/site-packages/flake8-3.1.0.dev0-py3.5.egg/flake8/main/application.py", line 316, in run
  File "/home/yen/.local/lib/python3.5/site-packages/flake8-3.1.0.dev0-py3.5.egg/flake8/main/application.py", line 300, in _run
  File "/home/yen/.local/lib/python3.5/site-packages/flake8-3.1.0.dev0-py3.5.egg/flake8/main/application.py", line 238, in run_checks
  File "/home/yen/.local/lib/python3.5/site-packages/flake8-3.1.0.dev0-py3.5.egg/flake8/checker.py", line 343, in run
  File "/home/yen/.local/lib/python3.5/site-packages/flake8-3.1.0.dev0-py3.5.egg/flake8/checker.py", line 327, in run_serial
  File "/home/yen/.local/lib/python3.5/site-packages/flake8-3.1.0.dev0-py3.5.egg/flake8/checker.py", line 595, in run_checks
  File "/home/yen/.local/lib/python3.5/site-packages/flake8-3.1.0.dev0-py3.5.egg/flake8/checker.py", line 579, in process_tokens
  File "/home/yen/.local/lib/python3.5/site-packages/flake8-3.1.0.dev0-py3.5.egg/flake8/checker.py", line 629, in handle_newline
  File "/home/yen/.local/lib/python3.5/site-packages/flake8-3.1.0.dev0-py3.5.egg/flake8/checker.py", line 530, in run_logical_checks
  File "/home/yen/.local/lib/python3.5/site-packages/flake8-3.1.0.dev0-py3.5.egg/flake8/checker.py", line 455, in run_check
flake8.exceptions.PluginRequestedUnknownParameters: "pycodestyle" requested unknown parameters causing 'FileProcessor' object has no attribute 'previous_unindented_logical_line'
```

**Comment by asottile** [comment]
In GitLab by @ael-code on Nov 6, 2016, 14:28

On the Arch linux community repository the pycodestyle package is already at version `2.1.0` [1], thus flake8 installed via official repository cannot be used :(

[1]  https://www.archlinux.org/packages/community/any/python-pycodestyle/

**Comment by asottile** [comment]
In GitLab by @yan12125 on Nov 6, 2016, 19:14

Submitted an Arch Linux bug report: https://bugs.archlinux.org/task/51728

**Comment by asottile** [comment]
In GitLab by @wavi on Nov 6, 2016, 23:03

Would be great to get pycodestyle 2.1 support, since my build is breaking due to a bug that's fixed in 2.1 (https://github.com/PyCQA/pycodestyle/issues/561)
Originally I incorrectly reported it here https://gitlab.com/pycqa/flake8/issues/176 .

**Comment by asottile** [comment]
In GitLab by @yan12125 on Nov 6, 2016, 23:43

Arch Linux package maintainer Felix Yan introduced a patch: https://git.archlinux.org/svntogit/community.git/tree/trunk/pycodestyle-2.1.patch?h=packages/flake8

**Comment by asottile** [comment]
In GitLab by @yan12125 on Nov 8, 2016, 07:37

Mentioned in merge request !134

**Comment by asottile** [comment]
In GitLab by @yan12125 on Nov 8, 2016, 07:40

Submitted !134. Now it's working: (in flake8 source directory)
```
$ flake8 
./setup.py:38:1: E305 expected 2 blank lines after class or function definition, found 1
./src/flake8/plugins/pyflakes.py:41:1: E305 expected 2 blank lines after class or function definition, found 0
```

**Comment by asottile** [comment]
In GitLab by @yan12125 on Nov 8, 2016, 19:12

Mentioned in commit sigmavirus24/flake8@6595d3a08dedec4ff07683bf2c8f5aca2637fc5f

**Comment by asottile** [comment]
In GitLab by @sigmavirus24 on Nov 8, 2016, 19:12

Mentioned in commit sigmavirus24/flake8@35a35c2a617ac346790180783c616b692d79c03b
