### ISSUE TITLE
Does not support inline comments in configuration file

### ISSUE THREAD

**Issue by rchl** [PyCQA/flake8#1795]
### how did you install flake8?

```console
pip3 install flake8
```

### unmodified output of `flake8 --bug-report`

```json
{
  "platform": {
    "python_implementation": "CPython",
    "python_version": "3.10.9",
    "system": "Darwin"
  },
  "plugins": [
    {
      "plugin": "mccabe",
      "version": "0.7.0"
    },
    {
      "plugin": "pycodestyle",
      "version": "2.10.0"
    },
    {
      "plugin": "pyflakes",
      "version": "3.0.1"
    }
  ],
  "version": "6.0.0"
}
```

#### what I expected to happen

Crashes with a `tox.ini` like:

```ini
[flake8]
exclude = third_party
ignore =
    F841  # local variable is assigned to but never used
    E252  # missing whitespace around parameter equals
    W504  # line break after binary operator
    F821  # undefined name
max-line-length = 120
```

that has `ignore` rules split into multiple lines and the lines contain inline comments

```
Traceback (most recent call last):
  File "/opt/homebrew/bin/flake8", line 8, in <module>
    sys.exit(main())
  File "/opt/homebrew/lib/python3.10/site-packages/flake8/main/cli.py", line 23, in main
    app.run(argv)
  File "/opt/homebrew/lib/python3.10/site-packages/flake8/main/application.py", line 198, in run
    self._run(argv)
  File "/opt/homebrew/lib/python3.10/site-packages/flake8/main/application.py", line 186, in _run
    self.initialize(argv)
  File "/opt/homebrew/lib/python3.10/site-packages/flake8/main/application.py", line 165, in initialize
    self.plugins, self.options = parse_args(argv)
  File "/opt/homebrew/lib/python3.10/site-packages/flake8/options/parse_args.py", line 53, in parse_args
    opts = aggregator.aggregate_options(option_manager, cfg, cfg_dir, rest)
  File "/opt/homebrew/lib/python3.10/site-packages/flake8/options/aggregator.py", line 30, in aggregate_options
    parsed_config = config.parse_config(manager, cfg, cfg_dir)
  File "/opt/homebrew/lib/python3.10/site-packages/flake8/options/config.py", line 131, in parse_config
    raise ValueError(
ValueError: Error code '#' supplied to 'ignore' option does not match '^[A-Z]{1,3}[0-9]{0,3}$'
```

It could be solved by using `inline_comment_prefixes` option of `RawConfigParser` used in https://github.com/PyCQA/flake8/blob/main/src/flake8/options/config.py but maybe it's not used on purpose because it could prevent user from setting actual settings that could contain `#` or `;`?

#### commands ran

```console
$ flake8 .
```

**Comment by rchl** [comment]
BTW. I had the same config file for a long while so I wonder if this has changes in recent versions of flake8...

**Comment by sigmavirus24** [comment]
In the future, please search **closed and** open issues before creating new ones that are duplicates.
