### ISSUE TITLE
Source code including null characters results crashes

### ISSUE THREAD

**Issue by youknowone** [PyCQA/flake8#1822]
### how did you install flake8?

```console
python -m pip install -U flake8
```

### unmodified output of `flake8 --bug-report`

```json
{
  "platform": {
    "python_implementation": "CPython",
    "python_version": "3.10.1",
    "system": "Darwin"
  },
  "plugins": [
    {
      "plugin": "mccabe",
      "version": "0.7.0"
    },
    {
      "plugin": "pycodestyle",
      "version": "2.10.0"
    },
    {
      "plugin": "pyflakes",
      "version": "3.0.1"
    }
  ],
  "version": "6.0.0"
}
```

#### what I expected to happen

1. Error with filename which causes errors
2. Proper flake8 styled error for the file

#### sample code

[null.py.zip](https://github.com/PyCQA/flake8/files/11352467/null.py.zip)

#### commands ran

```console
$ flake8 null.py
Traceback (most recent call last):
  File "~/.pyenv/versions/shell/bin/flake8", line 8, in <module>
    sys.exit(main())
  File "~/.pyenv/versions/3.10.1/envs/shell/lib/python3.10/site-packages/flake8/main/cli.py", line 23, in main
    app.run(argv)
  File "~/.pyenv/versions/3.10.1/envs/shell/lib/python3.10/site-packages/flake8/main/application.py", line 198, in run
    self._run(argv)
  File "~/.pyenv/versions/3.10.1/envs/shell/lib/python3.10/site-packages/flake8/main/application.py", line 187, in _run
    self.run_checks()
  File "~/.pyenv/versions/3.10.1/envs/shell/lib/python3.10/site-packages/flake8/main/application.py", line 103, in run_checks
    self.file_checker_manager.run()
  File "~/.pyenv/versions/3.10.1/envs/shell/lib/python3.10/site-packages/flake8/checker.py", line 236, in run
    self.run_serial()
  File "~/.pyenv/versions/3.10.1/envs/shell/lib/python3.10/site-packages/flake8/checker.py", line 214, in run_serial
    self.results = [
  File "~/.pyenv/versions/3.10.1/envs/shell/lib/python3.10/site-packages/flake8/checker.py", line 219, in <listcomp>
    ).run_checks()
  File "~/.pyenv/versions/3.10.1/envs/shell/lib/python3.10/site-packages/flake8/checker.py", line 524, in run_checks
    self.run_ast_checks()
  File "~/.pyenv/versions/3.10.1/envs/shell/lib/python3.10/site-packages/flake8/checker.py", line 416, in run_ast_checks
    ast = self.processor.build_ast()
  File "~/.pyenv/versions/3.10.1/envs/shell/lib/python3.10/site-packages/flake8/processor.py", line 218, in build_ast
    return ast.parse("".join(self.lines))
  File "~/.pyenv/versions/3.10.1/lib/python3.10/ast.py", line 50, in parse
    return compile(source, filename, mode, flags,
ValueError: source code string cannot contain null bytes
...
```

**Comment by youknowone** [comment]
dup #1682
