### ISSUE TITLE
Support for comment in configuration file

### ISSUE THREAD

**Issue by gsemet** [PyCQA/flake8#1846]
### describe the request

Hello

In flake8 5.x, the following syntax worked:
```
[flake8]
ignore =
    E121,     # continuation line under-indented for hanging indent
    E203,     # whitespace before : (enforced by black)
    E231,     # missing whitespace after ',' (enforced by black)
    E501,     # Line too long (handled by bugbear with 10% flexibility). Recommended by black
    E902,     # FileNotFoundError
    F401,     # imported but unused (check done by pylint)
    W503,     # line break before binary operator (enforced by black)
```

it does not work anymore in 6:
```
Traceback (most recent call last):
  File "/Users/path/to/my/project/.venv/bin/flake8", line 8, in <module>
    sys.exit(main())
  File "/Users/path/to/my/project/.venv/lib/python3.10/site-packages/flake8/main/cli.py", line 23, in main
    app.run(argv)
  File "/Users/path/to/my/project/.venv/lib/python3.10/site-packages/flake8/main/application.py", line 198, in run
    self._run(argv)
  File "/Users/path/to/my/project/.venv/lib/python3.10/site-packages/flake8/main/application.py", line 186, in _run
    self.initialize(argv)
  File "/Users/path/to/my/project/.venv/lib/python3.10/site-packages/flake8/main/application.py", line 165, in initialize
    self.plugins, self.options = parse_args(argv)
  File "/Users/path/to/my/project/.venv/lib/python3.10/site-packages/flake8/options/parse_args.py", line 53, in parse_args
    opts = aggregator.aggregate_options(option_manager, cfg, cfg_dir, rest)
  File "/Users/path/to/my/project/.venv/lib/python3.10/site-packages/flake8/options/aggregator.py", line 30, in aggregate_options
    parsed_config = config.parse_config(manager, cfg, cfg_dir)
  File "/Users/path/to/my/project/.venv/lib/python3.10/site-packages/flake8/options/config.py", line 131, in parse_config
    raise ValueError(
ValueError: Error code '#' supplied to 'ignore' option does not match '^[A-Z]{1,3}[0-9]{0,3}$'
```

**Comment by asottile** [comment]
search the issue tracker next time please
