### ISSUE TITLE
This is the wrong place to ask for help, I'm sorry

### ISSUE THREAD

**Issue by UP929312** [PyCQA/flake8#1869]
### how did you install flake8?

```console
pip install flake8
```

### unmodified output of `flake8 --bug-report`

```json
PS C:\Users\Ben\Desktop\flake8-pbp> flake8 --bug-report
Traceback (most recent call last):
  File "C:\Users\Ben\AppData\Local\Programs\Python\Python310\lib\site-packages\flake8\plugins\finder.py", line 291, in _load_plugin
    obj = plugin.entry_point.load()
  File "C:\Users\Ben\AppData\Local\Programs\Python\Python310\lib\importlib\metadata\__init__.py", line 171, in load
    module = import_module(match.group('module'))
  File "C:\Users\Ben\AppData\Local\Programs\Python\Python310\lib\importlib\__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "C:\Users\Ben\AppData\Local\Programs\Python\Python310\lib\site-packages\src\flake8_pbp.py", line 9, in <module>
    from checks import (
ModuleNotFoundError: No module named 'checks'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Ben\AppData\Local\Programs\Python\Python310\lib\runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\Ben\AppData\Local\Programs\Python\Python310\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "C:\Users\Ben\AppData\Local\Programs\Python\Python310\Scripts\flake8.exe\__main__.py", line 7, in <module>
  File "C:\Users\Ben\AppData\Local\Programs\Python\Python310\lib\site-packages\flake8\main\cli.py", line 23, in main
    app.run(argv)
  File "C:\Users\Ben\AppData\Local\Programs\Python\Python310\lib\site-packages\flake8\main\application.py", line 198, in run
    self._run(argv)
  File "C:\Users\Ben\AppData\Local\Programs\Python\Python310\lib\site-packages\flake8\main\application.py", line 186, in _run
    self.initialize(argv)
  File "C:\Users\Ben\AppData\Local\Programs\Python\Python310\lib\site-packages\flake8\main\application.py", line 165, in initialize
    self.plugins, self.options = parse_args(argv)
  File "C:\Users\Ben\AppData\Local\Programs\Python\Python310\lib\site-packages\flake8\options\parse_args.py", line 42, in parse_args
    plugins = finder.load_plugins(raw_plugins, plugin_opts)
  File "C:\Users\Ben\AppData\Local\Programs\Python\Python310\lib\site-packages\flake8\plugins\finder.py", line 365, in load_plugins
    return _classify_plugins(_import_plugins(plugins, opts), opts)
  File "C:\Users\Ben\AppData\Local\Programs\Python\Python310\lib\site-packages\flake8\plugins\finder.py", line 307, in _import_plugins
    return [_load_plugin(p) for p in plugins]
  File "C:\Users\Ben\AppData\Local\Programs\Python\Python310\lib\site-packages\flake8\plugins\finder.py", line 307, in <listcomp>
    return [_load_plugin(p) for p in plugins]
  File "C:\Users\Ben\AppData\Local\Programs\Python\Python310\lib\site-packages\flake8\plugins\finder.py", line 293, in _load_plugin
    raise FailedToLoadPlugin(plugin.package, e)
flake8.exceptions.FailedToLoadPlugin: Flake8 failed to load plugin "flake8-pgp" due to No module named 'checks'.
```

#### what I expected to happen
My plugin worked

#### sample code
Source code: https://github.com/UP929312/pbp

#### commands ran

```console
$ python -m flake8 example.py
...
```

Extract from SOURCES..txt in my build:
```
src/checks/PBP101_range_len.py
src/checks/PBP102_json_dot_loads.py
src/checks/PBP103_open_no_with.py
src/checks/PBP104_requests_json_dumps.py
src/checks/PBP105_assigns_to_list.py
src/checks/PBP106_camel_case_func.py
src/checks/PBP107_default_mutable_args.py
src/checks/PBP108_compares_types.py
src/checks/PBP109_compares_to_true.py
src/checks/PBP110_inherits_from_object.py
src/checks/PBP111_not_using_ternary.py
src/checks/PBP112_using_filter.py
src/checks/PBP113_shadow_builtins.py
src/checks/PBP114_no_pointless_ternary.py
src/checks/PBP115_better_any.py
src/checks/__init__.py
```
Clearly, the checks are being included, release on pypi here, but it won't run properly:
https://pypi.org/project/flake8-pgp

**Comment by sigmavirus24** [comment]
This is a basic python issue where you're appearing to rely on a relative import. Read the traceback more closely as it highlights the exact issue you're encountering.

Also, the module you're distributing is called `src` and will conflict with anyone else doing the same thing. As far as better Python practices that is incredibly bad to distribute such a generically named module.

**Comment by UP929312** [comment]
You're absolutely right, and I apologise for the noob question, but this helped me out and fixed the problem I've spent about 6 hours debugging, thank you so much @sigmavirus24 
I appreciate you
