### ISSUE TITLE
flake8 crash with certain file

### ISSUE THREAD

**Issue by Xoriun** [PyCQA/flake8#1960]
### how did you install flake8?

```console
pip install flake8
```

### unmodified output of `flake8 --bug-report`

```json
{
  "platform": {
    "python_implementation": "CPython",
    "python_version": "3.12.6",
    "system": "Windows"
  },
  "plugins": [
    {
      "plugin": "flake8-bandit",
      "version": "4.1.1"
    },
    {
      "plugin": "flake8-broken-line",
      "version": "1.0.0"
    },
    {
      "plugin": "flake8-bugbear",
      "version": "24.10.31"
    },
    {
      "plugin": "flake8-commas",
      "version": "2.1.0"
    },
    {
      "plugin": "flake8-comprehensions",
      "version": "3.16.0"
    },
    {
      "plugin": "flake8-debugger",
      "version": "4.1.2"
    },
    {
      "plugin": "flake8-docstrings",
      "version": "1.7.0"
    },
    {
      "plugin": "flake8-docstrings-complete",
      "version": "1.4.1"
    },
    {
      "plugin": "flake8-eradicate",
      "version": "1.5.0"
    },
    {
      "plugin": "flake8-isort",
      "version": "6.1.1"
    },
    {
      "plugin": "flake8-quotes",
      "version": "3.4.0"
    },
    {
      "plugin": "flake8-rst-docstrings",
      "version": "0.3.0"
    },
    {
      "plugin": "flake8-string-format",
      "version": "0.3.0"
    },
    {
      "plugin": "mccabe",
      "version": "0.7.0"
    },
    {
      "plugin": "pep8-naming",
      "version": "0.13.3"
    },
    {
      "plugin": "pycodestyle",
      "version": "2.12.1"
    },
    {
      "plugin": "pyflakes",
      "version": "3.2.0"
    },
    {
      "plugin": "wemake-python-styleguide",
      "version": "0.19.2"
    }
  ],
  "version": "7.1.1"
}
```

### describe the problem

When trying to run flake8 with [this file](https://github.com/user-attachments/files/18111848/user.txt) (`flake8 ./user.py`), I get the following output:
```
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "C:\Users\Praktikant\AppData\Local\Programs\Python\Python312\Scripts\flake8.exe\__main__.py", line 7, in <module>  File "C:\Users\Praktikant\AppData\Local\Programs\Python\Python312\Lib\site-packages\flake8\main\cli.py", line 23, in main
    app.run(argv)
  File "C:\Users\Praktikant\AppData\Local\Programs\Python\Python312\Lib\site-packages\flake8\main\application.py", line 198, in run
    self._run(argv)
  File "C:\Users\Praktikant\AppData\Local\Programs\Python\Python312\Lib\site-packages\flake8\main\application.py", line 187, in _run
    self.run_checks()
  File "C:\Users\Praktikant\AppData\Local\Programs\Python\Python312\Lib\site-packages\flake8\main\application.py", line 103, in run_checks
    self.file_checker_manager.run()
  File "C:\Users\Praktikant\AppData\Local\Programs\Python\Python312\Lib\site-packages\flake8\checker.py", line 238, in run
    self.run_serial()
  File "C:\Users\Praktikant\AppData\Local\Programs\Python\Python312\Lib\site-packages\flake8\checker.py", line 221, in run_serial
    ).run_checks()
      ^^^^^^^^^^^^
  File "C:\Users\Praktikant\AppData\Local\Programs\Python\Python312\Lib\site-packages\flake8\checker.py", line 526, in run_checks
    self.run_ast_checks()
  File "C:\Users\Praktikant\AppData\Local\Programs\Python\Python312\Lib\site-packages\flake8\checker.py", line 428, in run_ast_checks
    for line_number, offset, text, _ in runner:
  File "C:\Users\Praktikant\AppData\Local\Programs\Python\Python312\Lib\site-packages\flake8_commas\_base.py", line 333, in run
    for error in get_comma_errors(tokens):
                 ^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Praktikant\AppData\Local\Programs\Python\Python312\Lib\site-packages\flake8_commas\_base.py", line 306, in get_comma_errors
    (token.type == COLON and stack[-1].comma == LAMBDA_EXPR)
                             ~~~~~^^^^
IndexError: list index out of range
```

I only get this with this file, all other files in my project work just fine.

**Comment by sigmavirus24** [comment]
The exception is originating in `flake8-commas`, not in `flake8` itself.

```
  File "C:\Users\Praktikant\AppData\Local\Programs\Python\Python312\Lib\site-packages\flake8_commas\_base.py", line 333, in run
    for error in get_comma_errors(tokens):
                 ^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Praktikant\AppData\Local\Programs\Python\Python312\Lib\site-packages\flake8_commas\_base.py", line 306, in get_comma_errors
    (token.type == COLON and stack[-1].comma == LAMBDA_EXPR)
                             ~~~~~^^^^
IndexError: list index out of range
```

As that is a plugin, please file this with them.
