### ISSUE TITLE
pointing flake8 at a non-existant file raises an exception. AttributeError: 'NoneType' object has no attribute 'filename'

### ISSUE THREAD

**Issue by asottile** [PyCQA/flake8#204]
In GitLab by @graingert on Nov 22, 2016, 06:17

*Please describe how you installed Flake8*

Example:
```
$ python3.5 -m venv ~/.virtualenvs/flake8
$ pip install -U pip setuptools wheel
$ pip install -U flake8
```

*Please provide the exact, unmodified output of `flake8 --bug-report`*
```json
{
  "dependencies": [
    {
      "dependency": "setuptools",
      "version": "28.8.0"
    }
  ],
  "platform": {
    "python_implementation": "CPython",
    "python_version": "3.5.2+",
    "system": "Linux"
  },
  "plugins": [
    {
      "plugin": "mccabe",
      "version": "0.5.2"
    },
    {
      "plugin": "pycodestyle",
      "version": "2.2.0"
    },
    {
      "plugin": "pyflakes",
      "version": "1.3.0"
    }
  ],
  "version": "3.2.1"
}
```

*Please describe the problem or feature*
pointing flake8 at a non-existant file raises an exception.

*If this is a bug report, please explain with examples (and example code) what you expected to happen and what actually happened.*

```
flake8 foop          
Traceback (most recent call last):
  File "/home/graingert/.virtualenvs/tox/bin/flake8", line 11, in <module>
    sys.exit(main())
  File "/home/graingert/.virtualenvs/tox/lib/python3.5/site-packages/flake8/main/cli.py", line 16, in main
    app.run(argv)
  File "/home/graingert/.virtualenvs/tox/lib/python3.5/site-packages/flake8/main/application.py", line 322, in run
    self._run(argv)
  File "/home/graingert/.virtualenvs/tox/lib/python3.5/site-packages/flake8/main/application.py", line 306, in _run
    self.run_checks()
  File "/home/graingert/.virtualenvs/tox/lib/python3.5/site-packages/flake8/main/application.py", line 243, in run_checks
    self.file_checker_manager.start(files)
  File "/home/graingert/.virtualenvs/tox/lib/python3.5/site-packages/flake8/checker.py", line 371, in start
    self.make_checkers(paths)
  File "/home/graingert/.virtualenvs/tox/lib/python3.5/site-packages/flake8/checker.py", line 275, in make_checkers
    for argument in paths
  File "/home/graingert/.virtualenvs/tox/lib/python3.5/site-packages/flake8/checker.py", line 285, in <listcomp>
    if argument == filename or should_create_file_checker(filename)
  File "/home/graingert/.virtualenvs/tox/lib/python3.5/site-packages/flake8/checker.py", line 412, in __init__
    self.display_name = self.processor.filename
AttributeError: 'NoneType' object has no attribute 'filename'
```

**Comment by asottile** [comment]
In GitLab by @sigmavirus24 on Nov 22, 2016, 15:47

This is a duplicate of #268. Please look at open and closed issues before filing new ones.

**Comment by asottile** [comment]
In GitLab by @graingert on Nov 22, 2016, 15:50

I had a look for similar errors #268 was worded differently enough that I
missed it
