### ISSUE TITLE
flake8 crashes with python 3.5

### ISSUE THREAD

**Issue by asottile** [PyCQA/flake8#212]
In GitLab by @oren on Dec 7, 2016, 10:18

## System
```
➜  ~ $ sw_vers
ProductName:	Mac OS X
ProductVersion:	10.12.1
BuildVersion:	16B2657

➜  ~ $ brew info python3
python3: stable 3.5.2 (bottled), devel 3.6.0b4, HEAD
Interpreted, interactive, object-oriented programming language
https://www.python.org/
/usr/local/Cellar/python3/3.5.1 (7,675 files, 107M)
  Built from source on 2016-05-04 at 13:00:36
/usr/local/Cellar/python3/3.5.2_3 (3,616 files, 54.7M) *
  Poured from bottle on 2016-12-03 at 22:07:57
From: https://github.com/Homebrew/homebrew-core/blob/master/Formula/python3.rb
```

## Problem description
Flake8 fails the same way every time. (see below for traceback)

## flake8 installation and running:
```
➜  ~ $ mkdir ./temp/flake8

➜  ~ $ mkvirtualenv -p python3.5 flake8env -a ./temp/flake8
Running virtualenv with interpreter /usr/local/bin/python3.5
Using base prefix '/usr/local/Cellar/python3/3.5.2_3/Frameworks/Python.framework/Versions/3.5'
New python executable in /Users/orens/projects/virtualenv/envs/flake8env/bin/python3.5
Also creating executable in /Users/orens/projects/virtualenv/envs/flake8env/bin/python
Installing setuptools, pip, wheel...done.
virtualenvwrapper.user_scripts creating /Users/orens/projects/virtualenv/envs/flake8env/bin/predeactivate
virtualenvwrapper.user_scripts creating /Users/orens/projects/virtualenv/envs/flake8env/bin/postdeactivate
virtualenvwrapper.user_scripts creating /Users/orens/projects/virtualenv/envs/flake8env/bin/preactivate
virtualenvwrapper.user_scripts creating /Users/orens/projects/virtualenv/envs/flake8env/bin/postactivate
virtualenvwrapper.user_scripts creating /Users/orens/projects/virtualenv/envs/flake8env/bin/get_env_details
Setting project for flake8env to /Users/orens/temp/flake8

(flake8env) ➜  flake8 $ pip install flake8
Collecting flake8
  Using cached flake8-3.2.1-py2.py3-none-any.whl
Collecting pycodestyle<2.3.0,>=2.0.0 (from flake8)
  Using cached pycodestyle-2.2.0-py2.py3-none-any.whl
Collecting pyflakes!=1.2.0,!=1.2.1,!=1.2.2,<1.4.0,>=0.8.1 (from flake8)
  Using cached pyflakes-1.3.0-py2.py3-none-any.whl
Collecting mccabe<0.6.0,>=0.5.0 (from flake8)
  Using cached mccabe-0.5.2-py2.py3-none-any.whl
Installing collected packages: pycodestyle, pyflakes, mccabe, flake8
Successfully installed flake8-3.2.1 mccabe-0.5.2 pycodestyle-2.2.0 pyflakes-1.3.0
(flake8env) ➜  flake8 flake8
Traceback (most recent call last):
  File "/usr/local/bin/flake8", line 11, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.5/site-packages/flake8/main/cli.py", line 16, in main
    app.run(argv)
  File "/usr/local/lib/python3.5/site-packages/flake8/main/application.py", line 316, in run
    self._run(argv)
  File "/usr/local/lib/python3.5/site-packages/flake8/main/application.py", line 299, in _run
    self.initialize(argv)
  File "/usr/local/lib/python3.5/site-packages/flake8/main/application.py", line 290, in initialize
    self.register_plugin_options()
  File "/usr/local/lib/python3.5/site-packages/flake8/main/application.py", line 150, in register_plugin_options
    self.check_plugins.register_options(self.option_manager)
  File "/usr/local/lib/python3.5/site-packages/flake8/plugins/manager.py", line 481, in register_options
    list(self.manager.map(register_and_enable))
  File "/usr/local/lib/python3.5/site-packages/flake8/plugins/manager.py", line 277, in map
    yield func(self.plugins[name], *args, **kwargs)
  File "/usr/local/lib/python3.5/site-packages/flake8/plugins/manager.py", line 477, in register_and_enable
    call_register_options(plugin)
  File "/usr/local/lib/python3.5/site-packages/flake8/plugins/manager.py", line 373, in generated_function
    return method(optmanager, *args, **kwargs)
  File "/usr/local/lib/python3.5/site-packages/flake8/plugins/manager.py", line 223, in register_options
    add_options(optmanager)
  File "/usr/local/lib/python3.5/site-packages/flake8_future.py", line 30, in add_options
    parser.config_options.append('future-imports')
AttributeError: 'OptionManager' object has no attribute 'config_options'
```

## `flake8 --bug-report` output
```
(flake8env) ➜  flake8 $ flake8 --bug-report
Traceback (most recent call last):
  File "/usr/local/bin/flake8", line 11, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.5/site-packages/flake8/main/cli.py", line 16, in main
    app.run(argv)
  File "/usr/local/lib/python3.5/site-packages/flake8/main/application.py", line 316, in run
    self._run(argv)
  File "/usr/local/lib/python3.5/site-packages/flake8/main/application.py", line 299, in _run
    self.initialize(argv)
  File "/usr/local/lib/python3.5/site-packages/flake8/main/application.py", line 290, in initialize
    self.register_plugin_options()
  File "/usr/local/lib/python3.5/site-packages/flake8/main/application.py", line 150, in register_plugin_options
    self.check_plugins.register_options(self.option_manager)
  File "/usr/local/lib/python3.5/site-packages/flake8/plugins/manager.py", line 481, in register_options
    list(self.manager.map(register_and_enable))
  File "/usr/local/lib/python3.5/site-packages/flake8/plugins/manager.py", line 277, in map
    yield func(self.plugins[name], *args, **kwargs)
  File "/usr/local/lib/python3.5/site-packages/flake8/plugins/manager.py", line 477, in register_and_enable
    call_register_options(plugin)
  File "/usr/local/lib/python3.5/site-packages/flake8/plugins/manager.py", line 373, in generated_function
    return method(optmanager, *args, **kwargs)
  File "/usr/local/lib/python3.5/site-packages/flake8/plugins/manager.py", line 223, in register_options
    add_options(optmanager)
  File "/usr/local/lib/python3.5/site-packages/flake8_future.py", line 30, in add_options
    parser.config_options.append('future-imports')
AttributeError: 'OptionManager' object has no attribute 'config_options'
```

**Comment by asottile** [comment]
In GitLab by @sigmavirus24 on Dec 7, 2016, 10:22

It looks as though you have a plugin installed that is broken. If you
look at the stack trace, the final lines are from flake8_future.py
which makes me think this is a problem in that plugin, not
specifically Python 3.5 (which we test on and which flake8 runs on
just fine).

Please report the bug to your plugin instead.

**Comment by asottile** [comment]
In GitLab by @oren on Dec 8, 2016, 07:12

Thank you for your response

As you can see above, this is a fresh virtualenv. The only package I installed is pyflakes. I never installed any plugin, and I would happily remove it if I knew how.
Since the only apps I ever installed related to flakes is flake8, I'm assuming it was installed as part of it (or part of python).

Do you test it on OSX as well? Might be a problem related to the OS...

**Comment by asottile** [comment]
In GitLab by @sigmavirus24 on Dec 8, 2016, 07:42

If you still have that virtualenv, can you run `pip freeze | grep flake8`?

I do test it on OSX and I don't have this problem. OSX / Homebrew do
not install random plugins for you.

Try making a temporary virtualenv using plain virtualenv and see if
you can still reproduce this. I doubt you'll be able to

**Comment by asottile** [comment]
In GitLab by @sigmavirus24 on Dec 13, 2016, 03:56

closed

**Comment by asottile** [comment]
In GitLab by @oren on Dec 27, 2016, 01:02

I re-created the env:
```
pip freeze | grep flake8
flake8==3.2.1
```

Sorry it took me so long. And Thank you!

**Comment by asottile** [comment]
In GitLab by @pimiento on Sep 25, 2017, 02:01

I have the same problem with Python 2.7

`(flake) pimiento@e470:~/flake % flake8
Traceback (most recent call last):
  File "/usr/local/bin/flake8", line 11, in <module>
    sys.exit(main())
  File "/usr/local/lib/python2.7/dist-packages/flake8/main/cli.py", line 16, in main
    app.run(argv)
  File "/usr/local/lib/python2.7/dist-packages/flake8/main/application.py", line 348, in run
    self._run(argv)
  File "/usr/local/lib/python2.7/dist-packages/flake8/main/application.py", line 335, in _run
    self.initialize(argv)
  File "/usr/local/lib/python2.7/dist-packages/flake8/main/application.py", line 318, in initialize
    self.register_plugin_options()
  File "/usr/local/lib/python2.7/dist-packages/flake8/main/application.py", line 154, in register_plugin_options
    self.check_plugins.register_options(self.option_manager)
  File "/usr/local/lib/python2.7/dist-packages/flake8/plugins/manager.py", line 487, in register_options
    list(self.manager.map(register_and_enable))
  File "/usr/local/lib/python2.7/dist-packages/flake8/plugins/manager.py", line 284, in map
    yield func(self.plugins[name], *args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/flake8/plugins/manager.py", line 483, in register_and_enable
    call_register_options(plugin)
  File "/usr/local/lib/python2.7/dist-packages/flake8/plugins/manager.py", line 379, in generated_function
    return method(optmanager, *args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/flake8/plugins/manager.py", line 230, in register_options
    add_options(optmanager)
  File "/usr/lib/python2.7/dist-packages/pep8ext_naming.py", line 78, in add_options
    parser.config_options.append('ignore-names')
AttributeError: 'OptionManager' object has no attribute 'config_options'
(flake) pimiento@e470:~/flake % flake8 -h
Traceback (most recent call last):
  File "/usr/local/bin/flake8", line 11, in <module>
    sys.exit(main())
  File "/usr/local/lib/python2.7/dist-packages/flake8/main/cli.py", line 16, in main
    app.run(argv)
  File "/usr/local/lib/python2.7/dist-packages/flake8/main/application.py", line 348, in run
    self._run(argv)
  File "/usr/local/lib/python2.7/dist-packages/flake8/main/application.py", line 335, in _run
    self.initialize(argv)
  File "/usr/local/lib/python2.7/dist-packages/flake8/main/application.py", line 318, in initialize
    self.register_plugin_options()
  File "/usr/local/lib/python2.7/dist-packages/flake8/main/application.py", line 154, in register_plugin_options
    self.check_plugins.register_options(self.option_manager)
  File "/usr/local/lib/python2.7/dist-packages/flake8/plugins/manager.py", line 487, in register_options
    list(self.manager.map(register_and_enable))
  File "/usr/local/lib/python2.7/dist-packages/flake8/plugins/manager.py", line 284, in map
    yield func(self.plugins[name], *args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/flake8/plugins/manager.py", line 483, in register_and_enable
    call_register_options(plugin)
  File "/usr/local/lib/python2.7/dist-packages/flake8/plugins/manager.py", line 379, in generated_function
    return method(optmanager, *args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/flake8/plugins/manager.py", line 230, in register_options
    add_options(optmanager)
  File "/usr/lib/python2.7/dist-packages/pep8ext_naming.py", line 78, in add_options
    parser.config_options.append('ignore-names')
AttributeError: 'OptionManager' object has no attribute 'config_options'
(flake) pimiento@e470:~/flake % pip freeze 
configparser==3.5.0
enum34==1.1.6
flake8==3.4.1
mccabe==0.6.1
pkg-resources==0.0.0
pycodestyle==2.3.1
pyflakes==1.5.0
`

**Comment by asottile** [comment]
In GitLab by @mcandre on Oct 12, 2018, 08:12

For my machine, there was an intermittent problem with a `mccabe` Python package when downgrading pycodestyle. I uninstalled `mccabe`, reinstalled my other packages, and now I no longer see the `OptionManager` error.
