### ISSUE TITLE
AttributeError: 'Attribute' object has no attribute 'id'

### ISSUE THREAD

**Issue by asottile** [PyCQA/flake8#225]
In GitLab by @alex2 on May 5, 2018, 18:34

*Please describe how you installed Flake8*

Installed by tox (latest version):
```
$ tox
GLOB sdist-make: /home/travis/build/pyca/cryptography/setup.py
pep8 create: /home/travis/build/pyca/cryptography/.tox/pep8
pep8 installdeps: coverage==4.3.4, ./vectors
pep8 inst: /home/travis/build/pyca/cryptography/.tox/dist/cryptography-2.3.dev1.zip
pep8 installed: asn1crypto==0.24.0,cffi==1.11.5,configparser==3.5.0,coverage==4.3.4,cryptography==2.3.dev1,cryptography-vectors==2.3.dev1,enum34==1.1.6,flake8==3.5.0,flake8-import-order==0.17.1,flake8-polyfill==1.0.2,idna==2.6,ipaddress==1.0.22,mccabe==0.6.1,pep8-naming==0.6.0,pycodestyle==2.3.1,pycparser==2.18,pyflakes==1.6.0,six==1.11.0
pep8 runtests: PYTHONHASHSEED='1897484384'
pep8 runtests: commands[0] | flake8 .
Traceback (most recent call last):
  File "/home/travis/build/pyca/cryptography/.tox/pep8/bin/flake8", line 11, in <module>
    sys.exit(main())
  File "/home/travis/build/pyca/cryptography/.tox/pep8/lib/python2.7/site-packages/flake8/main/cli.py", line 16, in main
    app.run(argv)
  File "/home/travis/build/pyca/cryptography/.tox/pep8/lib/python2.7/site-packages/flake8/main/application.py", line 396, in run
    self._run(argv)
  File "/home/travis/build/pyca/cryptography/.tox/pep8/lib/python2.7/site-packages/flake8/main/application.py", line 384, in _run
    self.run_checks()
  File "/home/travis/build/pyca/cryptography/.tox/pep8/lib/python2.7/site-packages/flake8/main/application.py", line 310, in run_checks
    self.file_checker_manager.run()
  File "/home/travis/build/pyca/cryptography/.tox/pep8/lib/python2.7/site-packages/flake8/checker.py", line 319, in run
    self.run_parallel()
  File "/home/travis/build/pyca/cryptography/.tox/pep8/lib/python2.7/site-packages/flake8/checker.py", line 288, in run_parallel
    for ret in pool_map:
  File "/opt/python/2.7.14/lib/python2.7/multiprocessing/pool.py", line 289, in <genexpr>
    return (item for chunk in result for item in chunk)
  File "/opt/python/2.7.14/lib/python2.7/multiprocessing/pool.py", line 673, in next
    raise value
AttributeError: 'Attribute' object has no attribute 'id'
```

**Comment by asottile** [comment]
In GitLab by @sigmavirus24 on May 6, 2018, 04:49

https://github.com/PyCQA/pep8-naming/issues/53

**Comment by asottile** [comment]
In GitLab by @sigmavirus24 on May 6, 2018, 04:49

closed
