### ISSUE TITLE
Traceback: KeyError: 'exception'

### ISSUE THREAD

**Issue by asottile** [PyCQA/flake8#226]
In GitLab by @bocekm on May 11, 2018, 07:52

**How did I install Flake8**

```
$ sudo pip install flake8
WARNING: Running pip install with root privileges is generally not a good idea. Try `pip install --user` instead.
Collecting flake8
  Using cached https://files.pythonhosted.org/packages/b9/dc/14e9d94c770b8c4ef584e906c7583e74864786a58d47de101f2767d50c0b/flake8-3.5.0-py2.py3-none-any.whl
Requirement already satisfied: enum34; python_version < "3.4" in /usr/lib/python2.7/site-packages (from flake8)
Requirement already satisfied: configparser; python_version < "3.2" in /usr/lib/python2.7/site-packages (from flake8)
Requirement already satisfied: pycodestyle<2.4.0,>=2.0.0 in /usr/lib/python2.7/site-packages (from flake8)
Requirement already satisfied: pyflakes<1.7.0,>=1.5.0 in /usr/lib/python2.7/site-packages (from flake8)
Requirement already satisfied: mccabe<0.7.0,>=0.6.0 in /usr/lib/python2.7/site-packages (from flake8)
Installing collected packages: flake8
Successfully installed flake8-3.5.0
```
I'm on Fedora 28.
The same problem appears when I uninstall the pip flake8 and install Fedora's package `python2-flake8-3.4.1-3.fc28`.

**Exact, unmodified output of `flake8 --bug-report`**
```
$ flake8 --bug-report
{
  "dependencies": [
    {
      "dependency": "setuptools", 
      "version": "39.0.1"
    }
  ], 
  "platform": {
    "python_implementation": "CPython", 
    "python_version": "2.7.14", 
    "system": "Linux"
  }, 
  "plugins": [
    {
      "is_local": false, 
      "plugin": "ProxyChecker", 
      "version": "0.0.1"
    }, 
    {
      "is_local": false, 
      "plugin": "hacking.core", 
      "version": "0.0.1"
    }, 
    {
      "is_local": false, 
      "plugin": "mccabe", 
      "version": "0.6.1"
    }, 
    {
      "is_local": false, 
      "plugin": "pycodestyle", 
      "version": "2.3.1"
    }, 
    {
      "is_local": false, 
      "plugin": "pyflakes", 
      "version": "1.6.0"
    }
  ], 
  "version": "3.5.0"
}
```

**Problem**

The flake8 tracebacks with whatever file I try to analyze.
```
$ cat test.py 
import os
```

```
$ flake8 test.py 
Exception in thread Thread-3:
Traceback (most recent call last):
  File "/usr/lib64/python2.7/threading.py", line 804, in __bootstrap_inner
    self.run()
  File "/usr/lib64/python2.7/threading.py", line 757, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/usr/lib64/python2.7/multiprocessing/pool.py", line 392, in _handle_results
    task = get()
  File "/usr/lib/python2.7/site-packages/flake8/exceptions.py", line 66, in __init__
    self.original_exception = kwargs.pop('exception')
KeyError: 'exception'
```

Fun fact: I found it out when using VS Code Python extension (https://github.com/Microsoft/vscode-python/issues/1653)

**Comment by asottile** [comment]
In GitLab by @sigmavirus24 on May 13, 2018, 09:26

I've never seen this before. This is an interesting bug.

I'm wondering if you can reproduce this without the hacking plugin installed.

**Comment by asottile** [comment]
In GitLab by @bocekm on May 14, 2018, 04:59

Frankly I don't know what this "hacking" plugin is about. I haven't installed it intentionally. I'll try to figure it out.

**Comment by asottile** [comment]
In GitLab by @bocekm on May 14, 2018, 05:03

changed the description

**Comment by asottile** [comment]
In GitLab by @bocekm on May 14, 2018, 07:10

So the hacking plugin is to blame, specifically its old version. I uninstalled it (v0.11.0) and the flake8 started working. I installed the hacking again, but v1.1.0, and flake8 still works fine.
Thanks for the idea what could be wrong.

**Comment by asottile** [comment]
In GitLab by @bocekm on May 14, 2018, 07:10

closed

**Comment by asottile** [comment]
In GitLab by @mgedmin on Feb 19, 2019, 04:44

I'm seeing this, and I don't have the `hacking` plugin installed.  Here's what `python3 -m flake8 --bug-report` says:

```
{
  "dependencies": [
    {
      "dependency": "entrypoints",
      "version": "0.3"
    }
  ],
  "platform": {
    "python_implementation": "CPython",
    "python_version": "3.6.7",
    "system": "Linux"
  },
  "plugins": [
    {
      "is_local": false,
      "plugin": "mccabe",
      "version": "0.6.1"
    },
    {
      "is_local": false,
      "plugin": "pycodestyle",
      "version": "2.5.0"
    },
    {
      "is_local": false,
      "plugin": "pyflakes",
      "version": "2.1.0"
    }
  ],
  "version": "3.7.3"
}
```

The traceback looks the same:

```
python3 -m flake8 src
Exception in thread Thread-3:
Traceback (most recent call last):
  File "/usr/lib/python3.6/threading.py", line 916, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.6/threading.py", line 864, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/lib/python3.6/multiprocessing/pool.py", line 489, in _handle_results
    task = get()
  File "/usr/lib/python3.6/multiprocessing/connection.py", line 251, in recv
    return _ForkingPickler.loads(buf.getbuffer())
  File "/home/mg/.local/lib/python3.6/site-packages/flake8/exceptions.py", line 86, in __init__
    self.original_exception = kwargs.pop("exception")
KeyError: 'exception'

^C^C... stopped while processing files

[2m14s, exited with 1]
```

I installed flake8 with `python3 -m pip install --user flake8`.

I can reproduce the problem if I upgrade flake8 to the latest version with `python3 -m pip install -U flake8`
```
Successfully installed entrypoints-0.3 flake8-3.7.6 mccabe-0.6.1 pycodestyle-2.5.0 pyflakes-2.1.0
```

**Comment by asottile** [comment]
In GitLab by @mgedmin on Feb 19, 2019, 04:51

Passing `-j1` to flake8 gives some additional information:

```
"pyflakes" failed during execution due to "'NoneType' object has no attribute 'parent'"
Run flake8 with greater verbosity to see more details
```

Passing an extra `-v` doesn't really tell me anything else (no traceback, no mention on which source file pyflakes choked), passing `-vv` gives me way too much information (on stderr), but if I redirect it to a file and take a look, I see... 180 megabytes of logs that provide no more details!

```
...
flake8.checker            MainProcess  30458 DEBUG    Running {'name': 'F', 'parameters': OrderedDict([('tree', True), ('file_tokens', True), ('filename', True)]), 'parameter_names': ['tree', 'file_tokens', 'filename'], 'plugin': <class 'flake8.plugins.pyflakes.FlakesChecker'>, 'plugin_name': 'pyflakes'} with {'tree': <_ast.Module object at 0x7f00cb043c18>}
flake8.checker            MainProcess  30581 CRITICAL Plugin F raised an unexpected exception
flake8.main.application   MainProcess  30581 INFO     Finished running
...
```

Perhaps the first step would be to improve error reporting in flake8 so plugin crashes produce actionable tracebacks somewhere?

**Comment by asottile** [comment]
In GitLab by @asottile on Feb 19, 2019, 08:19

@mgedmin your specific issue is https://github.com/PyCQA/pyflakes/issues/421

This issue is a duplicate (though older) of #505 -- it looks like there's an easy fix though -- the current exception types aren't picklesafe
