### ISSUE TITLE
AttributeError: module 'pycodestyle' has no attribute 'break_around_binary_operator'

### ISSUE THREAD

**Issue by asottile** [PyCQA/flake8#233]
In GitLab by @nschloe on Jun 5, 2018, 10:59

Since upgrading my Python installation earlier today, I'm getting the error
```
Traceback (most recent call last):
  File "/home/nschloe/.local/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2332, in resolve
    return functools.reduce(getattr, self.attrs, module)
AttributeError: module 'pycodestyle' has no attribute 'break_around_binary_operator'
```
when running flake8.

**Comment by asottile** [comment]
In GitLab by @asottile on Jun 10, 2018, 13:42

This is caused by using a too-new `pycodestyle` which is incompatible with the current latest _released_ version of flake8. Hopefully #415 will be released soon (the code on master fixes this particular bug)

**Comment by asottile** [comment]
In GitLab by @sigmavirus24 on Oct 20, 2018, 10:03

closed

**Comment by asottile** [comment]
In GitLab by @moy on Apr 24, 2019, 06:00

A temporary fix is:
```
pip install --user pycodestyle==2.3
```

**Comment by asottile** [comment]
In GitLab by @asottile on Apr 24, 2019, 07:08

A better fix is to upgrade both, the latest version of both are now compatible again

**Comment by asottile** [comment]
In GitLab by @moy on Apr 24, 2019, 07:16

> A better fix is to upgrade both, the latest version of both are now compatible again

Unfortunately, this didn't work for me:

```
$ pip3 install --user --upgrade --no-cache pycodestyle flake8
Requirement already up-to-date: pycodestyle in /home/mmoy/.local/lib/python3.6/site-packages (2.5.0)
Requirement already up-to-date: flake8 in /home/mmoy/.local/lib/python3.6/site-packages (3.7.7)
Requirement already satisfied, skipping upgrade: entrypoints<0.4.0,>=0.3.0 in /home/mmoy/.local/lib/python3.6/site-packages (from flake8) (0.3)
Requirement already satisfied, skipping upgrade: mccabe<0.7.0,>=0.6.0 in /home/mmoy/.local/lib/python3.6/site-packages (from flake8) (0.6.1)
Requirement already satisfied, skipping upgrade: pyflakes<2.2.0,>=2.1.0 in /home/mmoy/.local/lib/python3.6/site-packages (from flake8) (2.1.1)
$ ~/.local/bin/flake8 --version                              
Traceback (most recent call last):
  File "/home/mmoy/.local/lib/python3.6/site-packages/flake8/plugins/manager.py", line 163, in load_plugin
    self._load()
  File "/home/mmoy/.local/lib/python3.6/site-packages/flake8/plugins/manager.py", line 140, in _load
    self._plugin = self.entry_point.load()
  File "/home/mmoy/.local/lib/python3.6/site-packages/entrypoints.py", line 86, in load
    obj = getattr(obj, attr)
AttributeError: module 'pycodestyle' has no attribute 'break_around_binary_operator'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/mmoy/.local/bin/flake8", line 10, in <module>
    sys.exit(main())
  File "/home/mmoy/.local/lib/python3.6/site-packages/flake8/main/cli.py", line 18, in main
    app.run(argv)
  File "/home/mmoy/.local/lib/python3.6/site-packages/flake8/main/application.py", line 394, in run
    self._run(argv)
  File "/home/mmoy/.local/lib/python3.6/site-packages/flake8/main/application.py", line 381, in _run
    self.initialize(argv)
  File "/home/mmoy/.local/lib/python3.6/site-packages/flake8/main/application.py", line 364, in initialize
    self.find_plugins()
  File "/home/mmoy/.local/lib/python3.6/site-packages/flake8/main/application.py", line 200, in find_plugins
    self.check_plugins.load_plugins()
  File "/home/mmoy/.local/lib/python3.6/site-packages/flake8/plugins/manager.py", line 417, in load_plugins
    plugins = list(self.manager.map(load_plugin))
  File "/home/mmoy/.local/lib/python3.6/site-packages/flake8/plugins/manager.py", line 302, in map
    yield func(self.plugins[name], *args, **kwargs)
  File "/home/mmoy/.local/lib/python3.6/site-packages/flake8/plugins/manager.py", line 415, in load_plugin
    return plugin.load_plugin()
  File "/home/mmoy/.local/lib/python3.6/site-packages/flake8/plugins/manager.py", line 170, in load_plugin
    raise failed_to_load
flake8.exceptions.FailedToLoadPlugin: Flake8 failed to load plugin "pycodestyle.break_around_binary_operator" due to module 'pycodestyle' has no attribute 'break_around_binary_operator'.
```

**Comment by asottile** [comment]
In GitLab by @asottile on Apr 24, 2019, 07:18

that looks like you've got two copies of flake8 installed, maybe one as an egg and one not (?)

**Comment by asottile** [comment]
In GitLab by @moy on Apr 24, 2019, 07:24

Strange: I had tried all sorts of `pip uninstall` to get rid of old flake8 versions, but using some old good `rm -fr` in `~/.local` instead and re-running `pip3 install flake8`, I do indeed get a working install. For the record, this is a working configuration:

```
$ pip3 install --user --upgrade --no-cache pycodestyle flake8
Requirement already up-to-date: pycodestyle in /home/mmoy/.local/lib/python3.6/site-packages (2.5.0)
Requirement already up-to-date: flake8 in /home/mmoy/.local/lib/python3.6/site-packages (3.7.7)
Requirement already satisfied, skipping upgrade: mccabe<0.7.0,>=0.6.0 in /home/mmoy/.local/lib/python3.6/site-packages (from flake8) (0.6.1)
Requirement already satisfied, skipping upgrade: entrypoints<0.4.0,>=0.3.0 in /home/mmoy/.local/lib/python3.6/site-packages (from flake8) (0.3)
Requirement already satisfied, skipping upgrade: pyflakes<2.2.0,>=2.1.0 in /home/mmoy/.local/lib/python3.6/site-packages (from flake8) (2.1.1)
```

Thanks for the help.

**Comment by asottile** [comment]
In GitLab by @asottile on Apr 24, 2019, 07:26

ah yeah, iirc latest pip won't uninstall eggs or something of the sort (?)

good to hear you got it fixed though :thumbsup:
