### ISSUE TITLE
Using format as function parameter crashes flake8

### ISSUE THREAD

**Issue by asottile** [PyCQA/flake8#241]
In GitLab by @jeverling on Jun 26, 2018, 06:06

The following code crashes flake8 (Python 2, pip-installed into a virtualenv, with some modules installed globally).

```python
def crash_flake8(format):
    pass
```

with the following traceback:

```
Traceback (most recent call last):
  File "/home/jeverling/.virtualenvs/kobo/bin/flake8", line 11, in <module>
    sys.exit(main())
  File "/home/jeverling/.virtualenvs/kobo/lib/python2.7/site-packages/flake8/main/cli.py", line 16, in main
    app.run(argv)
  File "/home/jeverling/.virtualenvs/kobo/lib/python2.7/site-packages/flake8/main/application.py", line 396, in run
    self._run(argv)
  File "/home/jeverling/.virtualenvs/kobo/lib/python2.7/site-packages/flake8/main/application.py", line 385, in _run
    self.report()
  File "/home/jeverling/.virtualenvs/kobo/lib/python2.7/site-packages/flake8/main/application.py", line 376, in report
    self.report_errors()
  File "/home/jeverling/.virtualenvs/kobo/lib/python2.7/site-packages/flake8/main/application.py", line 340, in report_errors
    results = self.file_checker_manager.report()
  File "/home/jeverling/.virtualenvs/kobo/lib/python2.7/site-packages/flake8/checker.py", line 267, in report
    results_reported += self._handle_results(filename, results)
  File "/home/jeverling/.virtualenvs/kobo/lib/python2.7/site-packages/flake8/checker.py", line 166, in _handle_results
    physical_line=physical_line,
  File "/home/jeverling/.virtualenvs/kobo/lib/python2.7/site-packages/flake8/style_guide.py", line 384, in handle_error
    error = Violation(code, filename, line_number, column_number + 1,
TypeError: cannot concatenate 'str' and 'int' objects
```

Output of `flake8 --bug-report`:

```
{
  "dependencies": [
    {
      "dependency": "setuptools", 
      "version": "39.2.0"
    }
  ], 
  "platform": {
    "python_implementation": "CPython", 
    "python_version": "2.7.15", 
    "system": "Linux"
  }, 
  "plugins": [
    {
      "is_local": false, 
      "plugin": "flake8-bandit", 
      "version": "v1.0.2"
    }, 
    {
      "is_local": false, 
      "plugin": "flake8-comprehensions", 
      "version": "1.4.1"
    }, 
    {
      "is_local": false, 
      "plugin": "flake8_builtins", 
      "version": "1.3"
    }, 
    {
      "is_local": false, 
      "plugin": "flake8_commas", 
      "version": "2.0.0"
    }, 
    {
      "is_local": false, 
      "plugin": "mccabe", 
      "version": "0.6.1"
    }, 
    {
      "is_local": false, 
      "plugin": "pycodestyle", 
      "version": "2.3.1"
    }, 
    {
      "is_local": false, 
      "plugin": "pyflakes", 
      "version": "1.6.0"
    }
  ], 
  "version": "3.5.0"
}
```

**Comment by asottile** [comment]
In GitLab by @asottile on Jun 26, 2018, 09:07

This is a bug in `flake8-builtins==1.3`, upgrade to `flake8-builtins==1.4.1`

**Comment by asottile** [comment]
In GitLab by @jeverling on Jun 26, 2018, 09:37

You are right, it works correctly with `flake8-builtins==1.4.1`. Thanks! :+1:

**Comment by asottile** [comment]
In GitLab by @jeverling on Jun 26, 2018, 09:38

closed
