### ISSUE TITLE
Waiting for upgrade

### ISSUE THREAD

**Issue by asottile** [PyCQA/flake8#250]
In GitLab by @AK88103_gitlab on Aug 3, 2018, 05:08

flake8 3.5.0 has requirement pycodestyle<2.4.0,>=2.0.0, but you have pycodestyle 2.4.0.
flake8 3.5.0 has requirement pyflakes<1.7.0,>=1.5.0, but you have pyflakes 2.0.0.

**Comment by asottile** [comment]
In GitLab by @diraol on Aug 3, 2018, 13:20

#415

**Comment by asottile** [comment]
In GitLab by @AK88103_gitlab on Aug 3, 2018, 18:21

@diraol Is it right?

`flake8 --bug-report`

Traceback (most recent call last):
  File "d:\program files\python\lib\site-packages\pkg_resources\__init__.py", line 2329, in resolve
    return functools.reduce(getattr, self.attrs, module)
AttributeError: module 'pycodestyle' has no attribute 'break_around_binary_operator'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "d:\program files\python\lib\site-packages\flake8\plugins\manager.py", line 178, in load_plugin
    self._load(verify_requirements)
  File "d:\program files\python\lib\site-packages\flake8\plugins\manager.py", line 150, in _load
    self._plugin = resolve()
  File "d:\program files\python\lib\site-packages\pkg_resources\__init__.py", line 2331, in resolve
    raise ImportError(str(exc))
ImportError: module 'pycodestyle' has no attribute 'break_around_binary_operator'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "d:\program files\python\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "d:\program files\python\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "D:\Program Files\Python\Scripts\flake8.exe\__main__.py", line 9, in <module>
  File "d:\program files\python\lib\site-packages\flake8\main\cli.py", line 16, in main
    app.run(argv)
  File "d:\program files\python\lib\site-packages\flake8\main\application.py", line 396, in run
    self._run(argv)
  File "d:\program files\python\lib\site-packages\flake8\main\application.py", line 383, in _run
    self.initialize(argv)
  File "d:\program files\python\lib\site-packages\flake8\main\application.py", line 365, in initialize
    self.find_plugins()
  File "d:\program files\python\lib\site-packages\flake8\main\application.py", line 191, in find_plugins
    self.check_plugins.load_plugins()
  File "d:\program files\python\lib\site-packages\flake8\plugins\manager.py", line 423, in load_plugins
    plugins = list(self.manager.map(load_plugin))
  File "d:\program files\python\lib\site-packages\flake8\plugins\manager.py", line 311, in map
    yield func(self.plugins[name], *args, **kwargs)
  File "d:\program files\python\lib\site-packages\flake8\plugins\manager.py", line 421, in load_plugin
    return plugin.load_plugin()
  File "d:\program files\python\lib\site-packages\flake8\plugins\manager.py", line 186, in load_plugin
    raise failed_to_load
flake8.exceptions.FailedToLoadPlugin: Flake8 failed to load plugin "pycodestyle.break_around_binary_operator" due to module 'pycodestyle' has no attribute 'break_around_binary_operator'.

**Comment by asottile** [comment]
In GitLab by @diraol on Aug 5, 2018, 12:05

Hi @AK88103\_gitlab 

looking on the issue I've mentioned, there is a Merge Request (https://gitlab.com/pycqa/flake8/merge_requests/230) associated with it that was already merged, but hasn't been released yet.

**Comment by asottile** [comment]
In GitLab by @AK88103_gitlab on Aug 5, 2018, 16:19

I had read the issue #415 .Release soon.

**Comment by asottile** [comment]
In GitLab by @AK88103_gitlab on Aug 5, 2018, 16:19

closed
