### ISSUE TITLE
latest flake8 conflicts with autopep8

### ISSUE THREAD

**Issue by asottile** [PyCQA/flake8#267]
In GitLab by @togakangaroo on Oct 20, 2018, 08:10

*Please describe how you installed Flake8*

Example:

```
$ pipenv install
```

with this `Pipenv` file

```

[packages]
flake8 = "*"
autopep8 = "*"

[dev-packages]

[requires]
python_version = "3.7"
```

*Please provide the exact, unmodified output of `flake8 --bug-report`*

```
~/code/testpipenv $ pipenv run flake8 --bug-report
Traceback (most recent call last):
  File "/Users/gmauer/.local/share/virtualenvs/testpipenv--d24wtdZ/lib/python3.7/site-packages/pkg_resources/__init__.py", line 2340, in resolve
    return functools.reduce(getattr, self.attrs, module)
AttributeError: module 'pycodestyle' has no attribute 'break_around_binary_operator'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/gmauer/.local/share/virtualenvs/testpipenv--d24wtdZ/lib/python3.7/site-packages/flake8/plugins/manager.py", line 178, in load_plugin
    self._load(verify_requirements)
  File "/Users/gmauer/.local/share/virtualenvs/testpipenv--d24wtdZ/lib/python3.7/site-packages/flake8/plugins/manager.py", line 150, in _load
    self._plugin = resolve()
  File "/Users/gmauer/.local/share/virtualenvs/testpipenv--d24wtdZ/lib/python3.7/site-packages/pkg_resources/__init__.py", line 2342, in resolve
    raise ImportError(str(exc))
ImportError: module 'pycodestyle' has no attribute 'break_around_binary_operator'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/gmauer/.local/share/virtualenvs/testpipenv--d24wtdZ/bin/flake8", line 11, in <module>
    sys.exit(main())
  File "/Users/gmauer/.local/share/virtualenvs/testpipenv--d24wtdZ/lib/python3.7/site-packages/flake8/main/cli.py", line 16, in main
    app.run(argv)
  File "/Users/gmauer/.local/share/virtualenvs/testpipenv--d24wtdZ/lib/python3.7/site-packages/flake8/main/application.py", line 396, in run
    self._run(argv)
  File "/Users/gmauer/.local/share/virtualenvs/testpipenv--d24wtdZ/lib/python3.7/site-packages/flake8/main/application.py", line 383, in _run
    self.initialize(argv)
  File "/Users/gmauer/.local/share/virtualenvs/testpipenv--d24wtdZ/lib/python3.7/site-packages/flake8/main/application.py", line 365, in initialize
    self.find_plugins()
  File "/Users/gmauer/.local/share/virtualenvs/testpipenv--d24wtdZ/lib/python3.7/site-packages/flake8/main/application.py", line 191, in find_plugins
    self.check_plugins.load_plugins()
  File "/Users/gmauer/.local/share/virtualenvs/testpipenv--d24wtdZ/lib/python3.7/site-packages/flake8/plugins/manager.py", line 423, in load_plugins
    plugins = list(self.manager.map(load_plugin))
  File "/Users/gmauer/.local/share/virtualenvs/testpipenv--d24wtdZ/lib/python3.7/site-packages/flake8/plugins/manager.py", line 311, in map
    yield func(self.plugins[name], *args, **kwargs)
  File "/Users/gmauer/.local/share/virtualenvs/testpipenv--d24wtdZ/lib/python3.7/site-packages/flake8/plugins/manager.py", line 421, in load_plugin
    return plugin.load_plugin()
  File "/Users/gmauer/.local/share/virtualenvs/testpipenv--d24wtdZ/lib/python3.7/site-packages/flake8/plugins/manager.py", line 186, in load_plugin
    raise failed_to_load
flake8.exceptions.FailedToLoadPlugin: Flake8 failed to load plugin "pycodestyle.break_around_binary_operator" due to module 'pycodestyle' has no attribute 'break_around_binary_operator'.
```

*Please describe the problem or feature*

`pipenv install` with no lockfile will generate this error

```

Warning: Your dependencies could not be resolved. You likely have a mismatch in your sub-dependencies.
  You can use $ pipenv install --skip-lock to bypass this mechanism, then run $ pipenv graph to inspect the situation.
  Hint: try $ pipenv lock --pre if it is a pre-release dependency.
Could not find a version that matches pycodestyle<2.4.0,>=2.0.0,>=2.4.0
Tried: 2.0.0, 2.0.0, 2.1.0, 2.1.0, 2.2.0, 2.2.0, 2.3.0, 2.3.0, 2.3.1, 2.3.1, 2.4.0, 2.4.0
Skipped pre-versions: 1.8.0.dev0, 1.8.0.dev0, 2.0.0a1, 2.0.0a1
There are incompatible versions in the resolved dependencies.
```

I'm submitting this specifically to flake8 since

```
~/code/testpipenv $ pipenv graph
autopep8==1.4.1
  - pycodestyle [required: >=2.4.0, installed: 2.4.0]
flake8==3.5.0
  - mccabe [required: >=0.6.0,<0.7.0, installed: 0.6.1]
  - pycodestyle [required: >=2.0.0,<2.4.0, installed: 2.4.0]
  - pyflakes [required: >=1.5.0,<1.7.0, installed: 1.6.0]

~/code/testpipenv $ pipenv graph
autopep8==1.4.1
  - pycodestyle [required: >=2.4.0, installed: 2.4.0]
flake8==3.5.0
  - mccabe [required: >=0.6.0,<0.7.0, installed: 0.6.1]
  - pycodestyle [required: >=2.0.0,<2.4.0, installed: 2.4.0]
  - pyflakes [required: >=1.5.0,<1.7.0, installed: 1.6.0]
```

And that `pycodestyle` `<2.4.0` dependency on flake8 is the most problematic and suspicious.

*If this is a bug report, please explain with examples (and example code) what you expected to happen and what actually happened.*

I would like for there not to be a fourth party dependency conflict :smile:

**Comment by asottile** [comment]
In GitLab by @sigmavirus24 on Oct 20, 2018, 09:52

> And that `pycodestyle` `<2.4.0` dependency on flake8 is the most problematic and suspicious.

You can use a different version of autopep8. You can also wait for a new version of Flake8 that supports 2.4.0 to be released. The latter may happen soon.

**Comment by asottile** [comment]
In GitLab by @sigmavirus24 on Oct 20, 2018, 09:52

closed

**Comment by asottile** [comment]
In GitLab by @togakangaroo on Oct 20, 2018, 19:21

Ok, for anyone coming along after, autopep8 1.4.0 seems to work fine
