### ISSUE TITLE
ForkingPickler: TypeError: __init__() missing 3 required positional arguments: 'type', 'value', and 'context'

### ISSUE THREAD

**Issue by asottile** [PyCQA/flake8#279]
In GitLab by @timthelion on Nov 23, 2018, 09:51

*Please describe how you installed Flake8*

```
$ pipenv install --dev --system
```

With the following dev packages (along with others).

```
"flake8" = "*"
"flake8-blind-except" = "*"
"flake8-comprehensions" = "*"
"flake8-import-order" = "*"
"flake8-tidy-imports" = "*"
"flake8-builtins" = "*"
"flake8_strict" = "*"
```

*Please provide the exact, unmodified output of `flake8 --bug-report`*

```
{
  "dependencies": [
    {
      "dependency": "setuptools",
      "version": "40.6.2"
    }
  ],
  "platform": {
    "python_implementation": "CPython",
    "python_version": "3.5.5",
    "system": "Linux"
  },
  "plugins": [
    {
      "is_local": false,
      "plugin": "flake8-blind-except",
      "version": "0.1.1"
    },
    {
      "is_local": false,
      "plugin": "flake8-comprehensions",
      "version": "1.4.1"
    },
    {
      "is_local": false,
      "plugin": "flake8-tidy-imports",
      "version": "1.1.0"
    },
    {
      "is_local": false,
      "plugin": "flake8_builtins",
      "version": "1.4.1"
    },
    {
      "is_local": false,
      "plugin": "flake8_strict",
      "version": "0.2.1"
    },
    {
      "is_local": false,
      "plugin": "import-order",
      "version": "0.18"
    },
    {
      "is_local": false,
      "plugin": "mccabe",
      "version": "0.6.1"
    },
    {
      "is_local": false,
      "plugin": "pycodestyle",
      "version": "2.4.0"
    },
    {
      "is_local": false,
      "plugin": "pyflakes",
      "version": "2.0.0"
    }
  ],
  "version": "3.6.0"
}
```

*Please describe the problem or feature*

```
$ flake8
Exception in thread Thread-3:
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/threading.py", line 914, in _bootstrap_inner
    self.run()
  File "/usr/local/lib/python3.5/threading.py", line 862, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/local/lib/python3.5/multiprocessing/pool.py", line 463, in _handle_results
    task = get()
  File "/usr/local/lib/python3.5/multiprocessing/connection.py", line 251, in recv
    return ForkingPickler.loads(buf.getbuffer())
TypeError: __init__() missing 3 required positional arguments: 'type', 'value', and 'context'
```

*If this is a bug report, please explain with examples (and example code) what you expected to happen and what actually happened.*

```
$ flake8
$ # No output
```

**Comment by asottile** [comment]
In GitLab by @asottile on Nov 23, 2018, 10:36

Is there a particular project you're running this on?  I'm not seeing any errors with just those installed on an empty project

**Comment by asottile** [comment]
In GitLab by @asottile on Nov 23, 2018, 10:38

Could you also show the output when using `flake8 --jobs=1`?

**Comment by asottile** [comment]
In GitLab by @timthelion on Nov 23, 2018, 10:50

```
$ flake8 --jobs=1
Traceback (most recent call last):
  File "/usr/local/bin/flake8", line 11, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.5/site-packages/flake8/main/cli.py", line 16, in main
    app.run(argv)
  File "/usr/local/lib/python3.5/site-packages/flake8/main/application.py", line 412, in run
    self._run(argv)
  File "/usr/local/lib/python3.5/site-packages/flake8/main/application.py", line 400, in _run
    self.run_checks()
  File "/usr/local/lib/python3.5/site-packages/flake8/main/application.py", line 318, in run_checks
    self.file_checker_manager.run()
  File "/usr/local/lib/python3.5/site-packages/flake8/checker.py", line 340, in run
    self.run_serial()
  File "/usr/local/lib/python3.5/site-packages/flake8/checker.py", line 324, in run_serial
    checker.run_checks()
  File "/usr/local/lib/python3.5/site-packages/flake8/checker.py", line 612, in run_checks
    self.run_ast_checks()
  File "/usr/local/lib/python3.5/site-packages/flake8/checker.py", line 520, in run_ast_checks
    for (line_number, offset, text, check) in runner:
  File "/usr/local/lib/python3.5/site-packages/flake8_strict.py", line 47, in run
    errors = _process_file(self._filename)
  File "/usr/local/lib/python3.5/site-packages/flake8_strict.py", line 64, in _process_file
    return _process_code(code)
  File "/usr/local/lib/python3.5/site-packages/flake8_strict.py", line 69, in _process_code
    '%s%s' % (code, '\n' if code and code[-1] != '\n' else ''),
  File "/usr/local/lib/python3.5/lib2to3/pgen2/driver.py", line 106, in parse_string
    return self.parse_tokens(tokens, debug)
  File "/usr/local/lib/python3.5/lib2to3/pgen2/driver.py", line 71, in parse_tokens
    if p.addtoken(type, value, (prefix, start)):
  File "/usr/local/lib/python3.5/lib2to3/pgen2/parse.py", line 159, in addtoken
    raise ParseError("bad input", type, value, context)
lib2to3.pgen2.parse.ParseError: bad input: type=1, value='or', context=(' ', (122, 56))
```

I get the error when running in the root of this directory https://github.com/auto-mat/do-prace-na-kole/tree/81aeaa25c5a8c4c827eb9922d0dba1d12d95266a if I cd to the `dpnk` directory where most of the code is, the error does not appear. So I guess there must be a file flake8 thinks is a python file but is failing to parse.

**Comment by asottile** [comment]
In GitLab by @timthelion on Nov 23, 2018, 10:51

Is there a good way of figuring out which file it's failing on?

**Comment by asottile** [comment]
In GitLab by @asottile on Nov 23, 2018, 11:17

The error message seems pretty unfortunate!  Though I think this is a bug with lib2to3 (and then subsequently the `flake8-strict` plugin).  Let me see if I can write you a small script to figure out what the bad apple is.  I wonder if there's a way to make `flake8` expose this plugin failure directly too :thinking: 

Usually something like this would show you the specific file it is failing on, but I'm still not seeing that myself:

```
git ls-files -- '*.py' | xargs -P4 --replace bash -c 'flake8 -j1 {} || echo {}'
```

It could also be something in a virtualenv that's not excluded?

---

Either way here's a minimal reproduction:

(using python<3.7, flake8-strict installed)

```python
print(
    _ for _ in range(5),
)
```

```console
$ flake8 -j2 t.py
Exception in thread Thread-3:
Traceback (most recent call last):
  File "/usr/lib/python3.5/threading.py", line 914, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.5/threading.py", line 862, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/lib/python3.5/multiprocessing/pool.py", line 463, in _handle_results
    task = get()
  File "/usr/lib/python3.5/multiprocessing/connection.py", line 251, in recv
    return ForkingPickler.loads(buf.getbuffer())
TypeError: __init__() missing 3 required positional arguments: 'type', 'value', and 'context'

(it now hangs forever)
```

**Comment by asottile** [comment]
In GitLab by @asottile on Nov 23, 2018, 11:29

heh appears it passes in python3.6 as well since flake8-strict does [some sketch things](https://github.com/smarkets/flake8-strict/blob/7c40ad30ecb6d8a31ac384ed49bb8107cfd5023e/flake8_strict.py#L16-L22)

**Comment by asottile** [comment]
In GitLab by @timthelion on Nov 23, 2018, 12:28

So the file was not tracked by git. Running `find -name "*.py" | xargs -P4 --replace bash -c 'flake8 -j1 {} || echo {}' &> flog` lead me to discover the file that causes the trouble:

```
$ flake8 pipenv/.local/share/virtualenvs/app-v-QaxYZVWa/lib/python3.5/site-packages/kombu/simple.py -j1
Traceback (most recent call last):
  File "/usr/local/bin/flake8", line 11, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.5/site-packages/flake8/main/cli.py", line 16, in main
    app.run(argv)
  File "/usr/local/lib/python3.5/site-packages/flake8/main/application.py", line 412, in run
    self._run(argv)
  File "/usr/local/lib/python3.5/site-packages/flake8/main/application.py", line 400, in _run
    self.run_checks()
  File "/usr/local/lib/python3.5/site-packages/flake8/main/application.py", line 318, in run_checks
    self.file_checker_manager.run()
  File "/usr/local/lib/python3.5/site-packages/flake8/checker.py", line 340, in run
    self.run_serial()
  File "/usr/local/lib/python3.5/site-packages/flake8/checker.py", line 324, in run_serial
    checker.run_checks()
  File "/usr/local/lib/python3.5/site-packages/flake8/checker.py", line 612, in run_checks
    self.run_ast_checks()
  File "/usr/local/lib/python3.5/site-packages/flake8/checker.py", line 520, in run_ast_checks
    for (line_number, offset, text, check) in runner:
  File "/usr/local/lib/python3.5/site-packages/flake8_strict.py", line 47, in run
    errors = _process_file(self._filename)
  File "/usr/local/lib/python3.5/site-packages/flake8_strict.py", line 64, in _process_file
    return _process_code(code)
  File "/usr/local/lib/python3.5/site-packages/flake8_strict.py", line 69, in _process_code
    '%s%s' % (code, '\n' if code and code[-1] != '\n' else ''),
  File "/usr/local/lib/python3.5/lib2to3/pgen2/driver.py", line 106, in parse_string
    return self.parse_tokens(tokens, debug)
  File "/usr/local/lib/python3.5/lib2to3/pgen2/driver.py", line 71, in parse_tokens
    if p.addtoken(type, value, (prefix, start)):
  File "/usr/local/lib/python3.5/lib2to3/pgen2/parse.py", line 159, in addtoken
    raise ParseError("bad input", type, value, context)
lib2to3.pgen2.parse.ParseError: bad input: type=1, value='or', context=(' ', (122, 56))
```

I cut that file down to:

```
class SimpleQueue(SimpleBase):
    def __init__():
        exchange_opts = dict(self.exchange_opts, **exchange_opts or {})
```

and I still get the error.

You can find the full file here: https://raw.githubusercontent.com/celery/kombu/master/kombu/simple.py

**Comment by asottile** [comment]
In GitLab by @sigmavirus24 on Nov 23, 2018, 17:02

This isn't the place to report bugs with flake8-strict, unfortuntaely. It seems as though they're using lib2to3 for some reason in parsing of input files.

lib2to3 is not used at all by Flake8 proper.

I do think we could be better about not crashing and reporting the error, but mostly we've tried to avoid having a broken plugin silently.

**Comment by asottile** [comment]
In GitLab by @asottile on Nov 25, 2018, 13:50

So the reason this crashes is `ParseError` is pickleable but not un-pickleable.  flake8 would normally expose the crash if it were able to propagate through the `multiprocessing` machinery.  I think this is probably a bug in cpython itself.

Here's what the exception itself looks like:

```
(Pdb) pickle.dumps(ParseError("bad input", type, value, context))
b"\x80\x03clib2to3.pgen2.parse\nParseError\nq\x00X4\x00\x00\x00bad input: type=8, value=')', context=('\\n', (3, 0))q\x01\x85q\x02Rq\x03}q\x04(X\x05\x00\x00\x00valueq\x05X\x01\x00\x00\x00)q\x06X\x03\x00\x00\x00msgq\x07X\t\x00\x00\x00bad inputq\x08X\x07\x00\x00\x00contextq\tX\x01\x00\x00\x00\nq\nK\x03K\x00\x86q\x0b\x86q\x0cX\x04\x00\x00\x00typeq\rK\x08ub."
(Pdb) pickle.loads(pickle.dumps(ParseError("bad input", type, value, context)))
*** TypeError: __init__() missing 3 required positional arguments: 'type', 'value', and 'context'
```

**Comment by asottile** [comment]
In GitLab by @asottile on Nov 25, 2018, 14:02

This appears to be a cpython bug so I've opened an issue here: https://bugs.python.org/issue35311

**Comment by asottile** [comment]
In GitLab by @asottile on Nov 25, 2018, 20:10

Created https://bugs.python.org/issue35312 as well

**Comment by asottile** [comment]
In GitLab by @asottile on Jan 3, 2019, 17:02

Closing this since it's a combination of several bugs, none of which it seems flake8 can do much about:
- flake8-strict using lib2to3 to reparse inputs
    - lib2to3 crashing on valid syntax
- multiprocessing crashing on un-unpickleable exceptions
- lib2to3 raising an un-unpickleable exception (I already fixed this)

**Comment by asottile** [comment]
In GitLab by @asottile on Jan 3, 2019, 17:02

closed

**Comment by asottile** [comment]
In GitLab by @mitar on Mar 1, 2021, 03:14

I got this error because I had a type with `...` in it: `typing.Union[typing.Tuple[typing.Any, ...], typing.Mapping[str, typing.Any]]`.

I escaped whole type into a string and it works now.

(I use some older version of tools at the moment, so probably newer versions do not have issues parsing this anymore.)
