### ISSUE TITLE
ValueError: Unexpected token: Token

### ISSUE THREAD

**Issue by asottile** [PyCQA/flake8#287]
In GitLab by @zsluedem on Jan 29, 2019, 22:50

Please read this brief portion of documentation before going any further: http://flake8.pycqa.org/en/latest/internal/contributing.html#filing-a-bug

*Please describe how you installed Flake8*

Example:

```
$ pip install flake8
```

**Note**: Some *nix distributions patch Flake8 arbitrarily to accommodate incompatible software versions. If you're on one of those distributions, your issue may be closed and you will be asked to open an issue with your distribution package maintainers instead.

*Please provide the exact, unmodified output of `flake8 --bug-report`*
```
{
  "dependencies": [
    {
      "dependency": "entrypoints",
      "version": "0.3"
    }
  ],
  "platform": {
    "python_implementation": "CPython",
    "python_version": "3.6.5",
    "system": "Darwin"
  },
  "plugins": [
    {
      "is_local": false,
      "plugin": "mccabe",
      "version": "0.6.1"
    },
    {
      "is_local": false,
      "plugin": "pycodestyle",
      "version": "2.5.0"
    },
    {
      "is_local": false,
      "plugin": "pyflakes",
      "version": "2.1.0"
    }
  ],
  "version": "3.7.0"
}
```
*Please describe the problem or feature*

`$ flake8 dir`

```
Traceback (most recent call last):
  File "/Users/willqiu/.virtualenvs/MonkTrader/bin/flake8", line 11, in <module>
    sys.exit(main())
  File "/Users/willqiu/.virtualenvs/MonkTrader/lib/python3.6/site-packages/flake8/main/cli.py", line 18, in main
    app.run(argv)
  File "/Users/willqiu/.virtualenvs/MonkTrader/lib/python3.6/site-packages/flake8/main/application.py", line 392, in run
    self._run(argv)
  File "/Users/willqiu/.virtualenvs/MonkTrader/lib/python3.6/site-packages/flake8/main/application.py", line 379, in _run
    self.initialize(argv)
  File "/Users/willqiu/.virtualenvs/MonkTrader/lib/python3.6/site-packages/flake8/main/application.py", line 366, in initialize
    self.make_guide()
  File "/Users/willqiu/.virtualenvs/MonkTrader/lib/python3.6/site-packages/flake8/main/application.py", line 268, in make_guide
    self.options, self.formatter
  File "/Users/willqiu/.virtualenvs/MonkTrader/lib/python3.6/site-packages/flake8/style_guide.py", line 345, in __init__
    self.populate_style_guides_with(options),
  File "/Users/willqiu/.virtualenvs/MonkTrader/lib/python3.6/site-packages/flake8/style_guide.py", line 362, in populate_style_guides_with
    options.per_file_ignores
  File "/Users/willqiu/.virtualenvs/MonkTrader/lib/python3.6/site-packages/flake8/utils.py", line 126, in parse_files_to_codes_mapping
    raise ValueError("Unexpected token: {}".format(token))
ValueError: Unexpected token: Token(tp='code', src='M')
```
*If this is a bug report, please explain with examples (and example code) what you expected to happen and what actually happened.*

**Comment by asottile** [comment]
In GitLab by @zsluedem on Jan 29, 2019, 22:52

changed the description

**Comment by asottile** [comment]
In GitLab by @asottile on Jan 29, 2019, 22:53

Do you have a project which this reproduces on? This looks like the new `per-file-ignores` settings

**Comment by asottile** [comment]
In GitLab by @zsluedem on Jan 29, 2019, 22:55

https://github.com/zsluedem/MonkTrader/pull/59/files#diff-380c6a8ebbbce17d55d50ef17d3cf906

**Comment by asottile** [comment]
In GitLab by @asottile on Jan 29, 2019, 22:56

yeah, looking at your configuration [here](https://github.com/zsluedem/MonkTrader/pull/59/files#diff-380c6a8ebbbce17d55d50ef17d3cf906R6)

The format is:

```
per-file-ignores =
    glob1: F123,E123,...
    glob2: F123,...
```

**Comment by asottile** [comment]
In GitLab by @zsluedem on Jan 29, 2019, 22:57

@asottile Great~! Thanks a lot.

**Comment by asottile** [comment]
In GitLab by @zsluedem on Jan 29, 2019, 22:57

closed

**Comment by asottile** [comment]
In GitLab by @asottile on Jan 29, 2019, 22:58

This should definitely produce a better error message, but the error message doesn't appear to be wrong here

**Comment by asottile** [comment]
In GitLab by @zsluedem on Jan 29, 2019, 23:04

@asottile 
```
per-file-ignores =
    MonkTrader/config/project_template/*: E225

```

Is this one right format? It still throws the error.

**Comment by asottile** [comment]
In GitLab by @zsluedem on Jan 29, 2019, 23:04

reopened

**Comment by asottile** [comment]
In GitLab by @asottile on Jan 29, 2019, 23:05

that looks right, let me see what that's mad about -- probably a faulty regex

**Comment by asottile** [comment]
In GitLab by @zsluedem on Jan 29, 2019, 23:07

flake8==3.6 doesn't have that problem.

**Comment by asottile** [comment]
In GitLab by @asottile on Jan 29, 2019, 23:11

correct, this is a new feature of 3.7 -- 3.6 didn't understand `per-file-ignores` (unless you used a plugin)

**Comment by asottile** [comment]
In GitLab by @asottile on Jan 29, 2019, 23:18

mentioned in merge request !290

**Comment by asottile** [comment]
In GitLab by @asottile on Jan 29, 2019, 23:29

closed via merge request !290

**Comment by asottile** [comment]
In GitLab by @asottile on Jan 29, 2019, 23:29

mentioned in commit ed3b133227f60a57eb6d18ca0ef6520d0be322b7

**Comment by asottile** [comment]
In GitLab by @asottile on Jan 29, 2019, 23:29

@zsluedem can you try out the latest master?

**Comment by asottile** [comment]
In GitLab by @zsluedem on Jan 29, 2019, 23:35

It still throws the error.
`ed3b133227f60a57eb6d18ca0ef6520d0be322b7` this version right?

**Comment by asottile** [comment]
In GitLab by @asottile on Jan 29, 2019, 23:38

this diff passes your repository for me:

```diff
--- a/setup.cfg
+++ b/setup.cfg
@@ -1,9 +1,6 @@
 [flake8]
 ignore = W504
 max-line-length = 119
-per-file-ignores =
-    local/*
-    MonkTrader/config/project_template/*
 
 [isort]
 combine_as_imports = true
```

Also this diff against master:

```diff
--- a/setup.cfg
+++ b/setup.cfg
@@ -2,8 +2,7 @@
 ignore = W504
 max-line-length = 119
 per-file-ignores =
-    local/*
-    MonkTrader/config/project_template/*
+    MonkTrader/config/project_template/*: E225
 
 [isort]
 combine_as_imports = true
```

I haven't improved the error message, just made capitalized filenames not-an-error -- your original format is still incorrect

**Comment by asottile** [comment]
In GitLab by @zsluedem on Jan 29, 2019, 23:40

@asottile oh. Sorry . It works fine. I forgot to add the `:E225`

**Comment by asottile** [comment]
In GitLab by @asottile on Jan 29, 2019, 23:42

sweet, I'll make this into 3.7.1 I guess (going to see if I can make the error message better quickly if not I'll just cut it here) -- sorry for the inconvenience again

**Comment by asottile** [comment]
In GitLab by @zsluedem on Jan 29, 2019, 23:43

@asottile :thumbsup: No worry. Glad to help.

**Comment by asottile** [comment]
In GitLab by @asottile on Jan 29, 2019, 23:49

going to punt on improving the messaging here, it looks like other configuration parsing errors are stacktraces right now anyway.  I'll make a followup issue for that

**Comment by asottile** [comment]
In GitLab by @asottile on Jan 30, 2019, 24:09

3.7.1 has the fix for this -- thanks again for the issue!
