### ISSUE TITLE
Commandline parsing errors result in stacktraces

### ISSUE THREAD

**Issue by asottile** [PyCQA/flake8#288]
In GitLab by @asottile on Jan 29, 2019, 23:53

*Please describe how you installed Flake8*

```
$ pip install -e .
```

```json
{
  "dependencies": [
    {
      "dependency": "entrypoints",
      "version": "0.3"
    }
  ],
  "platform": {
    "python_implementation": "CPython",
    "python_version": "3.6.7",
    "system": "Linux"
  },
  "plugins": [
    {
      "is_local": false,
      "plugin": "mccabe",
      "version": "0.6.1"
    },
    {
      "is_local": false,
      "plugin": "pycodestyle",
      "version": "2.5.0"
    },
    {
      "is_local": false,
      "plugin": "pyflakes",
      "version": "2.1.0"
    }
  ],
  "version": "3.7.0"
}
```

*Please describe the problem or feature*

malformed `setup.cfg` values can trigger a stacktrace.

For instance:

```ini
[flake8]
max-complexity = potato
```

```
$ flake8 src
Traceback (most recent call last):
  File "/tmp/flake8/venv/bin/flake8", line 11, in <module>
    load_entry_point('flake8', 'console_scripts', 'flake8')()
  File "/tmp/flake8/src/flake8/main/cli.py", line 18, in main
    app.run(argv)
  File "/tmp/flake8/src/flake8/main/application.py", line 392, in run
    self._run(argv)
  File "/tmp/flake8/src/flake8/main/application.py", line 379, in _run
    self.initialize(argv)
  File "/tmp/flake8/src/flake8/main/application.py", line 364, in initialize
    self.parse_configuration_and_cli(argv)
  File "/tmp/flake8/src/flake8/main/application.py", line 217, in parse_configuration_and_cli
    self.option_manager, self.config_finder, argv
  File "/tmp/flake8/src/flake8/options/aggregator.py", line 45, in aggregate_options
    original_values.config, original_values.isolated
  File "/tmp/flake8/src/flake8/options/config.py", line 327, in parse
    return self.merge_user_and_local_config()
  File "/tmp/flake8/src/flake8/options/config.py", line 286, in merge_user_and_local_config
    config = self.parse_local_config()
  File "/tmp/flake8/src/flake8/options/config.py", line 249, in parse_local_config
    return self._parse_config(config)
  File "/tmp/flake8/src/flake8/options/config.py", line 226, in _parse_config
    value = method(self.program_name, option_name)
  File "/usr/lib/python3.6/configparser.py", line 819, in getint
    fallback=fallback, **kwargs)
  File "/usr/lib/python3.6/configparser.py", line 809, in _get_conv
    **kwargs)
  File "/usr/lib/python3.6/configparser.py", line 803, in _get
    return conv(self.get(section, option, **kwargs))
ValueError: invalid literal for int() with base 10: 'potato'
```

or

```ini
[flake8]
per-file-ignores =
    potato
```

```
$ flake8 src
Traceback (most recent call last):
  File "/tmp/flake8/venv/bin/flake8", line 11, in <module>
    load_entry_point('flake8', 'console_scripts', 'flake8')()
  File "/tmp/flake8/src/flake8/main/cli.py", line 18, in main
    app.run(argv)
  File "/tmp/flake8/src/flake8/main/application.py", line 392, in run
    self._run(argv)
  File "/tmp/flake8/src/flake8/main/application.py", line 379, in _run
    self.initialize(argv)
  File "/tmp/flake8/src/flake8/main/application.py", line 366, in initialize
    self.make_guide()
  File "/tmp/flake8/src/flake8/main/application.py", line 268, in make_guide
    self.options, self.formatter
  File "/tmp/flake8/src/flake8/style_guide.py", line 345, in __init__
    self.populate_style_guides_with(options),
  File "/tmp/flake8/src/flake8/style_guide.py", line 362, in populate_style_guides_with
    options.per_file_ignores
  File "/tmp/flake8/src/flake8/utils.py", line 126, in parse_files_to_codes_mapping
    raise ValueError("Unexpected token: {}".format(token))
ValueError: Unexpected token: Token(tp='eof', src='')
```

**Comment by asottile** [comment]
In GitLab by @barbossa on Jan 30, 2019, 01:19

I've encountered with the same issue today

```Traceback (most recent call last):
  File "/home/vladimir/projects/test_project/venv/bin/flake8", line 11, in <module>
    sys.exit(main())
  File "/home/vladimir/projects/test_project/venv/lib/python3.5/site-packages/flake8/main/cli.py", line 18, in main
    app.run(argv)
  File "/home/vladimir/projects/test_project/venv/lib/python3.5/site-packages/flake8/main/application.py", line 392, in run
    self._run(argv)
  File "/home/vladimir/projects/test_project/venv/lib/python3.5/site-packages/flake8/main/application.py", line 379, in _run
    self.initialize(argv)
  File "/home/vladimir/projects/test_project/venv/lib/python3.5/site-packages/flake8/main/application.py", line 366, in initialize
    self.make_guide()
  File "/home/vladimir/projects/test_project/venv/lib/python3.5/site-packages/flake8/main/application.py", line 268, in make_guide
    self.options, self.formatter
  File "/home/vladimir/projects/test_project/venv/lib/python3.5/site-packages/flake8/style_guide.py", line 345, in __init__
    self.populate_style_guides_with(options),
  File "/home/vladimir/projects/test_project/venv/lib/python3.5/site-packages/flake8/style_guide.py", line 362, in populate_style_guides_with
    options.per_file_ignores
  File "/home/vladimir/projects/test_project/venv/lib/python3.5/site-packages/flake8/utils.py", line 126, in parse_files_to_codes_mapping
    raise ValueError("Unexpected token: {}".format(token))
ValueError: Unexpected token: Token(tp='eof', src='')
```

**Comment by asottile** [comment]
In GitLab by @asottile on Jan 30, 2019, 01:54

for those seeing the latter error message, this is telling you that the `per-file-ignores` setting you've configured is incorrectly formatted.  Prior to flake8 3.7.0 this field was not read (unless you were using the `flake8-per-file-ignores` plugin).

Here's a description (slightly outdated, not sure why RTD isn't updating CC @sigmavirus24) of how to format that option: http://flake8.pycqa.org/en/latest/user/options.html#cmdoption-flake8-per-file-ignores

Notably it looks like:

```
per-file-ignores
    filename:C123,A123
    glob/*:C123
    file1, file2, file3 : E1, F2
    file4 file5: E1 E2
```

(ignore globs mapping to codes, codes and filenames may be whitespace or comma delimited)

**Comment by asottile** [comment]
In GitLab by @sigmavirus24 on Jan 30, 2019, 13:31

The docs should be updated now

**Comment by asottile** [comment]
In GitLab by @asottile on Jan 30, 2019, 19:35

mentioned in merge request !298

**Comment by asottile** [comment]
In GitLab by @asottile on Jan 30, 2019, 19:38

mentioned in commit 9269987ccaaae4b6c5fe1295125e36a711525664

**Comment by asottile** [comment]
In GitLab by @asottile on Jan 30, 2019, 19:38

closed via merge request !298

**Comment by asottile** [comment]
In GitLab by @asottile on Jan 30, 2019, 19:58

I've improved the error message here in 3.7.3  Here's what it looks like now:

```
$ flake8 src
There was a critical error during execution of Flake8:
Expected `per-file-ignores` to be a mapping from file exclude patterns to ignore codes.

Configured `per-file-ignores` setting:

    foo/*
    bar/*
```
