### ISSUE TITLE
Problem with doctests

### ISSUE THREAD

**Issue by asottile** [PyCQA/flake8#289]
In GitLab by @michelts on Jan 30, 2019, 06:01

I've installed flake8

Example:

```
$ mkvirtualenv flake8_verification
$ pip install flake8==3.7.1
```

*Please provide the exact, unmodified output of `flake8 --bug-report`*

```
{
  "dependencies": [
    {
      "dependency": "entrypoints",
      "version": "0.3"
    }
  ],
  "platform": {
    "python_implementation": "CPython",
    "python_version": "3.6.3",
    "system": "Linux"
  },
  "plugins": [
    {
      "is_local": false,
      "plugin": "mccabe",
      "version": "0.6.1"
    },
    {
      "is_local": false,
      "plugin": "pycodestyle",
      "version": "2.5.0"
    },
    {
      "is_local": false,
      "plugin": "pyflakes",
      "version": "2.1.0"
    }
  ],
  "version": "3.7.0"
}
```

*Please describe the problem or feature*

I'm trying to parse a docstring that is valid in the flake8===3.6.0. See a code sample that fails:

```
from django.db import models
from django.dispatch import receiver
from django.utils.translation import ugettext_lazy as _


class Profile(models.Model):
    document = models.CharField(_('Document'))


@receiver(models.signals.pre_save, sender=Profile)
def normalize_cpf_number(sender, instance, **kwargs):
    """
    Make sure document has only digits.

    >>> instance = Profile(document='123.456.789-00')
    >>> normalize_cpf_number(sender=Profile, instance=instance)
    >>> instance.document
    '12345678900'
    """
    instance.document = ''.join(
        [c for c in instance.document if c.isdigit()])
```

The output is:

```
multiprocessing.pool.RemoteTraceback: 
"""
Traceback (most recent call last):
  File ".../lib/python3.6/site-packages/flake8/checker.py", line 443, in run_check
    return plugin["plugin"](**arguments)
  File ".../lib/python3.6/site-packages/flake8/plugins/pyflakes.py", line 106, in __init__
    file_tokens=file_tokens,
  File ".../lib/python3.6/site-packages/pyflakes/checker.py", line 665, in __init__
    self.runDeferred(self._deferredFunctions)
  File ".../lib/python3.6/site-packages/pyflakes/checker.py", line 702, in runDeferred
    handler()
  File ".../lib/python3.6/site-packages/pyflakes/checker.py", line 1410, in <lambda>
    self.deferFunction(lambda: self.handleDoctests(node))
  File ".../lib/python3.6/site-packages/pyflakes/checker.py", line 1148, in handleDoctests
    self.addBinding(None, Builtin('_'))
  File ".../lib/python3.6/site-packages/pyflakes/checker.py", line 870, in addBinding
    parent_stmt = self.getParent(value.source)
  File ".../lib/python3.6/site-packages/pyflakes/checker.py", line 808, in getParent
    node = node.parent
AttributeError: 'NoneType' object has no attribute 'parent'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.6/multiprocessing/pool.py", line 119, in worker
    result = (True, func(*args, **kwds))
  File ".../lib/python3.6/site-packages/flake8/checker.py", line 677, in _run_checks
    return checker.run_checks()
  File ".../lib/python3.6/site-packages/flake8/checker.py", line 616, in run_checks
    self.run_ast_checks()
  File ".../lib/python3.6/site-packages/flake8/checker.py", line 505, in run_ast_checks
    checker = self.run_check(plugin, tree=ast)
  File ".../lib/python3.6/site-packages/flake8/checker.py", line 449, in run_check
    plugin=plugin, excetion=all_exc
  File ".../lib/python3.6/site-packages/flake8/exceptions.py", line 86, in __init__
    self.original_exception = kwargs.pop("exception")
KeyError: 'exception'
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File ".../bin/flake8", line 11, in <module>
    sys.exit(main())
  File ".../lib/python3.6/site-packages/flake8/main/cli.py", line 18, in main
    app.run(argv)
  File ".../lib/python3.6/site-packages/flake8/main/application.py", line 392, in run
    self._run(argv)
  File ".../lib/python3.6/site-packages/flake8/main/application.py", line 380, in _run
    self.run_checks()
  File ".../lib/python3.6/site-packages/flake8/main/application.py", line 299, in run_checks
    self.file_checker_manager.run()
  File ".../lib/python3.6/site-packages/flake8/checker.py", line 330, in run
    self.run_parallel()
  File ".../lib/python3.6/site-packages/flake8/checker.py", line 294, in run_parallel
    for ret in pool_map:
  File "/usr/lib/python3.6/multiprocessing/pool.py", line 761, in next
    raise value
KeyError: 'exception'
```

If I fix the flake8/checker.py:449 typo (excetion term), the error still happens:

```
Exception in thread Thread-3:
Traceback (most recent call last):
  File "/usr/lib/python3.6/threading.py", line 916, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.6/threading.py", line 864, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/lib/python3.6/multiprocessing/pool.py", line 489, in _handle_results
    task = get()
  File "/usr/lib/python3.6/multiprocessing/connection.py", line 251, in recv
    return _ForkingPickler.loads(buf.getbuffer())
  File ".../lib/python3.6/site-packages/flake8/exceptions.py", line 86, in __init__
    self.original_exception = kwargs.pop("exception")
KeyError: 'exception'
```

The cursor wouldn't be released in the case.

If I strip the `ugettext_lazy` underscore alias, then flake8 is able to parse the doctest correctly:

```
from django.db import models
from django.dispatch import receiver
from django.utils.translation import ugettext_lazy  # do not use _


class Profile(models.Model):
    document = models.CharField(ugettext_lazy('Document'))  # do not use _


@receiver(models.signals.pre_save, sender=Profile)
def normalize_cpf_number(sender, instance, **kwargs):
    """
    Make sure document has only digits.

    >>> instance = Profile(document='123.456.789-00')
    >>> normalize_cpf_number(sender=Profile, instance=instance)
    >>> instance.document
    '12345678900'
    """
    instance.document = ''.join(
        [c for c in instance.document if c.isdigit()])
```

But this is happening only in combination with doctests, without the `--doctest` flag, the rest of the python code are parsed without any problem.

**Comment by asottile** [comment]
In GitLab by @asottile on Jan 30, 2019, 08:23

I've opened https://github.com/PyCQA/pyflakes/issues/421

flake8 is a framework and pyflakes is one of the tools that's integrated though this issue stems directly from the plugin and not from the framework

Thanks for the issue!  I'd suggest following the one I created ^^^

**Comment by asottile** [comment]
In GitLab by @asottile on Jan 30, 2019, 08:23

closed

**Comment by asottile** [comment]
In GitLab by @michelts on Jan 30, 2019, 08:35

My fault @asottile :) I will follow pyflakes issue you've created. Thanks!

**Comment by asottile** [comment]
In GitLab by @asottile on Jan 30, 2019, 08:37

No problem! This one is pretty sneaky to try and reproduce with pyflakes since you need to know about the `PYFLAKES_DOCTESTS` environment variable (which, imo, is a bit of a hack!)
