### ISSUE TITLE
Optparse Conflict for custom options when running flake8 as a module

### ISSUE THREAD

**Issue by asottile** [PyCQA/flake8#338]
In GitLab by @sco11 on Jan 18, 2020, 14:06

*Please describe how you installed Flake8*

Installed in a fresh Python 3.8.1 virtualenv using the following `setup.py` and `pip install -e .`

```py
from setuptools import setup


setup(
    name="flake8-test",
    version="1.0.0",
    description="Flake8 test",
    author="hello",
    entry_points={
        "flake8.extension": ["TST = flake8_test:TestChecker"]
    },
    install_requires=["flake8"],
)
```

```bash
$ pip list
Package     Version Location
----------- ------- --------
entrypoints 0.3
flake8      3.7.9
flake8-test 1.0.0   c:\test
mccabe      0.6.1
pip         19.3.1
pycodestyle 2.5.0
pyflakes    2.1.1
setuptools  45.0.0
wheel       0.33.6
$ flake8 --version
3.7.9 (flake8-test: 1.0.0, mccabe: 0.6.1, pycodestyle: 2.5.0, pyflakes: 2.1.1) CPython 3.8.1 on Windows
```

*Please provide the exact, unmodified output of `flake8 --bug-report`*
```bash
$ flake8 --bug-report
{
  "dependencies": [
    {
      "dependency": "entrypoints",
      "version": "0.3"
    }
  ],
  "platform": {
    "python_implementation": "CPython",
    "python_version": "3.8.1",
    "system": "Windows"
  },
  "plugins": [
    {
      "is_local": false,
      "plugin": "flake8-test",
      "version": "1.0.0"
    },
    {
      "is_local": false,
      "plugin": "mccabe",
      "version": "0.6.1"
    },
    {
      "is_local": false,
      "plugin": "pycodestyle",
      "version": "2.5.0"
    },
    {
      "is_local": false,
      "plugin": "pyflakes",
      "version": "2.1.1"
    }
  ],
  "version": "3.7.9"
}
```

*Please describe the problem or feature*
When registering a custom configuration option, flake8 raises an error, via optparse, when invoked as a module (e.g. `python -m flake8`).

Using the following skeleton:

```py
from flake8.options.manager import OptionManager


class TestChecker:
    name = "flake8-test"
    version = "1.0.0"

    def __init__(self, tree, lines):
        self.lines = lines
        self.tree = tree

    def run(self):
        yield (1, 1, "This is a test", TestChecker)

    @classmethod
    def add_options(cls, parser) -> None:
        """Add custom configuration option(s) to flake8."""
        parser.add_option(
            "--test-config-option",
            default=False,
            action="store_true",
            parse_from_config=True,
            help="This is a test"
        )

    @classmethod
    def parse_options(cls, options) -> None:
        """Parse the custom configuration options given to flake8."""
        cls.test_config_option = options.test_config_option
```

I recieve the following:
```bash
$ python -m flake8 setup.py
Traceback (most recent call last):
  File "C:\Users\User\AppData\Local\Programs\Python\Python38\Lib\runpy.py", line 193, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\User\AppData\Local\Programs\Python\Python38\Lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "C:\test\.venv\lib\site-packages\flake8\__main__.py", line 4, in <module>
    cli.main()
  File "C:\test\.venv\lib\site-packages\flake8\main\cli.py", line 18, in main
    app.run(argv)
  File "C:\test\.venv\lib\site-packages\flake8\main\application.py", line 393, in run
    self._run(argv)
  File "C:\test\.venv\lib\site-packages\flake8\main\application.py", line 380, in _run
    self.initialize(argv)
  File "C:\test\.venv\lib\site-packages\flake8\main\application.py", line 364, in initialize
    self.register_plugin_options()
  File "C:\test\.venv\lib\site-packages\flake8\main\application.py", line 205, in register_plugin_options
    self.check_plugins.register_options(self.option_manager)
  File "C:\test\.venv\lib\site-packages\flake8\plugins\manager.py", line 489, in register_options
    list(self.manager.map(register_and_enable))
  File "C:\test\.venv\lib\site-packages\flake8\plugins\manager.py", line 297, in map
    yield func(self.plugins[name], *args, **kwargs)
  File "C:\test\.venv\lib\site-packages\flake8\plugins\manager.py", line 485, in register_and_enable
    call_register_options(plugin)
  File "C:\test\.venv\lib\site-packages\flake8\plugins\manager.py", line 397, in generated_function
    return method(optmanager, *args, **kwargs)
  File "C:\test\.venv\lib\site-packages\flake8\plugins\manager.py", line 216, in register_options
    add_options(optmanager)
  File "C:\test\flake8_test.py", line 18, in add_options
    parser.add_option(
  File "C:\test\.venv\lib\site-packages\flake8\options\manager.py", line 231, in add_option
    self.parser.add_option(option.to_optparse())
  File "C:\Users\User\AppData\Local\Programs\Python\Python38\Lib\optparse.py", line 1008, in add_option
    self._check_conflict(option)
  File "C:\Users\User\AppData\Local\Programs\Python\Python38\Lib\optparse.py", line 980, in _check_conflict
    raise OptionConflictError(
optparse.OptionConflictError: option --test-config-option: conflicting option string(s): --test-config-option
```

While `flake8` behaves as expected:

```bash
$ flake8 setup.py
setup.py:13:2: W292 no newline at end of file
```

For broader context, this is causing CI for my plugin ([flake8-annotations](https://github.com/python-discord/flake8-annotations/tree/dev-next)) to fail ([Azure](https://dev.azure.com/python-discord/Python%20Discord/_build/results?buildId=5198&view=results)) since we're invoking flake8 as a module rather than from the defined entry point.

While we should be able to resolve this by adjusting the Azure config to the flake8 invocation that works correctly, is this a bug or something that's working as intended?

**Comment by asottile** [comment]
In GitLab by @sco11 on Jan 18, 2020, 14:14

changed title from **Optparse Conflict when running flake8 as a module** to **Optparse Conflict {+for custom options +}when running flake8 as a module**

**Comment by asottile** [comment]
In GitLab by @asottile on Jan 18, 2020, 14:14

This appears to be fixed on master already, though I don't know why :)

my guess would be this commit: d3c95f00d0ac14adcceb423173ff7106aa42d116 (verified by reverting it)

**Comment by asottile** [comment]
In GitLab by @asottile on Jan 18, 2020, 14:14

closed

**Comment by asottile** [comment]
In GitLab by @asottile on Jan 18, 2020, 14:17

which probably means there is a bug in the `entrypoints` library (which we moved away from) -- I'd suggest reporting there

**Comment by asottile** [comment]
In GitLab by @sco11 on Jan 18, 2020, 14:24

Thanks! Can also confirm that this issue disappears with flake8 installed from master rather than PyPI.

Will adjust our CI accordingly & report upstream.
