### ISSUE TITLE
No module named enum in 2.7

### ISSUE THREAD

**Issue by asottile** [PyCQA/flake8#347]
In GitLab by @stephanebruckert on Feb 22, 2020, 03:44

With python2.7, this currently breaks:

    pip install flake8

with `No module named enum`:

```
Collecting flake8
  Downloading flake8-3.7.9-py2.py3-none-any.whl (69 kB)
Collecting entrypoints<0.4.0,>=0.3.0
  Downloading entrypoints-0.3-py2.py3-none-any.whl (11 kB)
Downloading configparser-4.0.2-py2.py3-none-any.whl (22 kB)
Collecting pyflakes<2.2.0,>=2.1.0
  Downloading pyflakes-2.1.1-py2.py3-none-any.whl (59 kB)
Collecting functools32; python_version < "3.2"
  Downloading functools32-3.2.3-2.tar.gz (31 kB)
Collecting enum34; python_version < "3.4"
  Downloading enum34-1.1.8-py2-none-any.whl (1.5 kB)
Collecting mccabe<0.7.0,>=0.6.0
  Downloading mccabe-0.6.1-py2.py3-none-any.whl (8.6 kB)
Collecting typing; python_version < "3.5"
  Downloading typing-3.7.4.1-py2-none-any.whl (26 kB)
Collecting pycodestyle<2.6.0,>=2.5.0
  Downloading pycodestyle-2.5.0-py2.py3-none-any.whl (51 kB)
Installing collected packages: configparser, entrypoints, pyflakes, functools32, enum34, mccabe, typing, pycodestyle, flake8
    Running setup.py install for functools32: started
    Running setup.py install for functools32: finished with status 'done'
Successfully installed configparser-4.0.2 entrypoints-0.3 enum34-1.1.8 flake8-3.7.9 functools32-3.2.3.post2 mccabe-0.6.1 pycodestyle-2.5.0 pyflakes-2.1.1 typing-3.7.4.1
Traceback (most recent call last):
  File "/opt/hostedtoolcache/Python/2.7.17/x64/bin/flake8", line 5, in <module>
    from flake8.main.cli import main
  File "/opt/hostedtoolcache/Python/2.7.17/x64/lib/python2.7/site-packages/flake8/main/cli.py", line 4, in <module>
    from flake8.main import application
  File "/opt/hostedtoolcache/Python/2.7.17/x64/lib/python2.7/site-packages/flake8/main/application.py", line 14, in <module>
    from flake8 import style_guide
  File "/opt/hostedtoolcache/Python/2.7.17/x64/lib/python2.7/site-packages/flake8/style_guide.py", line 5, in <module>
    import enum
ImportError: No module named enum
```

because of https://bitbucket.org/stoneleaf/enum34/issues/27/enum34-118-broken

A quick fix is to pin enum34 to 1.1.6

    pip install -Iv enum34==1.1.6

**Comment by asottile** [comment]
In GitLab by @asottile on Feb 22, 2020, 06:59

unfortunate, but nothing we can really do about it here -- thanks for the report, hopefully they fix their packaging

**Comment by asottile** [comment]
In GitLab by @asottile on Feb 22, 2020, 06:59

closed
