### ISSUE TITLE
mock can't override sys.stdout.flush on Python 2.7, mock sys.stdout instead - [closed]

### ISSUE THREAD

**Issue by asottile** [PyCQA/flake8#416]
In GitLab by @tamentis on Dec 25, 2015, 16:00

_Merges master -> master_

The test suite currently fails on Python 2.7 and probably below due to mock failing to override sys.stdout.flush.  This patch mocks sys.stdout instead.

**Comment by asottile** [comment]
In GitLab by @sigmavirus24 on Dec 25, 2015, 16:01

:white_check_mark: Jenkins Build Success

Results available at: [Jenkins](http://ci.sigmavir.us/job/flake8/271/)

**Comment by asottile** [comment]
In GitLab by @sigmavirus24 on Dec 25, 2015, 16:03

Build triggered.

**Comment by asottile** [comment]
In GitLab by @sigmavirus24 on Dec 25, 2015, 16:04

Build finished.  Tests PASSED.
Build results available at: [http://ci.sigmavir.us/job/flake8/272/](http://ci.sigmavir.us/job/flake8/272/)

**Comment by asottile** [comment]
In GitLab by @sigmavirus24 on Dec 27, 2015, 20:44

Hi @tamentis 

There's no issue for this so could you please describe the following:

1. What version of the tests you're seeing this problem with
1. What operating system you're using
1. The exact output of `python --version`
1. How you're running the tests
1. The list output of `pip freeze` on the environment in which you're testing (if you're using tox, then you can do `.tox/py27/bin/pip freeze` for example)
1. The exact output of the failure you're seeing

I cannot reproduce this but I would like to try.

**Comment by asottile** [comment]
In GitLab by @tamentis on Dec 28, 2015, 04:13

1. 2.5.1 and master
2. Linux, OpenBSD and OS X
3. Respectively Python 2.7.3, Python 2.7.11 and Python 2.7.10
4. python -m unittest discover

5.
```
flake8==2.5.1
funcsigs==0.4
mccabe==0.3.1
mock==1.3.0
pbr==1.8.1
pep8==1.5.7
pyflakes==1.0.0
six==1.10.0
wheel==0.24.0
```

6.
```
(venv)/tmp/flake8-2.5.1$ python -m unittest discover
......................E..stdin:1:1: F821 undefined name 'notathing'
..Traceback (most recent call last):
.  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/multiprocessing/queues.py", line 268, in _feed
..Traceback (most recent call last):
.....  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/multiprocessing/queues.py", line 268, in _feed
.........
======================================================================
ERROR: test_jobs (flake8.tests.test_integration.IntegrationTestCase)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/private/tmp/flake8-2.5.1/flake8/tests/test_integration.py", line 56, in test_jobs
    self._job_tester(2)
  File "/private/tmp/flake8-2.5.1/flake8/tests/test_integration.py", line 43, in _job_tester
    with mock.patch('sys.stdout.flush') as mocked:
  File "/private/tmp/venv/lib/python2.7/site-packages/mock/mock.py", line 1460, in __enter__
    setattr(self.target, self.attribute, new_attr)
AttributeError: 'file' object attribute 'flush' is read-only

----------------------------------------------------------------------
Ran 44 tests in 0.126s

FAILED (errors=1)
    send(obj)
    send(obj)
IOError: [Errno 32] Broken pipe
IOError: [Errno 32] Broken pipe
```

**Comment by asottile** [comment]
In GitLab by @tamentis on Dec 28, 2015, 04:44

My fault, I wasn't using the proper testing framework. I tried with Nose and it works fine.  Nose is wrapping the sys.stdout/err objects which is why mock is able to replace their functions.
