### ISSUE TITLE
Value I/O error while working in a virtualenv

### ISSUE THREAD

**Issue by asottile** [PyCQA/flake8#447]
In GitLab by @shipperizer on Oct 13, 2015, 24:50

Hi, while using linter-flake8 in Atom i stepped into this: https://github.com/AtomLinter/linter-flake8/issues/86

basically all my code is supposed to be running inside a virtualenv, and flake8 was installed in it (and globally as well), 
```bash
[shipperizer@archer user-service]$ cat /home/shipperizer/development/portal/manage.py | flake8 -
Traceback (most recent call last):
  File "/usr/bin/flake8", line 11, in <module>
    sys.exit(main())
  File "/usr/lib/python3.5/site-packages/flake8/main.py", line 33, in main
    report = flake8_style.check_files()
  File "/usr/lib/python3.5/site-packages/pep8.py", line 1672, in check_files
    runner(path)
  File "/usr/lib/python3.5/site-packages/flake8/engine.py", line 95, in input_file
    return fchecker.check_all(expected=expected, line_offset=line_offset)
  File "/usr/lib/python3.5/site-packages/pep8.py", line 1412, in check_all
    self.check_ast()
  File "/usr/lib/python3.5/site-packages/pep8.py", line 1359, in check_ast
    for lineno, offset, text, check in checker.run():
  File "/usr/lib/python3.5/site-packages/flake8_pep257.py", line 94, in run
    filename, source = load_file(self.filename)
  File "/usr/lib/python3.5/site-packages/flake8_pep257.py", line 29, in load_file
    return 'stdin', pep8.stdin_get_value()
  File "/usr/lib/python3.5/site-packages/pep8.py", line 1060, in stdin_get_value
    return TextIOWrapper(sys.stdin.buffer, errors='ignore').read()
ValueError: I/O operation on closed file
```
but inside a virtualenv I get:
```bash
[shipperizer@archer portal]$ source env/bin/activate
(env) [shipperizer@archer portal]$ cat /home/shipperizer/development/portal/manage.py | flake8 -
stdin:23:80: E501 line too long (91 > 79 characters)
```
is it the normal behaviour?

**Comment by asottile** [comment]
In GitLab by @sigmavirus24 on Oct 13, 2015, 07:01

Please look closely at your stack trace: This is coming from the `flake8-pep257` plugin that you're using.

```
  File "/usr/lib/python3.5/site-packages/flake8_pep257.py", line 94, in run
    filename, source = load_file(self.filename)
  File "/usr/lib/python3.5/site-packages/flake8_pep257.py", line 29, in load_file
    return 'stdin', pep8.stdin_get_value()
```

We can't do very much to help you when plugins are broken.

I suspect that your virtual environment doesn't have that plugin installed and that's why this works.
