### ISSUE TITLE
List index out of range on scopeStack

### ISSUE THREAD

**Issue by asottile** [PyCQA/flake8#451]
In GitLab by @gozdal on Oct 29, 2015, 08:11

I am using flake8 on some Python code and after upgrading to 2.5.0 from 2.4.1 I started getting this error:

```
Traceback (most recent call last):
  File "/home/gozdalik/.virtualenvs/starfish/bin/flake8", line 11, in <module>
    sys.exit(main())
  File "/home/gozdalik/.virtualenvs/starfish/local/lib/python2.7/site-packages/flake8/main.py", line 33, in main
    report = flake8_style.check_files()
  File "/home/gozdalik/.virtualenvs/starfish/local/lib/python2.7/site-packages/flake8/engine.py", line 176, in check_files
    return self._retry_serial(self._styleguide.check_files, paths=paths)
  File "/home/gozdalik/.virtualenvs/starfish/local/lib/python2.7/site-packages/flake8/engine.py", line 167, in _retry_serial
    return func(*args, **kwargs)
  File "/home/gozdalik/.virtualenvs/starfish/local/lib/python2.7/site-packages/pep8.py", line 1670, in check_files
    self.input_dir(path)
  File "/home/gozdalik/.virtualenvs/starfish/local/lib/python2.7/site-packages/pep8.py", line 1706, in input_dir
    runner(os.path.join(root, filename))
  File "/home/gozdalik/.virtualenvs/starfish/local/lib/python2.7/site-packages/flake8/engine.py", line 121, in input_file
    return fchecker.check_all(expected=expected, line_offset=line_offset)
  File "/home/gozdalik/.virtualenvs/starfish/local/lib/python2.7/site-packages/pep8.py", line 1412, in check_all
    self.check_ast()
  File "/home/gozdalik/.virtualenvs/starfish/local/lib/python2.7/site-packages/pep8.py", line 1358, in check_ast
    checker = cls(tree, self.filename)
  File "/home/gozdalik/.virtualenvs/starfish/local/lib/python2.7/site-packages/flake8/_pyflakes.py", line 43, in __init__
    withDoctest=self.withDoctest)
  File "/home/gozdalik/.virtualenvs/starfish/local/lib/python2.7/site-packages/pyflakes/checker.py", line 294, in __init__
    self.handleChildren(tree)
  File "/home/gozdalik/.virtualenvs/starfish/local/lib/python2.7/site-packages/pyflakes/checker.py", line 567, in handleChildren
    self.handleNode(node, tree)
  File "/home/gozdalik/.virtualenvs/starfish/local/lib/python2.7/site-packages/pyflakes/checker.py", line 609, in handleNode
    handler(node)
  File "/home/gozdalik/.virtualenvs/starfish/local/lib/python2.7/site-packages/pyflakes/checker.py", line 686, in GLOBAL
    global_scope = self.scopeStack[global_scope_index]
IndexError: list index out of range
```

The code I'm running flake8 on is proprietary so unfortunately I can't share it. Any idea how to help debugging this issue?

**Comment by asottile** [comment]
In GitLab by @sigmavirus24 on Oct 29, 2015, 09:41

This is a bug in pyflakes. Please report it at https://github.com/pyflakes/pyflakes/issues
