### ISSUE TITLE
flake8 crashes on class with unterminated docstring

### ISSUE THREAD

**Issue by asottile** [PyCQA/flake8#464]
In GitLab by @iivvoo on Dec 15, 2015, 08:56

Tested on 2.4.1, 2.5.0 and 2.5.1

sample.py:

    class Foo(object):
        """

Running flake8 on it:

    Traceback (most recent call last):
      File "/home/ivo/Atom/bin/flake8", line 11, in <module>
        sys.exit(main())
      File "/home/ivo/Atom/local/lib/python2.7/site-packages/flake8/main.py", line 33, in main
        report = flake8_style.check_files()
      File "/home/ivo/Atom/local/lib/python2.7/site-packages/flake8/engine.py",   line 180, in check_files
        return self._retry_serial(self._styleguide.check_files, paths=paths)
      File "/home/ivo/Atom/local/lib/python2.7/site-packages/flake8/engine.py", line 171, in _retry_serial
        return func(*args, **kwargs)
      File "/home/ivo/Atom/local/lib/python2.7/site-packages/pep8.py", line 1672, in check_files
        runner(path)
      File "/home/ivo/Atom/local/lib/python2.7/site-packages/flake8/engine.py", line 125, in input_file
        return fchecker.check_all(expected=expected, line_offset=line_offset)
      File "/home/ivo/Atom/local/lib/python2.7/site-packages/pep8.py", line 1456, in check_all
        self.check_logical()
      File "/home/ivo/Atom/local/lib/python2.7/site-packages/pep8.py", line 1328, in check_logical
        (start_row, start_col) = mapping[0][1]
    TypeError: 'NoneType' object has no attribute '__getitem__'

**Comment by asottile** [comment]
In GitLab by @iivvoo on Dec 15, 2015, 09:05

Just noticed this is a pep8 issue. Updating pep8 to 1.6.2 solves the problem, but flake8 seems to explicitly exclude that version:

https://gitlab.com/pycqa/flake8/blob/master/setup.py#L53

**Comment by asottile** [comment]
In GitLab by @sigmavirus24 on Dec 15, 2015, 09:12

Please read the FAQ in the README. pep8 is broken in many other ways that make it not suitable for use with Flake8. We will not be upgrading pep8 until it a new version is fixed that solves the integration pain points with Flake8.
