### ISSUE TITLE
Missing 2.5.3 testing?

### ISSUE THREAD

**Issue by asottile** [PyCQA/flake8#475]
In GitLab by @doismellburning on Feb 11, 2016, 10:20

(If this isn't the desired medium for things like this, sorry, please let me know)

I just hit #119, saw the fix committed for it came with no test to reproduce the problem, and figured I'd try to help by adding a test to avoid regressions.

At this point I noticed that the existing tests did indeed catch it:

```
$ git co 2.5.3
Previous HEAD position was e2d6f33... Fix AttributeError referring to enabled_extensions
HEAD is now at 1845ec3... Bump version for 2.5.3 and update changes

$ tox -e py27

# Snip

======================================================================
ERROR: test_disables_extensions_that_are_not_selected (flake8.tests.test_engine.TestEngine)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/kristian/git/flake8/flake8/tests/test_engine.py", line 117, in test_disables_extensions_that_are_not_selected
    sg = engine.get_style_guide()
  File "/Users/kristian/git/flake8/flake8/engine.py", line 236, in get_style_guide
    _disable_extensions(kwargs['parser'], options)
  File "/Users/kristian/git/flake8/flake8/engine.py", line 219, in _disable_extensions
    enabled = set(_parse_multi_options(options.enabled_extensions))
AttributeError: Values instance has no attribute 'enabled_extensions'

# Snip
```

Did something happen with the testing for this release?
Is there any way I can help?
(I don't know much about GitLab except "the tools I'd immediately reach for are Travis/Circle and afaik they don't support it", so I don't know *how* I could help, but if I can somehow I'd like to!)

Cheers!

**Comment by asottile** [comment]
In GitLab by @sigmavirus24 on Feb 11, 2016, 10:28

Not really. We have a Jenkins instance running. Had I sent a PR here instead of just pushing everything I though I had completed last night, it would have caught it too. I was in a rush though purely because I've had a specific consumer on back about this bug for a while.
