### ISSUE TITLE
Error with Multiple Arguments to Flake8 Exetensions

### ISSUE THREAD

**Issue by asottile** [PyCQA/flake8#478]
In GitLab by @Miserlou on Feb 17, 2016, 09:20

Hey all! 

I've written a new Flake8 extension for metrics around per-line code density.

I have two metrics, so two arguments. However, I get an error from Flake8 engine now:

```
Traceback (most recent call last):
  File "/Users/rjones/null/superfart/env/bin/flake8", line 11, in <module>
    sys.exit(main())
  File "/Users/rjones/null/superfart/env/lib/python2.7/site-packages/flake8/main.py", line 33, in main
    report = flake8_style.check_files()
  File "/Users/rjones/null/superfart/env/lib/python2.7/site-packages/flake8/engine.py", line 181, in check_files
    return self._retry_serial(self._styleguide.check_files, paths=paths)
  File "/Users/rjones/null/superfart/env/lib/python2.7/site-packages/flake8/engine.py", line 172, in _retry_serial
    return func(*args, **kwargs)
  File "/Users/rjones/null/superfart/env/lib/python2.7/site-packages/pep8.py", line 1840, in check_files
    self.input_dir(path)
  File "/Users/rjones/null/superfart/env/lib/python2.7/site-packages/pep8.py", line 1876, in input_dir
    runner(os.path.join(root, filename))
  File "/Users/rjones/null/superfart/env/lib/python2.7/site-packages/flake8/engine.py", line 126, in input_file
    return fchecker.check_all(expected=expected, line_offset=line_offset)
  File "/Users/rjones/null/superfart/env/lib/python2.7/site-packages/pep8.py", line 1574, in check_all
    self.check_ast()
  File "/Users/rjones/null/superfart/env/lib/python2.7/site-packages/pep8.py", line 1522, in check_ast
    if not self.lines or not noqa(self.lines[lineno - 1]):
TypeError: unsupported operand type(s) for -: 'str' and 'int'
```

Any thoughts?

You can see the new extension here - I think it's pretty neat! https://github.com/Miserlou/JonesComplexity

(Also, how would I go about getting this included in the default flake8 distribution? It's really handy for identifying lines that should be refactored.)

**Comment by asottile** [comment]
In GitLab by @sigmavirus24 on Feb 17, 2016, 09:53

So I'm not sure what update you made but you do the following:

You [yield `line, 0, text, type(self)`](https://github.com/Miserlou/JonesComplexity/blob/783bef0418f2aa1f1624d8e6c39816b68ccaaa28/jones_complexity.py#L116) where `line` is returned from [a sorted and ordered dictionary](https://github.com/Miserlou/JonesComplexity/blob/783bef0418f2aa1f1624d8e6c39816b68ccaaa28/jones_complexity.py#L46) whose [keys are strings](https://github.com/Miserlou/JonesComplexity/blob/783bef0418f2aa1f1624d8e6c39816b68ccaaa28/jones_complexity.py#L39).

I suspect, then, that the `TypeError` you're seeing is related to pep8 *expecting* an integer and receiving a string instead.

As for getting that included in the default list of dependencies for flake8, we only do that for plugins that are widely used which right now are only pep8, mccabe, and pyflakes (to the best of my knowledge).

If there was a groundswell of users demanding something be a core dependency, we would reconsider then whether or not the plugin is sufficiently valuable and does not conflict with existing plugins in its error code naming.
