### ISSUE TITLE
Flake8 raises AttributeError: 'ExceptHandler' object has no attribute 'depth'

### ISSUE THREAD

**Issue by asottile** [PyCQA/flake8#482]
In GitLab by @sanand0 on Mar 15, 2016, 10:17

**Version information**

- Version of Python which has Flake8 installed: `Python 2.7.11 :: Anaconda 2.4.1 (64-bit)` on Windows
- How you installed Flake8 (e.g., `pip`, `apt`, `yum`, etc.): `pip install --upgrade flake8`
  - If you used pip, the version of pip installed: `pip 7.1.2 from D:\Anaconda\64\lib\site-packages (python 2.7)`
- Version of setuptools installed: `19.6.2`
- Version of Flake8 installed: `2.5.4`

**The problem**

When I run `flake8 test.py` on this `test.py` (a simplified version of my actual program):

    if True:
        try:
            x = 1
            x = 2 if x else 3
        except:
            pass

... I get the following error:

    Traceback (most recent call last):
      File "d:\anaconda\64\lib\runpy.py", line 162, in _run_module_as_main
        "__main__", fname, loader, pkg_name)
      File "d:\anaconda\64\lib\runpy.py", line 72, in _run_code
        exec code in run_globals
      File "D:\Anaconda\64\Scripts\flake8.exe\__main__.py", line 9, in <module>
      File "d:\anaconda\64\lib\site-packages\flake8\main.py", line 33, in main
        report = flake8_style.check_files()
      File "d:\anaconda\64\lib\site-packages\flake8\engine.py", line 181, in check_files
        return self._retry_serial(self._styleguide.check_files, paths=paths)
      File "d:\anaconda\64\lib\site-packages\flake8\engine.py", line 172, in _retry_serial
        return func(*args, **kwargs)
      File "d:\anaconda\64\lib\site-packages\pep8.py", line 1842, in check_files
        runner(path)
      File "d:\anaconda\64\lib\site-packages\flake8\engine.py", line 126, in input_file
        return fchecker.check_all(expected=expected, line_offset=line_offset)
      File "d:\anaconda\64\lib\site-packages\pep8.py", line 1574, in check_all
        self.check_ast()
      File "d:\anaconda\64\lib\site-packages\pep8.py", line 1520, in check_ast
        checker = cls(tree, self.filename)
      File "d:\anaconda\64\lib\site-packages\flake8\_pyflakes.py", line 62, in __init__
        withDoctest=withDoctest)
      File "d:\anaconda\64\lib\site-packages\pyflakes\checker.py", line 294, in __init__
        self.handleChildren(tree)
      File "d:\anaconda\64\lib\site-packages\pyflakes\checker.py", line 567, in handleChildren
        self.handleNode(node, tree)
      File "d:\anaconda\64\lib\site-packages\pyflakes\checker.py", line 609, in handleNode
        handler(node)
      File "d:\anaconda\64\lib\site-packages\pyflakes\checker.py", line 567, in handleChildren
        self.handleNode(node, tree)
      File "d:\anaconda\64\lib\site-packages\pyflakes\checker.py", line 609, in handleNode
        handler(node)
      File "d:\anaconda\64\lib\site-packages\pyflakes\checker.py", line 913, in TRY
        self.handleNode(child, node)
      File "d:\anaconda\64\lib\site-packages\pyflakes\checker.py", line 609, in handleNode
        handler(node)
      File "d:\anaconda\64\lib\site-packages\pyflakes\checker.py", line 567, in handleChildren
        self.handleNode(node, tree)
      File "d:\anaconda\64\lib\site-packages\pyflakes\checker.py", line 609, in handleNode
        handler(node)
      File "d:\anaconda\64\lib\site-packages\pyflakes\checker.py", line 732, in NAME
        self.handleNodeStore(node)
      File "d:\anaconda\64\lib\site-packages\pyflakes\checker.py", line 533, in handleNodeStore
        self.addBinding(node, binding)
      File "d:\anaconda\64\lib\site-packages\pyflakes\checker.py", line 431, in addBinding
        if existing and not self.differentForks(node, existing.source):
      File "d:\anaconda\64\lib\site-packages\pyflakes\checker.py", line 413, in differentForks
        if self.descendantOf(lnode, items, ancestor) ^ \
      File "d:\anaconda\64\lib\site-packages\pyflakes\checker.py", line 403, in descendantOf
        if self.getCommonAncestor(node, a, stop):
      File "d:\anaconda\64\lib\site-packages\pyflakes\checker.py", line 395, in getCommonAncestor
        if (lnode.depth > rnode.depth):
    AttributeError: 'ExceptHandler' object has no attribute 'depth'

**Comment by asottile** [comment]
In GitLab by @sigmavirus24 on Mar 15, 2016, 10:31

Can you provide the *exact* output of `flake8 --version` please?

**Comment by asottile** [comment]
In GitLab by @sanand0 on Mar 15, 2016, 10:48

Thanks @sigmavirus24 -- I looked at `flake8 --version` and saw a plugin that looked like it might be the cause. It was. I will close this issue.

**Comment by asottile** [comment]
In GitLab by @sigmavirus24 on Mar 15, 2016, 11:23

@sanand0 please file a bug report on that plugin and link it back here for others.

**Comment by asottile** [comment]
In GitLab by @asottile on May 2, 2019, 23:59

I've triaged this here: https://gitlab.com/pycqa/flake8/issues/536
