### ISSUE TITLE
multiprocessing problem

### ISSUE THREAD

**Issue by asottile** [PyCQA/flake8#486]
In GitLab by @orihime-akami on Apr 19, 2016, 19:09

*Please provide the following version information*

- Version of Python which has Flake8 installed (e.g., `python -V`)

```
(hogefuga_env)fugafuga@hogefuga:~/work/flake8-bug$ python -V
Python 2.7.6
```

- How you installed Flake8 (e.g., `pip`, `apt`, `yum`, etc.)
  Installed from pip
  - If you used pip, the version of pip installed (e.g., `pip --version`)

  ```
  (hogefuga_env)fugafuga@hogefuga:~/work/flake8-bug$ pip --version
  pip 8.1.1 from /home/fugafuga/hogefuga_env/local/lib/python2.7/site-packages (python 2.7)
  ```

- Version of setuptools installed (e.g., `python -c 'import setuptools; print(setuptools.__version__)'`)

  ```
  (hogefuga_env)fugafuga@hogefuga:~/work/flake8-bug$ python -c 'import setuptools; print(setuptools.__version__)'
  20.9.0
  ```

- Version of Flake8 installed (i.e., copy and paste all of the output from `flake8 --version`)

  ```
  (hogefuga_env)fugafuga@hogefuga:~/work/flake8-bug$ flake8 --version
  2.2.4 (pep8: 1.5.7, flake8-pep257: 1.0.5, pyflakes: 0.8.1, mccabe: 0.2.1, hacking.core: 0.0.1, ProxyChecker: 0.0.1, import-order: 0.7) CPython 2.7.6 on Linux
  ```

*Please describe the problem or feature*

```
(hogefuga_env)fugafuga@hogefuga:~/work/flake8-bug$ flake8 file2.py
Process Process-1:
Traceback (most recent call last):
  File "/usr/lib/python2.7/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
  File "/usr/lib/python2.7/multiprocessing/process.py", line 114, in run
    self._target(*self._args, **self._kwargs)
  File "/home/fugafuga/hogefuga_env/local/lib/python2.7/site-packages/flake8/reporter.py", line 73, in process_main
```

*If this is a bug report, please explain with examples (and example code) what you expected to happen and what actually happened.*

example code(file2.py):

```
# -*- coding: utf_8 -*-
"""
ABCDE モジュール
実験用。

現状、以下の機能を実装しています。
* 実験１
* 実験２
** ToDo: 実験３

実験４
"""


class Abcde(object):

    def abcde1(self, x, y):
        """
        データ登録。
        ほげほげ。
        fugafugaふがふが。
        """
        self.x = x
        self.y = y

    def abcde2(self, hogefuga):
        """
        ほげほげ。
        ふがふが。
        """
        self.abcde2 = hogefuga

    def abcde3(self, hogehoge):
        """
        ほげほげ。
        ふがふが。
        """
        self.abcde3 = hogehoge

    def abcde4(self, fugafuga):
        """
        ほげほげ。
        ふがふが。
        """
        self.abcde4 = fugafuga
```

**Comment by asottile** [comment]
In GitLab by @sigmavirus24 on Apr 20, 2016, 07:09

Have you been able to reproduce this with the latest version of flake8? Also, could you **please** provide the *complete* traceback? The one above stops early and is not enough to help.

**Comment by asottile** [comment]
In GitLab by @orihime-akami on Apr 20, 2016, 23:42

sorry, I can't reproduce this with the latest version.

in my new environment flake8 2.5.4 (pep8: 1.5.7, hacking.core: 0.0.1, ProxyChecker: 0.0.1, pyflakes: 0.8.1, mccabe: 0.2.1, import-order: 0.7) CPython 2.7.6 on Linux , result of flake8 with my "file.py" is this:

```
$ flake8 file.py
file.py:22:1: H404  multi line docstring should start without a leading new line
file.py:22:1: H405  multi line docstring summary not separated with an empty line
file.py:30:1: H404  multi line docstring should start without a leading new line
file.py:30:1: H405  multi line docstring summary not separated with an empty line
file.py:37:1: H404  multi line docstring should start without a leading new line
file.py:37:1: H405  multi line docstring summary not separated with an empty line
file.py:44:1: H404  multi line docstring should start without a leading new line
file.py:44:1: H405  multi line docstring summary not separated with an empty line
```
