### ISSUE TITLE
Provide way to parallelize flake8 on Windows

### ISSUE THREAD

**Issue by asottile** [PyCQA/flake8#490]
In GitLab by @cool-RR on May 8, 2016, 03:14

It seems that the jobs parameter is ignored on Windows, so I can't find another way to parallelize flake8 on Windows. It would be good to provide a way to do that.

**Comment by asottile** [comment]
In GitLab by @schlamar on May 31, 2016, 07:20

You can enable multiprocessing on Windows if Python >= 2.7.11 or Python >= 3.2. See https://github.com/pypa/pip/issues/1891 for details.

**Comment by asottile** [comment]
In GitLab by @schlamar on May 31, 2016, 07:26

    affected_mp_version = (sys.version_info <= (2, 7, 11) or
                           (3, 0) <= sys.version_info < (3, 2))

**Comment by asottile** [comment]
In GitLab by @schlamar on May 31, 2016, 07:28

However, with enabled multiprocessing I get the following exception for every process:

    Process Process-1:
    Traceback (most recent call last):
      File "c:\python27\Lib\multiprocessing\process.py", line 258, in _bootstrap
        self.run()
      File "c:\python27\Lib\multiprocessing\process.py", line 114, in run
        self._target(*self._args, **self._kwargs)
      File "c:\users\schlaich\venv-main\lib\site-packages\flake8\reporter.py", line 89, in process_main
        self._process_main()
      File "c:\users\schlaich\venv-main\lib\site-packages\flake8\reporter.py", line 62, in _process_main
        from flake8.main import get_style_guide, DEFAULT_CONFIG
    ImportError: cannot import name DEFAULT_CONFIG

**Comment by asottile** [comment]
In GitLab by @sigmavirus24 on May 31, 2016, 09:23

I don't have a Windows image to test on. If y'all have time to debug this and send a pull request to make it work, let me know.

If we can enable multiprocessing for Windows on versions of Python > 3.2, that's fine by me. I don't want to try to constrain it to a patch release of 2.7 though.  People really should just be upgrading to Python 3 as best as they can.

**Comment by asottile** [comment]
In GitLab by @schlamar on May 31, 2016, 22:57

mentioned in merge request !61

**Comment by asottile** [comment]
In GitLab by @sigmavirus24 on Jun 15, 2016, 04:32

mentioned in commit 7bed004c0617b65b5f5149d1a59e52cefdff893e
