### ISSUE TITLE
Flake8 2.6.0 is broken in Python 2

### ISSUE THREAD

**Issue by asottile** [PyCQA/flake8#500]
In GitLab by @kottenator on Jun 16, 2016, 14:14

- Python 2.7.11
- pip 8.1.2
- setuptools 22.0.5
- flake8 2.6.0

When I install `flake8` in Python 2.7 and run `flake8 my-lib/` - I get:

```
Traceback (most recent call last):
  File "~/.virtualenvs/my-venv/bin/flake8", line 11, in <module>
    sys.exit(main())
  File "~/.virtualenvs/my-venv/lib/python2.7/site-packages/flake8/main.py", line 28, in main
    flake8_style = get_style_guide(parse_argv=True)
  File "~/.virtualenvs/my-venv/lib/python2.7/site-packages/flake8/engine.py", line 233, in get_style_guide
    kwargs['parser'], options_hooks = get_parser()
  File "~/.virtualenvs/my-venv/lib/python2.7/site-packages/flake8/engine.py", line 74, in get_parser
    (extensions, parser_hooks, options_hooks, ignored) = _register_extensions()
  File "~/.virtualenvs/my-venv/lib/python2.7/site-packages/flake8/engine.py", line 58, in _register_extensions
    checker = _load_entry_point(entry, verify_requirements=False)
  File "~/.virtualenvs/my-venv/lib/python2.7/site-packages/flake8/engine.py", line 37, in _load_entry_point
    plugin = entry_point.resolve()
  File "~/.virtualenvs/my-venv/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2235, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "~/.virtualenvs/my-venv/lib/python2.7/site-packages/teamcity/flake8_plugin.py", line 1, in <module>
    import pep8
ImportError: No module named pep8
```

_Note:_ ait seems to work fine in Python 3.4

**Comment by asottile** [comment]
In GitLab by @sigmavirus24 on Jun 16, 2016, 14:15

Your plugin is broken, not Flake8. Flake8 2.6.0 switched to pycodestyle (which is what pep8 has been renamed to). Your plugin should have an explicit dependency on pep8.

**Comment by asottile** [comment]
In GitLab by @kottenator on Jun 16, 2016, 14:23

Well, it's not my plugin, it's `teamcity-messages==1.18` ...

**Comment by asottile** [comment]
In GitLab by @sigmavirus24 on Jun 16, 2016, 14:33

Please report the problem to the maintainer of that plugin. This is not a problem in Flake8.

**Comment by asottile** [comment]
In GitLab by @sigmavirus24 on Jun 16, 2016, 14:35

In fact, there's already a pull request there for this problem: https://github.com/JetBrains/teamcity-messages/pull/104

**Comment by asottile** [comment]
In GitLab by @kottenator on Jun 16, 2016, 16:06

Thank you for investigating this ;)
