### ISSUE TITLE
3.0.0b2 with hacking installed: AttributeError: 'FileProcessor' object has no attribute 'physical_line'

### ISSUE THREAD

**Issue by asottile** [PyCQA/flake8#508]
In GitLab by @The-Compiler on Jun 30, 2016, 24:10

For some reason this only happens with `hacking` installed, but as this clearly happens inside flake8, I'm reporting it here.

With `hacking` and `flake8` installed, when I run flake8 on any file, I get:

```
Process Process-1:
Traceback (most recent call last):
  File "/usr/lib64/python3.5/multiprocessing/process.py", line 254, in _bootstrap
    self.run()
  File "/usr/lib64/python3.5/multiprocessing/process.py", line 93, in run
    self._target(*self._args, **self._kwargs)
  File "/home/florian/tmp/flake8/.venv/lib/python3.5/site-packages/flake8/checker.py", line 222, in _run_checks_from_queue
    checker.run_checks(self.results_queue, self.statistics_queue)
  File "/home/florian/tmp/flake8/.venv/lib/python3.5/site-packages/flake8/checker.py", line 551, in run_checks
    self.process_tokens()
  File "/home/florian/tmp/flake8/.venv/lib/python3.5/site-packages/flake8/checker.py", line 535, in process_tokens
    self.handle_newline(token_type)
  File "/home/florian/tmp/flake8/.venv/lib/python3.5/site-packages/flake8/checker.py", line 578, in handle_newline
    self.run_logical_checks()
  File "/home/florian/tmp/flake8/.venv/lib/python3.5/site-packages/flake8/checker.py", line 487, in run_logical_checks
    results = self.run_check(plugin, logical_line=logical_line) or ()
  File "/home/florian/tmp/flake8/.venv/lib/python3.5/site-packages/flake8/checker.py", line 442, in run_check
    self.processor.keyword_arguments_for(plugin.parameters, arguments)
  File "/home/florian/tmp/flake8/.venv/lib/python3.5/site-packages/flake8/processor.py", line 213, in keyword_arguments_for
    arguments[param] = getattr(self, param)
AttributeError: 'FileProcessor' object has no attribute 'physical_line'
```

Full session:

```
florian@ginny flake8]$ virtualenv .venv
Using base prefix '/usr'
New python executable in /home/florian/tmp/flake8/.venv/bin/python3
Also creating executable in /home/florian/tmp/flake8/.venv/bin/python
Installing setuptools, pip, wheel...done.
```

```
[florian@ginny flake8]$ ./.venv/bin/python --version
Python 3.5.1
```

```
[florian@ginny flake8]$ ./.venv/bin/pip --version
pip 8.1.2 from /home/florian/tmp/flake8/.venv/lib/python3.5/site-packages (python 3.5)
```

```
[florian@ginny flake8]$ ./.venv/bin/pip install --pre flake8 hacking
[...]
Successfully installed flake8-3.0.0b2 hacking-0.11.0 mccabe-0.5.0 pbr-1.10.0 pep8-1.5.7 pycodestyle-2.0.0 pyflakes-1.2.3 six-1.10.0
```

```
[florian@ginny flake8]$ ./.venv/bin/flake8 --version 
3.0.0b2 (mccabe: 0.5.0, hacking.core: 0.0.1, pyflakes: 1.2.3, pycodestyle: 2.0.0, ProxyChecker: 0.0.1) CPython 3.5.1 on Linux
```

```
[florian@ginny flake8]$ cat foo.py
print("Hello World")
```

```
[florian@ginny flake8]$ ./.venv/bin/flake8 foo.py 
Process Process-1:
Traceback (most recent call last):

[...]

[hangs]
```

**Comment by asottile** [comment]
In GitLab by @sigmavirus24 on Jun 30, 2016, 04:41

So Hacking does something unexpected (expecting both `logical_line` and `physical_line`). See also: https://review.openstack.org/335965
