### ISSUE TITLE
Flake8 version 3 chokes on reported errors in empty files

### ISSUE THREAD

**Issue by asottile** [PyCQA/flake8#512]
In GitLab by @xZise on Jul 4, 2016, 15:02

With version 3.0.0b2 installed it chokes on empty files when there is an error reported for the file and hangs up:

```
$ touch empty.py
$ flake8 empty.py 
Process Process-1:
Traceback (most recent call last):
  File "/home/xzise/.pyenv/versions/3.5.1/lib/python3.5/multiprocessing/process.py", line 254, in _bootstrap
    self.run()
  File "/home/xzise/.pyenv/versions/3.5.1/lib/python3.5/multiprocessing/process.py", line 93, in run
    self._target(*self._args, **self._kwargs)
  File "/home/xzise/.pyenv/versions/3.5.1/lib/python3.5/site-packages/flake8/checker.py", line 222, in _run_checks_from_queue
    checker.run_checks(self.results_queue, self.statistics_queue)
  File "/home/xzise/.pyenv/versions/3.5.1/lib/python3.5/site-packages/flake8/checker.py", line 556, in run_checks
    self.run_ast_checks()
  File "/home/xzise/.pyenv/versions/3.5.1/lib/python3.5/site-packages/flake8/checker.py", line 473, in run_ast_checks
    text=text,
  File "/home/xzise/.pyenv/versions/3.5.1/lib/python3.5/site-packages/flake8/checker.py", line 433, in report
    physical_line = self.processor.line_for(line_number)
  File "/home/xzise/.pyenv/versions/3.5.1/lib/python3.5/site-packages/flake8/processor.py", line 253, in line_for
    return self.lines[line_number - 1]
IndexError: list index out of range
^C... stopped while processing files
```

The version of flake8 installed: `3.0.0b2 (flake8-string-format: 0.3.0.dev0, flake8_quotes: 0.3.0, mccabe: 0.5.0, pyflakes: 1.2.3, pycodestyle: 2.0.0, flake8-future-import: 0.4.3) CPython 3.5.1 on Linux`

In this case `flake8-future-import` complains that a `__future__` import is missing in line `1`.

**Comment by asottile** [comment]
In GitLab by @sigmavirus24 on Jul 5, 2016, 13:03

I can't reproduce this without any plugins. I suspect you figure out which one causes this and then let me know how I can help fix this.

**Comment by asottile** [comment]
In GitLab by @xZise on Jul 5, 2016, 14:20

Agreed as observed there: https://github.com/zheller/flake8-quotes/pull/35 I'll test it further which of my two plugins cause that error, although neither of them is using Flake8 3.x special code (apart from registering the error codes).

**Comment by asottile** [comment]
In GitLab by @xZise on Jul 5, 2016, 14:24

Hmpf I should've waited before commenting, but quick testing revealed that `flake8-future-import` is causing this. This also happens with the version from pypi so if you want you could probably reproduce it.

**Comment by asottile** [comment]
In GitLab by @xZise on Jul 5, 2016, 14:32

Okay I figured it out, and I'm not sure what the best solution here is. The reason `flake8-future-import` is causing this error is because that plugin reports an error and the given line number obviously does not exist. If you set `require-code` to `True`, it'll skip the file and doesn't complain.

So now the question is whether this is actually a bug? Should plugins/Flake8 report issues in empty files? And if that is the case, what line number should it use? I used the integer “1” in my case.

**Comment by asottile** [comment]
In GitLab by @xZise on Jul 5, 2016, 14:34

Changed title: **Flake8 version 3 chokes on empty files** → **Flake8 version 3 chokes on {+reported errors in +}empty files**

**Comment by asottile** [comment]
In GitLab by @sigmavirus24 on Jul 6, 2016, 06:40

> So now the question is whether this is actually a bug? Should plugins/Flake8 report issues in empty files? And if that is the case, what line number should it use? I used the integer “1” in my case.

So this will require special casing. Some things will report issues in empty files (I think flake8-docstrings/pydocstyle will at least). This means that if someone is using `--show-source` though, that we show them *what* exactly? I'm tempted to have something like `<<file empty>>`. Thoughts?

**Comment by asottile** [comment]
In GitLab by @xZise on Jul 7, 2016, 02:37

Okay 2.6 at the moment just shows “nothing”:

```
$ flake8 empty.py --show-source
empty.py:1:1: D100 Missing docstring in public module

^
empty.py:1:1: FI10 __future__ import "division" missing

^
empty.py:1:1: FI11 __future__ import "absolute_import" missing

^
[…]
```

But afaik this should be something like:

```
$ flake8 empty.py --show-source
empty.py:1:1: D100 Missing docstring in public module
empty.py:1:1: FI10 __future__ import "division" missing
empty.py:1:1: FI11 __future__ import "absolute_import" missing
(Source code cannot be shown: file is empty)
```

Either add that after each entry or just after the last one for the file (if your parallel implementation doesn't “mix” different files). And by not having that cursor it cannot be confused with a file actually containing the string (whether it is `<<file empty>>` or something else). And you could actually show different error messages (e.g. file cannot be read because of missing permissions).

**Comment by asottile** [comment]
In GitLab by @sigmavirus24 on Jul 9, 2016, 17:43

mentioned in merge request !70

**Comment by asottile** [comment]
In GitLab by @sigmavirus24 on Jul 9, 2016, 17:54

mentioned in commit 7ea6da2d55b8c5120358ba8aec16bde8f798e371

**Comment by asottile** [comment]
In GitLab by @sigmavirus24 on Jul 9, 2016, 18:22

mentioned in commit 57e82688df3f36d023352e3d12435f36f51ee9ac

**Comment by asottile** [comment]
In GitLab by @sigmavirus24 on Jul 9, 2016, 18:23

mentioned in merge request !71

**Comment by asottile** [comment]
In GitLab by @sigmavirus24 on Jul 9, 2016, 18:29

Status changed to closed by commit 57e82688df3f36d023352e3d12435f36f51ee9ac

**Comment by asottile** [comment]
In GitLab by @sigmavirus24 on Jul 9, 2016, 18:29

mentioned in commit edd84fba5298cedfb3c6f456a00107f1d3f642c2

**Comment by asottile** [comment]
In GitLab by @ssbarnea on Jul 20, 2016, 08:03

This bug seems to still be present in the latest release which seems to be 3.0.0b2 -- why is closed?

PS. Considering the severity, I would say that's the kind of bug for which you may even want to remove a release from PYPI.

**Comment by asottile** [comment]
In GitLab by @sigmavirus24 on Jul 20, 2016, 08:07

@sbarnea it's closed because it's fixed (as the label indicates). It will be included in the next release.

Regardless, this only happens with plugins that took advantage of previously undefined behaviour.
