### ISSUE TITLE
Flake8 3.0 does not work, throws AttributeError exception

### ISSUE THREAD

**Issue by asottile** [PyCQA/flake8#527]
In GitLab by @akittas on Jul 25, 2016, 08:52

Python version: 3.5.2 64-bit

OS: Windows 10 Pro 64 bit

Installation: pip install flake8

pip version: 8.1.2

setuptools version: 25.0.1

flake 8 --version: 3.0.0 (pycodestyle: 2.0.0, mccabe: 0.5.0, pyflakes: 1.2.3) CPython 3.5.2 on Windows

running method: flake8 program.py or python -m flake8 program.py

Flake8 3.0 throws the following exception when executing on any file: **AttributeError: 'FlakesChecker' object has no attribute 'with_doctest'**

```
Traceback (most recent call last):

  File "c:\programs\python35\lib\multiprocessing\process.py", line 249, in _bootstrap
    self.run()

  File "c:\programs\python35\lib\multiprocessing\process.py", line 93, in run
    self._target(*self._args, **self._kwargs)

  File "c:\programs\python35\lib\site-packages\flake8\checker.py", line 222, in _run_checks_from_queue
    checker.run_checks(self.results_queue, self.statistics_queue)

  File "c:\programs\python35\lib\site-packages\flake8\checker.py", line 563, in run_checks
    self.run_ast_checks()

  File "c:\programs\python35\lib\site-packages\flake8\checker.py", line 468, in run_ast_checks
    checker = self.run_check(plugin, tree=ast)

  File "c:\programs\python35\lib\site-packages\flake8\checker.py", line 448, in run_check
    return plugin.execute(**arguments)

  File "c:\programs\python35\lib\site-packages\flake8\plugins\manager.py", line 126, in execute
    return self.plugin(*args, **kwargs)  # pylint: disable=not-callable

  File "c:\programs\python35\lib\site-packages\flake8\plugins\pyflakes.py", line 53, in __init__
    with_doctest = self.with_doctest

AttributeError: 'FlakesChecker' object has no attribute 'with_doctest'
```

Flake8 2.6.2 works  as expected.

**Comment by asottile** [comment]
In GitLab by @sigmavirus24 on Jul 25, 2016, 08:55

You did not provide the actual output of `flake8 --version`. Please provide that.

**Comment by asottile** [comment]
In GitLab by @sigmavirus24 on Jul 25, 2016, 08:56

Also please provide how you are invoking Flake8 and the exact traceback please.

**Comment by asottile** [comment]
In GitLab by @akittas on Jul 25, 2016, 09:03

Thanks for the reply, I have provided the missing details

**Comment by asottile** [comment]
In GitLab by @sigmavirus24 on Jul 25, 2016, 09:43

So this seems to be a problem with Windows. I can only reproduce it there (see also [appveyor](https://ci.appveyor.com/project/sigmavirus24/flake8/build/3.0.8#L170)). I'm getting a Windows VM to test this on from [here](https://developer.microsoft.com/en-us/windows/downloads/virtual-machines).

If anyone else cares to help debug this, I'd greatly appreciate it.

**Comment by asottile** [comment]
In GitLab by @sigmavirus24 on Jul 25, 2016, 13:03

I don't think this will make it's way into 3.0.1, but I hope to get it into a 3.0.x release, for what it's worth @akittas. Thank you for the report.

**Comment by asottile** [comment]
In GitLab by @wbond on Jul 26, 2016, 04:57

I ran into a separate issue with multiprocessing on 3.0.0 and Windows that was likely due to the way I was envoking flake8 (legacy api). A temporary workaround for this issue and that one is to set `--jobs` to `1`.

**Comment by asottile** [comment]
In GitLab by @schlamar on Jul 26, 2016, 23:12

mentioned in merge request !97

**Comment by asottile** [comment]
In GitLab by @sigmavirus24 on Jul 27, 2016, 04:44

mentioned in commit 846bfafe6c63870f41bac0eadf41b2a0a85c85aa

**Comment by asottile** [comment]
In GitLab by @sigmavirus24 on Jul 27, 2016, 06:18

mentioned in commit 9c8aa6bec13e183c0e07b0ceb07702b1604f0feb

**Comment by asottile** [comment]
In GitLab by @sigmavirus24 on Jul 27, 2016, 06:19

mentioned in merge request !98

**Comment by asottile** [comment]
In GitLab by @wjwwood on Jul 29, 2016, 14:15

I can confirm this bug only happens on Windows (using flake8 3.0.2 and Python 3.5 on Windows 10). I can also confirm that @wbond's workaround of using `--jobs 1` works for me.

I have a Windows machine, so I'll look into a proper fix time permitting.

**Comment by asottile** [comment]
In GitLab by @sigmavirus24 on Jul 29, 2016, 14:33

Hey @wjwwood 

Just a warning that this is a problem with Python's multiprocessing module on Windows. See https://gitlab.com/pycqa/flake8/merge_requests/105 which I hope to release soon in 3.0.3.

**Comment by asottile** [comment]
In GitLab by @wjwwood on Jul 29, 2016, 14:36

I was just getting to the same conclusion :smiley:. Thanks for the heads up!

**Comment by asottile** [comment]
In GitLab by @sigmavirus24 on Aug 3, 2016, 14:49

mentioned in commit e14d0e6352efcf78d33c896a425ddc41405acd02

**Comment by asottile** [comment]
In GitLab by @sigmavirus24 on Aug 5, 2016, 12:58

mentioned in commit ce94cfea695881db456f0be01e759632829b3e7f

**Comment by asottile** [comment]
In GitLab by @sigmavirus24 on Oct 23, 2016, 05:39

Mentioned in commit sigmavirus24/flake8@ce94cfea695881db456f0be01e759632829b3e7f
