### ISSUE TITLE
Flake8 throws AttributeError exception

### ISSUE THREAD

**Issue by asottile** [PyCQA/flake8#539]
In GitLab by @master.bvik on Jul 31, 2016, 23:58

*Please provide the following version information*

- Version of Python which has Flake8 installed  : python3.5.2(e.g., `python -V`)
- Installed using pip (e.g., `pip`, `apt`, `yum`, etc.)
  - pip version = 8.1.2(e.g., `pip --version`)
- Version of setuptools installed : 25.1.0
- Version of Flake8 installed (pyflakes: 1.2.3, pycodestyle: 2.0.0, mccabe: 0.5.2) CPython 3.5.2 on Linux
*Please describe the problem or feature*
- This problem arises only if there is a syntax error in the file i am checking :

I run flake8 myfile.py

It throws an AttributeError saying TokenError object has no attribute message, i am pretty sure this has something to do with the fact that python3 has no message attribute for it's Exception class which TokenError inherits from.

Here is the deatailed traceback:

```python
Traceback (most recent call last):
  File "/home/vikash/lpackages/anaconda3/envs/MLenv/lib/python3.5/site-packages/flake8/processor.py", line 238, in generate_tokens
    for token in tokenize.generate_tokens(self.next_line):
  File "/home/vikash/lpackages/anaconda3/envs/MLenv/lib/python3.5/tokenize.py", line 597, in _tokenize
    raise TokenError("EOF in multi-line statement", (lnum, 0))
tokenize.TokenError: ('EOF in multi-line statement', (8, 0))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/vikash/lpackages/anaconda3/envs/MLenv/lib/python3.5/multiprocessing/process.py", line 249, in _bootstrap
    self.run()
  File "/home/vikash/lpackages/anaconda3/envs/MLenv/lib/python3.5/multiprocessing/process.py", line 93, in run
    self._target(*self._args, **self._kwargs)
  File "/home/vikash/lpackages/anaconda3/envs/MLenv/lib/python3.5/site-packages/flake8/checker.py", line 46, in _run_checks_from_queue
    checker.run_checks(results_queue, statistics_queue)
  File "/home/vikash/lpackages/anaconda3/envs/MLenv/lib/python3.5/site-packages/flake8/checker.py", line 579, in run_checks
    self.process_tokens()
  File "/home/vikash/lpackages/anaconda3/envs/MLenv/lib/python3.5/site-packages/flake8/checker.py", line 554, in process_tokens
    for token in file_processor.generate_tokens():
  File "/home/vikash/lpackages/anaconda3/envs/MLenv/lib/python3.5/site-packages/flake8/processor.py", line 250, in generate_tokens
    raise exceptions.InvalidSyntax(exc.message, exception=exc)
AttributeError: 'TokenError' object has no attribute 'message'
```

I am thinking the **exc.message** should be **str(exc)** for python3. 

**EDIT**:

I have verified, changing **exc.message** to **str(exc)** along with fixing another piece of code in **exceptions.py** which had a similar issue, fixed the problem.

I don't know if what i did was a temporary work-around or a correct fix, please look into it.

**Comment by asottile** [comment]
In GitLab by @yan12125 on Aug 1, 2016, 04:05

Got the same error with flake8 3.0.3. A minimum test file:
```
def foo():
    print(
    return
```
Environment: Arch Linux x86_64. All packages are installed via the system package manager ```pacman```:
```
pacman -Q python flake8 python-{pip,pyflakes,mccabe,pycodestyle} 
python 3.5.2-1
flake8 1:3.0.3-1
python-pip 8.1.2-1
python-pyflakes 1.2.3-1
python-mccabe 0.5.1-1
python-pycodestyle 2.0.0-1
```
(```1:``` in flake8's version means it's versioning scheme has once changed in Arch's build script. You can simply ignore it)

**Comment by asottile** [comment]
In GitLab by @sigmavirus24 on Aug 1, 2016, 07:30

@master.bvik that fix looks fine to me, would you like to send a merge request with that fix?

**Comment by asottile** [comment]
In GitLab by @wbolster on Aug 5, 2016, 02:19

mentioned in merge request !112

**Comment by asottile** [comment]
In GitLab by @wbolster on Aug 5, 2016, 02:58

i've opened !112 that fixes these crashes for me. since i run flake8 automatically from my editor during editing, i constantly get backtraces while typing code, e.g. right after typing a `(` character and thinking for a bit what to type next.

**Comment by asottile** [comment]
In GitLab by @wbolster on Aug 5, 2016, 04:54

mentioned in commit 45ae0b9eebc1e47df1a049e75d64e25118299d65

**Comment by asottile** [comment]
In GitLab by @wbolster on Aug 5, 2016, 04:54

mentioned in commit cddf982a0a16db11bfb68bd4c620535ac44bcb4b

**Comment by asottile** [comment]
In GitLab by @pjacock on Aug 7, 2017, 06:40

mentioned in merge request !198
