### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'rstrip'

### ISSUE THREAD

**Issue by asottile** [PyCQA/flake8#542]
In GitLab by @simonklb on Nov 30, 2016, 05:01

```
$ pip install flake8
```

```
$ flake8 --bug-report
{
  "dependencies": [
    {
      "dependency": "setuptools",
      "version": "20.7.0"
    }
  ],
  "platform": {
    "python_implementation": "CPython",
    "python_version": "3.5.2",
    "system": "Linux"
  },
  "plugins": [
    {
      "plugin": "mccabe",
      "version": "0.5.2"
    },
    {
      "plugin": "pycodestyle",
      "version": "2.2.0"
    },
    {
      "plugin": "pyflakes",
      "version": "1.3.0"
    }
  ],
  "version": "3.2.1"
}
```

```
$ cat test.py 
print(a=1, 2)

$ python test.py 
  File "test.py", line 1
    print(a=1, 2)
              ^
SyntaxError: positional argument follows keyword argument

$ flake8 test.py 
Process Process-1:
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/flake8/checker.py", line 502, in run_ast_checks
    ast = self.processor.build_ast()
  File "/usr/local/lib/python3.5/dist-packages/flake8/processor.py", line 211, in build_ast
    return compile(''.join(self.lines), '', 'exec', PyCF_ONLY_AST)
  File "<string>", line 1
SyntaxError: positional argument follows keyword argument

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.5/multiprocessing/process.py", line 249, in _bootstrap
    self.run()
  File "/usr/lib/python3.5/multiprocessing/process.py", line 93, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/local/lib/python3.5/dist-packages/flake8/checker.py", line 667, in _run_checks_from_queue
    checker.run_checks(results_queue, statistics_queue)
  File "/usr/local/lib/python3.5/dist-packages/flake8/checker.py", line 607, in run_checks
    self.run_ast_checks()
  File "/usr/local/lib/python3.5/dist-packages/flake8/checker.py", line 505, in run_ast_checks
    row, column = self._extract_syntax_information(exception)
  File "/usr/local/lib/python3.5/dist-packages/flake8/checker.py", line 489, in _extract_syntax_information
    lines = physical_line.rstrip('\n').split('\n')
AttributeError: 'NoneType' object has no attribute 'rstrip'
```

**Comment by asottile** [comment]
In GitLab by @kovan on Dec 16, 2016, 09:17

`k@k-arch ~/sandbox/build/prj-flask ±master⚡ » flake8 --bug-report
{
  "dependencies": [
    {
      "dependency": "setuptools",
      "version": "30.4.0"
    }
  ],
  "platform": {
    "python_implementation": "CPython",
    "python_version": "3.5.2",
    "system": "Linux"
  },
  "plugins": [
    {
      "plugin": "mccabe",
      "version": "0.5.3"
    },
    {
      "plugin": "pycodestyle",
      "version": "2.2.0"
    },
    {
      "plugin": "pyflakes",
      "version": "1.3.0"
    }
  ],
  "version": "3.2.1"
}
`


`@k-arch ~/sandbox/build/prj-flask ±master⚡ » flake8 app             
Process Process-3:
Traceback (most recent call last):
  File "/usr/lib/python3.5/site-packages/flake8/checker.py", line 501, in run_ast_checks
    ast = self.processor.build_ast()
  File "/usr/lib/python3.5/site-packages/flake8/processor.py", line 211, in build_ast
    return compile(''.join(self.lines), '', 'exec', PyCF_ONLY_AST)
  File "<string>", line 50
SyntaxError: positional argument follows keyword argument unpacking

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.5/multiprocessing/process.py", line 249, in _bootstrap
    self.run()
  File "/usr/lib/python3.5/multiprocessing/process.py", line 93, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/lib/python3.5/site-packages/flake8/checker.py", line 666, in _run_checks_from_queue
    checker.run_checks(results_queue, statistics_queue)
  File "/usr/lib/python3.5/site-packages/flake8/checker.py", line 606, in run_checks
    self.run_ast_checks()
  File "/usr/lib/python3.5/site-packages/flake8/checker.py", line 504, in run_ast_checks
    row, column = self._extract_syntax_information(exception)
  File "/usr/lib/python3.5/site-packages/flake8/checker.py", line 488, in _extract_syntax_information
    lines = physical_line.rstrip('\n').split('\n')
AttributeError: 'NoneType' object has no attribute 'rstrip'
`

> 
> 
> I am totally unable to make GitLab properly format as code the text above, sorry.

**Comment by asottile** [comment]
In GitLab by @wayslog on Jan 3, 2017, 20:12

I get the same error, In Python 3.6.0.

**Comment by asottile** [comment]
In GitLab by @ghost1 on Jan 5, 2017, 11:18

Got the same errors too with Python 3.5.2 with flake8 version 3.2.1

**Comment by asottile** [comment]
In GitLab by @bjorngi on Jan 10, 2017, 02:49

Same issue:
`
Process Process-1:
Traceback (most recent call last):
  File "/usr/lib/python3.5/site-packages/flake8/checker.py", line 501, in run_ast_checks
    ast = self.processor.build_ast()
  File "/usr/lib/python3.5/site-packages/flake8/processor.py", line 211, in build_ast
    return compile(''.join(self.lines), '', 'exec', PyCF_ONLY_AST)
  File "<string>", line 96
SyntaxError: keyword can't be an expression
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/usr/lib/python3.5/multiprocessing/process.py", line 249, in _bootstrap
    self.run()
  File "/usr/lib/python3.5/multiprocessing/process.py", line 93, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/lib/python3.5/site-packages/flake8/checker.py", line 666, in _run_checks_from_queue
    checker.run_checks(results_queue, statistics_queue)
  File "/usr/lib/python3.5/site-packages/flake8/checker.py", line 606, in run_checks
    self.run_ast_checks()
  File "/usr/lib/python3.5/site-packages/flake8/checker.py", line 504, in run_ast_checks
    row, column = self._extract_syntax_information(exception)
  File "/usr/lib/python3.5/site-packages/flake8/checker.py", line 488, in _extract_syntax_information
    lines = physical_line.rstrip('\n').split('\n')
AttributeError: 'NoneType' object has no attribute 'rstrip'
`

For me it seems to be triggered by a spesific error. According to pyflakes it's

`
± pyflakes server.py
server.py:96:8: keyword can't be an expression
Hotspot.alias = token_data['hotspot']
`

System information:
Linux dummy 4.4.38-1-MANJARO #1 SMP PREEMPT Sat Dec 10 23:03:09 UTC 2016 x86_64 GNU/Linux

Flake8 information:
`
{
  "dependencies": [
    {
      "dependency": "setuptools",
      "version": "32.3.1"
    }
  ],
  "platform": {
    "python_implementation": "CPython",
    "python_version": "3.5.2",
    "system": "Linux"
  },
  "plugins": [
    {
      "plugin": "mccabe",
      "version": "0.5.3"
    },
    {
      "plugin": "pycodestyle",
      "version": "2.2.0"
    },
    {
      "plugin": "pyflakes",
      "version": "1.3.0"
    }
  ],
  "version": "3.2.1"
}
`

It is an actual error in my code, and when it fixed the issue goes away.

**Comment by asottile** [comment]
In GitLab by @sigmavirus24 on Jan 16, 2017, 17:15

assigned to @sigmavirus24

**Comment by asottile** [comment]
In GitLab by @sigmavirus24 on Jan 27, 2017, 13:24

mentioned in merge request !173

**Comment by asottile** [comment]
In GitLab by @sigmavirus24 on Jan 27, 2017, 13:29

closed via merge request !173

**Comment by asottile** [comment]
In GitLab by @sigmavirus24 on Jan 27, 2017, 14:00

mentioned in commit sigmavirus24/flake8@77d887f4000fe3c85b6a191bff071d7c08d5e189

**Comment by asottile** [comment]
In GitLab by @sigmavirus24 on Apr 29, 2017, 15:28

mentioned in commit jdufresne/flake8@7ca05a9ca188c9487b0b3067ca100ea105dca205
