### ISSUE TITLE
Parser chokes on `from A import B,` (trailing comma)

### ISSUE THREAD

**Issue by asottile** [PyCQA/flake8#555]
In GitLab by @12345ieee on Jan 16, 2017, 14:55

*Please describe how you installed Flake8*

Via `apt`, Debian sid:

```
andreas@trelitri:/tmp$ apt show flake8 
Package: flake8
Version: 3.2.1-1
```

*Please provide the exact, unmodified output of `flake8 --bug-report`*

```
andreas@trelitri:/tmp$ flake8 --bug-report
{
  "dependencies": [
    {
      "dependency": "setuptools",
      "version": "28.3.0"
    }
  ],
  "platform": {
    "python_implementation": "CPython",
    "python_version": "3.5.3rc1",
    "system": "Linux"
  },
  "plugins": [
    {
      "plugin": "mccabe",
      "version": "0.5.2"
    },
    {
      "plugin": "pycodestyle",
      "version": "2.2.0"
    },
    {
      "plugin": "pyflakes",
      "version": "1.3.0"
    }
  ],
  "version": "3.2.1"
}
```

*Please describe the problem or feature*

Title says it all, the parser chokes on `from A import B,` (note the the trailing comma)

*If this is a bug report, please explain with examples (and example code) what you expected to happen and what actually happened.*

```
andreas@trelitri:/tmp$ cat test.py 
from A import B,
andreas@trelitri:/tmp$ flake8 test.py 
Process Process-1:
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/flake8/checker.py", line 501, in run_ast_checks
    ast = self.processor.build_ast()
  File "/usr/lib/python3/dist-packages/flake8/processor.py", line 211, in build_ast
    return compile(''.join(self.lines), '', 'exec', PyCF_ONLY_AST)
  File "<string>", line 1
SyntaxError: trailing comma not allowed without surrounding parentheses

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.5/multiprocessing/process.py", line 249, in _bootstrap
    self.run()
  File "/usr/lib/python3.5/multiprocessing/process.py", line 93, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/lib/python3/dist-packages/flake8/checker.py", line 666, in _run_checks_from_queue
    checker.run_checks(results_queue, statistics_queue)
  File "/usr/lib/python3/dist-packages/flake8/checker.py", line 606, in run_checks
    self.run_ast_checks()
  File "/usr/lib/python3/dist-packages/flake8/checker.py", line 504, in run_ast_checks
    row, column = self._extract_syntax_information(exception)
  File "/usr/lib/python3/dist-packages/flake8/checker.py", line 488, in _extract_syntax_information
    lines = physical_line.rstrip('\n').split('\n')
AttributeError: 'NoneType' object has no attribute 'rstrip'
andreas@trelitri:/tmp$ 
```

I expected the program not to crash, I'd say.

I'm sorry if this was already reported, I'm having problems navigating the issues here at gitlab.

**Comment by asottile** [comment]
In GitLab by @sigmavirus24 on Jan 16, 2017, 16:48

This is a duplicate of #279

**Comment by asottile** [comment]
In GitLab by @sigmavirus24 on Jan 16, 2017, 16:48

closed
