### ISSUE TITLE
Attempting to call flake8 results in KeyError: 'default'

### ISSUE THREAD

**Issue by asottile** [PyCQA/flake8#574]
In GitLab by @jay-tyler on Apr 4, 2017, 14:47

Install via `pip install --user flake8` with following output:
```
$ pip install --user flake8
Downloading/unpacking flake8
  Downloading flake8-3.3.0-py2.py3-none-any.whl (66kB): 66kB downloaded
Downloading/unpacking pyflakes>=1.5.0,<1.6.0 (from flake8)
  Downloading pyflakes-1.5.0-py2.py3-none-any.whl (225kB): 225kB downloaded
Downloading/unpacking configparser (from flake8)
  Downloading configparser-3.5.0.tar.gz
  Running setup.py (path:/tmp/pip_build_jtyler/configparser/setup.py) egg_info for package configparser

Downloading/unpacking mccabe>=0.6.0,<0.7.0 (from flake8)
  Downloading mccabe-0.6.1-py2.py3-none-any.whl
Downloading/unpacking pycodestyle>=2.0.0,<2.4.0 (from flake8)
  Downloading pycodestyle-2.3.1-py2.py3-none-any.whl (45kB): 45kB downloaded
Downloading/unpacking enum34 (from flake8)
  Downloading enum34-1.1.6-py2-none-any.whl
Installing collected packages: flake8, pyflakes, configparser, mccabe, pycodestyle, enum34
  Running setup.py install for configparser

    Skipping installation of /home/jtyler/.local/lib/python2.7/site-packages/backports/__init__.py (namespace package)
    Installing /home/jtyler/.local/lib/python2.7/site-packages/configparser-3.5.0-py2.7-nspkg.pth
Successfully installed flake8 pyflakes configparser mccabe pycodestyle enum34
Cleaning up...
```
Here's what happens when attempting to call flake8 on a file:
```
$ flake8 TestFile.py
Traceback (most recent call last):
  File "/home/jtyler/.local/bin/flake8", line 11, in <module>
    sys.exit(main())
  File "/home/jtyler/.local/lib/python2.7/site-packages/flake8/main/cli.py", line 16, in main
    app.run(argv)
  File "/home/jtyler/.local/lib/python2.7/site-packages/flake8/main/application.py", line 328, in run
    self._run(argv)
  File "/home/jtyler/.local/lib/python2.7/site-packages/flake8/main/application.py", line 315, in _run
    self.initialize(argv)
  File "/home/jtyler/.local/lib/python2.7/site-packages/flake8/main/application.py", line 300, in initialize
    self.make_formatter()
  File "/home/jtyler/.local/lib/python2.7/site-packages/flake8/main/application.py", line 200, in make_formatter
    format_plugin, self.formatting_plugins['default']
  File "/home/jtyler/.local/lib/python2.7/site-packages/flake8/plugins/manager.py", line 345, in __getitem__
    return self.plugins[name]
KeyError: 'default'
```

Same thing happens when calling the executable by itself:
```
$ flake8
Traceback (most recent call last):
  File "/home/jtyler/.local/bin/flake8", line 11, in <module>
    sys.exit(main())
  File "/home/jtyler/.local/lib/python2.7/site-packages/flake8/main/cli.py", line 16, in main
    app.run(argv)
  File "/home/jtyler/.local/lib/python2.7/site-packages/flake8/main/application.py", line 328, in run
    self._run(argv)
  File "/home/jtyler/.local/lib/python2.7/site-packages/flake8/main/application.py", line 315, in _run
    self.initialize(argv)
  File "/home/jtyler/.local/lib/python2.7/site-packages/flake8/main/application.py", line 300, in initialize
    self.make_formatter()
  File "/home/jtyler/.local/lib/python2.7/site-packages/flake8/main/application.py", line 200, in make_formatter
    format_plugin, self.formatting_plugins['default']
  File "/home/jtyler/.local/lib/python2.7/site-packages/flake8/plugins/manager.py", line 345, in __getitem__
    return self.plugins[name]
KeyError: 'default'
```

Is there something special about the installation that I'm missing? The instructions [here](http://flake8.pycqa.org/en/latest/index.html#installation) seemed pretty straightforward. A colleague is experiencing the same issue. Thanks!

**Comment by asottile** [comment]
In GitLab by @sigmavirus24 on Apr 4, 2017, 16:33

Does `flake8 --bug-report` work? Can you tell me the version of
pip/setuptools you're using if it fails?

**Comment by asottile** [comment]
In GitLab by @jay-tyler on Apr 4, 2017, 16:59

`flake8 --bug-report` did not work. Same error.

We're currently on pip 1.5.6. Eek, that's old. I can't update it, but I'll get someone to do so and see if that resolves this issue. Will update this issue once that happens.

**Comment by asottile** [comment]
In GitLab by @sigmavirus24 on Apr 4, 2017, 23:12

Even `flake8 -vv` would be useful. But also could you give me the version of setuptools you're using? 1.5.6 is old, yes, but the more important thing is the version of setuptools that's installed. If that's too old, I'm not sure there's much I can do for you.

**Comment by asottile** [comment]
In GitLab by @pjacock on Apr 24, 2017, 10:56

Confirmed using macOS ad Apple provided python 2.7, having done:

```
$ sudo python -m ensurepip
...
```

```
$ python -c "import setuptools; print(setuptools.__version__)"
0.6
$ python -c "import pip; print(pip.__version__)"
6.1.1
```

I then installed flake8 using pip and got the same failure as reported above.

I removed flake8, updated setuptools, reinstalled flake8, and it worked. Now have:

```
$ sudo python -m pip install --upgrade setuptools
...
$ python -c "import setuptools; print(setuptools.__version__)"
35.0.1
$ python -c "import pip; print(pip.__version__)"
6.1.1
```

I did not need to update pip, but will do so now anyway.

**Comment by asottile** [comment]
In GitLab by @sigmavirus24 on May 12, 2017, 18:08

So I think the way to solve this for others would be to specify a minimum version of setuptools that we can use. The issue with that is of course with users on ancient versions of Ubuntu, etc.

That said, we also need to handle this KeyError.

**Comment by asottile** [comment]
In GitLab by @sigmavirus24 on May 13, 2017, 04:55

mentioned in merge request !182

**Comment by asottile** [comment]
In GitLab by @sigmavirus24 on May 13, 2017, 06:07

closed via merge request !182

**Comment by asottile** [comment]
In GitLab by @sigmavirus24 on May 13, 2017, 07:11

mentioned in commit jdufresne/flake8@23b1f37ffd4c69a867aff87079c9fae2b5004155
