### ISSUE TITLE
UnicodeDecodeError when checking working utf-8 source code under Windows

### ISSUE THREAD

**Issue by asottile** [PyCQA/flake8#576]
In GitLab by @jcrmatos on Apr 20, 2017, 16:21

Hello,

I installed flake8 with
`pip install flake8`
under a virtualenv created with virtualenvwrapper-win.

My env is Windows7P+SP1 x64 with Python 3.5.2 32bits.

I have the following packages installed under my venv:
```
appdirs (1.4.3)
astroid (1.4.9)
bandit (1.4.0)
click (6.7)
colorama (0.3.7)
docopt (0.6.2)
first (2.0.1)
flake8 (3.3.0)
flake8-builtins (0.2)
flake8-coding (1.3.0)
flake8-comprehensions (1.2.1)
flake8-copyright (0.2.0)
flake8-deprecated (1.1)
flake8-docstrings (1.0.3)
flake8-polyfill (1.0.1)
flake8-string-format (0.2.3)
gitdb2 (2.0.0)
GitPython (2.1.3)
html5lib (1.0b8)
httplib2 (0.10.3)
isort (4.2.5)
jedi (0.10.0)
lazy-object-proxy (1.2.2)
mccabe (0.6.1)
mypy (0.501)
olefile (0.44)
packaging (16.8)
pbr (2.0.0)
Pillow (4.0.0)
pip (9.0.1)
pip-tools (1.8.0)
prompt-toolkit (1.0.13)
ptpython (0.36)
pycodestyle (2.3.1)
pydocstyle (1.1.1)
pyflakes (1.5.0)
Pygments (2.2.0)
pylint (1.6.5)
pyparsing (2.2.0)
PyPDF2 (1.26.0)
pypiwin32 (219)
PyYAML (3.12)
reportlab (3.3.0)
setuptools (34.3.2)
six (1.10.0)
smmap2 (2.0.1)
stevedore (1.21.0)
typed-ast (1.0.2)
virtualenv (15.1.0)
virtualenvwrapper-win (1.2.1)
wcwidth (0.1.7)
wheel (0.29.0)
wrapt (1.10.8)
xhtml2pdf (0.1b3)
```

The output from 
`flake8 --bug-report`
is
```
{
  "dependencies": [
    {
      "dependency": "setuptools",
      "version": "34.3.2"
    }
  ],
  "platform": {
    "python_implementation": "CPython",
    "python_version": "3.5.2",
    "system": "Windows"
  },
  "plugins": [
    {
      "plugin": "flake8-comprehensions",
      "version": "1.2.1"
    },
    {
      "plugin": "flake8-docstrings",
      "version": "1.0.3, pydocstyle: 1.1.1"
    },
    {
      "plugin": "flake8-string-format",
      "version": "0.2.3"
    },
    {
      "plugin": "flake8_builtins",
      "version": "0.1"
    },
    {
      "plugin": "flake8_coding",
      "version": "1.3.0"
    },
    {
      "plugin": "flake8_copyright",
      "version": "0.2.0"
    },
    {
      "plugin": "flake8_deprecated",
      "version": "1.1"
    },
    {
      "plugin": "mccabe",
      "version": "0.6.1"
    },
    {
      "plugin": "pycodestyle",
      "version": "2.3.1"
    },
    {
      "plugin": "pyflakes",
      "version": "1.5.0"
    }
  ],
  "version": "3.3.0"
}
```

The problem is when checking a source file with a new function which has accented characters.

This is the function:

```
def replace_accent_chars(text, to_be_replaced=None, replacements=None):
    # type: (str, Optional[str], Optional[str]) -> str
    """Replace accent characters with ASCII.

    :param text: text to be corrected.
    :param to_be_replaced: chars to be replaced (default in the code).
    :param replacements: replacement chars (default in the code).
    :return: corrected text.
    """
    assert isinstance(text, str) and text != ''
    assert (to_be_replaced is None
            or (isinstance(to_be_replaced, str) and to_be_replaced != ''))
    assert (replacements is None
            or (isinstance(replacements, str) and replacements != ''))

    if to_be_replaced is None:
        to_be_replaced = 'áàãâäÁÀÃÂÄéèêëÉÈÊËíìîïÍÌÎÏóòõôöÓÒÕÔÖúùûüÚÙÛÜçÇºªñÑ'  # This is the line that trips flake8.

    if replacements is None:
        replacements = 'aaaaaAAAAAeeeeEEEEiiiiIIIIoooooOOOOOuuuuUUUUcCoanN'

    new_text = text  # type: str
    # idx: int
    # char: str
    for idx, char in enumerate(to_be_replaced):
        new_text = new_text.replace(char, replacements[idx])
    return new_text
```

The traceback returned by flake8 is:

```
(my_modules) C:\Users\JMatos\MEOCloud\Python\my_modules\my_modules>flake8 common
.py
Traceback (most recent call last):
  File "c:\python35-32\Lib\runpy.py", line 184, in _run_module_as_main
    "__main__", mod_spec)
  File "c:\python35-32\Lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Users\JMatos\Envs\my_modules\Scripts\flake8.exe\__main__.py", line 9,
 in <module>
  File "c:\users\jmatos\envs\my_modules\lib\site-packages\flake8\main\cli.py", l
ine 16, in main
    app.run(argv)
  File "c:\users\jmatos\envs\my_modules\lib\site-packages\flake8\main\applicatio
n.py", line 328, in run
    self._run(argv)
  File "c:\users\jmatos\envs\my_modules\lib\site-packages\flake8\main\applicatio
n.py", line 316, in _run
    self.run_checks()
  File "c:\users\jmatos\envs\my_modules\lib\site-packages\flake8\main\applicatio
n.py", line 246, in run_checks
    self.file_checker_manager.run()
  File "c:\users\jmatos\envs\my_modules\lib\site-packages\flake8\checker.py", li
ne 319, in run
    self.run_serial()
  File "c:\users\jmatos\envs\my_modules\lib\site-packages\flake8\checker.py", li
ne 303, in run_serial
    checker.run_checks()
  File "c:\users\jmatos\envs\my_modules\lib\site-packages\flake8\checker.py", li
ne 573, in run_checks
    self.run_ast_checks()
  File "c:\users\jmatos\envs\my_modules\lib\site-packages\flake8\checker.py", li
ne 487, in run_ast_checks
    for (line_number, offset, text, check) in runner:
  File "c:\users\jmatos\envs\my_modules\lib\site-packages\flake8_deprecated.py",
 line 32, in run
    for lineno, line in enumerate(f, start=1):
  File "c:\users\jmatos\envs\my_modules\lib\encodings\cp1252.py", line 23, in de
code
    return codecs.charmap_decode(input,self.errors,decoding_table)[0]
UnicodeDecodeError: 'charmap' codec can't decode byte 0x81 in position 5151: cha
racter maps to <undefined>
```

My source code is in utf-8 format and I tried with and without the coding line at the start of the file
```
#!/usr/bin/env python3
# -*- coding: utf-8 -*-
```
Both show the same traceback.

I also tried running flake8 with
`python -m flake8 common.py`
with the same traceback.

If I remove the line with the accented chars flake8 runs fine.

The source file runs (and does what it is supposed to do) without any error under Python 3.

Any ideas?

Best regards,

JM

**Comment by asottile** [comment]
In GitLab by @sigmavirus24 on Apr 22, 2017, 06:46

If you remove `flake8-deprecated`, do you still get this?

I ask because I see that the exception starts in that plugin:

```
  File "c:\users\jmatos\envs\my_modules\lib\site-packages\flake8_deprecated.py",
 line 32, in run
    for lineno, line in enumerate(f, start=1):
  File "c:\users\jmatos\envs\my_modules\lib\encodings\cp1252.py", line 23, in de
code
    return codecs.charmap_decode(input,self.errors,decoding_table)[0]
UnicodeDecodeError: 'charmap' codec can't decode byte 0x81 in position 5151: cha
racter maps to <undefined>
```

I _suspect_ this is actually a bug in that plugin.

**Comment by asottile** [comment]
In GitLab by @jcrmatos on Apr 22, 2017, 09:06

Hello,

I've removed the plugin and flake8 works fine.
Thanks for the help.


Best regards,

JM

**Comment by asottile** [comment]
In GitLab by @jcrmatos on Apr 22, 2017, 09:06

closed
