### ISSUE TITLE
Exception in flake8 with specific file

### ISSUE THREAD

**Issue by asottile** [PyCQA/flake8#582]
In GitLab by @luisgerhorst on May 1, 2017, 12:59

I installed flake8 using `python3 -m pip install flake8`

`flake8 --bug-report`:

```
{
  "dependencies": [
    {
      "dependency": "setuptools",
      "version": "32.2.0"
    }
  ],
  "platform": {
    "python_implementation": "CPython",
    "python_version": "3.6.1",
    "system": "Darwin"
  },
  "plugins": [
    {
      "plugin": "mccabe",
      "version": "0.6.1"
    },
    {
      "plugin": "pycodestyle",
      "version": "2.3.1"
    },
    {
      "plugin": "pyflakes",
      "version": "1.5.0"
    }
  ],
  "version": "3.3.0"
}
```

Here's what I get when I open a python file in Emacs and enable flycheck which uses flake8 to check the syntax:

```
Suspicious state from syntax checker python-flake8: Flycheck checker python-flake8 returned non-zero exit code 1, but its output contained no errors: Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/flake8/checker.py", line 471, in run_ast_checks
    ast = self.processor.build_ast()
  File "/usr/local/lib/python3.6/site-packages/flake8/processor.py", line 211, in build_ast
    return compile(''.join(self.lines), '', 'exec', PyCF_ONLY_AST)
UnicodeEncodeError: 'utf-8' codec can't encode characters in position 1290-1291: surrogates not allowed

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/bin/flake8", line 11, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.6/site-packages/flake8/main/cli.py", line 16, in main
    app.run(argv)
  File "/usr/local/lib/python3.6/site-packages/flake8/main/application.py", line 328, in run
    self._run(argv)
  File "/usr/local/lib/python3.6/site-packages/flake8/main/application.py", line 316, in _run
    self.run_checks()
  File "/usr/local/lib/python3.6/site-packages/flake8/main/application.py", line 246, in run_checks
    self.file_checker_manager.run()
  File "/usr/local/lib/python3.6/site-packages/flake8/checker.py", line 319, in run
    self.run_serial()
  File "/usr/local/lib/python3.6/site-packages/flake8/checker.py", line 303, in run_serial
    checker.run_checks()
  File "/usr/local/lib/python3.6/site-packages/flake8/checker.py", line 573, in run_checks
    self.run_ast_checks()
  File "/usr/local/lib/python3.6/site-packages/flake8/checker.py", line 474, in run_ast_checks
    row, column = self._extract_syntax_information(exception)
  File "/usr/local/lib/python3.6/site-packages/flake8/checker.py", line 441, in _extract_syntax_information
    if column > 0 and token and isinstance(exception, SyntaxError):
TypeError: '>' not supported between instances of 'str' and 'int'

Try installing a more recent version of python-flake8, and please open a bug report if the issue persists in the latest release.  Thanks!
```

I guess this has something to do with the encoding of the file so here it is: [float.py](/uploads/38aefdecacc4dc2a32a2880119194215/float.py) When I use another file it works.

**Comment by asottile** [comment]
In GitLab by @luisgerhorst on May 1, 2017, 13:08

closed
