### ISSUE TITLE
2.2.5: test failure: AttributeError: 'FinalizingSuiteWrapper' object has no attribute '_removed_tests'

### ISSUE THREAD

**Issue by asottile** [PyCQA/flake8#62]
In GitLab by @_wiz_ on Jan 2, 2015, 16:30

On NetBSD with python-3.4.2 I see the following issue when running the tests:
````
running build_ext
test_get_parser (flake8.tests.test_engine.TestEngine) ... ok
test_get_python_version (flake8.tests.test_engine.TestEngine) ... ok
test_get_style_guide (flake8.tests.test_engine.TestEngine) ... ok
test_get_style_guide_kwargs (flake8.tests.test_engine.TestEngine) ... ok
test_register_extensions (flake8.tests.test_engine.TestEngine) ... ok
test_stdin_disables_jobs (flake8.tests.test_engine.TestEngine) ... ok
test_windows_disables_jobs (flake8.tests.test_engine.TestEngine) ... ok
Traceback (most recent call last):
  File "setup.py", line 74, in <module>
    test_suite='nose.collector',
  File "/usr/pkg/lib/python3.4/distutils/core.py", line 148, in setup
    dist.run_commands()
  File "/usr/pkg/lib/python3.4/distutils/dist.py", line 955, in run_commands
    self.run_command(cmd)
  File "/usr/pkg/lib/python3.4/distutils/dist.py", line 974, in run_command
    cmd_obj.run()
  File "/usr/pkg/lib/python3.4/site-packages/setuptools/command/test.py", line 142, in run
    self.with_project_on_sys_path(self.run_tests)
  File "/usr/pkg/lib/python3.4/site-packages/setuptools/command/test.py", line 122, in with_project_on_sys_path
    func()
  File "/usr/pkg/lib/python3.4/site-packages/setuptools/command/test.py", line 163, in run_tests
    testRunner=self._resolve_as_ep(self.test_runner),
  File "/usr/pkg/lib/python3.4/unittest/main.py", line 93, in __init__
    self.runTests()
  File "/usr/pkg/lib/python3.4/unittest/main.py", line 244, in runTests
    self.result = testRunner.run(self.test)
  File "/usr/pkg/lib/python3.4/unittest/runner.py", line 168, in run
    test(result)
  File "/usr/pkg/lib/python3.4/unittest/suite.py", line 87, in __call__
    return self.run(*args, **kwds)
  File "/usr/pkg/lib/python3.4/unittest/suite.py", line 130, in run
    self._removeTestAtIndex(index)
  File "/usr/pkg/lib/python3.4/unittest/suite.py", line 83, in _removeTestAtIndex
    self._removed_tests += test.countTestCases()
  File "/usr/pkg/lib/python3.4/unittest/suite.py", line 41, in countTestCases
    cases = self._removed_tests
AttributeError: 'FinalizingSuiteWrapper' object has no attribute '_removed_tests'
*** Error code 1
````

**Comment by asottile** [comment]
In GitLab by @sigmavirus24 on Jan 2, 2015, 17:05

That looks (at first glance) to be caused by unittest not flake8's tests.

**Comment by asottile** [comment]
In GitLab by @_wiz_ on Jan 3, 2015, 11:40

Based on your comment I have reported this at http://bugs.python.org/issue23155

**Comment by asottile** [comment]
In GitLab by @sigmavirus24 on Jan 6, 2015, 06:50

@_wiz_ out of curiousity, how're you running the tests? Did you try using `tox`? If not did you do `python setup.py test -q`?

**Comment by asottile** [comment]
In GitLab by @_wiz_ on Jan 6, 2015, 07:36

I don't use tox. I just run `python setup.py test`. I get the same error with `python setup.py test -q`.

**Comment by asottile** [comment]
In GitLab by @sigmavirus24 on Jan 6, 2015, 07:55

So as I mentioned on the bpo issue, it could also be an issue with NetBSD's distribution of Python 3.4.2. I've tried 3.4.2 on different architectures and operating systems and can't reproduce this with Flake8's test suite.

**Comment by asottile** [comment]
In GitLab by @_wiz_ on Jan 6, 2015, 08:07

Of course, that's a possibility, but it doesn't look like an issue in the core executable, and there are no patches to unittest in pkgsrc. You can see all patches here:

http://cvsweb.netbsd.org/bsdweb.cgi/pkgsrc/lang/python34/patches/

**Comment by asottile** [comment]
In GitLab by @sigmavirus24 on Jan 24, 2015, 11:33

@_wiz_ any updates on this?

**Comment by asottile** [comment]
In GitLab by @_wiz_ on Jan 24, 2015, 11:53

No. I never heard from the python people and I don't know how to debug this. Ideas?

**Comment by asottile** [comment]
In GitLab by @sigmavirus24 on Jan 24, 2015, 12:51

I'm currently installing freebsd to try to reproduce this.

**Comment by asottile** [comment]
In GitLab by @sigmavirus24 on Jan 24, 2015, 13:13

Well, I can't get netbsd to install Python currently and I have much higher priorities than this. I've tested on 3.4.2 on ubuntu, osx, and debian and can't reproduce this. This seems to emphatically not be a bug in Flake8 so I'm closing it.

**Comment by asottile** [comment]
In GitLab by @_wiz_ on Jan 24, 2015, 13:21

Once you have installed NetBSD, 'pkg_add python34' should install python-3.4.x for you.
