### ISSUE TITLE
UnicodeEncodeError when path contains non-ascii characters (linter-flake8 Atom plugin)

### ISSUE THREAD

**Issue by asottile** [PyCQA/flake8#654]
In GitLab by @cbrnr on May 15, 2018, 03:34

I'm using Flake8 installed via `pip` and I'm using it in Atom via the [linter-flake8](https://github.com/AtomLinter/linter-flake8) plugin. Whenever the path (which includes the file name) contains a non-ascii character (e.g. the German ü), I get a warning message in Atom, which is caused by a `UnicodeEncodeError` in `flake8`:

```
linter-flake8:: Flake8 returned an error Traceback (most recent call last):
  File "/usr/local/bin/flake8", line 11, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.6/site-packages/flake8/main/cli.py", line 16, in main
    app.run(argv)
  File "/usr/local/lib/python3.6/site-packages/flake8/main/application.py", line 396, in run
    self._run(argv)
  File "/usr/local/lib/python3.6/site-packages/flake8/main/application.py", line 385, in _run
    self.report()
  File "/usr/local/lib/python3.6/site-packages/flake8/main/application.py", line 376, in report
    self.report_errors()
  File "/usr/local/lib/python3.6/site-packages/flake8/main/application.py", line 340, in report_errors
    results = self.file_checker_manager.report()
  File "/usr/local/lib/python3.6/site-packages/flake8/checker.py", line 267, in report
    results_reported += self._handle_results(filename, results)
  File "/usr/local/lib/python3.6/site-packages/flake8/checker.py", line 166, in _handle_results
    physical_line=physical_line,
  File "/usr/local/lib/python3.6/site-packages/flake8/style_guide.py", line 392, in handle_error
    self.formatter.handle(error)
  File "/usr/local/lib/python3.6/site-packages/flake8/formatting/base.py", line 88, in handle
    self.write(line, source)
  File "/usr/local/lib/python3.6/site-packages/flake8/formatting/base.py", line 191, in write
    self._write(line)
  File "/usr/local/lib/python3.6/site-packages/flake8/formatting/base.py", line 175, in _write
    print(output)
UnicodeEncodeError: 'ascii' codec can't encode character '\u0308' in position 24: ordinal not in range(128)
```

This error disappears if I remove the non-ascii characters from the file name/path.

Note that this error does not occur if I run `flake8` directly in a terminal. Therefore, I'm not sure if this is a problem that Flake8 can fix.

**Comment by asottile** [comment]
In GitLab by @sigmavirus24 on May 15, 2018, 05:38

It is entirely likely that `locale` in your terminal does not match `locale` in Atom. That would make this a bug with either Atom or linter-flake8. Perhaps @Arcanemagus can help us with this?

**Comment by asottile** [comment]
In GitLab by @cbrnr on May 16, 2018, 01:11

Thanks @sigmavirus24, I've created an issue there (https://github.com/AtomLinter/linter-flake8/issues/603). My locale is en_US.UTF-8, and I'm not sure how to determine this setting in Atom.

**Comment by asottile** [comment]
In GitLab by @sigmavirus24 on Oct 20, 2018, 10:23

closed
