### ISSUE TITLE
release 3.7.1 is incompatible with / breaks when flake8-per-file-ignores is installed

### ISSUE THREAD

**Issue by asottile** [PyCQA/flake8#671]
In GitLab by @oseiberts11 on Jan 30, 2019, 08:38

Please read this brief portion of documentation before going any further: http://flake8.pycqa.org/en/latest/internal/contributing.html#filing-a-bug

*Please describe how you installed Flake8*

```
$ virtualenv --python python3.5 ./venv
Running virtualenv with interpreter /usr/bin/python3.5
Using base prefix '/usr'
New python executable in /home/oseibert/underlay/midoquery/venv/bin/python3.5
Also creating executable in /home/oseibert/underlay/midoquery/venv/bin/python
Installing setuptools, pkg_resources, pip, wheel...done.
$ . venv/bin/activate
(venv) $ pip3 install tox
Collecting tox
  Using cached https://files.pythonhosted.org/packages/4a/bd/50cd91221508db5bb66e211ac327d0da4a5db6d0db5ad35d6fbf1e4af5dc/tox-3.7.0-py2.py3-none-any.whl
Collecting py<2,>=1.4.17 (from tox)
  Using cached https://files.pythonhosted.org/packages/3e/c7/3da685ef117d42ac8d71af525208759742dd235f8094221fdaafcd3dba8f/py-1.7.0-py2.py3-none-any.whl
Collecting toml>=0.9.4 (from tox)
  Using cached https://files.pythonhosted.org/packages/a2/12/ced7105d2de62fa7c8fb5fce92cc4ce66b57c95fb875e9318dba7f8c5db0/toml-0.10.0-py2.py3-none-any.whl
Requirement already satisfied: setuptools>=30.0.0 in ./venv/lib/python3.5/site-packages (from tox) (40.7.1)
Collecting filelock<4,>=3.0.0 (from tox)
  Using cached https://files.pythonhosted.org/packages/d7/ca/3c74396a9ed8a4cfab5459800edeef9a1269591cb21f5a49bd71a49c5fa2/filelock-3.0.10-py3-none-any.whl
Collecting pluggy<1,>=0.3.0 (from tox)
  Using cached https://files.pythonhosted.org/packages/2d/60/f58d9e8197f911f9405bf7e02227b43a2acc2c2f1a8cbb1be5ecf6bfd0b8/pluggy-0.8.1-py2.py3-none-any.whl
Collecting virtualenv>=1.11.2 (from tox)
  Using cached https://files.pythonhosted.org/packages/8f/f1/c0b069ca6cb44f9681715232e6d3d65c75866dd231c5e4a88e80a46634bb/virtualenv-16.3.0-py2.py3-none-any.whl
Collecting six<2,>=1.0.0 (from tox)
  Using cached https://files.pythonhosted.org/packages/73/fb/00a976f728d0d1fecfe898238ce23f502a721c0ac0ecfedb80e0d88c64e9/six-1.12.0-py2.py3-none-any.whl
Installing collected packages: py, toml, filelock, pluggy, virtualenv, six, tox
Successfully installed filelock-3.0.10 pluggy-0.8.1 py-1.7.0 six-1.12.0 toml-0.10.0 tox-3.7.0 virtualenv-16.3.0
(venv) $ tox
GLOB sdist-make: /home/oseibert/underlay/midoquery/setup.py
lint inst-nodeps: /home/oseibert/underlay/midoquery/.tox/.tmp/package/1/midoquery-0.1.0.zip
lint installed: attrs==18.2.0,certifi==2018.11.29,chardet==3.0.4,entrypoints==0.3,flake8==3.7.1,flake8-bugbear==18.8.0,flake8-commas==2.0.0,flake8-docstrings==1.3.0,flake8-import-order==0.18,flake8-per-file-ignores==0.7,flake8-polyfill==1.0.2,idna==2.8,mccabe==0.6.1,midoquery==0.1.0,pathmatch==0.2.1,pep8-naming==0.8.0,pycodestyle==2.5.0,pydocstyle==3.0.0,pyflakes==2.1.0,requests==2.21.0,six==1.12.0,snowballstemmer==1.2.1,typing==3.6.6,urllib3==1.24.1
lint run-test-pre: PYTHONHASHSEED='1144981324'
lint runtests: commands[0] | flake8 midoquery/
Traceback (most recent call last):
  File "/home/oseibert/underlay/midoquery/.tox/lint/bin/flake8", line 10, in <module>
    sys.exit(main())
  File "/home/oseibert/underlay/midoquery/.tox/lint/lib/python3.5/site-packages/flake8/main/cli.py", line 18, in main
    app.run(argv)
  File "/home/oseibert/underlay/midoquery/.tox/lint/lib/python3.5/site-packages/flake8/main/application.py", line 392, in run
    self._run(argv)
  File "/home/oseibert/underlay/midoquery/.tox/lint/lib/python3.5/site-packages/flake8/main/application.py", line 379, in _run
    self.initialize(argv)
  File "/home/oseibert/underlay/midoquery/.tox/lint/lib/python3.5/site-packages/flake8/main/application.py", line 363, in initialize
    self.register_plugin_options()
  File "/home/oseibert/underlay/midoquery/.tox/lint/lib/python3.5/site-packages/flake8/main/application.py", line 204, in register_plugin_options
    self.check_plugins.register_options(self.option_manager)
  File "/home/oseibert/underlay/midoquery/.tox/lint/lib/python3.5/site-packages/flake8/plugins/manager.py", line 490, in register_options
    list(self.manager.map(register_and_enable))
  File "/home/oseibert/underlay/midoquery/.tox/lint/lib/python3.5/site-packages/flake8/plugins/manager.py", line 296, in map
    yield func(self.plugins[name], *args, **kwargs)
  File "/home/oseibert/underlay/midoquery/.tox/lint/lib/python3.5/site-packages/flake8/plugins/manager.py", line 486, in register_and_enable
    call_register_options(plugin)
  File "/home/oseibert/underlay/midoquery/.tox/lint/lib/python3.5/site-packages/flake8/plugins/manager.py", line 398, in generated_function
    return method(optmanager, *args, **kwargs)
  File "/home/oseibert/underlay/midoquery/.tox/lint/lib/python3.5/site-packages/flake8/plugins/manager.py", line 221, in register_options
    add_options(optmanager)
  File "/home/oseibert/underlay/midoquery/.tox/lint/lib/python3.5/site-packages/flake8_per_file_ignores.py", line 82, in add_options
    parser.add_option('--per-file-ignores', parse_from_config=True)
  File "/home/oseibert/underlay/midoquery/.tox/lint/lib/python3.5/site-packages/flake8/options/manager.py", line 230, in add_option
    self.parser.add_option(option.to_optparse())
  File "/usr/lib/python3.5/optparse.py", line 1007, in add_option
    self._check_conflict(option)
  File "/usr/lib/python3.5/optparse.py", line 982, in _check_conflict
    option)
optparse.OptionConflictError: option --per-file-ignores: conflicting option string(s): --per-file-ignores
ERROR: InvocationError for command '/home/oseibert/underlay/midoquery/.tox/lint/bin/flake8 midoquery/' (exited with code 1)
py35 inst-nodeps: /home/oseibert/underlay/midoquery/.tox/.tmp/package/1/midoquery-0.1.0.zip
py35 installed: atomicwrites==1.2.1,attrs==18.2.0,certifi==2018.11.29,chardet==3.0.4,idna==2.8,midoquery==0.1.0,mock==2.0.0,more-itertools==5.0.0,pathlib2==2.3.3,pbr==5.1.1,pluggy==0.8.1,py==1.7.0,pytest==4.1.1,requests==2.21.0,six==1.12.0,urllib3==1.24.1
py35 run-test-pre: PYTHONHASHSEED='1144981324'
py35 runtests: commands[0] | pytest
============================================================ test session starts ============================================================
platform linux -- Python 3.5.2, pytest-4.1.1, py-1.7.0, pluggy-0.8.1
cachedir: .tox/py35/.pytest_cache
rootdir: /home/oseibert/underlay/midoquery, inifile:
collected 19 items

tests/test_print_dict.py .                                                                                                            [  5%]
tests/test_show_result.py .......                                                                                                     [ 42%]
tests/test_table.py ...........                                                                                                       [100%]

========================================================= 19 passed in 0.08 seconds =========================================================
__________________________________________________________________ summary __________________________________________________________________
ERROR:   lint: commands failed
  py35: commands succeeded
$
```

tox.ini contains among others:
```
testenv:lint]
deps =
    flake8
    flake8-bugbear
    flake8-commas
    flake8-docstrings
    flake8-import-order
    flake8-per-file-ignores
    mccabe
    pep8-naming
```

*Please provide the exact, unmodified output of `flake8 --bug-report`*

```
(venv) $ flake8 --bug-report
The program 'flake8' is currently not installed. You can install it by typing:
sudo apt install flake8
(venv) $
(venv) $
(venv) $ .tox/lint/bin/flake8 --bug-report
Traceback (most recent call last):
  File ".tox/lint/bin/flake8", line 10, in <module>
    sys.exit(main())
  File "/home/oseibert/underlay/midoquery/.tox/lint/lib/python3.5/site-packages/flake8/main/cli.py", line 18, in main
    app.run(argv)
  File "/home/oseibert/underlay/midoquery/.tox/lint/lib/python3.5/site-packages/flake8/main/application.py", line 392, in run
    self._run(argv)
  File "/home/oseibert/underlay/midoquery/.tox/lint/lib/python3.5/site-packages/flake8/main/application.py", line 379, in _run
    self.initialize(argv)
  File "/home/oseibert/underlay/midoquery/.tox/lint/lib/python3.5/site-packages/flake8/main/application.py", line 363, in initialize
    self.register_plugin_options()
  File "/home/oseibert/underlay/midoquery/.tox/lint/lib/python3.5/site-packages/flake8/main/application.py", line 204, in register_plugin_options
    self.check_plugins.register_options(self.option_manager)
  File "/home/oseibert/underlay/midoquery/.tox/lint/lib/python3.5/site-packages/flake8/plugins/manager.py", line 490, in register_options
    list(self.manager.map(register_and_enable))
  File "/home/oseibert/underlay/midoquery/.tox/lint/lib/python3.5/site-packages/flake8/plugins/manager.py", line 296, in map
    yield func(self.plugins[name], *args, **kwargs)
  File "/home/oseibert/underlay/midoquery/.tox/lint/lib/python3.5/site-packages/flake8/plugins/manager.py", line 486, in register_and_enable
    call_register_options(plugin)
  File "/home/oseibert/underlay/midoquery/.tox/lint/lib/python3.5/site-packages/flake8/plugins/manager.py", line 398, in generated_function
    return method(optmanager, *args, **kwargs)
  File "/home/oseibert/underlay/midoquery/.tox/lint/lib/python3.5/site-packages/flake8/plugins/manager.py", line 221, in register_options
    add_options(optmanager)
  File "/home/oseibert/underlay/midoquery/.tox/lint/lib/python3.5/site-packages/flake8_per_file_ignores.py", line 82, in add_options
    parser.add_option('--per-file-ignores', parse_from_config=True)
  File "/home/oseibert/underlay/midoquery/.tox/lint/lib/python3.5/site-packages/flake8/options/manager.py", line 230, in add_option
    self.parser.add_option(option.to_optparse())
  File "/usr/lib/python3.5/optparse.py", line 1007, in add_option
    self._check_conflict(option)
  File "/usr/lib/python3.5/optparse.py", line 982, in _check_conflict
    option)
optparse.OptionConflictError: option --per-file-ignores: conflicting option string(s): --per-file-ignores
```
*Please describe the problem or feature*

flake8 breaks totally if you use the `flake8-per-file-ignores` plugin.

From searching for the string "per-file-ignores", it seems that the functionality of the plugin is now in the main program, but I was unable to find any release notes detailing such a change. In fact I was unable to locate any release notes at all. I expected to find those starting from https://pypi.org/project/flake8/3.7.1/#history, but I had no such luck.

Any such functionality changes should be handled more gracefully and be docmented.

**Comment by asottile** [comment]
In GitLab by @asottile on Jan 30, 2019, 08:41

This is documented in the [3.7.0 release notes](https://gitlab.com/pycqa/flake8/blob/master/docs/source/release-notes/3.7.0.rst)

**Comment by asottile** [comment]
In GitLab by @asottile on Jan 30, 2019, 08:41

closed

**Comment by asottile** [comment]
In GitLab by @oseiberts11 on Jan 30, 2019, 08:44

Why can't I find those linked from https://pypi.org/project/flake8/3.7.1/#history which is the first place to look?

Nevertheless, such a breaking change should be handled more gracefully.

And in any case, the breakage I mention is *not* documented in those release notes at all.

**Comment by asottile** [comment]
In GitLab by @oseiberts11 on Jan 30, 2019, 08:46

The release notes are also not visible from https://gitlab.com/pycqa/flake8/releases which is the other place where one might find releases. So I still have no idea how I would have found the release notes.

**Comment by asottile** [comment]
In GitLab by @asottile on Jan 30, 2019, 08:49

They are available through http://flake8.pycqa.org/en/latest/release-notes/index.html which is linked from the pypi page

there's something currently broken with the documentation upload right now and unfortunately I have no control over it

**Comment by asottile** [comment]
In GitLab by @asottile on Jan 30, 2019, 08:52

I've created https://gitlab.com/pycqa/flake8/issues/496 to track the docs not updating

**Comment by asottile** [comment]
In GitLab by @timhoffm on Jan 30, 2019, 13:54

It's correctly documented that flake8 now supports per-file-ignores out of the box.

However, it would have been good to note that the per-files-ignores plugin must not be installed. Or even better, ignore the plugin and issue a warning to get a smooth transition for the existing users of per-file-ignores. Just breaking with the cryptic `optparse.OptionConflictError` is a bit unhelpful.

**Comment by asottile** [comment]
In GitLab by @asottile on Jan 30, 2019, 19:00

mentioned in merge request !297

**Comment by asottile** [comment]
In GitLab by @asottile on Jan 30, 2019, 19:58

flake8 3.7.3 (just released) will skip `flake8-per-file-ignores` to prevent the stacktrace
