### ISSUE TITLE
pyflakes messaging format changed for "referenced before assignment"

### ISSUE THREAD

**Issue by asottile** [PyCQA/flake8#679]
In GitLab by @asottile on Jan 31, 2019, 21:41

I found this one accidentally :S

```python
import x


def s():
    x = x
```

```
$ flake8 --bug-report
{
  "dependencies": [
    {
      "dependency": "entrypoints",
      "version": "0.3"
    }
  ],
  "platform": {
    "python_implementation": "CPython",
    "python_version": "3.6.7",
    "system": "Linux"
  },
  "plugins": [
    {
      "is_local": false,
      "plugin": "mccabe",
      "version": "0.6.1"
    },
    {
      "is_local": false,
      "plugin": "pycodestyle",
      "version": "2.5.0"
    },
    {
      "is_local": false,
      "plugin": "pyflakes",
      "version": "2.1.0"
    }
  ],
  "version": "3.7.4"
}
$ flake8 -j1 t.py 
Traceback (most recent call last):
  File "/tmp/venv/bin/flake8", line 10, in <module>
    sys.exit(main())
  File "/tmp/venv/lib/python3.6/site-packages/flake8/main/cli.py", line 18, in main
    app.run(argv)
  File "/tmp/venv/lib/python3.6/site-packages/flake8/main/application.py", line 393, in run
    self._run(argv)
  File "/tmp/venv/lib/python3.6/site-packages/flake8/main/application.py", line 381, in _run
    self.run_checks()
  File "/tmp/venv/lib/python3.6/site-packages/flake8/main/application.py", line 300, in run_checks
    self.file_checker_manager.run()
  File "/tmp/venv/lib/python3.6/site-packages/flake8/checker.py", line 332, in run
    self.run_serial()
  File "/tmp/venv/lib/python3.6/site-packages/flake8/checker.py", line 316, in run_serial
    checker.run_checks()
  File "/tmp/venv/lib/python3.6/site-packages/flake8/checker.py", line 616, in run_checks
    self.run_ast_checks()
  File "/tmp/venv/lib/python3.6/site-packages/flake8/checker.py", line 512, in run_ast_checks
    for (line_number, offset, text, check) in runner:
  File "/tmp/venv/lib/python3.6/site-packages/flake8/plugins/pyflakes.py", line 191, in run
    (message.flake8_msg % message.message_args),
TypeError: not all arguments converted during string formatting
```

This is where it was changed in pyflakes.  Quite annoying that they're mixing two string formatting approaches: https://github.com/PyCQA/pyflakes/commit/fb1f223ac2141772f140be6f1108d02009c1d658#diff-c90fb97304a204835e9c3fd69ab6cbef

**Comment by asottile** [comment]
In GitLab by @asottile on Jan 31, 2019, 21:55

mentioned in merge request !302

**Comment by asottile** [comment]
In GitLab by @asottile on Feb 1, 2019, 14:54

mentioned in commit a35ed4a998e959f73ba48024de400b5df300e11d

**Comment by asottile** [comment]
In GitLab by @asottile on Feb 1, 2019, 14:54

closed via merge request !302
