### ISSUE TITLE
"pyflakes" failed during execution due to "'ExceptHandler' object has no attribute 'depth'" [REPLACEMENT ISSUE]

### ISSUE THREAD

**Issue by asottile** [PyCQA/flake8#702]
The original issue

	Id: 536
	Title: "pyflakes" failed during execution due to "'ExceptHandler' object has no attribute 'depth'"

could not be created.
This is a dummy issue, replacing the original one. It contains everything but the original issue description. In case the gitlab repository is still existing, visit the following link to show the original issue:

TODO

**Comment by asottile** [comment]
In GitLab by @asottile on May 2, 2019, 23:18

I can at least reproduce this, it only seems to happen when using `flake8-bandit` and only when the bandit plugin runs before the pyflakes one.

I suspect there's something sketchy that bandit / flake8-bandit is doing which disrupts pyflakes but I have yet to track it down.

Of note, I can't reproduce in python3.6 -- the plugin ordering randomization appears to be a dict-key-ordering somewhere if I had to guess

**Comment by asottile** [comment]
In GitLab by @asottile on May 2, 2019, 23:20

Here's a more complete stacktrace:

```
Traceback (most recent call last):
  File "/tmp/t/venv/lib/python3.5/site-packages/flake8/plugins/pyflakes.py", line 94, in __init__
    file_tokens=file_tokens,
  File "/tmp/t/venv/lib/python3.5/site-packages/pyflakes/checker.py", line 673, in __init__
    self.runDeferred(self._deferredFunctions)
  File "/tmp/t/venv/lib/python3.5/site-packages/pyflakes/checker.py", line 710, in runDeferred
    handler()
  File "/tmp/t/venv/lib/python3.5/site-packages/pyflakes/checker.py", line 1474, in runFunction
    self.handleChildren(node, omit='decorator_list')
  File "/tmp/t/venv/lib/python3.5/site-packages/pyflakes/checker.py", line 1073, in handleChildren
    self.handleNode(node, tree)
  File "/tmp/t/venv/lib/python3.5/site-packages/pyflakes/checker.py", line 1120, in handleNode
    handler(node)
  File "/tmp/t/venv/lib/python3.5/site-packages/pyflakes/checker.py", line 1623, in TRY
    self.handleNode(child, node)
  File "/tmp/t/venv/lib/python3.5/site-packages/pyflakes/checker.py", line 1120, in handleNode
    handler(node)
  File "/tmp/t/venv/lib/python3.5/site-packages/pyflakes/checker.py", line 1073, in handleChildren
    self.handleNode(node, tree)
  File "/tmp/t/venv/lib/python3.5/site-packages/pyflakes/checker.py", line 1120, in handleNode
    handler(node)
  File "/tmp/t/venv/lib/python3.5/site-packages/pyflakes/checker.py", line 1073, in handleChildren
    self.handleNode(node, tree)
  File "/tmp/t/venv/lib/python3.5/site-packages/pyflakes/checker.py", line 1120, in handleNode
    handler(node)
  File "/tmp/t/venv/lib/python3.5/site-packages/pyflakes/checker.py", line 1353, in NAME
    self.handleNodeStore(node)
  File "/tmp/t/venv/lib/python3.5/site-packages/pyflakes/checker.py", line 1017, in handleNodeStore
    self.addBinding(node, binding)
  File "/tmp/t/venv/lib/python3.5/site-packages/pyflakes/checker.py", line 876, in addBinding
    not self.differentForks(node, existing.source)):
  File "/tmp/t/venv/lib/python3.5/site-packages/pyflakes/checker.py", line 857, in differentForks
    if self.descendantOf(lnode, items, ancestor) ^ \
  File "/tmp/t/venv/lib/python3.5/site-packages/pyflakes/checker.py", line 835, in descendantOf
    if self.getCommonAncestor(node, a, stop):
  File "/tmp/t/venv/lib/python3.5/site-packages/pyflakes/checker.py", line 827, in getCommonAncestor
    if (lnode.depth > rnode.depth):
AttributeError: 'ExceptHandler' object has no attribute 'depth'
```

**Comment by asottile** [comment]
In GitLab by @asottile on May 2, 2019, 23:45

These two lines don't play well together:

https://github.com/PyCQA/bandit/blob/823138f418905a99fb7bbff8bb35b97f6dc9e5ab/bandit/core/node_visitor.py#L240

https://github.com/PyCQA/pyflakes/blob/232cb1d27ee134bf96adc8f37e53589dc259b159/pyflakes/checker.py#L830-L831

https://github.com/PyCQA/pyflakes/blob/232cb1d27ee134bf96adc8f37e53589dc259b159/pyflakes/checker.py#L1126

Both bandit and pyflakes monkeypatch the ast nodes, then inspect that state later.  In this case, the bandit monkeypatching interferes with pyflakes detection of its own monkeypatching.

Since this is not an issue with flake8 but with the plugins themselves I'd suggest reporting that information there.

For what it's worth, here's a reproduction without flake8:

```pycon
>>> from bandit.core.config import BanditConfig
>>> from bandit.core.meta_ast import BanditMetaAst
>>> from bandit.core.metrics import Metrics
>>> from bandit.core.node_visitor import BanditNodeVisitor
>>> from bandit.core.test_set import BanditTestSet
>>> from pyflakes.checker import Checker
>>> import ast
>>> profile = {}
>>> bnv = BanditNodeVisitor(
...     'filename',
...     BanditMetaAst(),
...     BanditTestSet(BanditConfig(), profile=profile),
...     False,
...     [],
...     Metrics(),
... )
>>> tree = ast.parse("""def test():
...     try:
...         x = 5
...         if True:
...             x = 10  # noqa: F841
...     except AttributeError:
...         pass
... """)
>>> bnv.generic_visit(tree)
>>> Checker(tree=tree)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/tmp/t/venv/lib/python3.5/site-packages/pyflakes/checker.py", line 673, in __init__
    self.runDeferred(self._deferredFunctions)
  File "/tmp/t/venv/lib/python3.5/site-packages/pyflakes/checker.py", line 710, in runDeferred
    handler()
  File "/tmp/t/venv/lib/python3.5/site-packages/pyflakes/checker.py", line 1474, in runFunction
    self.handleChildren(node, omit='decorator_list')
  File "/tmp/t/venv/lib/python3.5/site-packages/pyflakes/checker.py", line 1073, in handleChildren
    self.handleNode(node, tree)
  File "/tmp/t/venv/lib/python3.5/site-packages/pyflakes/checker.py", line 1120, in handleNode
    handler(node)
  File "/tmp/t/venv/lib/python3.5/site-packages/pyflakes/checker.py", line 1623, in TRY
    self.handleNode(child, node)
  File "/tmp/t/venv/lib/python3.5/site-packages/pyflakes/checker.py", line 1120, in handleNode
    handler(node)
  File "/tmp/t/venv/lib/python3.5/site-packages/pyflakes/checker.py", line 1073, in handleChildren
    self.handleNode(node, tree)
  File "/tmp/t/venv/lib/python3.5/site-packages/pyflakes/checker.py", line 1120, in handleNode
    handler(node)
  File "/tmp/t/venv/lib/python3.5/site-packages/pyflakes/checker.py", line 1073, in handleChildren
    self.handleNode(node, tree)
  File "/tmp/t/venv/lib/python3.5/site-packages/pyflakes/checker.py", line 1120, in handleNode
    handler(node)
  File "/tmp/t/venv/lib/python3.5/site-packages/pyflakes/checker.py", line 1353, in NAME
    self.handleNodeStore(node)
  File "/tmp/t/venv/lib/python3.5/site-packages/pyflakes/checker.py", line 1017, in handleNodeStore
    self.addBinding(node, binding)
  File "/tmp/t/venv/lib/python3.5/site-packages/pyflakes/checker.py", line 876, in addBinding
    not self.differentForks(node, existing.source)):
  File "/tmp/t/venv/lib/python3.5/site-packages/pyflakes/checker.py", line 857, in differentForks
    if self.descendantOf(lnode, items, ancestor) ^ \
  File "/tmp/t/venv/lib/python3.5/site-packages/pyflakes/checker.py", line 835, in descendantOf
    if self.getCommonAncestor(node, a, stop):
  File "/tmp/t/venv/lib/python3.5/site-packages/pyflakes/checker.py", line 827, in getCommonAncestor
    if (lnode.depth > rnode.depth):
AttributeError: 'ExceptHandler' object has no attribute 'depth'
```

**Comment by asottile** [comment]
In GitLab by @asottile on May 2, 2019, 23:53

I made https://github.com/PyCQA/pyflakes/pull/444 which should at least fix it from the pyflakes side -- since there's nothing really that flake8 can do here I'm going to close this

**Comment by asottile** [comment]
In GitLab by @asottile on May 2, 2019, 23:53

closed

**Comment by asottile** [comment]
In GitLab by @wuck on May 3, 2019, 24:29

I just tested on Windows 10.  I can reproduce it on 3.5.3-amd64 but not the latest 3.7.3-amd64.

**Comment by asottile** [comment]
In GitLab by @wuck on May 3, 2019, 24:30

Thanks. I'll take a closer look at this to see if I should report other bugs.

**Comment by asottile** [comment]
In GitLab by @wuck on May 5, 2019, 19:40

Reported to bandit at https://github.com/PyCQA/bandit/issues/487
