### ISSUE TITLE
flake8 --max-line-length abc => AttributeError (during preliminary argument parsing)

### ISSUE THREAD

**Issue by asottile** [PyCQA/flake8#704]
In GitLab by @asottile on May 19, 2019, 16:19

```
$ pip install -e .  # latest git
```

```console
$ flake8 src --max-line-length abc
Traceback (most recent call last):
  File "/usr/lib/python3.6/optparse.py", line 430, in check_builtin
    return cvt(value)
  File "/usr/lib/python3.6/optparse.py", line 420, in _parse_int
    return _parse_num(val, int)
  File "/usr/lib/python3.6/optparse.py", line 417, in _parse_num
    return type(val, radix)
ValueError: invalid literal for int() with base 10: 'abc'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/asottile/workspace/flake8/src/flake8/options/manager.py", line 340, in parse_known_args
    self.parser._process_args(largs, rargs, values)
  File "/usr/lib/python3.6/optparse.py", line 1427, in _process_args
    self._process_long_opt(rargs, values)
  File "/usr/lib/python3.6/optparse.py", line 1501, in _process_long_opt
    option.process(opt, value, values, self)
  File "/usr/lib/python3.6/optparse.py", line 779, in process
    value = self.convert_value(opt, value)
  File "/usr/lib/python3.6/optparse.py", line 771, in convert_value
    return self.check_value(opt, value)
  File "/usr/lib/python3.6/optparse.py", line 766, in check_value
    return checker(self, opt, value)
  File "/usr/lib/python3.6/optparse.py", line 433, in check_builtin
    _("option %s: invalid %s value: %r") % (opt, what, value))
optparse.OptionValueError: option --max-line-length: invalid integer value: 'abc'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/asottile/workspace/flake8/venv/bin/flake8", line 11, in <module>
    load_entry_point('flake8', 'console_scripts', 'flake8')()
  File "/home/asottile/workspace/flake8/src/flake8/main/cli.py", line 18, in main
    app.run(argv)
  File "/home/asottile/workspace/flake8/src/flake8/main/application.py", line 394, in run
    self._run(argv)
  File "/home/asottile/workspace/flake8/src/flake8/main/application.py", line 381, in _run
    self.initialize(argv)
  File "/home/asottile/workspace/flake8/src/flake8/main/application.py", line 359, in initialize
    self.parse_preliminary_options_and_args(argv)
  File "/home/asottile/workspace/flake8/src/flake8/main/application.py", line 139, in parse_preliminary_options_and_args
    opts, args = self.option_manager.parse_known_args(args)
  File "/home/asottile/workspace/flake8/src/flake8/options/manager.py", line 345, in parse_known_args
    largs.append(err.opt_str)
AttributeError: 'OptionValueError' object has no attribute 'opt_str'
```

mypy found this bug while I was adding type annotations, I'm going to `# type: ignore` in this branch for now as the branch is getting pretty big already!

**Comment by asottile** [comment]
In GitLab by @asottile on Aug 6, 2019, 08:48

I think in order to solve this we'll need to port to argparse

The tricky bits for moving to argparse are:

1. convert `type` to a callable
2. convert `callback_*` to `action`
3. issue warnings for any conversions necessary
4. fix up internals

**Comment by asottile** [comment]
In GitLab by @asottile on Aug 8, 2019, 08:25

mentioned in merge request !337

**Comment by asottile** [comment]
In GitLab by @asottile on Aug 18, 2019, 15:45

via !341:

```console
$ flake8 --max-line-length abc
usage: flake8 [options] file file ...
flake8: error: argument --max-line-length: invalid int value: 'abc'
```

**Comment by asottile** [comment]
In GitLab by @asottile on Aug 18, 2019, 15:45

closed
