### ISSUE TITLE
Unclear error behaviour when logical_line plugin returns invalid column position (UnboundLocalError)

### ISSUE THREAD

**Issue by asottile** [PyCQA/flake8#723]
In GitLab by @PeterJCLaw on May 5, 2020, 12:56

On `flake8` `3.8.0a2` and `master` (at 0c3b8045a7b51aec7abf19dea94d5292cebeeea0), I'm getting an error when a local plugin reports an error on a line number which is too large:

`UnboundLocalError: local variable 'position' referenced before assignment`

I've since realised that the reason for this is that the plugin is wrong, however I think `flake8`'s documentation could be improved to clarify the expected behaviour for each of the different kinds of plugin.

It would also be great if `flake8` could emit a nicer error than the crash which is experienced in this case.

Here's the checker:
``` python
def quox_check(logical_line, line_number):
    if logical_line.startswith("quox"):
        yield (
            line_number,
            "QUOX quox",
        )

quox_check.name = 'quox-check'
quox_check.version = None
```

The error here, which I found very non-obvious (the original author missed it and I only worked it out while digging into the `flake8` sources to report this, which I originally thought was a `flake8` bug) is that yielding the `line_number` here is incorrect -- it seems that that value should instead be a 0-based column number.

<details>

The `setup.cfg` I'm using:
``` ini
[flake8:local-plugins]
extension =
    Q = quox_check:quox_check
paths = .
```

A demo file:
``` python













quox = 'quox'

bar = 'bar'
```
The `quox` line here is line 14. Note that this error doesn't reproduce with it on line 13, but does reproduce from 14 onwards.

From a quick look through the git history it looks like b42e758ac71f2ddcf4b3f4e47453dec3e0604dfa changed this from having a quietly incorrect column number to crashing instead.

Here's the output under flake8 3.8:
```
$ (cd /tmp/bug/ && flake8 demo.py)
Traceback (most recent call last):
  File "/home/peter/.virtualenvs/flake8/bin/flake8", line 11, in <module>
    load_entry_point('flake8', 'console_scripts', 'flake8')()
  File "/home/play/flake8/src/flake8/main/cli.py", line 22, in main
    app.run(argv)
  File "/home/play/flake8/src/flake8/main/application.py", line 355, in run
    self._run(argv)
  File "/home/play/flake8/src/flake8/main/application.py", line 343, in _run
    self.run_checks()
  File "/home/play/flake8/src/flake8/main/application.py", line 257, in run_checks
    self.file_checker_manager.run()
  File "/home/play/flake8/src/flake8/checker.py", line 334, in run
    self.run_serial()
  File "/home/play/flake8/src/flake8/checker.py", line 318, in run_serial
    checker.run_checks()
  File "/home/play/flake8/src/flake8/checker.py", line 596, in run_checks
    self.process_tokens()
  File "/home/play/flake8/src/flake8/checker.py", line 586, in process_tokens
    self.handle_newline(token_type)
  File "/home/play/flake8/src/flake8/checker.py", line 613, in handle_newline
    self.run_logical_checks()
  File "/home/play/flake8/src/flake8/checker.py", line 526, in run_logical_checks
    offset = find_offset(offset, mapping)
  File "/home/play/flake8/src/flake8/checker.py", line 677, in find_offset
    return (position[0], position[1] + offset - token_offset)
UnboundLocalError: local variable 'position' referenced before assignment
```

Here's the output under 3.7.9:
```
$ (cd /tmp/bug/ && flake8 demo.py)
demo.py:14:1: E303 too many blank lines (12)
demo.py:14:15: QUOX quox
```

Note that apparently the error is on column 15 of line 14, which does not exist.
</details>

**Comment by asottile** [comment]
In GitLab by @PeterJCLaw on May 5, 2020, 12:57

changed the description

**Comment by asottile** [comment]
In GitLab by @PeterJCLaw on May 5, 2020, 12:58

changed the description

**Comment by asottile** [comment]
In GitLab by @asottile on May 5, 2020, 13:06

changed the description

**Comment by asottile** [comment]
In GitLab by @asottile on May 5, 2020, 13:07

definitely think this is a bug in flake8 as well, it shouldn't crash in this situation

**Comment by asottile** [comment]
In GitLab by @asottile on May 7, 2020, 11:24

mentioned in merge request !422

**Comment by asottile** [comment]
In GitLab by @asottile on May 7, 2020, 11:25

closed via merge request !422

**Comment by asottile** [comment]
In GitLab by @asottile on May 7, 2020, 11:25

mentioned in commit 8905a7af9e7d50b2654a4e04b5f51aefec834b60
