### ISSUE TITLE
HTMLPlugin error with flake8 >3.8.0

### ISSUE THREAD

**Issue by asottile** [PyCQA/flake8#727]
In GitLab by @yuyucalella on May 12, 2020, 07:12

With the update flake8>3.8.0, I have an error of compatibility with flake8-html==0.4.0:

AttributeError: type object 'HTMLPlugin' has no attribute 'name'.

Which doesn't happen with flake8==3.7.9

**Comment by asottile** [comment]
In GitLab by @asottile on May 12, 2020, 07:31

please fill out the issue template next time, it really helps us out -- thanks!

Here's the error:

```console
$ flake8 --bug-report
Traceback (most recent call last):
  File "/tmp/x/venv/bin/flake8", line 8, in <module>
    sys.exit(main())
  File "/tmp/x/venv/lib/python3.6/site-packages/flake8/main/cli.py", line 22, in main
    app.run(argv)
  File "/tmp/x/venv/lib/python3.6/site-packages/flake8/main/application.py", line 360, in run
    self._run(argv)
  File "/tmp/x/venv/lib/python3.6/site-packages/flake8/main/application.py", line 347, in _run
    self.initialize(argv)
  File "/tmp/x/venv/lib/python3.6/site-packages/flake8/main/application.py", line 329, in initialize
    self.register_plugin_options()
  File "/tmp/x/venv/lib/python3.6/site-packages/flake8/main/application.py", line 167, in register_plugin_options
    self.formatting_plugins.register_options(self.option_manager)
  File "/tmp/x/venv/lib/python3.6/site-packages/flake8/plugins/manager.py", line 433, in register_options
    list(self.manager.map(call_register_options))
  File "/tmp/x/venv/lib/python3.6/site-packages/flake8/plugins/manager.py", line 302, in map
    yield func(self.plugins[name], *args, **kwargs)
  File "/tmp/x/venv/lib/python3.6/site-packages/flake8/plugins/manager.py", line 402, in generated_function
    return method(optmanager, *args, **kwargs)
  File "/tmp/x/venv/lib/python3.6/site-packages/flake8/plugins/manager.py", line 215, in register_options
    with optmanager.group(self.plugin_name):
  File "/tmp/x/venv/lib/python3.6/site-packages/flake8/plugins/manager.py", line 120, in plugin_name
    self._plugin_name = self.plugin.name
AttributeError: type object 'HTMLPlugin' has no attribute 'name'
```

**Comment by asottile** [comment]
In GitLab by @asottile on May 12, 2020, 08:57

hmm it seems that we're now depending on `plugin_name` for formatter plugins as well, where previously it was only for extensions.

I think the best fix here is to add `name` to flake8-html so I've opened a PR there: https://github.com/lordmauve/flake8-html/pull/16

**Comment by asottile** [comment]
In GitLab by @asottile on May 12, 2020, 23:40

that fix has been merged (and presumably will be released soon) -- thanks again for the report!

**Comment by asottile** [comment]
In GitLab by @asottile on May 12, 2020, 23:40

closed
