### ISSUE TITLE
ModuleNotFoundError for 'importlib.metadata' when running version >3.7.9

### ISSUE THREAD

**Issue by asottile** [PyCQA/flake8#731]
In GitLab by @pcrist13 on May 12, 2020, 12:40

*Please describe how you installed Flake8*

As part of our Jenkinsfile, we're simply running the following install command in our container:
```
$ pip3 install flake8
```

*Please provide the exact, unmodified output of `flake8 --bug-report`*

Don't have access to the container running the linting as it is gated by our dev-ops team.

*Please describe the problem or feature*

When building our project in Jenkins, we run flake8 as a validation step for the whole project. Recent changes appear to have broken this process due to a `ModuleNotFoundError` shown below. Pinning the version to `3.7.9` resolved the issue and fixed our build.
```
Traceback (most recent call last):
  File "/usr/local/bin/flake8", line 5, in <module>
    from flake8.main.cli import main
  File "/usr/local/lib/python3.8/site-packages/flake8/main/cli.py", line 5, in <module>
    from flake8.main import application
  File "/usr/local/lib/python3.8/site-packages/flake8/main/application.py", line 11, in <module>
    from flake8 import checker
  File "/usr/local/lib/python3.8/site-packages/flake8/checker.py", line 18, in <module>
    from flake8 import processor
  File "/usr/local/lib/python3.8/site-packages/flake8/processor.py", line 13, in <module>
    from flake8 import utils
  File "/usr/local/lib/python3.8/site-packages/flake8/utils.py", line 16, in <module>
    from flake8._compat import lru_cache
  File "/usr/local/lib/python3.8/site-packages/flake8/_compat.py", line 10, in <module>
    import importlib.metadata as importlib_metadata
ModuleNotFoundError: No module named 'importlib.metadata'
```

**Comment by asottile** [comment]
In GitLab by @asottile on May 12, 2020, 12:43

could you run these for me?
- `python3 --version --version`
- `python3 -c 'import importlib.metadata'`

importlib.metadata is a standard library module that's new in python3.8 -- if it's missing for you I suspect your installation of python is busted in some way

**Comment by asottile** [comment]
In GitLab by @pcrist13 on May 12, 2020, 13:06

I get the following running those commands:
```
Python 3.8.0a3 (default, Mar 27 2019, 23:35:25) 
[GCC 8.2.0]
Traceback (most recent call last):
  File "<string>", line 1, in <module>
ModuleNotFoundError: No module named 'importlib.metadata'
```

**Comment by asottile** [comment]
In GitLab by @asottile on May 12, 2020, 13:08

ah yes, you're using an alpha version of python before the module was introduced -- please upgrade to 3.8.0 or greater

**Comment by asottile** [comment]
In GitLab by @asottile on May 12, 2020, 13:08

closed

**Comment by asottile** [comment]
In GitLab by @pcrist13 on May 12, 2020, 13:39

Thank you, found we're using an image for aws-cli which hasn't been updated since that alpha release. I appreciate it Anthony!

**Comment by asottile** [comment]
In GitLab by @asottile on May 12, 2020, 13:44

no problem! glad I could help :)

**Comment by asottile** [comment]
In GitLab by @allekmott on May 13, 2020, 22:14

I'm running into a similar error while running `flake8` with `pipenv`, where instead of raising `ModuleNotFoundError` for `importlib.metadata`, it's being raised for `importlib_metadata`. This seems to happen only with Python <3.8.

Example stack trace:
```
Traceback (most recent call last):
  File "/Users/.../bin/flake8", line 5, in <module>
    from flake8.main.cli import main
  File "/Users/.../lib/python3.7/site-packages/flake8/main/cli.py", line 5, in <module>
    from flake8.main import application
  File "/Users/.../lib/python3.7/site-packages/flake8/main/application.py", line 11, in <module>
    from flake8 import checker
  File "/Users/.../lib/python3.7/site-packages/flake8/checker.py", line 18, in <module>
    from flake8 import processor
  File "/Users/.../lib/python3.7/site-packages/flake8/processor.py", line 13, in <module>
    from flake8 import utils
  File "/Users/.../lib/python3.7/site-packages/flake8/utils.py", line 16, in <module>
    from flake8._compat import lru_cache
  File "/Users/.../lib/python3.7/site-packages/flake8/_compat.py", line 12, in <module>
    import importlib_metadata
ModuleNotFoundError: No module named 'importlib_metadata'
```

Example output from the commands suggested above:
```sh
$ pipenv run python --version --version

Python 3.7.6 (default, May 13 2020, 21:33:04) 
[Clang 11.0.0 (clang-1100.0.33.8)]
```

```sh
$ pipenv run python -c 'import importlib.metadata'

Traceback (most recent call last):
  File "<string>", line 1, in <module>
ModuleNotFoundError: No module named 'importlib.metadata'
```

**Comment by asottile** [comment]
In GitLab by @asottile on May 13, 2020, 22:16

if you freeze your pipenv environment using python3.8 and then install with 3.7 you'll hit that (which isn't a flake8 bug but a pipenv bug)

**Comment by asottile** [comment]
In GitLab by @allekmott on May 13, 2020, 22:26

Ah, yup, that was it. Thanks 👍
