### ISSUE TITLE
configparser 5.0 do not support python 2.7

### ISSUE THREAD

**Issue by asottile** [PyCQA/flake8#735]
In GitLab by @heyinling on May 14, 2020, 20:54

*Please describe how you installed Flake8*

Example:

```
$ pip2 install --user flake8
```

*Please provide the exact, unmodified output of `flake8 --bug-report`*

```
Traceback (most recent call last):
  File "/usr/local/bin/flake8", line 7, in <module>
    from flake8.main.cli import main
  File "/usr/local/lib/python2.7/dist-packages/flake8/main/cli.py", line 4, in <module>
    from flake8.main import application
  File "/usr/local/lib/python2.7/dist-packages/flake8/main/application.py", line 16, in <module>
    from flake8.main import options
  File "/usr/local/lib/python2.7/dist-packages/flake8/main/options.py", line 3, in <module>
    from flake8.main import debug
  File "/usr/local/lib/python2.7/dist-packages/flake8/main/debug.py", line 7, in <module>
    import entrypoints
  File "/usr/local/lib/python2.7/dist-packages/entrypoints.py", line 19, in <module>
    from backports import configparser
ImportError: No module named backports
```

*Please describe the problem or feature*

Failed to use flake8 after install flake8 to new python 2.7 virtual env.

*If this is a bug report, please explain with examples (and example code) what you expected to happen and what actually happened.*

According to logs, configparser is not correctly installed:

```
Downloading https://files.pythonhosted.org/packages/e5/7c/d4ccbcde76b4eea8cbd73b67b88c72578e8b4944d1270021596e80b13deb/configparser-5.0.0.tar.gz (75kB)
1267   Running setup.py (path:/tmp/pip-build-NO7651/configparser/setup.py) egg_info for package configparser produced metadata for project name unknown. Fix your #egg=configparser fragments.
```

configparser 5.0 does not support python2 any more. We should use configparser 4.0.2.

**Comment by asottile** [comment]
In GitLab by @asottile on May 14, 2020, 20:57

this works fine for me, `configparser` specifies `python_requires` metadata such that it doesn't get installed in python2.  make sure you're using at least `pip>=9` such that it respects `python_requires`

```console
$ python --version
Python 2.7.17
$ python -m pip install flake8
DEPRECATION: Python 2.7 reached the end of its life on January 1st, 2020. Please upgrade your Python as Python 2.7 is no longer maintained. A future version of pip will drop support for Python 2.7. More details about Python 2 support in pip, can be found at https://pip.pypa.io/en/latest/development/release-process/#python-2-support
Collecting flake8
  Using cached flake8-3.8.1-py2.py3-none-any.whl (72 kB)
Collecting typing; python_version < "3.5"
  Using cached typing-3.7.4.1-py2-none-any.whl (26 kB)
Collecting mccabe<0.7.0,>=0.6.0
  Using cached mccabe-0.6.1-py2.py3-none-any.whl (8.6 kB)
Collecting pycodestyle<2.7.0,>=2.6.0a1
  Using cached pycodestyle-2.6.0-py2.py3-none-any.whl (41 kB)
Processing /home/asottile/.cache/pip/wheels/c2/ea/a3/25af52265fad6418a74df0b8d9ca8b89e0b3735dbd4d0d3794/functools32-3.2.3.post2-py2-none-any.whl
Collecting importlib-metadata; python_version < "3.8"
  Using cached importlib_metadata-1.6.0-py2.py3-none-any.whl (30 kB)
Collecting pyflakes<2.3.0,>=2.2.0
  Using cached pyflakes-2.2.0-py2.py3-none-any.whl (66 kB)
Collecting enum34; python_version < "3.4"
  Using cached enum34-1.1.10-py2-none-any.whl (11 kB)
Collecting configparser; python_version < "3.2"
  Using cached configparser-4.0.2-py2.py3-none-any.whl (22 kB)
Collecting contextlib2; python_version < "3"
  Using cached contextlib2-0.6.0.post1-py2.py3-none-any.whl (9.8 kB)
Collecting zipp>=0.5
  Using cached zipp-1.2.0-py2.py3-none-any.whl (4.8 kB)
Collecting pathlib2; python_version < "3"
  Using cached pathlib2-2.3.5-py2.py3-none-any.whl (18 kB)
Processing /home/asottile/.cache/pip/wheels/91/95/75/19c98a91239878abbc7c59970abd3b4e0438a7dd5b61778335/scandir-1.10.0-cp27-cp27mu-linux_x86_64.whl
Collecting six
  Using cached six-1.14.0-py2.py3-none-any.whl (10 kB)
Installing collected packages: typing, mccabe, pycodestyle, functools32, contextlib2, zipp, configparser, scandir, six, pathlib2, importlib-metadata, pyflakes, enum34, flake8
Successfully installed configparser-4.0.2 contextlib2-0.6.0.post1 enum34-1.1.10 flake8-3.8.1 functools32-3.2.3.post2 importlib-metadata-1.6.0 mccabe-0.6.1 pathlib2-2.3.5 pycodestyle-2.6.0 pyflakes-2.2.0 scandir-1.10.0 six-1.14.0 typing-3.7.4.1 zipp-1.2.0
WARNING: You are using pip version 20.0.2; however, version 20.1 is available.
You should consider upgrading via the '/tmp/venv/bin/python -m pip install --upgrade pip' command.
$ flake8 --version
3.8.1 (mccabe: 0.6.1, pycodestyle: 2.6.0, pyflakes: 2.2.0) CPython 2.7.17 on
Linux
```

**Comment by asottile** [comment]
In GitLab by @asottile on May 14, 2020, 20:57

closed

**Comment by asottile** [comment]
In GitLab by @heyinling on May 14, 2020, 21:07

@asottile Thanks for quick response. It's fixed after I upgrade pip.
