### ISSUE TITLE
IndentationError crash on incorrect indentation after block

### ISSUE THREAD

**Issue by asottile** [PyCQA/flake8#747]
In GitLab by @thormick on Jun 2, 2020, 03:27

*Please describe how you installed Flake8*

```
$ source env-u20.04/bin/activate
(env-u20.04) $ pip install flake8==3.8.2
...
Successfully installed flake8-3.8.2 pycodestyle-2.6.0 pyflakes-2.2.0
```

*Please provide the exact, unmodified output of `flake8 --bug-report`*
```
(env-u20.04) $ flake8 --bug-report
{
  "dependencies": [],
  "platform": {
    "python_implementation": "CPython",
    "python_version": "3.8.2",
    "system": "Linux"
  },
  "plugins": [
    {
      "is_local": false,
      "plugin": "mccabe",
      "version": "0.6.1"
    },
    {
      "is_local": false,
      "plugin": "pycodestyle",
      "version": "2.6.0"
    },
    {
      "is_local": false,
      "plugin": "pyflakes",
      "version": "2.2.0"
    }
  ],
  "version": "3.8.2"
}
```

*Please describe the problem or feature*

flake8 3.8.2 crashes with an IndentationError if it encounters an incorrectly indented line after a correctly indented block.

```
(env-u20.04) $ cat ok.py
print("Foo!")
 print("Bar!")
(env-u20.04) $ cat bad.py
if True:
    print("Foo!")
 print("Bar!")
(env-u20.04) $ flake8 ok.py
ok.py:2:1: E999 IndentationError: unexpected indent
ok.py:2:2: E111 indentation is not a multiple of four
ok.py:2:2: E113 unexpected indentation
(env-u20.04) $ flake8 bad.py
Traceback (most recent call last):
  File "/home/thormick/gapit/env-u20.04/lib/python3.8/site-packages/flake8/processor.py", line 272, in generate_tokens
    for token in tokenize.generate_tokens(self.next_line):
  File "/usr/lib/python3.8/tokenize.py", line 512, in _tokenize
    raise IndentationError(
  File "<tokenize>", line 3
    print("Bar!")
    ^
IndentationError: unindent does not match any outer indentation level

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/thormick/gapit/env-u20.04/lib/python3.8/site-packages/flake8/checker.py", line 588, in run_checks
    self.process_tokens()
  File "/home/thormick/gapit/env-u20.04/lib/python3.8/site-packages/flake8/checker.py", line 569, in process_tokens
    for token in file_processor.generate_tokens():
  File "/home/thormick/gapit/env-u20.04/lib/python3.8/site-packages/flake8/processor.py", line 278, in generate_tokens
    raise exceptions.InvalidSyntax(exception=exc)
flake8.exceptions.InvalidSyntax: IndentationError: unindent does not match any outer indentation level

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/thormick/gapit/env-u20.04/bin/flake8", line 8, in <module>
    sys.exit(main())
  File "/home/thormick/gapit/env-u20.04/lib/python3.8/site-packages/flake8/main/cli.py", line 22, in main
    app.run(argv)
  File "/home/thormick/gapit/env-u20.04/lib/python3.8/site-packages/flake8/main/application.py", line 360, in run
    self._run(argv)
  File "/home/thormick/gapit/env-u20.04/lib/python3.8/site-packages/flake8/main/application.py", line 348, in _run
    self.run_checks()
  File "/home/thormick/gapit/env-u20.04/lib/python3.8/site-packages/flake8/main/application.py", line 262, in run_checks
    self.file_checker_manager.run()
  File "/home/thormick/gapit/env-u20.04/lib/python3.8/site-packages/flake8/checker.py", line 325, in run
    self.run_serial()
  File "/home/thormick/gapit/env-u20.04/lib/python3.8/site-packages/flake8/checker.py", line 309, in run_serial
    checker.run_checks()
  File "/home/thormick/gapit/env-u20.04/lib/python3.8/site-packages/flake8/checker.py", line 591, in run_checks
    self.report(
  File "/home/thormick/gapit/env-u20.04/lib/python3.8/site-packages/flake8/checker.py", line 409, in report
    line = self.processor.noqa_line_for(line_number)
  File "/home/thormick/gapit/env-u20.04/lib/python3.8/site-packages/flake8/processor.py", line 290, in noqa_line_for
    file_tokens = self.file_tokens
  File "/home/thormick/gapit/env-u20.04/lib/python3.8/site-packages/flake8/processor.py", line 125, in file_tokens
    self._file_tokens = list(
  File "/usr/lib/python3.8/tokenize.py", line 512, in _tokenize
    raise IndentationError(
  File "<tokenize>", line 3
    print("Bar!")
    ^
IndentationError: unindent does not match any outer indentation level
```

Have verified that it also happens in 3.8.1, 3.8.0, 3.8.0a2 and 3.8.0a1, and that it does not occur with 3.7.9, the latter of which works as expected.

```
(env-u20.04) $ pip install flake8==3.7.9
...
Successfully installed flake8-3.7.9 pycodestyle-2.5.0 pyflakes-2.1.1
(env-u20.04) $ flake8 ok.py
ok.py:2:1: E999 IndentationError: unexpected indent
ok.py:2:2: E111 indentation is not a multiple of four
ok.py:2:2: E113 unexpected indentation
(env-u20.04) $ flake8 bad.py
bad.py:1:1: E902 IndentationError: unindent does not match any outer indentation level
```
I'm using Python from Ubuntu 20.04, don't know whether that is significant, seeing as it seems to start in tokenize.py.

The only other similar issue I've found is #205, which does not seem relevant in this case.

**Comment by asottile** [comment]
In GitLab by @ericvw on Jun 2, 2020, 06:39

I have identified that https://gitlab.com/pycqa/flake8/-/blob/40716454a285b7a3f63c398f78106fafd5c668e7/src/flake8/processor.py#L124-129 needs to also catch `SyntaxError`.

I have a merge request on the way.

**Comment by asottile** [comment]
In GitLab by @ericvw on Jun 2, 2020, 06:57

mentioned in merge request !433

**Comment by asottile** [comment]
In GitLab by @ericvw on Jun 2, 2020, 06:57

Created !433 to address this issue.

**Comment by asottile** [comment]
In GitLab by @asottile on Jun 2, 2020, 11:42

closed via merge request !433

**Comment by asottile** [comment]
In GitLab by @asottile on Jun 2, 2020, 11:42

mentioned in commit 94304de68480ac3007377404837130df72534ee3

**Comment by asottile** [comment]
In GitLab by @asottile on Dec 2, 2020, 22:04

locked this issue
