### ISSUE TITLE
Bug: Function definition with duplicate argument causes flake8 to crash

### ISSUE THREAD

**Issue by asottile** [PyCQA/flake8#756]
In GitLab by @ConorLazarou on Jun 30, 2020, 07:12

Edit: Issue already resolved, this occurred on an outdated version of flake8.

*Please describe how you installed Flake8*

```
$ brew install flake8
```

*Please provide the exact, unmodified output of `flake8 --bug-report`*
```
{
  "dependencies": [
    {
      "dependency": "entrypoints",
      "version": "0.3"
    }
  ],
  "platform": {
    "python_implementation": "CPython",
    "python_version": "3.7.6",
    "system": "Darwin"
  },
  "plugins": [
    {
      "is_local": false,
      "plugin": "flake8-docstrings",
      "version": "1.5.0, pydocstyle: 5.0.2"
    },
    {
      "is_local": false,
      "plugin": "hacking.core",
      "version": "0.0.1"
    },
    {
      "is_local": false,
      "plugin": "mccabe",
      "version": "0.6.1"
    },
    {
      "is_local": false,
      "plugin": "pycodestyle",
      "version": "2.5.0"
    },
    {
      "is_local": false,
      "plugin": "pyflakes",
      "version": "2.1.1"
    }
  ],
  "version": "3.7.9"
}
```

*Please describe the problem*

Function definition with duplicate argument causes flake8 to crash.

*If this is a bug report, please explain with examples (and example code) what you expected to happen and what actually happened.*

Code to reproduce:
```
def f(var1, var1):
    pass
```

Expected behaviour:

Return `test.py:1:7: E999 SyntaxError: invalid syntax` or other appropriate error message.

Actual behaviour:

```
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/pydocstyle/parser.py", line 319, in parse
    compile(src, filename, 'exec')
  File "test.py", line 1
    def f(var1, var1):
    ^
SyntaxError: duplicate argument 'var1' in function definition

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/bin/flake8", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.7/site-packages/flake8/main/cli.py", line 18, in main
    app.run(argv)
  File "/usr/local/lib/python3.7/site-packages/flake8/main/application.py", line 393, in run
    self._run(argv)
  File "/usr/local/lib/python3.7/site-packages/flake8/main/application.py", line 381, in _run
    self.run_checks()
  File "/usr/local/lib/python3.7/site-packages/flake8/main/application.py", line 300, in run_checks
    self.file_checker_manager.run()
  File "/usr/local/lib/python3.7/site-packages/flake8/checker.py", line 331, in run
    self.run_serial()
  File "/usr/local/lib/python3.7/site-packages/flake8/checker.py", line 315, in run_serial
    checker.run_checks()
  File "/usr/local/lib/python3.7/site-packages/flake8/checker.py", line 598, in run_checks
    self.run_ast_checks()
  File "/usr/local/lib/python3.7/site-packages/flake8/checker.py", line 502, in run_ast_checks
    for (line_number, offset, text, check) in runner:
  File "/usr/local/lib/python3.7/site-packages/flake8_docstrings.py", line 131, in run
    for error in self._check_source():
  File "/usr/local/lib/python3.7/site-packages/flake8_docstrings.py", line 115, in _check_source
    ignore_decorators=self.ignore_decorators,
  File "/usr/local/lib/python3.7/site-packages/pydocstyle/checker.py", line 108, in check_source
    module = parse(StringIO(source), filename)
  File "/usr/local/lib/python3.7/site-packages/pydocstyle/parser.py", line 333, in __call__
    return self.parse(*args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/pydocstyle/parser.py", line 321, in parse
    raise ParseError() from error
pydocstyle.parser.ParseError: Cannot parse file.
```

**Comment by asottile** [comment]
In GitLab by @ConorLazarou on Jun 30, 2020, 07:22

closed

**Comment by asottile** [comment]
In GitLab by @ConorLazarou on Jun 30, 2020, 07:23

I was running an old version of flake8, apologies :face_palm:

**Comment by asottile** [comment]
In GitLab by @ConorLazarou on Jun 30, 2020, 07:24

changed the description
