### ISSUE TITLE
Fixed UnicodeEncodingError that appears while running flake8 in TeamCity - [closed]

### ISSUE THREAD

**Issue by asottile** [PyCQA/flake8#852]
In GitLab by @d.aleskarova on Apr 19, 2017, 23:51

_Merges master -> master_

There is an issue (https://github.com/JetBrains/teamcity-messages/issues/122): checking files with flake8 formatting plugin for TeamCity failes with UnicodeEncodingError if the files contains non-ASCII charecters.

I've done some analisys that shows the problem in the following: teamcity plugin puts lines of code from the checked file where flake8 had found an error and returns the error message from format() method in Unicode. Then when flake8 is going to write the error message into file or stdout it doesn't expect non-ASCII symbols in it and raised UnicodeEncodingError.

I've made small changes that check the type of output lines and encode it to UTF-8 in case it is Unicode before writing it to outputfile or stdout. I think this will solve the problem.

**Comment by asottile** [comment]
In GitLab by @codecov on Apr 19, 2017, 23:51

# [Codecov](https://codecov.io/gl/pycqa/flake8/pull/179?src=pr&el=h1) Report
> Merging [#179](https://codecov.io/gl/pycqa/flake8/pull/179?src=pr&el=desc) into [master](https://codecov.io/gl/pycqa/flake8/commit/733a4f053b093d0d061ce780963e936861327c95?src=pr&el=desc) will **decrease** coverage by `0.04%`.
> The diff coverage is `33.33%`.

[![Impacted file tree graph](https://codecov.io/gl/pycqa/flake8/pull/179/graphs/tree.svg?token=QL6TVnaXih&src=pr&width=650&height=150)](https://codecov.io/gl/pycqa/flake8/pull/179?src=pr&el=tree)

```diff
@@            Coverage Diff             @@
##           master     #179      +/-   ##
==========================================
- Coverage   68.78%   68.73%   -0.05%     
==========================================
  Files          27       27              
  Lines        2201     2204       +3     
  Branches      359      360       +1     
==========================================
+ Hits         1514     1515       +1     
- Misses        610      613       +3     
+ Partials       77       76       -1
```


| [Impacted Files](https://codecov.io/gl/pycqa/flake8/pull/179?src=pr&el=tree) | Coverage Δ | |
|---|---|---|
| [src/flake8/main/cli.py](https://codecov.io/gl/pycqa/flake8/pull/179?src=pr&el=tree#diff-c3JjL2ZsYWtlOC9tYWluL2NsaS5weQ==) | `0% <ø> (ø)` | :arrow_up: |
| [src/flake8/api/legacy.py](https://codecov.io/gl/pycqa/flake8/pull/179?src=pr&el=tree#diff-c3JjL2ZsYWtlOC9hcGkvbGVnYWN5LnB5) | `89.83% <ø> (ø)` | :arrow_up: |
| [src/flake8/plugins/manager.py](https://codecov.io/gl/pycqa/flake8/pull/179?src=pr&el=tree#diff-c3JjL2ZsYWtlOC9wbHVnaW5zL21hbmFnZXIucHk=) | `93.99% <ø> (ø)` | :arrow_up: |
| [src/flake8/options/manager.py](https://codecov.io/gl/pycqa/flake8/pull/179?src=pr&el=tree#diff-c3JjL2ZsYWtlOC9vcHRpb25zL21hbmFnZXIucHk=) | `90.47% <ø> (ø)` | :arrow_up: |
| [src/flake8/formatting/base.py](https://codecov.io/gl/pycqa/flake8/pull/179?src=pr&el=tree#diff-c3JjL2ZsYWtlOC9mb3JtYXR0aW5nL2Jhc2UucHk=) | `68.33% <33.33%> (-1.85%)` | :arrow_down: |
| [src/flake8/statistics.py](https://codecov.io/gl/pycqa/flake8/pull/179?src=pr&el=tree#diff-c3JjL2ZsYWtlOC9zdGF0aXN0aWNzLnB5) | `93.54% <0%> (ø)` | :arrow_up: |
| [src/flake8/main/git.py](https://codecov.io/gl/pycqa/flake8/pull/179?src=pr&el=tree#diff-c3JjL2ZsYWtlOC9tYWluL2dpdC5weQ==) | `33.92% <0%> (ø)` | :arrow_up: |

------

[Continue to review full report at Codecov](https://codecov.io/gl/pycqa/flake8/pull/179?src=pr&el=continue).
> **Legend** - [Click here to learn more](https://docs.codecov.io/docs/codecov-delta)
> `Δ = absolute <relative> (impact)`, `ø = not affected`, `? = missing data`
> Powered by [Codecov](https://codecov.io/gl/pycqa/flake8/pull/179?src=pr&el=footer). Last update [733a4f0...52d8009](https://codecov.io/gl/pycqa/flake8/pull/179?src=pr&el=lastupdated). Read the [comment docs](https://docs.codecov.io/docs/pull-request-comments).

**Comment by asottile** [comment]
In GitLab by @sigmavirus24 on Apr 22, 2017, 06:44

Commented on [src/flake8/formatting/base.py line 169](https://github.com/PyCQA/flake8/compare/733a4f053b093d0d061ce780963e936861327c95..1ae5e0afe657c194599047207baa8c925693d1c3#diff-07314551583f789e485604eea9190c17R169)



I'm pretty sure this isn't what you actually want. This also *breaks* the handling on Python 3.

I'll need far more information on how you trigger this error than you have in this pull request or in the TeamCity issue.

**Comment by asottile** [comment]
In GitLab by @d.aleskarova on Apr 24, 2017, 24:58

added 1 commit

* 394f21a1 - Encoding output if it&#x27;s Unicode only for python2

[Compare with previous version](https://gitlab.com/pycqa/flake8/merge_requests/179/diffs?diff_id=4027563&start_sha=1ae5e0afe657c194599047207baa8c925693d1c3)

**Comment by asottile** [comment]
In GitLab by @d.aleskarova on Apr 24, 2017, 04:06

Commented on [src/flake8/formatting/base.py line 169](https://github.com/PyCQA/flake8/compare/733a4f053b093d0d061ce780963e936861327c95..1ae5e0afe657c194599047207baa8c925693d1c3#diff-07314551583f789e485604eea9190c17R169)



Sorry, but I can't quite agree with you. I don't think this breaks the handling on Python 3. I wrote this way for the folling reasons:
* "output" argument of \_write method is likely to be the type of str or unicode. For Python 3 all strings are _str_ type, but in Python 2 string might be either _str_ or _unicode_ type. So I checked if "output" is not _str_ (then it's _unicode_) and encode it to get _str_.
* Actually output parameter might be not only _str_ or _unicode_ type and then output.encode('UTF-8') fails with AtributeError. But in this case even without my changes there would be TypeError during the attempt to concatenate _output_ with _self.newline_ (which is str type)


To make my changes more explicit I've rewritten them to
```python
if sys.version_info < (3, 0) and isnstance(output, unicode):
    output = output.encode('UTF-8')
```
and now it encodes output only the Python version is less than 3.0 and output is unicode type.


I don't insist that the code if my merge request is the best way to fix this error. But I think flake8 should somehow check the _output_ argument and prevents from raising this kind of errors. If you know the better way to do it, please, consider including it into flake8 code.

**Comment by asottile** [comment]
In GitLab by @d.aleskarova on Apr 25, 2017, 06:30

_The command to install flake8_: ```pip install flake8==3.2.1```

_Unmodified output of ```flake8 --bug-report```_:
```
{
  "dependencies": [
    {
      "dependency": "setuptools",
      "version": "35.0.1"
    }
  ],
  "platform": {
    "python_implementation": "CPython",
    "python_version": "2.7.13",
    "system": "Windows"
  },
  "plugins": [
    {
      "plugin": "mccabe",
      "version": "0.5.3"
    },
    {
      "plugin": "pycodestyle",
      "version": "2.2.0"
    },
    {
      "plugin": "pyflakes",
      "version": "1.3.0"
    },
    {
      "plugin": "teamcity-messages",
      "version": "1.21"
    }
  ],
  "version": "3.2.1"
}
```

I triggered this error in enviroment of Python 2.7.13 with installed flake8==3.2.1 (actually the same error also appears with later versions of flake8) and teamcity-messages==1.21 when running command ```flake8 --teamcity=True --output=result.txt example.py``` where the content of example.py is
```python
# coding=utf-8

SomeVa='fsdf ававв'  # Non ascci symbols

```

The error traceback is
```
Traceback (most recent call last):
  File "C:\Users\user\PycharmProjects\test-repo\venv_patched\Scripts\flake8-script.py", line 11, in <module>
    load_entry_point('flake8==3.3.0', 'console_scripts', 'flake8')()
  File "c:\users\user\pycharmprojects\test-repo\venv_patched\lib\site-packages\flake8\main\cli.py", line 16, in main
    app.run(argv)
  File "c:\users\user\pycharmprojects\test-repo\venv_patched\lib\site-packages\flake8\main\application.py", line 328, in run
    self._run(argv)
  File "c:\users\user\pycharmprojects\test-repo\venv_patched\lib\site-packages\flake8\main\application.py", line 317, in _run
    self.report()
  File "c:\users\user\pycharmprojects\test-repo\venv_patched\lib\site-packages\flake8\main\application.py", line 308, in report
    self.report_errors()
  File "c:\users\user\pycharmprojects\test-repo\venv_patched\lib\site-packages\flake8\main\application.py", line 276, in report_errors
    results = self.file_checker_manager.report()
  File "c:\users\user\pycharmprojects\test-repo\venv_patched\lib\site-packages\flake8\checker.py", line 265, in report
    results_reported += self._handle_results(filename, results)
  File "c:\users\user\pycharmprojects\test-repo\venv_patched\lib\site-packages\flake8\checker.py", line 166, in _handle_results
    physical_line=physical_line,
  File "c:\users\user\pycharmprojects\test-repo\venv_patched\lib\site-packages\flake8\style_guide.py", line 292, in handle_error
    self.formatter.handle(error)
  File "c:\users\user\pycharmprojects\test-repo\venv_patched\lib\site-packages\flake8\formatting\base.py", line 87, in handle
    self.write(line, source)
  File "c:\users\user\pycharmprojects\test-repo\venv_patched\lib\site-packages\flake8\formatting\base.py", line 188, in write
    self._write(line)
  File "c:\users\user\pycharmprojects\test-repo\venv_patched\lib\site-packages\flake8\formatting\base.py", line 170, in _write
    self.output_fd.write(output + self.newline)
UnicodeEncodeError: 'ascii' codec can't encode characters in position 210-214: ordinal not in range(128)
```

But if I run the same command using flake8 with the changed I made for this merge request, the output file `result.txt` is created with the text:
```
##teamcity[testStarted timestamp='2017-04-25T16:52:36.051' name='pep8: example.py:3:7: E225 missing whitespace around operator']
##teamcity[testFailed timestamp='2017-04-25T16:52:36.051' details='SomeVa=|'fsdf ававв|'  # Non ascci symbols|n       ^' message='E225 missing whitespace around operator' name='pep8: example.py:3:7: E225 missing whitespace around operator']
##teamcity[testFinished timestamp='2017-04-25T16:52:36.051' name='pep8: example.py:3:7: E225 missing whitespace around operator']
```
and that's what I need.


In my opinion the cause of this error is:
* it runs fine untill the line `line = self.format(error)` in 
https://gitlab.com/pycqa/flake8/blob/master/src/flake8/formatting/base.py#L85 where `format` method from _teamcity_messages_ is called (https://github.com/JetBrains/teamcity-messages/blob/master/teamcity/flake8_v3_plugin.py#L33) which returns line in Unicode format.
* after that it goes to `self.write(line, source)` (https://gitlab.com/pycqa/flake8/blob/master/src/flake8/formatting/base.py#L87), then to `self._write(line)` (https://gitlab.com/pycqa/flake8/blob/master/src/flake8/formatting/base.py#L188) and finally ends up in `self.output_fd.write(output + self.newline)` (https://gitlab.com/pycqa/flake8/blob/master/src/flake8/formatting/base.py#L170) when to concatenate it with `self.newline` python interpreter tries to encode it into _str_ using default ASCII encoding, but in case if there are non-ASCII characters in _output_, the encoding fails with UnicodeEncodeError.

**Comment by asottile** [comment]
In GitLab by @d.aleskarova on May 1, 2017, 23:30

Please, let me know if you need more information about this error and what kind of inforamiton you need.

**Comment by asottile** [comment]
In GitLab by @d.aleskarova on May 1, 2017, 23:41

added 1 commit

* e376e7bc - Fixed code style error E302

[Compare with previous version](https://gitlab.com/pycqa/flake8/merge_requests/179/diffs?diff_id=4172160&start_sha=394f21a1f0832d0e4dda8e68d654d52ed6ad5be8)

**Comment by asottile** [comment]
In GitLab by @d.aleskarova on May 2, 2017, 24:45

added 1 commit

* 0e8a0625 - Fixed errors found during linters test

[Compare with previous version](https://gitlab.com/pycqa/flake8/merge_requests/179/diffs?diff_id=4172832&start_sha=e376e7bc9f3f7eed6d17d2e1b228fe580456ca66)

**Comment by asottile** [comment]
In GitLab by @d.aleskarova on May 2, 2017, 01:01

added 1 commit

* f1c8abe0 - Fixed errors found by linters

[Compare with previous version](https://gitlab.com/pycqa/flake8/merge_requests/179/diffs?diff_id=4173069&start_sha=0e8a0625d5302cacbfafa7f49e2a86980d10d6b2)

**Comment by asottile** [comment]
In GitLab by @d.aleskarova on May 2, 2017, 01:10

added 1 commit

* 52d8009f - Fixed a typo and D200 error

[Compare with previous version](https://gitlab.com/pycqa/flake8/merge_requests/179/diffs?diff_id=4173184&start_sha=f1c8abe003428d8461a57a0058f916a3590ffd8a)

**Comment by asottile** [comment]
In GitLab by @d.aleskarova on May 2, 2017, 04:30

Hi! I have fixed code style errors which made the linters test fails. One of them was because of my changes in this merge request, so I rewrote it and now check ```if sys.version_info < (3, 0) and not isinstance(output, str)``` instead of ```if sys.version_info < (3, 0) and isinstance(output, unicode)```. It will work as I want if output is the type of ```unicode``` or ```str``` and I don't think it makes sence for any flake8 plugin to return data which then goes as output in another formats.

Please, could you tell what you think about this merge request now? This error affects my project and I really need to know if I can rely on this merge request to solve it or do something else.

**Comment by asottile** [comment]
In GitLab by @sigmavirus24 on May 13, 2017, 05:04

Hi @d.aleskarova 

I was quite busy with other things and not attentive to any of the F/OSS projects I work on. I'm very sorry for that.

One issue that Flake8 has had previously with encoding has stemmed from the fact that the user's system is configured for a different setting. In particular, a user has their environment configured for `C` (a.k.a., `ASCII`) but are trying to write out Unicode code-points. This tends to cause several issues.

There are a few things I'd ask you to check before I merge this:

- `PYTHONIOENCODING` and if it's unset, what the behaviour is with this set to `utf8`
- The output of `locale`

**Comment by asottile** [comment]
In GitLab by @d.aleskarova on May 16, 2017, 05:05

@sigmavirus24, thank you for your reply. I understand that you have lots of things to do except this project.

About your questions:
* ```PYTHONIOENCODING``` wasn't set but when I set it to ```utf8``` (or I even tryed ```UTF-8``` and ```utf-8```), I get the same error
* The output of ```locale``` is

```
LANG=
LC_CTYPE="C.UTF-8"
LC_NUMERIC="C.UTF-8"
LC_TIME="C.UTF-8"
LC_COLLATE="C.UTF-8"
LC_MONETARY="C.UTF-8"
LC_MESSAGES="C.UTF-8"
LC_ALL=
```

**Comment by asottile** [comment]
In GitLab by @d.aleskarova on May 30, 2017, 07:42

@sigmavirus24, thank you very much for your suggestion to set ```PYTHONIOENCODING``` to ```utf-8```. Although it doesn't help when I want to write output messages into a file (like in the example of reproducing this error) but acutally it works in Teamcity enviroment where I use flake8 and teamcity-messages to check code style of my project.

I think this is probable the best solution for this problem.

**Comment by asottile** [comment]
In GitLab by @sigmavirus24 on May 30, 2017, 18:11

Hm, so it might be prudent to open the file with a specific encoding then, yes?

**Comment by asottile** [comment]
In GitLab by @asottile on Mar 29, 2021, 17:17

we're dropping python 2 so this is not necessary any more #690
