### ISSUE TITLE
Hook test failing on Windows

### ISSUE THREAD

**Issue by asottile** [PyCQA/flake8#86]
In GitLab by @christianmlong on Mar 11, 2015, 18:06

`test_hooks.TestGitHook` is failing on Python 2.7, 3.3, and 3.4 on Windows 8.1

    Traceback (most recent call last):
      File "c:\python34\Lib\unittest\mock.py", line 1136, in patched
        return func(*args, **keywargs)
      File "C:\Users\Me\Documents\Documents\Computer\Projects\git\flake8\flake8\tests\test_hooks.py", line 37, in test_prepends_tmp_directory_to_exclude
        style_guide.check_files.assert_called_once_with([tmpfile])
      File "c:\python34\Lib\unittest\mock.py", line 782, in assert_called_once_with
        return self.assert_called_with(*args, **kwargs)
      File "c:\python34\Lib\unittest\mock.py", line 771, in assert_called_with
        raise AssertionError(_error_message()) from cause
    AssertionError: Expected call: check_files(['/fake/tmp\\:\\Users\\Me\\Documents\\Documents\\Computer\\Projects\\git\\flake8\\foo\\bfile.py'])
    Actual call: check_files(['/fake/tmp\\foo\\bfile.py'])

I see two problems: the paths in the test have hardcoded posix path separators, and the path manipulation doesn't account for drive letters. I have a patch ready which I will PR soon.

**Comment by asottile** [comment]
In GitLab by @sigmavirus24 on Mar 11, 2015, 18:08

:heart:

**Comment by asottile** [comment]
In GitLab by @christianmlong on Mar 11, 2015, 18:11

mentioned in merge request !24

**Comment by asottile** [comment]
In GitLab by @sigmavirus24 on Mar 11, 2015, 20:01

Status changed to closed by commit e8460dfe51135dc8c7cf17864269504b69049190
