### ISSUE TITLE
Jobs warning tests failing on Windows with Python < 3.4

### ISSUE THREAD

**Issue by asottile** [PyCQA/flake8#87]
In GitLab by @christianmlong on Mar 11, 2015, 18:42

Flake8 issues warnings when the `--jobs` option is used in an incompatible way (e.g. with the `--diff` option). The tests for this feature are in `flake8/tests/test_warnings.py`.

Under certain condition, the tests in `test_warnings.py` fail.

---

#### Tests pass 

Linux - Ubuntu 14.10

2.6, 2.7, 3.2, 3.3, 3.4

Windows - 8.1

3.4

---

#### Tests fail 

Windows - 8.1

2.7, 3.3

---

They fail because the warnings are not issued, or are not captured. However, when the tests in `test_warnings.py` are run alone, without the rest of the test suite, they pass. Using the `nosetests --isolation` option does not help.

The nature of the tests (patching stdin, stdout) and the pattern of failure (Windows, Python &lt; 3.4) makes me think the failure might have something to do with [PEP 446](https://www.python.org/dev/peps/pep-0446/) "Make newly created file descriptors non-inheritable".

---

One proposed solution (PR coming soon) is to run the tests in `test_warnings.py` separately, in a separate line in the tox `[testenv]` stanza.

---

### Tracebacks

    
    ======================================================================
    FAIL: test_jobs_verbose (flake8.tests.test_warnings.IntegrationTestCaseWarnings)
    ----------------------------------------------------------------------
    Traceback (most recent call last):
      File "C:\Users\Me\Documents\Documents\Computer\Projects\git\flake8\flake8\tests\test_warnings.py", line 190, in test_jobs_verbose
        self.test_jobs(verbose=True)
      File "C:\Users\Me\Documents\Documents\Computer\Projects\git\flake8\flake8\tests\test_warnings.py", line 160, in test_jobs
        self._job_tester(2, verbose=verbose)
      File "C:\Users\Me\Documents\Documents\Computer\Projects\git\flake8\flake8\tests\test_warnings.py", line 157, in _job_tester
        self.verify_warnings(collected_warnings, expected_warings)
      File "C:\Users\Me\Documents\Documents\Computer\Projects\git\flake8\flake8\tests\test_warnings.py", line 88, in verify_warnings
        len(expected_warnings))
    nose.proxy.AssertionError: 0 != 1
    -------------------- >> begin captured stdout << ---------------------
    local configuration: in C:\Users\Me\Documents\Documents\Computer\Projects\git\flake8
    checking C:\Users\Me\Documents\Documents\Computer\Projects\git\flake8\flake8\tests\test_warnings.py
    
    --------------------- >> end captured stdout << ----------------------
    
    ======================================================================
    FAIL: test_stdin_jobs_warning_verbose (flake8.tests.test_warnings.IntegrationTestCaseWarnings)
    ----------------------------------------------------------------------
    Traceback (most recent call last):
      File "C:\Users\Me\Documents\Documents\Computer\Projects\git\flake8\flake8\tests\test_warnings.py", line 196, in test_stdin_jobs_warning_verbose
        self.test_stdin_jobs_warning(verbose=True)
      File "C:\Users\Me\Documents\Documents\Computer\Projects\git\flake8\flake8\tests\test_warnings.py", line 186, in test_stdin_jobs_warning
        self.verify_warnings(collected_warnings, expected_warings)
      File "C:\Users\Me\Documents\Documents\Computer\Projects\git\flake8\flake8\tests\test_warnings.py", line 88, in verify_warnings
        len(expected_warnings))
    nose.proxy.AssertionError: 1 != 2
    -------------------- >> begin captured stdout << ---------------------
    local configuration: in C:\Users\Me\Documents\Documents\Computer\Projects\git\flake8
    checking -
    
    --------------------- >> end captured stdout << ----------------------

**Comment by asottile** [comment]
In GitLab by @christianmlong on Mar 11, 2015, 21:43

mentioned in merge request !25

**Comment by asottile** [comment]
In GitLab by @christianmlong on Mar 16, 2015, 17:22


## The Problem


Some of the tests in this module pass when this module is run on its own, but they fail when this module is run as part of the whole test suite. These are the problematic tests:

    test_jobs_verbose
    test_stdin_jobs_warning

On some platforms, the warnings.capture_warnings function doesn't work properly when run with the other flake8 tests. It drops some warnings, even though the warnings filter is set to 'always'. However, when run separately, these tests pass.

This problem only occurs on Windows, with Python 3.3 and older. Maybe it's related to [PEP 446 - Inheritable file descriptors](https://www.python.org/dev/peps/pep-0446/)?

---



## Things that didn't work


### Nose --attr

I tried using the nosetests --attr feature to run the tests separately. I put the following in setup.cfg

    [nosetests]
    atttr=!run_alone

Then I added a tox section thst did this

    nosetests --attr=run_alone

However, the command line --attr would not override the config file --attr, so the special tox section wound up runing all the tests, and failing.


### Nose --with-isolation

The nosetests --with-isolation flag did not help.


### unittest.skipIf

I tried decorating the problematic tests with the unittest.skipIf
decorator.

    @unittest.skipIf(is_windows() and sys.version_info < (3, 4),
                     "Fails on Windows with Python < 3.4 when run with other"
                     " tests.")

The idea is, skip the tests in the main test run, on affected platforms. Then, only on those platforms, come back in later and run the tests separately.

I added a new stanza to tox.ini, to run the tests separately on the affected platforms.

    nosetests --no-skip

I ran in to a bug in the nosetests skip plugin. It would report the test as having been run, but it would not actually run the test. So, when run with `--no-skip`, the following test would be reported as having run and passed!

    @unittest.skip("This passes o_o")
    def test_should_fail(self):
        assert 0

This bug has been reported here: [--no-skip broken with Python 2.7](https://github.com/nose-devs/nose/issues/512)


### py.test

Code for this attempt can be seen at christianmlong/flake8@6dbb843f

I tried using py.test, and its `@pytest.mark.xfail` decorator. I added some separate stanzas in tox, and useing the pytest `--runxfail` option to run the tests separately. This allows us to run all the tests together, on platforms that allow it. On platforms that don't allow us to run the tests all together, this still runs all the tests, but in two separate steps.

This is the same solution as the nosetests `--no-skip` solution I described above, but `--runxfail` does not have the same bug as `--no-skip`.

This has the advantage that all tests are discoverable by default, outside of tox. However, nose does not recognize the `pytest.mark.xfail` decorator. So, if a user runs nosetests, it still tries to run the problematic tests together with the rest of the test suite, causing them to fail.

---


## Solution

Move the problematic tests to _test_warnings.py, so nose.collector will not find them. Set up a separate section in tox.ini that runs this:

    nosetests flake8.tests._test_warnings

This allows all tests to pass on all platforms, when run through tox. However, it means that, even on unaffected platforms, the problematic tests are not discovered and run outside of tox (if the user just runs nosetests manually, for example).

**Comment by asottile** [comment]
In GitLab by @christianmlong on Mar 16, 2015, 17:35

mentioned in merge request !26

**Comment by asottile** [comment]
In GitLab by @sigmavirus24 on Mar 16, 2015, 20:50

mentioned in commit ea628fa9d16b3adc6e15e6726439128d345d80d4

**Comment by asottile** [comment]
In GitLab by @sigmavirus24 on Mar 25, 2015, 09:50

Closed by !26
