### ISSUE TITLE
Improve config's error reporting - [closed]

### ISSUE THREAD

**Issue by asottile** [PyCQA/flake8#886]
In GitLab by @x10an14 on Oct 8, 2018, 08:44

_Merges improved_config_error_reporting -> master_

Hi!

Just recently stumbled upon this use-case myself. I'd putten `Verbose = True` in my `setup.cfg` under the `[flake8]` section.

This stacktrace ain't all that helpful for those who prefer _not_ to start digging into other's code, so I hope my PR might be of aid/inspiration to help ease the user's experience =)
```python
> python -m pipenv run python -m flake8 overtime_calculator
C:\\Users\\x10an14\\.virtualenvs\\overtime-calculator-voKtduX3\\lib\\site-packages\\pycodestyle.py:113: FutureWarning: Possible nested set at position 1
  EXTRANEOUS_WHITESPACE_REGEX = re.compile(r'[[({] | []}),;:]')
Traceback (most recent call last):
  File "C:\\Program Files\\Python37\\Lib\\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "C:\\Program Files\\Python37\\Lib\\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\\Users\\x10an14\\.virtualenvs\\overtime-calculator-voKtduX3\\lib\\site-packages\\flake8\\__main__.py", line 4, in <module>
    cli.main()
  File "C:\\Users\\x10an14\\.virtualenvs\\overtime-calculator-voKtduX3\\lib\\site-packages\\flake8\\main\\cli.py", line 16, in main
    app.run(argv)
  File "C:\\Users\\x10an14\\.virtualenvs\\overtime-calculator-voKtduX3\\lib\\site-packages\\flake8\\main\\application.py", line 396, in run
    self._run(argv)
  File "C:\\Users\\x10an14\\.virtualenvs\\overtime-calculator-voKtduX3\\lib\\site-packages\\flake8\\main\\application.py", line 383, in _run
    self.initialize(argv)
  File "C:\\Users\\x10an14\\.virtualenvs\\overtime-calculator-voKtduX3\\lib\\site-packages\\flake8\\main\\application.py", line 367, in initialize
    self.parse_configuration_and_cli(argv)
  File "C:\\Users\\x10an14\\.virtualenvs\\overtime-calculator-voKtduX3\\lib\\site-packages\\flake8\\main\\application.py", line 212, in parse_configuration_and_cli
    self.option_manager, self.config_finder, argv
  File "C:\\Users\\x10an14\\.virtualenvs\\overtime-calculator-voKtduX3\\lib\\site-packages\\flake8\\options\\aggregator.py", line 46, in aggregate_options
    original_values.isolated)
  File "C:\\Users\\x10an14\\.virtualenvs\\overtime-calculator-voKtduX3\\lib\\site-packages\\flake8\\options\\config.py", line 297, in parse
    return self.merge_user_and_local_config()
  File "C:\\Users\\x10an14\\.virtualenvs\\overtime-calculator-voKtduX3\\lib\\site-packages\\flake8\\options\\config.py", line 261, in merge_user_and_local_config
    config = self.parse_local_config()
  File "C:\\Users\\x10an14\\.virtualenvs\\overtime-calculator-voKtduX3\\lib\\site-packages\\flake8\\options\\config.py", line 228, in parse_local_config
    return self._parse_config(config)
  File "C:\\Users\\x10an14\\.virtualenvs\\overtime-calculator-voKtduX3\\lib\\site-packages\\flake8\\options\\config.py", line 207, in _parse_config
    value = method(self.program_name, option_name)
  File "C:\\Program Files\\Python37\\Lib\\configparser.py", line 818, in getint
    fallback=fallback, **kwargs)
  File "C:\\Program Files\\Python37\\Lib\\configparser.py", line 808, in _get_conv
    **kwargs)
  File "C:\\Program Files\\Python37\\Lib\\configparser.py", line 802, in _get
    return conv(self.get(section, option, **kwargs))
ValueError: invalid literal for int() with base 10: 'True'
```

**Comment by asottile** [comment]
In GitLab by @x10an14 on Oct 8, 2018, 08:45

changed the description

**Comment by asottile** [comment]
In GitLab by @codecov on Oct 8, 2018, 08:48

# [Codecov](https://codecov.io/gl/pycqa/flake8/pull/248?src=pr&el=h1) Report
> Merging [#248](https://codecov.io/gl/pycqa/flake8/pull/248?src=pr&el=desc) into [master](https://codecov.io/gl/pycqa/flake8/commit/9631dac52aa6ed8a3de9d0983c3c7b0267ae7d6d?src=pr&el=desc) will **decrease** coverage by `0.04%`.
> The diff coverage is `42.85%`.

[![Impacted file tree graph](https://codecov.io/gl/pycqa/flake8/pull/248/graphs/tree.svg?width=650&token=QL6TVnaXih&height=150&src=pr)](https://codecov.io/gl/pycqa/flake8/pull/248?src=pr&el=tree)

```diff
@@            Coverage Diff             @@
##           master     #248      +/-   ##
==========================================
- Coverage   70.73%   70.68%   -0.05%     
==========================================
  Files          27       27              
  Lines        2351     2354       +3     
  Branches      383      383              
==========================================
+ Hits         1663     1664       +1     
- Misses        610      612       +2     
  Partials       78       78
```


| [Impacted Files](https://codecov.io/gl/pycqa/flake8/pull/248?src=pr&el=tree) | Coverage Δ | |
|---|---|---|
| [src/flake8/options/config.py](https://codecov.io/gl/pycqa/flake8/pull/248/diff?src=pr&el=tree#diff-c3JjL2ZsYWtlOC9vcHRpb25zL2NvbmZpZy5weQ==) | `93.18% <42.85%> (-1.04%)` | :arrow_down: |

------

[Continue to review full report at Codecov](https://codecov.io/gl/pycqa/flake8/pull/248?src=pr&el=continue).
> **Legend** - [Click here to learn more](https://docs.codecov.io/docs/codecov-delta)
> `Δ = absolute <relative> (impact)`, `ø = not affected`, `? = missing data`
> Powered by [Codecov](https://codecov.io/gl/pycqa/flake8/pull/248?src=pr&el=footer). Last update [9631dac...9e2c34c](https://codecov.io/gl/pycqa/flake8/pull/248?src=pr&el=lastupdated). Read the [comment docs](https://docs.codecov.io/docs/pull-request-comments).

**Comment by asottile** [comment]
In GitLab by @x10an14 on Oct 8, 2018, 08:56

changed the description

**Comment by asottile** [comment]
In GitLab by @sigmavirus24 on Oct 20, 2018, 05:08

Commented on [src/flake8/options/config.py line 216](https://github.com/PyCQA/flake8/compare/9631dac52aa6ed8a3de9d0983c3c7b0267ae7d6d..9e2c34c136eb61828f83544bec5189620fc72d18#diff-f88a46c2a2384c25f0ca4f25b56f9bfbL216)



I believe this is where the `ValueError` is coming from, no?

**Comment by asottile** [comment]
In GitLab by @asottile on Jan 16, 2020, 11:09

this is no longer needed after !360 (which removes `verbose` from the configuration parsing since it did nothing there)

**Comment by asottile** [comment]
In GitLab by @asottile on Jan 16, 2020, 11:09

closed
