### ISSUE TITLE
Show traceback on plugin exception - [merged]

### ISSUE THREAD

**Issue by asottile** [PyCQA/flake8#926]
In GitLab by @native-api on May 19, 2019, 04:56

_Merges show_traceback -> master_

As can be seen in https://travis-ci.org/native-api/speech_recognition/jobs/534390636#L568, if a plugin fails with error, only exception value is shown. As a result, one cannot see what's wrong. Contrary to the accompanying message, this doesn't change if verbosity is increased.

The MR prints a full traceback instead.

**Comment by asottile** [comment]
In GitLab by @native-api on May 19, 2019, 04:58

changed the description

**Comment by asottile** [comment]
In GitLab by @native-api on May 19, 2019, 05:01

added 1 commit

<ul><li>69247267 - Fix flake8 violation</li></ul>

[Compare with previous version](https://gitlab.com/pycqa/flake8/merge_requests/317/diffs?diff_id=42495710&start_sha=bd170744c40735a0ed995dccb61dcc602e8fcd82)

**Comment by asottile** [comment]
In GitLab by @codecov on May 19, 2019, 05:03

# [Codecov](https://codecov.io/gl/pycqa/flake8/pull/317?src=pr&el=h1) Report
> Merging [#317](https://codecov.io/gl/pycqa/flake8/pull/317?src=pr&el=desc) into [master](https://codecov.io/gl/pycqa/flake8/commit/b6ba6d4d03109965d3cf5174d5c2e6868d7d92bb?src=pr&el=desc) will **not change** coverage.
> The diff coverage is `n/a`.

[![Impacted file tree graph](https://codecov.io/gl/pycqa/flake8/pull/317/graphs/tree.svg?width=650&token=QL6TVnaXih&height=150&src=pr)](https://codecov.io/gl/pycqa/flake8/pull/317?src=pr&el=tree)

```diff
@@          Coverage Diff           @@
##           master    #317   +/-   ##
======================================
  Coverage    80.2%   80.2%           
======================================
  Files          25      25           
  Lines        2354    2354           
  Branches      390     390           
======================================
  Hits         1888    1888           
  Misses        385     385           
  Partials       81      81
```


| [Impacted Files](https://codecov.io/gl/pycqa/flake8/pull/317?src=pr&el=tree) | Coverage Δ | |
|---|---|---|
| [src/flake8/checker.py](https://codecov.io/gl/pycqa/flake8/pull/317/diff?src=pr&el=tree#diff-c3JjL2ZsYWtlOC9jaGVja2VyLnB5) | `75.73% <ø> (ø)` | :arrow_up: |

------

[Continue to review full report at Codecov](https://codecov.io/gl/pycqa/flake8/pull/317?src=pr&el=continue).
> **Legend** - [Click here to learn more](https://docs.codecov.io/docs/codecov-delta)
> `Δ = absolute <relative> (impact)`, `ø = not affected`, `? = missing data`
> Powered by [Codecov](https://codecov.io/gl/pycqa/flake8/pull/317?src=pr&el=footer). Last update [b6ba6d4...6813f15](https://codecov.io/gl/pycqa/flake8/pull/317?src=pr&el=lastupdated). Read the [comment docs](https://docs.codecov.io/docs/pull-request-comments).

**Comment by asottile** [comment]
In GitLab by @native-api on May 19, 2019, 05:12

https://gitlab.com/native-api/flake8/-/jobs/215120933 failure is unrelated to the change, it's a false positive for https://bandit.readthedocs.io/en/latest/plugins/b105_hardcoded_password_string.html .

**Comment by asottile** [comment]
In GitLab by @asottile on May 19, 2019, 09:06

we should not be showing tracebacks to the user by default -- the way this was _intended_ to work was to have the exception traceback appear in logging due to a `log.X(..., exc_info=True)` I believe

**Comment by asottile** [comment]
In GitLab by @asottile on May 19, 2019, 09:43

I'm fixing the bandit false-positive in !318

**Comment by asottile** [comment]
In GitLab by @native-api on May 20, 2019, 03:01

added 3 commits

<ul><li>69247267...b6ba6d4d - 2 commits from branch <code>pycqa:master</code></li><li>41ab56f3 - Merge branch &#39;master&#39; into show_traceback</li></ul>

[Compare with previous version](https://gitlab.com/pycqa/flake8/merge_requests/317/diffs?diff_id=42560644&start_sha=6924726775135ea37745b370ede1444eb8774fcd)

**Comment by asottile** [comment]
In GitLab by @native-api on May 20, 2019, 05:47

added 3 commits

<ul><li>4b7a76cc - Show traceback on plugin exception</li><li>20c4f4db - Fix flake8 violation</li><li>f0588f1c - Print traceback in the critical log message instead</li></ul>

[Compare with previous version](https://gitlab.com/pycqa/flake8/merge_requests/317/diffs?diff_id=42583173&start_sha=41ab56f349ff8055ccf7960587e7afd81b2dc0d2)

**Comment by asottile** [comment]
In GitLab by @native-api on May 20, 2019, 07:46

I moved the traceback to the critical log message.

An exception message is useless without traceback (see http://idownvotedbecau.se/noexceptiondetails/ why) so it's pointless to print it alone IMO. But if you are sure about this, fine by me.

**Comment by asottile** [comment]
In GitLab by @asottile on May 20, 2019, 08:04

I don't need the attitude, please.  flake8 currently tries very hard not to produce stacktraces in default mode and I'm not about to change that.

Your change to the exception message makes the output worse:


### Before

```
$ flake8 -j1 t.py
"pyflakes" failed during execution due to "'ExceptHandler' object has no attribute 'depth'"
Run flake8 with greater verbosity to see more details
```

### After


```
$ flake8 -j1 t.py
"pyflakes" failed during execution due to exception:
"'ExceptHandler' object has no attribute 'depth'"
Run flake8 with greater verbosity to see more details
```

### the actual change works though!

```
$ $ flake8 -v -j1 t.py
flake8.plugins.manager    MainProcess     48 INFO     Loading entry-points for "flake8.extension".
flake8.plugins.manager    MainProcess     59 INFO     Loading entry-points for "flake8.report".
flake8.plugins.manager    MainProcess     69 INFO     Loading plugin "C90" from entry-point.
flake8.plugins.manager    MainProcess     70 INFO     Loading plugin "S" from entry-point.
flake8.plugins.manager    MainProcess    161 INFO     Loading plugin "F" from entry-point.
flake8.plugins.manager    MainProcess    185 INFO     Loading plugin "pycodestyle.ambiguous_identifier" from entry-point.
flake8.plugins.manager    MainProcess    185 INFO     Loading plugin "pycodestyle.bare_except" from entry-point.
flake8.plugins.manager    MainProcess    185 INFO     Loading plugin "pycodestyle.blank_lines" from entry-point.
flake8.plugins.manager    MainProcess    186 INFO     Loading plugin "pycodestyle.break_after_binary_operator" from entry-point.
flake8.plugins.manager    MainProcess    186 INFO     Loading plugin "pycodestyle.break_before_binary_operator" from entry-point.
flake8.plugins.manager    MainProcess    186 INFO     Loading plugin "pycodestyle.comparison_negative" from entry-point.
flake8.plugins.manager    MainProcess    186 INFO     Loading plugin "pycodestyle.comparison_to_singleton" from entry-point.
flake8.plugins.manager    MainProcess    186 INFO     Loading plugin "pycodestyle.comparison_type" from entry-point.
flake8.plugins.manager    MainProcess    186 INFO     Loading plugin "pycodestyle.compound_statements" from entry-point.
flake8.plugins.manager    MainProcess    186 INFO     Loading plugin "pycodestyle.continued_indentation" from entry-point.
flake8.plugins.manager    MainProcess    186 INFO     Loading plugin "pycodestyle.explicit_line_join" from entry-point.
flake8.plugins.manager    MainProcess    187 INFO     Loading plugin "pycodestyle.extraneous_whitespace" from entry-point.
flake8.plugins.manager    MainProcess    187 INFO     Loading plugin "pycodestyle.imports_on_separate_lines" from entry-point.
flake8.plugins.manager    MainProcess    187 INFO     Loading plugin "pycodestyle.indentation" from entry-point.
flake8.plugins.manager    MainProcess    187 INFO     Loading plugin "pycodestyle.maximum_doc_length" from entry-point.
flake8.plugins.manager    MainProcess    188 INFO     Loading plugin "pycodestyle.maximum_line_length" from entry-point.
flake8.plugins.manager    MainProcess    189 INFO     Loading plugin "pycodestyle.missing_whitespace" from entry-point.
flake8.plugins.manager    MainProcess    189 INFO     Loading plugin "pycodestyle.missing_whitespace_after_import_keyword" from entry-point.
flake8.plugins.manager    MainProcess    189 INFO     Loading plugin "pycodestyle.missing_whitespace_around_operator" from entry-point.
flake8.plugins.manager    MainProcess    189 INFO     Loading plugin "pycodestyle.module_imports_on_top_of_file" from entry-point.
flake8.plugins.manager    MainProcess    189 INFO     Loading plugin "pycodestyle.python_3000_async_await_keywords" from entry-point.
flake8.plugins.manager    MainProcess    189 INFO     Loading plugin "pycodestyle.python_3000_backticks" from entry-point.
flake8.plugins.manager    MainProcess    190 INFO     Loading plugin "pycodestyle.python_3000_has_key" from entry-point.
flake8.plugins.manager    MainProcess    190 INFO     Loading plugin "pycodestyle.python_3000_invalid_escape_sequence" from entry-point.
flake8.plugins.manager    MainProcess    190 INFO     Loading plugin "pycodestyle.python_3000_not_equal" from entry-point.
flake8.plugins.manager    MainProcess    190 INFO     Loading plugin "pycodestyle.python_3000_raise_comma" from entry-point.
flake8.plugins.manager    MainProcess    190 INFO     Loading plugin "pycodestyle.tabs_obsolete" from entry-point.
flake8.plugins.manager    MainProcess    190 INFO     Loading plugin "pycodestyle.tabs_or_spaces" from entry-point.
flake8.plugins.manager    MainProcess    190 INFO     Loading plugin "pycodestyle.trailing_blank_lines" from entry-point.
flake8.plugins.manager    MainProcess    191 INFO     Loading plugin "pycodestyle.trailing_whitespace" from entry-point.
flake8.plugins.manager    MainProcess    191 INFO     Loading plugin "pycodestyle.whitespace_around_comma" from entry-point.
flake8.plugins.manager    MainProcess    191 INFO     Loading plugin "pycodestyle.whitespace_around_keywords" from entry-point.
flake8.plugins.manager    MainProcess    191 INFO     Loading plugin "pycodestyle.whitespace_around_named_parameter_equals" from entry-point.
flake8.plugins.manager    MainProcess    191 INFO     Loading plugin "pycodestyle.whitespace_around_operator" from entry-point.
flake8.plugins.manager    MainProcess    191 INFO     Loading plugin "pycodestyle.whitespace_before_comment" from entry-point.
flake8.plugins.manager    MainProcess    191 INFO     Loading plugin "pycodestyle.whitespace_before_parameters" from entry-point.
flake8.plugins.manager    MainProcess    191 INFO     Loading plugin "default" from entry-point.
flake8.plugins.manager    MainProcess    193 INFO     Loading plugin "pylint" from entry-point.
flake8.plugins.manager    MainProcess    193 INFO     Loading plugin "quiet-filename" from entry-point.
flake8.plugins.manager    MainProcess    193 INFO     Loading plugin "quiet-nothing" from entry-point.
flake8.main.application   MainProcess    197 WARNING  "${cyan}%(path)s${reset}:${yellow_bold}%(row)d${reset}:${green_bold}%(col)d${reset}: ${red_bold}%(code)s${reset} %(text)s" is an unknown formatter. Falling back to default.
flake8.checker            MainProcess    197 INFO     Making checkers
flake8.checker            MainProcess    202 INFO     Checking 1 files
flake8.checker            MainProcess    225 CRITICAL Plugin F raised an unexpected exception
Traceback (most recent call last):
  File "/home/asottile/workspace/flake8/src/flake8/checker.py", line 435, in run_check
    return plugin["plugin"](**arguments)
  File "/home/asottile/workspace/flake8/src/flake8/plugins/pyflakes.py", line 93, in __init__
    file_tokens=file_tokens,
  File "/home/asottile/workspace/flake8/t/venv/lib/python3.5/site-packages/pyflakes/checker.py", line 673, in __init__
    self.runDeferred(self._deferredFunctions)
  File "/home/asottile/workspace/flake8/t/venv/lib/python3.5/site-packages/pyflakes/checker.py", line 710, in runDeferred
    handler()
  File "/home/asottile/workspace/flake8/t/venv/lib/python3.5/site-packages/pyflakes/checker.py", line 1474, in runFunction
    self.handleChildren(node, omit='decorator_list')
  File "/home/asottile/workspace/flake8/t/venv/lib/python3.5/site-packages/pyflakes/checker.py", line 1073, in handleChildren
    self.handleNode(node, tree)
  File "/home/asottile/workspace/flake8/t/venv/lib/python3.5/site-packages/pyflakes/checker.py", line 1120, in handleNode
    handler(node)
  File "/home/asottile/workspace/flake8/t/venv/lib/python3.5/site-packages/pyflakes/checker.py", line 1623, in TRY
    self.handleNode(child, node)
  File "/home/asottile/workspace/flake8/t/venv/lib/python3.5/site-packages/pyflakes/checker.py", line 1120, in handleNode
    handler(node)
  File "/home/asottile/workspace/flake8/t/venv/lib/python3.5/site-packages/pyflakes/checker.py", line 1073, in handleChildren
    self.handleNode(node, tree)
  File "/home/asottile/workspace/flake8/t/venv/lib/python3.5/site-packages/pyflakes/checker.py", line 1120, in handleNode
    handler(node)
  File "/home/asottile/workspace/flake8/t/venv/lib/python3.5/site-packages/pyflakes/checker.py", line 1073, in handleChildren
    self.handleNode(node, tree)
  File "/home/asottile/workspace/flake8/t/venv/lib/python3.5/site-packages/pyflakes/checker.py", line 1120, in handleNode
    handler(node)
  File "/home/asottile/workspace/flake8/t/venv/lib/python3.5/site-packages/pyflakes/checker.py", line 1353, in NAME
    self.handleNodeStore(node)
  File "/home/asottile/workspace/flake8/t/venv/lib/python3.5/site-packages/pyflakes/checker.py", line 1017, in handleNodeStore
    self.addBinding(node, binding)
  File "/home/asottile/workspace/flake8/t/venv/lib/python3.5/site-packages/pyflakes/checker.py", line 876, in addBinding
    not self.differentForks(node, existing.source)):
  File "/home/asottile/workspace/flake8/t/venv/lib/python3.5/site-packages/pyflakes/checker.py", line 857, in differentForks
    if self.descendantOf(lnode, items, ancestor) ^ \
  File "/home/asottile/workspace/flake8/t/venv/lib/python3.5/site-packages/pyflakes/checker.py", line 835, in descendantOf
    if self.getCommonAncestor(node, a, stop):
  File "/home/asottile/workspace/flake8/t/venv/lib/python3.5/site-packages/pyflakes/checker.py", line 827, in getCommonAncestor
    if (lnode.depth > rnode.depth):
AttributeError: 'ExceptHandler' object has no attribute 'depth'
"pyflakes" failed during execution due to exception:
"'ExceptHandler' object has no attribute 'depth'"
Run flake8 with greater verbosity to see more details
flake8.main.application   MainProcess    227 INFO     Finished running
flake8.main.application   MainProcess    227 INFO     Reporting errors
flake8.main.application   MainProcess    227 INFO     Found a total of 0 violations and reported 0
```

please put your other change back

**Comment by asottile** [comment]
In GitLab by @native-api on May 20, 2019, 12:44

added 1 commit

<ul><li>6813f159 - Show traceback on plugin exception</li></ul>

[Compare with previous version](https://gitlab.com/pycqa/flake8/merge_requests/317/diffs?diff_id=42642179&start_sha=f0588f1cd3045fd5c7e8438527353467e1e6a9c6)

**Comment by asottile** [comment]
In GitLab by @asottile on Jun 14, 2019, 11:03

merged

**Comment by asottile** [comment]
In GitLab by @asottile on Jun 14, 2019, 11:03

mentioned in commit 2f8bc64b1e688cc835e57547c544f34b8bcd7a2a

**Comment by asottile** [comment]
In GitLab by @asottile on Jun 14, 2019, 11:03

Thanks!
