### ISSUE TITLE
Fix type='str' optparse options - [merged]

### ISSUE THREAD

**Issue by asottile** [PyCQA/flake8#984]
In GitLab by @asottile on Apr 24, 2020, 10:45

_Merges keyerror_str -> master_

Example traceback:

```
Traceback (most recent call last):
  File "/home/asottile/.cache/pre-commit/repovwkudiwz/py_env-python3/bin/flake8", line 8, in <module>
    sys.exit(main())
  File "/home/asottile/.cache/pre-commit/repovwkudiwz/py_env-python3/lib/python3.6/site-packages/flake8/main/cli.py", line 22, in main
    app.run(argv)
  File "/home/asottile/.cache/pre-commit/repovwkudiwz/py_env-python3/lib/python3.6/site-packages/flake8/main/application.py", line 355, in run
    self._run(argv)
  File "/home/asottile/.cache/pre-commit/repovwkudiwz/py_env-python3/lib/python3.6/site-packages/flake8/main/application.py", line 342, in _run
    self.initialize(argv)
  File "/home/asottile/.cache/pre-commit/repovwkudiwz/py_env-python3/lib/python3.6/site-packages/flake8/main/application.py", line 324, in initialize
    self.register_plugin_options()
  File "/home/asottile/.cache/pre-commit/repovwkudiwz/py_env-python3/lib/python3.6/site-packages/flake8/main/application.py", line 160, in register_plugin_options
    self.check_plugins.register_options(self.option_manager)
  File "/home/asottile/.cache/pre-commit/repovwkudiwz/py_env-python3/lib/python3.6/site-packages/flake8/plugins/manager.py", line 494, in register_options
    list(self.manager.map(register_and_enable))
  File "/home/asottile/.cache/pre-commit/repovwkudiwz/py_env-python3/lib/python3.6/site-packages/flake8/plugins/manager.py", line 302, in map
    yield func(self.plugins[name], *args, **kwargs)
  File "/home/asottile/.cache/pre-commit/repovwkudiwz/py_env-python3/lib/python3.6/site-packages/flake8/plugins/manager.py", line 490, in register_and_enable
    call_register_options(plugin)
  File "/home/asottile/.cache/pre-commit/repovwkudiwz/py_env-python3/lib/python3.6/site-packages/flake8/plugins/manager.py", line 402, in generated_function
    return method(optmanager, *args, **kwargs)
  File "/home/asottile/.cache/pre-commit/repovwkudiwz/py_env-python3/lib/python3.6/site-packages/flake8/plugins/manager.py", line 216, in register_options
    add_options(optmanager)
  File "/home/asottile/.cache/pre-commit/repovwkudiwz/py_env-python3/lib/python3.6/site-packages/flake8_typing_imports.py", line 538, in add_options
    'Minimum version of python your code supports, '
  File "/home/asottile/.cache/pre-commit/repovwkudiwz/py_env-python3/lib/python3.6/site-packages/flake8/options/manager.py", line 403, in add_option
    option = Option(*args, **kwargs)
  File "/home/asottile/.cache/pre-commit/repovwkudiwz/py_env-python3/lib/python3.6/site-packages/flake8/options/manager.py", line 211, in __init__
    type = _optparse_callable_map[type]
KeyError: 'str'
```

Example code: https://github.com/asottile/flake8-typing-imports/blob/08c6c2eec2a221e62183f8f84a2f034ba39b9942/flake8_typing_imports.py#L710

**Comment by asottile** [comment]
In GitLab by @codecov on Apr 24, 2020, 10:45

# [Codecov](https://codecov.io/gl/pycqa/flake8/pull/419?src=pr&el=h1) Report
> :exclamation: No coverage uploaded for pull request base (`master@2cb1c65`). [Click here to learn what that means](https://docs.codecov.io/docs/error-reference#section-missing-base-commit).
> The diff coverage is `n/a`.

[![Impacted file tree graph](https://codecov.io/gl/pycqa/flake8/pull/419/graphs/tree.svg?width=650&height=150&src=pr&token=QL6TVnaXih)](https://codecov.io/gl/pycqa/flake8/pull/419?src=pr&el=tree)

```diff
@@            Coverage Diff            @@
##             master     #419   +/-   ##
=========================================
  Coverage          ?   90.48%           
=========================================
  Files             ?       58           
  Lines             ?     4119           
  Branches          ?      414           
=========================================
  Hits              ?     3727           
  Misses            ?      336           
  Partials          ?       56           
```


| [Impacted Files](https://codecov.io/gl/pycqa/flake8/pull/419?src=pr&el=tree) | Coverage Δ | |
|---|---|---|
| [src/flake8/options/manager.py](https://codecov.io/gl/pycqa/flake8/pull/419/diff?src=pr&el=tree#diff-c3JjL2ZsYWtlOC9vcHRpb25zL21hbmFnZXIucHk=) | `90.37% <ø> (ø)` | |
| [tests/unit/test\_option\_manager.py](https://codecov.io/gl/pycqa/flake8/pull/419/diff?src=pr&el=tree#diff-dGVzdHMvdW5pdC90ZXN0X29wdGlvbl9tYW5hZ2VyLnB5) | `100.00% <ø> (ø)` | |
| [tests/unit/test\_style\_guide.py](https://codecov.io/gl/pycqa/flake8/pull/419/diff?src=pr&el=tree#diff-dGVzdHMvdW5pdC90ZXN0X3N0eWxlX2d1aWRlLnB5) | `100.00% <0.00%> (ø)` | |
| [src/flake8/formatting/default.py](https://codecov.io/gl/pycqa/flake8/pull/419/diff?src=pr&el=tree#diff-c3JjL2ZsYWtlOC9mb3JtYXR0aW5nL2RlZmF1bHQucHk=) | `100.00% <0.00%> (ø)` | |
| [tests/integration/test\_main.py](https://codecov.io/gl/pycqa/flake8/pull/419/diff?src=pr&el=tree#diff-dGVzdHMvaW50ZWdyYXRpb24vdGVzdF9tYWluLnB5) | `100.00% <0.00%> (ø)` | |
| [tests/unit/test\_file\_checker.py](https://codecov.io/gl/pycqa/flake8/pull/419/diff?src=pr&el=tree#diff-dGVzdHMvdW5pdC90ZXN0X2ZpbGVfY2hlY2tlci5weQ==) | `100.00% <0.00%> (ø)` | |
| [tests/unit/test\_plugin\_manager.py](https://codecov.io/gl/pycqa/flake8/pull/419/diff?src=pr&el=tree#diff-dGVzdHMvdW5pdC90ZXN0X3BsdWdpbl9tYW5hZ2VyLnB5) | `100.00% <0.00%> (ø)` | |
| [src/flake8/main/cli.py](https://codecov.io/gl/pycqa/flake8/pull/419/diff?src=pr&el=tree#diff-c3JjL2ZsYWtlOC9tYWluL2NsaS5weQ==) | `100.00% <0.00%> (ø)` | |
| [src/flake8/main/vcs.py](https://codecov.io/gl/pycqa/flake8/pull/419/diff?src=pr&el=tree#diff-c3JjL2ZsYWtlOC9tYWluL3Zjcy5weQ==) | `45.00% <0.00%> (ø)` | |
| ... and [50 more](https://codecov.io/gl/pycqa/flake8/pull/419/diff?src=pr&el=tree-more) | |

------

[Continue to review full report at Codecov](https://codecov.io/gl/pycqa/flake8/pull/419?src=pr&el=continue).
> **Legend** - [Click here to learn more](https://docs.codecov.io/docs/codecov-delta)
> `Δ = absolute <relative> (impact)`, `ø = not affected`, `? = missing data`
> Powered by [Codecov](https://codecov.io/gl/pycqa/flake8/pull/419?src=pr&el=footer). Last update [2cb1c65...3b490bb](https://codecov.io/gl/pycqa/flake8/pull/419?src=pr&el=lastupdated). Read the [comment docs](https://docs.codecov.io/docs/pull-request-comments).

**Comment by asottile** [comment]
In GitLab by @asottile on Apr 24, 2020, 10:45

enabled an automatic merge when the pipeline for 3b490bb3c5775fedca7167a98c5bf4aee5e171f7 succeeds

**Comment by asottile** [comment]
In GitLab by @asottile on Apr 24, 2020, 10:47

merged

**Comment by asottile** [comment]
In GitLab by @asottile on Apr 24, 2020, 10:47

mentioned in commit 6f28112957be99f766e308e8a6bd8204640f465a
